### ISSUE TITLE
Table.read().csv() hangs.

### ISSUE THREAD

**Issue by jackeywall** [jtablesaw/tablesaw#1002]
Hi there. Using your latest libs:

	
	<dependency org="tech.tablesaw" name="tablesaw-core" rev="0.38.5"/>
	
	<dependency org="tech.tablesaw" name="tablesaw-jsplot" rev="0.38.5"/>
	
	<dependency org="tech.tablesaw" name="tablesaw-plot" rev="0.24.4"/>
	
	<dependency org="tech.tablesaw" name="tablesaw-json" rev="0.38.5"/>

Java 1.8.0_275 on BigSur 11.06 - my daily dev environment with no known issues.

Each supplied example of Table.read().csv(parameter) hangs, regardless of the parameter for csv(); e.g., Reader, InputStream, file reference, StringBuilder to String, etc.

This works (from your tests):
String json =
			        "[[\"Date\",\"Value\"],[1453438800000,-2.1448117025014],[1454043600000,-2.9763153817574],[1454648400000,-2.9545283436391]]";
			    Table table = Table.read().string(json, "json");

And this fails (adapted from your csv tests), no exceptions, just hangs:

String LINE_END = System.lineSeparator();

			final Reader reader =
					new StringReader("Text" + LINE_END + "\"short\"" + LINE_END + "1234567890" + LINE_END);

			final int maxCharsPerColumn = 12;

			Table result = Table.read().csv( CsvReadOptions.builder(reader).maxCharsPerColumn(maxCharsPerColumn));
			assertEquals(2, result.rowCount());
                        // Log line never prints ...
			Logger.warn("Good-value test COMPLETED!");

I've successfully plotted data by directly building the arrays[] ...

Just can't get csv to read/parse into the Table.

Certainly appreciate any suggestions on what I may be missing.

Thank you!

**Comment by lwhite1** [comment]
I can look into it more tomorrow but on the surface it looks like you’re
using an obsolete library:  tablesaw-plot is no longer supported. Only the
jsplot library is supported.

On the other hand. That doesn’t sound related to the issue you’re
describing.

**Comment by jackeywall** [comment]
Thank you for the pointer on the obsolete lib - that was a holdover from an example found elsewhere. I did remove and retried the csv test, just in case a conflict existed; however, no success.

I did forget to mention that Eclipse is my IDE, Version: 2021-06 (4.20.0).

Again, very much appreciate your insights - cheers ...

**Comment by jackeywall** [comment]
Quickly, I tried the csv test from my first message on a 2nd dev machine in the office, same results. The env on that machine is slightly different (os version, Eclipse version, JRE, etc.). It still could be a common "cause" that I'm missing, but want to be sure that I can back your effort to help, as much as I can.

Cheers ...

**Comment by jackeywall** [comment]
Thank you @ccleva - it could be that I have an older JDK, with some incompatibility, mine (jdk1.8.0_91.jdk) is certainly older than your reference. Will change and see if that is the remedy.

Cheers ...

**Comment by lwhite1** [comment]
I did a check of Univociy issues to see if there were any references to hanging and didn't see any. I don't believe there is any explicit multi-threading in Tablesaw's CSV import logic. I'm kinda at a loss.

**Comment by Bitsy-Chuck** [comment]
works for maven project but is stuck for playframework
