### ISSUE TITLE
Join performance test case

### ISSUE THREAD

**Issue by gilleshuron** [jtablesaw/tablesaw#1039]
Hi
Thanks for maintaining this great project.

Below a test case of performance degradation in a multi column join, depending on how the independent join column values separate rows distinctly enough (performance OK) or, to the contrary involve a large selection of overlapping row values in a multi column join (performance issue)

This code snippet can be added to the DataFrameJoinerPerformanceTest.java.
It joins 2 table of size N, resulting in a table of size N 
It yields an execution time of ~20s, only due to the z column bringing a large amount of indices when building the selection, in some sort of O(N^2) complexity.
If the z column was like the others, filled with a range, test executes in less that 1 s

You may want to improve that corner case in future. 
Thanks

```java
  private static Table createXYZTable(String name, int cardinality) {
    Table table = Table.create(name);
    int[] filler = new int[cardinality];
    Arrays.fill(filler, 1);
    IntColumn x =
            IntColumn.create("x", IntStream.range(0, cardinality).toArray());
    IntColumn y =
            IntColumn.create("y", IntStream.range(0, cardinality).toArray());
    IntColumn z =
            IntColumn.create("z", filler);
    table.addColumns(x,y,z);
    addFillerColumn(table, 5, name);
    return table;
  }

  @Test
  public void test() {
    Table a = createXYZTable("a", 50000);
    Table b = createXYZTable("b", 50000);
    assertTimeout(Duration.ofSeconds(1), () -> a.joinOn("x","y","z").inner(b));
  }
```

**Comment by lwhite1** [comment]
yeah, joins are two slow. They use a cross product. It really needs implementations of hash join and merge join, with the algorithm chosen automatically.

**Comment by lwhite1** [comment]
Hi @gilleshuron, any chance you have the code for addFillerColumn()? or recall what it does?  Thanks.

**Comment by lwhite1** [comment]
Got it. Thanks.

**Comment by lwhite1** [comment]
integrated
