### ISSUE TITLE
Doublecolumn is displaying as text column so that it throws Exception while using set method

### ISSUE THREAD

**Issue by meghana-chennam** [jtablesaw/tablesaw#1046]
The main issue which I faced many times is , I have created a double column and appended to the table, But while printing the structure of the table its showing as Text column and while applying the operations on double column it throwing exception like you cant access text column.
Please have a look on to this issue which is very problematic because tablesaw looks like strictly type specific.

**Comment by lwhite1** [comment]
Can you provide a code example where this is happening?

**Comment by lwhite1** [comment]
Closing as not reproducable.
