### ISSUE TITLE
Null pointer exception when using NumberColumn::setPrintFormatter function

### ISSUE THREAD

**Issue by hongwingl** [jtablesaw/tablesaw#1047]
When I use `setPrintFormatter(NumberFormat format, String missingValueIndicator)` function in `NumberColumn` class, I get a NPE when the table is written to file. The problem is that `formatter.setColumnType(this.type());` is not called in this function variant.

Fix is to change the function definition to

```
public void setPrintFormatter(NumberFormat format, String missingValueIndicator) {
    setPrintFormatter(new NumberColumnFormatter(format, missingValueIndicator));
}
```

**Comment by lwhite1** [comment]
i will look into this soon. sorry for the lengthy delay

**Comment by lwhite1** [comment]
fixed. Thank you @hongwingl  for the bug report and for identifying the fix. Always appreciated.
