### ISSUE TITLE
Table generated from JSON string not maintaining the column orders

### ISSUE THREAD

**Issue by varshaldavda** [jtablesaw/tablesaw#1050]
I am using tablesaw-core and tablesaw-json  V0.42.0.
I am facing an issue that when I create a Table using json string builder, it does not maintain the column orders.

Here is my json data 

```
[
  {
    "id": 186459,
    "approvalRequired": "Y",
    "approveAllAtOnce": true,
    "status": "IN_PROGRESS",
    "title": "Title 1",
    "assignDateTime": 1643868421897,
    "lastUpdatedDate": 1643871005816
  },
  {
    "id": 11111,
    "approvalRequired": "N",
    "approveAllAtOnce": true,
    "status": "COMPLETED",
    "title": "Title 2",
    "assignDateTime": 1643868421897,
    "lastUpdatedDate": 1643871005816
  }
]
```

and here is the output : 

```
lastUpdatedDate  |  assignDateTime  |  approvalRequired  |  approveAllAtOnce  |    id    |   title   |    status     |
-----------------------------------------------------------------------------------------------------------------------
   1643871005816  |   1643868421897  |              true  |              true  |  186459  |  Title 1  |  IN_PROGRESS  |
   1643871005816  |   1643868421897  |             false  |              true  |   11111  |  Title 2  |    COMPLETED  |
```

Here is my java code to generate this table : 

```
JsonReadOptions options = JsonReadOptions.builderFromString(json).build();
Table table = Table.read().usingOptions(options);
System.out.println(table);
```

Due to this issue, I am not able to use functions like column reordering, column removing, etc. using column index. 

Am I doing anything wrong here ?
Please help me.

Thanks,
Varshal

**Comment by lwhite1** [comment]
I think the answer is that Json columns don't have an order under the standard. For example, when I google "json column orders" the first answer is from stack exchange: 

> The data represented by an object in JSON has no inherent order, so you can't count on JSON to maintain an order for an unordered object.

I'm sure that's not an entirely satisfactory answer, but my guess is that's how the library we use works.

**Comment by lwhite1** [comment]
i will close this, unless there's more definitely a tablesaw but here. Please feel free to reopen if you think that's not correct.
