### ISSUE TITLE
A table imported via read().csv() cannot be exported to json

### ISSUE THREAD

**Issue by dfioravanti** [jtablesaw/tablesaw#1057]
Hey everyone, first at all thanks for this great project. I have a table like the following in CSV format
```
Username, Identifier,First name,Last name
booker12,9012,Rachel,Booker
grey07,2070,Laura,Grey
johnson81,4081,Craig,Johnson
jenkins46,9346,Mary,Jenkins
smith79,5079,Jamie,Smith
```
and I am reading it into a table via `read().csv()`. This works great, now I do a series of operations and I would like to export this table without headers as JSON. 

If I do `table.write().toString("json")` it works but I get the headers and it is a Map instead of a List. To fix this I would like to use 
```
table.write().usingOptions(JsonWriteOptions.builder(writer).asObjects(false).header(false).build())
```
but I get `Void` (I am using kotlin so technically I get `Unit`) instead of the expected result and I not figure it out why. I got the code from https://github.com/jtablesaw/tablesaw/issues/450#issuecomment-519686728 and if I use the provided example it works. Is this a bug or expected behaviour? Thanks a lot

**Comment by lwhite1** [comment]
Hi Diego,
I've never worked on (or used) the Json functionality, but I will take a
look when I have a moment.

**Comment by dfioravanti** [comment]
Ok, yesterday I was an idiot. Instead of calling `writer.toString()` I extected `table.write().usingOptions(JsonWriteOptions.builder(writer).asObjects(false).header(false).build())` to return the string directly. Of course it does not return anything so it absolutely right that I get `Void` out. Sorry for wasting your time
