### ISSUE TITLE
eliminate the use of shade plugin, if possible

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#1060]
I thought we stopped using this years ago. Not sure why/if it's necessary

**Comment by lwhite1** [comment]
@benmccann Do you have any idea if we need the shade plugin in our poms? 

I commented them out of the poms, rebuilt and installed the jar, and used the new version from another project that uses both jsplot and core. I don't see any issues.

**Comment by lwhite1** [comment]
removed a few that were missed. All gone now.

**Comment by lwhite1** [comment]
@

**Comment by hallvard** [comment]
Hi,

My understanding was that it was used so consumers could have a single dependency instead of several and also know that everything was contained in case they didn't use maven but downloaded the jar.

etabIesaw will adjust to whatever the project does, and could shade itself if needed.

________________________________________

**Comment by lwhite1** [comment]
Hi @hallvard, thanks for the feedback and the flexibility. I'm not sure if or when we will move to Java 9+, so i don't think a change is necessary now. 

Regarding the shaded pom. I know i introduced it originally, but i was under the mis-impression that @benmccann  removed it at some point. I got a lot of criticism in the early days (although it might have just been one or two noisy people) that deploying to Maven Central with a shaded jar was a terrible thing.  Apparently, it's not so bad.

**Comment by benmccann** [comment]
I don't recall anything about the shaded jar. I do think it's generally better practice not to use them, but if it's not causing trouble then I don't feel strong about it

**Comment by lwhite1** [comment]
removed on the 1.0 branch
