### ISSUE TITLE
Don't use shade when publishing to maven central

### ISSUE THREAD

**Issue by kno10** [jtablesaw/tablesaw#108]
Instead, expose dependencies to dependency management.

To detect/avoid/resolve version conflicts.

**Comment by hadim** [comment]
@lwhite1 could you comment on this ?

**Comment by lwhite1** [comment]
seems reasonable but I don't know when i will get to it. I don't really have time to actively maintain this software now.

**Comment by lwhite1** [comment]
This will be addressed in the near future.

**Comment by benmccann** [comment]
The most straightforward fix would be to simply remove the shade plugin from the `pom.xml`. Would that be something that could be considered? Or is there a reason the uber shaded jar was being built?

**Comment by lwhite1** [comment]
No real reason. I think I was trying to support an early user who was a deep newbie and didn't understand maven.  Removing the shade plugin is a fine solution and would be great to fix.

**Comment by benmccann** [comment]
This should be fixed with the recent split into core and plot modules
