### ISSUE TITLE
How can I use DateTimeFilters to mactch exact hour and minute data in DateTimeColumn

### ISSUE THREAD

**Issue by ShukriChiu** [jtablesaw/tablesaw#1088]
For example, my data is [(2022/03/01 15:42:00, 5) (2022/03/01 15:47:00, 6) (2022/03/02 15:42:00, 7) (2022/03/02 15:47:00, 8)]

I'm trying to use `data.where(data.DateTimeColumn("").xxx method )` to match the exact (15:42) data, the result should be :

[(2022/03/01 15:42:00, 5),(2022/03/02 15:42:00, 5)] 

I checked the Javadoc, and I can't find a suitable method.

**Comment by lwhite1** [comment]
hi @ShukriChiu,

You have to extract the time first, so something like:

`myTable.where(myTable.dateTimeColumn("foo").time().isEqualTo(LocalTime.of(15, 42))
`

should work.

**Comment by lwhite1** [comment]
Note to self: This clearly isn't terribly efficient as it requires creating a TimeColumn using the time() function. It should be fairly easy to implement a query like this directly on the internal representation of the original DateTimeColumn, as the hour and minute elements are easily extracted. That would save the overhead of creating the temporary column in memory.
