### ISSUE TITLE
BooleanColumn should be a NumericColumn

### ISSUE THREAD

**Issue by batterseapower** [jtablesaw/tablesaw#110]
toDoubleArray, min, max, mean etc are all well defined if we just treat false as 0 and true as 1. This would match the behaviour of the equivalent stuff in Numpy/Pandas.

I ran across then when trying to represent a dummy variable as a BooleanColumn - I wasn't expecting toDoubleArray to throw when I was converting the column to an arary for the purposes of running a regression.

**Comment by lwhite1** [comment]
Is it sufficient to implement toDoubleArray in BooleanColumn? The numeric types are morphing to support a consistent set of math and statistical operations and that seems like overkill for boolean.

**Comment by batterseapower** [comment]
Personally my preference would be support all the numeric operations, just because it's less surprising. It would be odd if booleans could be treated as numbers in some contexts but not others, wouldn't it?

**Comment by lwhite1** [comment]
Although I appreciate the argument and the consistency with Pandas, I'm leaning towards the more limited solution. In Java, Boolean isn't a numeric type (subclass of java's Number class). The toDoubleArray method doesn't suggest that it's a weak number, but rather that its a different type that is convertible to a numeric value.

**Comment by lwhite1** [comment]
closed with workaround of using toDoubleArray() to convert the boolean column to something the Smile ML functions can use.
