### ISSUE TITLE
DictionaryMap.categoryArray does not return items in numeric order

### ISSUE THREAD

**Issue by batterseapower** [jtablesaw/tablesaw#111]
At https://github.com/lwhite1/tablesaw/blob/master/src/main/java/com/github/lwhite1/tablesaw/util/DictionaryMap.java#L80 the documentation claims that the String[] categoryArray will be in order of the numeric key, but because it is being derived from a Int2ObjectOpenHashMap there is no guarantee that this will be true.

**Comment by lwhite1** [comment]
First, apologies for taking so long to get to this. 

Is this something that can be fixed by correcting the documentation or is there a use-case where you need the results to be in key order?

**Comment by batterseapower** [comment]
No problem at all.

 I think in general the sorted representation is quite useful, because it has the nice property that you can find the string associated with a particular int value by just indexing into the array. This is indeed what I wanted to do in the application I was writing when I raised the issue. So personally I think it would better to fix the implementation than the documentation.

**Comment by lwhite1** [comment]
Off the top of my head, I think there is a risk in doing what you are suggesting. As long as your dataset is immutable you're fine, but If any of the values change you may end up violating the assumption that the there is a match between the index and the key.  Beyond that, my primary concern is adding the overhead of the sort where it may not generally be needed.

**Comment by batterseapower** [comment]
You are right to say that using this pattern is a potential risk with mutable data. But nonetheless there are many safe ways to use it.

I don't think that the sort will be a big perf hit -- after all, the whole idea of a category data type is that there shouldn't be too many unique values in the array. You can always add a categoryArrayUnsorted later if perf does prove to be a problem.

**Comment by lwhite1** [comment]
Will not fix, as the dictionary map should not be accessible in the first place. Keeping it so will make future improvements difficult.
