### ISSUE TITLE
DoubleColumn.set takes a float, not a double

### ISSUE THREAD

**Issue by batterseapower** [jtablesaw/tablesaw#112]
Presumably just a copy-paste error.

https://github.com/lwhite1/tablesaw/blob/master/src/main/java/com/github/lwhite1/tablesaw/api/DoubleColumn.java#L630

**Comment by lwhite1** [comment]
It is fixed in the next release. Not sure of the timing yet.

**Comment by batterseapower** [comment]
Ah, you're getting rid of float support. That's a bit sad, but OK.

As I'm sure you are aware, other projects which need to do unboxing in Java use code generation to avoid the maintenance headache of copy-pasting code: https://github.com/vigna/fastutil/blob/master/drv/ArrayList.drv. Maybe worth considering as an alternative to reducing the number of supported types.

**Comment by lwhite1** [comment]
Yes. That's a lot easier with things like collections where the API is the same regardless of the type. When you're trying to do type specific operations like math it's not as straightforward.

**Comment by lwhite1** [comment]
fixed

**Comment by batterseapower** [comment]
Thanks!
