### ISSUE TITLE
Convert ColumnType to Class

### ISSUE THREAD

**Issue by tischi** [jtablesaw/tablesaw#1128]
Hi!

Thanks a lot for developing this great library!

Should one use the issues to ask questions or is there some other chat channel for this?

I would like to know whether there is something to convert `ColumnType` to `Class`.
Something like  `String.class = getClass( ColumnType.String )`?

**Comment by lwhite1** [comment]
FWIW, the mapping is:
String, Text -> String
Boolean and numeric columns -> their Java equivalent (or the unboxed version)
InstantColumn -> Instant
Date, DateTime, Time -> LocalDate, LocalDateTime, LocalTIme

**Comment by tischi** [comment]
Thanks a lot! 
Good idea! 
I will then just add the corresponding `Map<ColumnType, Class>` to my code.

**Comment by tischi** [comment]
Implemented like this:

```Java
public abstract class TableSawColumnTypes
{
	public static Map< ColumnType, Class< ? > > typeToClass;
	static {
		typeToClass = new HashMap<>();
		typeToClass.put( ColumnType.STRING, String.class );
		typeToClass.put( ColumnType.DOUBLE, Double.class );
		typeToClass.put( ColumnType.INTEGER, Integer.class );
		typeToClass.put( ColumnType.SHORT, Short.class );
		typeToClass.put( ColumnType.LONG, Long.class );
		//...
	}
}
```
