### ISSUE TITLE
reversing columns or rows

### ISSUE THREAD

**Issue by PeteSahad** [jtablesaw/tablesaw#1130]
How do I reverse columns or rows. Like with python x=x[::-1]

**Comment by lwhite1** [comment]
There's no built-in function for those operations.

If i wanted to reverse rows, I would:
- create an index column. There is a class method on IntColumn for doing
that.
- add it to the table
- sort the table on that column in descending order
- remove the column

Reversing columns is a bit trickier. There is a method on Table called
reorderColumns that takes an array of column names.
i would probably create the array
loop over the columns in reverse order using a for loop and selecting each
column by index
put the name of each name in the array.
pass that array to table.reorderColumns()

**Comment by PeteSahad** [comment]
yeah, I did the reorderColumns-way in the end.

I just thought I was too blind to find the proper function.

Thanks for the feedback, though!

**Comment by lwhite1** [comment]
closing
