### ISSUE TITLE
not reading after "0" value in row.

### ISSUE THREAD

**Issue by Piyush-Shell** [jtablesaw/tablesaw#1147]
I want to read excel where data is as follows.

col1, col2, col3
0, 0, 0
1, 10, 20
2, 30, 40

So its only parsing the header and no data, but if I change any of "0" value like,

col1, col2, col3
0, 0, 1
1, 10, 20
2, 30, 40

then it reads the entire table. Also if parse table like,

col1, col2, col3
1, 10, 20
0, 0, 0
2, 30, 40

then it only reads till row (1, 10, 20) and no data after that.

Can anyone suggest why when an entire row is "0" it is not parsing the rows, and how to read such tables?

**Comment by lwhite1** [comment]
I'm just guessing as i'm not really familiar with this, but i believe the
code uses an Apache library for the Excel parsing, and it relies on
Excel's interpretation of what type is found in a cell. I suspect it is
treating '0' as a missing value.

**Comment by mo20053444** [comment]
@lwhite1 Hi! I created a PR to fix this issue [(link)](https://github.com/jtablesaw/tablesaw/pull/1149#issue-1380884443)
Would you mind taking a look?
Many thanks!
