### ISSUE TITLE
Minimal jars and maven dependency

### ISSUE THREAD

**Issue by tischi** [jtablesaw/tablesaw#1155]
Hi,

I am depending on tablesaw like this:

```
        <dependency>
            <groupId>tech.tablesaw</groupId>
            <artifactId>tablesaw-core</artifactId>
            <version>0.43.1</version>
        </dependency>
```

In addition to the `tablesaw-core.jar` there are a couple of transitive dependencies. 

Do you know whether all of them are needed for it to work?

Examples: `fastutils`, `univocity-parsers`, `RoaringBitmap`

**Comment by lwhite1** [comment]
Yes they’re needed.  Fwiw.  I don’t think any are  very large, but I could
be wrong.

**Comment by HannesWell** [comment]
> Yes they’re needed. Fwiw. I don’t think any are very large, but I could be wrong.

Can you say if `fastutil-core` would maybe be sufficient? That stripped down version is significantly smaller than the full `fastutil`.
