### ISSUE TITLE
How to join two tables with identical column names

### ISSUE THREAD

**Issue by tischi** [jtablesaw/tablesaw#1168]
We would like to join tables. Right now we are using:

```
table = table.joinOn( joinByColumns ).leftOuter( additionalTable  );
```

Challenges:
  - `additionalTable` has columns that exist already in `table`.
  - `additionalTable` may have missing rows.

We would like to have it such that values in `additionalTable` should _replace_ the values in `table` in columns with duplicate names.

Is there an implementation for this?

**Comment by lwhite1** [comment]
there's a flag for handling duplicate column names in the implementation of
leftOuter, I think.
missing rows should be fine due to the use of leftOuter.

**Comment by tischi** [comment]
Thanks! In fact, I saw this but it does not replace the duplicate columns but rather keeps all by means of renaming. A `replaceDuplicateColumns` option would be what we are after...

```
/**
   * Joins to the given tables assuming that they have a column of the name we're joining on
   *
   * @param allowDuplicateColumnNames if {@code false} the join will fail if any columns other than
   *     the join column have the same name if {@code true} the join will succeed and duplicate
   *     columns are renamed*
   * @param tables The tables to join with
   * @return The resulting table
   */
  public Table leftOuter(boolean allowDuplicateColumnNames, Table... tables) 
```

**Comment by lwhite1** [comment]
That doesn't seem like a standard option for this kind of thing. I don't
understand why you want to "keep" the right side columns but replace them
with the values from the left side. I assume this would leave you with two
columns in the table for every duplicate, all pairs having the same data.
Is that what you want?

If the renaming is a concern, Tablesaw doesn't allow two columns with the
same name in a table, so it's not an option to duplicate without a name
change.

If it were me I would try to write something that found all the duplicate
names and did a column replace on the right side version using a copy of
the left side column as the argument, but i still might not be getting what
you need.

**Comment by tischi** [comment]
> I don't understand why you want to "keep" the right side columns but replace them
with the values from the left side.

We need it want it the other way around: replace the columns on the left with the columns on the right.

> If it were me I would try to write something that found all the duplicate
names and did a column replace

That sounds good! Is there something to directly replace a column, or would I need to do a column removal followed by an addition?

**Comment by lwhite1** [comment]
there is a replace method

**Comment by tischi** [comment]
Thanks a lot for your help!
