### ISSUE TITLE
IntColumns returning double types for min/max/median/sum

### ISSUE THREAD

**Issue by minhster99** [jtablesaw/tablesaw#1172]
Just thought I'd raise this minor bug. When calling the min/max/median/sum functions on an intColumn, the return type is double which isn't right. It should be integers. We can work around the problem by casting it to an int.

eg
double min = table.intColumn("my integers").min();
table.intColumn("my integers").setMissingTo( (int) min)

note the need to cast

**Comment by lwhite1** [comment]
This is a known issue. It is done so that the results of min() etc., can be
consistent across all numeric column types, which allows them to be put in
the same column as results from other types.
I don't see this changing.

**Comment by minhster99** [comment]
fair enough
