### ISSUE TITLE
don't see new versions of tablesaw

### ISSUE THREAD

**Issue by tymsoncyferki** [jtablesaw/tablesaw#1180]
Hi, the latest version that is recognized by intellij is 0.25.1.  Been trying to add it both in project structure and by editing pom.xml file. Any tips?
![Screenshot 2023-01-21 172732](https://user-images.githubusercontent.com/115067539/213876716-5e36ed0e-780b-48c5-8737-89cd5b280a18.png)

**Comment by lwhite1** [comment]
Are you looking at maven central?  You can check it using your browser to
see what versions are there.

**Comment by tymsoncyferki** [comment]
Oh, i did not check there. Thought adding library "from maven" would do the work. Thanks a lot, now its up and running
