### ISSUE TITLE
Printing out a table.first or table.where(Selection) causes an exception

### ISSUE THREAD

**Issue by pyrator** [jtablesaw/tablesaw#1196]
### Discussed in https://github.com/jtablesaw/tablesaw/discussions/1194

<div type='discussions-op-text'>

<sup>Originally posted by **pyrator** March 19, 2023</sup>
The table has been read from a csv file. Altering the table and viewing the table structure or saving to csv file works ok, but
    System.out.println(table.first(10));  causes:
Receiver class tech.tablesaw.selection.BitmapBackedSelection$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object next()' of interface java.util.Iterator.
	at tech.tablesaw.api.Table.copyRowsToTable(Table.java:510)
	at tech.tablesaw.api.Table.where(Table.java:854)
	at tech.tablesaw.api.Table.inRange(Table.java:828)
	at tech.tablesaw.api.Table.first(Table.java:653)
	at uk.khall.openai.TestTablesaw.main(TestTablesaw.java:19)

Note that line Table.java:653 refers to an empty line in https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/api/Table.java
I wonder if there is some sort of mismatch between Maven Repository and current source

    Selection smallToken = tokenColumn.isLessThan(1001);
    Table resultTable = table.where(smallToken); also causes this:
 Exception in thread "main" java.lang.AbstractMethodError: Receiver class tech.tablesaw.selection.BitmapBackedSelection$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object next()' of interface java.util.Iterator.

My maven dependency is 
        <dependency>
            <groupId>tech.tablesaw</groupId>
            <artifactId>tablesaw-core</artifactId>
            <version>0.43.1</version>
        </dependency>
During debugging the table itself in Intellij is shown as an empty string, but the table structure, columnList etc. can be seen correctly.
I am running this with Java jdk-17.0.1 in Windows 11
the csv file has been downloaded from 
https://github.com/openai/openai-cookbook/tree/main/examples/data/fine_food_reviews_1k.csv

Thanks</div>
[TestTablesaw.txt](https://github.com/jtablesaw/tablesaw/files/11028596/TestTablesaw.txt)

**Comment by lwhite1** [comment]
If you’re getting an error like that at runtime, my guess is there’s a
problem with the dependencies in your project.  A class that implements
iterator but not next() should not compile.

**Comment by pyrator** [comment]
Yes you're right. I think there are dependency issues. I've split off the part that is just requiring tablesaw and changed my maven build accordingly and that now works correctly. 
Strange that I've never encountered this before.
