### ISSUE TITLE
How to summarize a StringColumn

### ISSUE THREAD

**Issue by tischi** [jtablesaw/tablesaw#1199]
Hi, 

I need to summarize a StringColumn.

Are there any AggregateFunctions for this?

**Comment by lwhite1** [comment]
I don’t recall if there are any.  If there are you should be able to find
them in the package with the other aggregation functions.

The main issue is that there’s no obvious answer to the question “how would
I aggregate a string column”.  Once you know what you want to say about the
strings you can probably write something to do it.

**Comment by tischi** [comment]
Thanks @lwhite1, for me, picking the first one would work.

I therefore tried this:

```
/** A function that takes a column argument and returns the earliest Instant in that column */
  public static final InstantAggregateFunction minInstant =
      new InstantAggregateFunction("Min Instant") {
        @Override
        public Instant summarize(InstantColumn column) {
          return column.min();
        }
      };
```

But it threw me an error for columns of type String.

I guess it should be easy to implement an own `AggregateFunction` that would simply return the first item in the column?

**Comment by lwhite1** [comment]
You have to write your function to extend StringAggregateFunction.

Something like this should work:

  public static final StringAggregateFunction firstString =
      new StringAggregateFunction("First String") {
        @Override
        public String summarize(StringColumn column) {

          if (column.size() > 0) return column.get(0);

          return "";

        }

      };

**Comment by tischi** [comment]
Thanks that works perfectly!!
