### ISSUE TITLE
IllegalArgumentException when creating a simple OHLC plot

### ISSUE THREAD

**Issue by francescopeloi** [jtablesaw/tablesaw#1237]
I replicated with a small test a problem that I found when generating an OHLC plot, this test throws a IllegalArgumentException but I don't understand why. Am I doing anything wrong in here?

    @Test
    void createsIllegalArgumentException() {
        String timeTitle = "time";
        String openTitle = "open";
        String closeTitle = "close";
        String highTitle = "high";
        String lowTitle = "low";
        String graphTitle = "title";

        LocalDateTime now = LocalDateTime.now();
        List<LocalDateTime> time = List.of(now, now.plusSeconds(5), now.plusSeconds(10));
        List<BigDecimal> open = List.of(BigDecimal.ONE, BigDecimal.TWO, BigDecimal.TEN);
        List<BigDecimal> close = List.of(BigDecimal.ONE, BigDecimal.TWO, BigDecimal.TEN);
        List<BigDecimal> high = List.of(BigDecimal.ONE, BigDecimal.TWO, BigDecimal.TEN);
        List<BigDecimal> low = List.of(BigDecimal.ONE, BigDecimal.TWO, BigDecimal.TEN);

        DateTimeColumn timeColumn = DateTimeColumn.create(timeTitle, time);
        DoubleColumn openColumn = DoubleColumn.create(openTitle, open);
        DoubleColumn closeColumn = DoubleColumn.create(closeTitle, close);
        DoubleColumn highColumn = DoubleColumn.create(highTitle, high);
        DoubleColumn lowColumn = DoubleColumn.create(lowTitle, low);

        Table priceTable = Table.create(timeColumn, openColumn, closeColumn, highColumn, lowColumn);
        OHLCPlot.create(graphTitle, priceTable, timeTitle, openTitle, highTitle, lowTitle, closeTitle);
    }

**Comment by lwhite1** [comment]
BigDecimal is not supported. Use ints or longs if you can.

**Comment by francescopeloi** [comment]
I tried with Integers just in case, throws the same expection on my message above.

**Comment by francescopeloi** [comment]
This is the code that fails: https://github.com/jtablesaw/tablesaw/blob/master/jsplot/src/main/java/tech/tablesaw/plotly/api/PricePlot.java#L35

It's comparing 2 different instances so the result of the comparison is false, and then the flow goes into the exception branch.

**Comment by francescopeloi** [comment]
@lwhite1 I created a PR for it: https://github.com/jtablesaw/tablesaw/pull/1238
