### ISSUE TITLE
Inconsistent Column creation API

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#126]
To create an `IntColumn` I need to call `IntColumn.create`. For every other `Column` type I can call their constructors. I don't know why we would use factory methods in this case, so it seems like it'd make sense to make the `IntColumn` constructors public

**Comment by lwhite1** [comment]
Ok. They should certainly be consistent. I guess standardizing on constructors is fine. I would be happy to clean this up and make sure it's consistent across all column types. I expect I can get to it this evening.

**Comment by benmccann** [comment]
Fixed via https://github.com/jtablesaw/tablesaw/commit/c2953532ff3cb369e029a4994fa284c88aee37de

Allows porting back to tablesaw in the following line in deeplearning4j: https://github.com/deeplearning4j/DataVec/blob/30936e1d5523fae76fdf3fa3ccfc07458f5d118f/datavec-local/src/main/java/org/datavec/local/transforms/TableRecords.java#L865

**Comment by lwhite1** [comment]
I think we need to be clear about how to construct instances. I have
extended your changes to mark the .create() methods private. Alternatively
I could deprecate them, but I think it's not unreasonable to make them
private at this stage in the project. Let me know if you feel differently.

**Comment by benmccann** [comment]
I'm fine with making them private, but in that case I'm guessing nothing would be calling them, so it'd probably be better to just delete them?

**Comment by lwhite1** [comment]
yes. Most could be deleted with a bit more cleanup. I'll do that in a
subsequent push
