### ISSUE TITLE
read/write api

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#129]
Spark and Morpheus both have read/write APIs that I found well-structured. E.g. `spark.read.json` or `DataFrame.read().csv`. I'm wondering if it would make sense to model our APIs similarly

**Comment by lwhite1** [comment]
I'm not familiar with Morpheus. Would you be able to prototype a couple methods in the context of Tablesaw so I could better understand the proposal.

**Comment by benmccann** [comment]
Basically instead of Table.createFromCsv(file) we'd have Table.read().csv(file).  The thing I like about this API is that it's easy to discover all the read/write related methods because they're all nicely organized in the same reader or writer class. It's nice for the people calling the methods and also for us as library authors in organizing the code.

**Comment by lwhite1** [comment]
How would it handle non-default file attributes? For example, if it is tab-delimited or has no header?

**Comment by benmccann** [comment]
The Morpheus API looks like:

```
DataFrame.read().csv(options -> {
  options.setResource("http://zavtech.com/data/samples/cars93.csv");
    options.setExcludeColumnIndexes(0);
})
```

The spark API looks like:

```
sqlContext.read.format("com.databricks.spark.csv") .option("header", "true") .load("/home/CaseData_1000.csv")
```

They both provide the ability to register new reader types. E.g. in Morpheus you can do:

```
DataFrame<LocalDate,YahooField> frame = DataFrame.read().apply(YahooQuoteHistoryOptions.class, options -> {
                options.setTicker(ticker);
                options.setStart(start);
                options.setEnd(end);
                options.setAdjustForSplits(true);
            });
```

**Comment by lwhite1** [comment]
They both look nice.

I guess using an external format file allows you to register new types, but
I think I'd like to hide that bit if possible, so perhaps we could have
methods for common formats. Like so:

sqlContext.read.formatCsv.option("header", "true")
.load("/home/CaseData_1000.csv")

what do you think?

**Comment by benmccann** [comment]
Agreed. I also think we should have typesafe options objects instead of sting options, so much closer to the Morpheus example. Though I'd make the setters chainable. I'll try to put together a more concrete proposal on Sunday and possibly send a PR if this is making sense

**Comment by lwhite1** [comment]
Sounds good
