### ISSUE TITLE
Support for multiple backends?

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#130]
I saw that Morpheus has dense, mapped, and sparse columns. Would this make sense?

https://github.com/zavtech/morpheus-core/tree/master/src/main/java/com/zavtech/morpheus/array

**Comment by lwhite1** [comment]
Overall, I like the idea. Multiple backends are interesting, and I like what Morpheus has done. I have considered for some time using off-heap memory for a second backend, and found a library I like to help with that. I assume this is what Morpheus' mapped backend does. It would require some additional research to look into what it would take to provide the same functionality as the current tablesaw.

A couple concerns spring to mind: How does sorting work? Is there a performance hit for common operations? (Obviously there should be a memory savings). Can you do range queries on an off-heap back-end? etc.

As to timing, I have some concern about adding more backends before some of the core functionality is complete. I suspect it would slow down feature development and we're still missing some big things like joins.
