### ISSUE TITLE
Implement a Bubble Plot

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#133]
Using xChart create an interface that enables easy rendering of a bubble plot from a tablesaw table. See the implementation of scatter plots for a very similar example.  The task is basically to add a new chart type for BubblePlot, with a constructor that takes exactly three columns of numeric data (subclasses of NumericColumn)

https://github.com/jtablesaw/tablesaw/blob/master/plot/src/main/java/tech/tablesaw/api/plot/Scatter.java

**Comment by mario-s** [comment]
I can offer a helping hand here.

**Comment by lwhite1** [comment]
That would be great! Thanks.

**Comment by mario-s** [comment]
@lwhite1 Could you assign this issue to me? Thanks.

**Comment by lwhite1** [comment]
@mario-s I don't think I can 'assign' anyone unless they're a member of the project, but it's not necessary in any case. The contributors guide describes the usual approach: https://jtablesaw.github.io/tablesaw/contributing

**Comment by mario-s** [comment]
One questions regarding GUI-Test: I see that the Test are written as examples with a main methods. Is this intend for interested users to get a feeling of how to use API?
I'm asking this because I would like to write the test with Jemmy.
http://wiki.netbeans.org/Jemmy

**Comment by lwhite1** [comment]
Implemented by @mario-s. Closing
