### ISSUE TITLE
Eliminate deprecation warnings

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#134]
A number of the libraries we rely on have changed their APIs recently, including OpenCSV, RoaringBitmaps, FastUtil, and commons.lang3. The current list of warnings is below: 

/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/Table.java
    Warning:Warning:line (1,119)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/BooleanColumn.java
    Warning:Warning:line (151)java: entrySet() in it.unimi.dsi.fastutil.bytes.Byte2IntMap has been deprecated
    Warning:Warning:line (424)java: add(java.lang.Boolean) in it.unimi.dsi.fastutil.booleans.BooleanSet has been deprecated
    Warning:Warning:line (430)java: contains(java.lang.Object) in it.unimi.dsi.fastutil.bytes.AbstractByteCollection has been deprecated
    Warning:Warning:line (501)java: next() in it.unimi.dsi.fastutil.bytes.ByteIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/table/TemporaryView.java
    Warning:Warning:line (119)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
    Warning:Warning:line (149)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
    Warning:Warning:line (316)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/CategoryColumn.java
    Warning:Warning:line (205)java: entrySet() in it.unimi.dsi.fastutil.ints.Int2IntMap has been deprecated
    Warning:Warning:line (635)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/mapping/StringMapUtils.java
    Warning:Warning:line (168)java: getLevenshteinDistance(java.lang.CharSequence,java.lang.CharSequence) in org.apache.commons.lang3.StringUtils has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/ShortColumn.java
    Warning:Warning:line (139)java: next() in it.unimi.dsi.fastutil.shorts.ShortIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/LongColumn.java
    Warning:Warning:line (142)java: next() in it.unimi.dsi.fastutil.longs.LongIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/DateColumn.java
    Warning:Warning:line (764)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/TimeColumn.java
    Warning:Warning:line (558)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
    Warning:Warning:line (818)java: next() in it.unimi.dsi.fastutil.longs.LongIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/util/DictionaryMap.java
    Warning:Warning:line (52)java: remove(java.lang.Object) in it.unimi.dsi.fastutil.objects.Object2IntMap has been deprecated
    Warning:Warning:line (56)java: remove(java.lang.Object) in it.unimi.dsi.fastutil.objects.Object2IntMap has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/util/BitmapBackedSelection.java
    Warning:Warning:line (93)java: add(int,int) in org.roaringbitmap.RoaringBitmap has been deprecated
    Warning:Warning:line (139)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/io/csv/CsvCombiner.java
    Warning:Warning:line (28)java: CSVWriter(java.io.Writer,char) in com.opencsv.CSVWriter has been deprecated
    Warning:Warning:line (45)java: CSVReader(java.io.Reader,char) in com.opencsv.CSVReader has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
    Warning:Warning:line (280)java: CSVReader(java.io.Reader,char,char) in com.opencsv.CSVReader has been deprecated
    Warning:Warning:line (426)java: CSVReader(java.io.Reader,char,char,int) in com.opencsv.CSVReader has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/test/java/tech/tablesaw/examples/ObservationDataTest.java
    Warning:Warning:line (18)java: org.apache.commons.lang3.RandomStringUtils in org.apache.commons.lang3 has been deprecated
    Warning:Warning:line (164)java: org.apache.commons.lang3.RandomStringUtils in org.apache.commons.lang3 has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/test/java/tech/tablesaw/filters/TimeDependentFilteringTest.java
    Warning:Warning:line (18)java: org.apache.commons.lang3.RandomStringUtils in org.apache.commons.lang3 has been deprecated
    Warning:Warning:line (169)java: org.apache.commons.lang3.RandomStringUtils in org.apache.commons.lang3 has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java
    Warning:Warning:line (178)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated
/Users/larrywhite/IdeaProjects/jtablesaw/tablesaw/core/src/test/java/tech/tablesaw/api/FloatColumnTest.java
    Warning:Warning:line (182)java: next() in it.unimi.dsi.fastutil.ints.IntIterator has been deprecated

**Comment by benmccann** [comment]
@lwhite1 I've fixed the majority of these. I left a small handful that I thought you would know better how to fix. Can you take a stab at the remaining?

Description	Resource	Path	Location	Type
'next(): Int!' is deprecated. Deprecated in Java	Col.kt	/tablesaw-core/src/main/kotlin/tech/tablesaw/kapi	Unknown	Java Problem
'next(): Int!' is deprecated. Deprecated in Java	IntCol.kt	/tablesaw-core/src/main/kotlin/tech/tablesaw/kapi	Unknown	Java Problem
The corresponding parameter in the supertype 'NumericCol' is named 'index'. This may cause problems when calling this function with named arguments.	IntCol.kt	/tablesaw-core/src/main/kotlin/tech/tablesaw/kapi	Unknown	Java Problem
The method add(Boolean) from the type BooleanSet is deprecated	BooleanColumn.java	/tablesaw-core/src/main/java/tech/tablesaw/api	line 418	Java Problem
The method add(int, int) from the type RoaringBitmap is deprecated	BitmapBackedSelection.java	/tablesaw-core/src/main/java/tech/tablesaw/util	line 93	Java Problem
The method contains(Object) from the type AbstractByteCollection is deprecated	BooleanColumn.java	/tablesaw-core/src/main/java/tech/tablesaw/api	line 424	Java Problem
The method remove(Object) from the type Object2IntMap<String> is deprecated	DictionaryMap.java	/tablesaw-core/src/main/java/tech/tablesaw/util	line 56	Java Problem

**Comment by benmccann** [comment]
Btw, I fixed all the compilation warnings except for the above. Not just the deprecation warnings

**Comment by lwhite1** [comment]
thanks, Ben! I will look into the rest of them

**Comment by lwhite1** [comment]
done
