### ISSUE TITLE
Move user guide documentation to github so it can be maintained collaboratively

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#137]

**Comment by benmccann** [comment]
What do you think about using gitbook to generate the docs? I also contribute to chart.js who use it for their docs: http://www.chartjs.org/docs/latest/

I personally prefer single page docs, which can also be generated, but chart.js made it multi-page.

Do you know how the deploy process would work? Would we create it in this repo or a separate repo or does it matter?

**Comment by benmccann** [comment]
Maybe you would be able to use a tool like one of the below to do ~80% of the conversion?

https://github.com/thomasf/exitwp
https://github.com/dreikanter/wp2md

**Comment by lwhite1** [comment]
I was thinking of using git pages, which require a separate repo.
I will take a look at git book and chart.js also

**Comment by lwhite1** [comment]
oooh. good. thanks.

**Comment by benmccann** [comment]
agreed on github pages

**Comment by lwhite1** [comment]
closing. Moved, but needs work.

**Comment by benmccann** [comment]
Woohoo! This is great!

I just pushed a few improvements. Not sure if they'll get automatically deployed or not...

**Comment by lwhite1** [comment]
yeah. pushing = deploying
