### ISSUE TITLE
Remove hardcoded "/Users/larrywhite" from examples

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#139]
We have directories like `/Users/larrywhite/IdeaProjects/testdata/bigdata`

Maybe we could use something like `~/tablesaw-data` as a default instead?

**Comment by lwhite1** [comment]
the big problem here is that these tests use "bigdata" or at least those
that reference "testdata/bigdata" do. I think the right thing to do is to
remove them and put them in a separate project, along with instructions on
where to find the data on the web. The data in question is too large to put
into our github repo.

what do you think?

**Comment by lwhite1** [comment]
fixed. I removed the big data tests

**Comment by benmccann** [comment]
I don't know that we necessarily have to remove these or put them in a separate repo. I think they can be nice to have in the main repo. E.g. it was helpful to me to have the taxi example for improving the csv loading time. I like the idea of providing instructions on where to find the data on the web though. And then maybe we can just change the paths to be relative paths to a git ignored directory or use something like `${HOME}/tablesaw/` instead of `/Users/larrywhite/IdeaProjects`

**Comment by yuj** [comment]
`${HOME}/tablesaw/` is a pretty good choice.

**Comment by lwhite1** [comment]
will ${HOME}/tablesaw/ that work on Windows?

**Comment by yuj** [comment]
Actually I meant `${USER.HOME}/tablesaw/`.

Specifically, System.getProperty("user.home");    // user's home directory. should work cross-OS with Java 8

**Comment by benmccann** [comment]
Yeah, System.getProperty("user.home") looks like it will work cross-platform. What do you think about that @lwhite1?

**Comment by lwhite1** [comment]
i like it. :)

I seem to have broken the build tho, with some odd javadoc errors so i'm
 not sure when i'll get to it
