### ISSUE TITLE
JavaDocs link broken on Wordpress site

### ISSUE THREAD

**Issue by jimmoores** [jtablesaw/tablesaw#143]
the current link [http://lwhite1.github.io/tablesaw/apidocs/](http://lwhite1.github.io/tablesaw/apidocs/), returns a 404 for me.

**Comment by lwhite1** [comment]
Thank you very much Jim for reporting this issue.

The javadoc, is probably hanging off my personal account. In any case, it's
way out of date.

The fix for this issue should include a way of automating the deployment of
fresh javadoc on a regular basis.

**Comment by lwhite1** [comment]
Fixed. Will open a separate ticket for automating deployment of javascript

**Comment by jimmoores** [comment]
Thanks!

**Comment by lwhite1** [comment]
My pleasure. Thanks again for trying Tablesaw.
