### ISSUE TITLE
Implement interface for hierarchical clustering using Smile

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#144]
Implement an interface to perform hierarchical cluster using Smile's implementation of the algorithm.  See the Non-hierarchical cluster interface code that has been implemented.

**Comment by crew102** [comment]
Greetings, I've been working on this issue and wanted to see if it's OK if I introduce a dependency on smile-math in tablesaw? There are various implementations/measures of distance provided in the `smile.math.distance` package that would be helpful when creating the proximity matrix that is required for both hierarchical clustering and MDS (e.g., #149 ).

**Comment by lwhite1** [comment]
As long as it's limited to the tablesaw-smile artifact that would be fine.
Thanks very much!
