### ISSUE TITLE
[Question] Conversion of String attributes to Numbers 

### ISSUE THREAD

**Issue by Malkitti** [jtablesaw/tablesaw#153]
Consider a  machine learning problem where the training CSV has  9 columns.  The "site" is the one that we need to predict. How we can convert  this string value to number so that we can  apply machine learning algorithms on the top of it.  For instance, in the case of Spark we have 
  StringIndexer().

"","site","parcel","code","island","id","plot","trt","ears","harvwt"
"1","DBAN","I",58,1,3,3,111,43.5,5.16
"2","LFAN","I",58,1,40,4,111,40.5,2.93

**Comment by lwhite1** [comment]
For classifiers, it's done automatically. For example:

```
    public static LogisticRegression learn(CategoryColumn labels, NumericColumn... predictors) {
        smile.classification.LogisticRegression classifierModel =
                new smile.classification.LogisticRegression(DoubleArrays.to2dArray(predictors), labels.data().toIntArray());
        return new LogisticRegression(classifierModel);
    }

```
The predicted values in the CategoryColumn 'labels' are converted to ints by the method invocation labels.data().toIntArray(). 

So you shouldn't have to do anything.

**Comment by lwhite1** [comment]
I should have added that when you interpret the results of the model (as by creating a confusion matrix), the ints are automatically converted back to the original labels so your output is easier to interpret.

**Comment by lwhite1** [comment]
Closing as answered. LMK if you are unsatisfied with the answer in any way and I'll re-open
