### ISSUE TITLE
automate creation of javadoc in /docs/apidocs

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#154]
should be able to build with javadoc:javadoc maven target and have output placed in the 
(project root/docs/) in the core and plot subdirectories

**Comment by benmccann** [comment]
Most projects I see just have a single apidocs directory with the docs for all their modules aggregated together

E.g. the [Play Framework javadocs](https://www.playframework.com/documentation/2.6.x/api/java/index.html) have the javadocs for the core modules as well as non-core modules like their cache module
The [Spark javadocs](https://spark.apache.org/docs/latest/api/java/index.html) includes the javadocs for extra modules like the sql module and mllib module
These were just the first two I checked, but I'm fairly sure that's what most projects do.

Maybe we should switch to doing it that way? It has the nice side-effect of being easier to generate and manage :-)

**Comment by lwhite1** [comment]
That would actually be my preference, but i had two issues/concerns. 

First, the default behavior of javadoc was to write them to separate directories under the project. 

Second, I wasn't sure that when you split the project, we didn't end up with classes with the same names in each section, so I was nervous about trying to address issue 1 in case documentation might get over-written.

**Comment by benmccann** [comment]
We'd have worse problems than the documentation if we had two classes with the same fully qualified name. That would cause users not to be able to use one of the classes and would cause runtime exceptions. We'll have to make sure to avoid that regardless.

**Comment by benmccann** [comment]
I just tried creating a duplicate class. It broke compilation, such that I couldn't compile Tablesaw
