### ISSUE TITLE
Move CONTRIBUTING.md to docs directory

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#156]
It would be nice to have the contributors guide on the website

**Comment by lwhite1** [comment]
Indeed.

**Comment by benmccann** [comment]
It looks like we have two copies now? One in docs/contributing.md and one in docs/contributing/CONTRIBUTING.md

**Comment by lwhite1** [comment]
Yeah.  I've been trying to get either to render as a web page but it
doesn't work. Not sure why yet.

Do you see the same issue?

I will clean up when I get it figured out.

**Comment by lwhite1** [comment]
hmm. Couldn't get it to work so went to StackOverflow and got this:

Github Pages doesn't support building Jekyll pages from files that have names that Github recognizes for other purposes. These file names include (in addition to their lowercase versions):

CONTRIBUTING.md

So there's no way to have it render as html. Unless you have some ideas

**Comment by benmccann** [comment]
Maybe we should just rename to contributors-guide.md or something

**Comment by lwhite1** [comment]
yeah that's probably the best alternative. it just won't be linked anymore
to the github UI, so there won't be a link displayed when people are
opening bugs or whatnot.

but, yeah, i'll rename it.

**Comment by lwhite1** [comment]
stack exchange came thru with solution. fixed

**Comment by benmccann** [comment]
that's awesome! the new docs are looking really good!

it looks like there's a few things we could migrate over still:
* the [getting started](https://jtablesaw.wordpress.com/an-introduction/)
* [k-means](https://jtablesaw.wordpress.com/2016/08/08/k-means-clustering-in-java/) / [knn](https://jtablesaw.wordpress.com/2016/08/06/a-k-nearest-neighbors-classifier-in-java/)
* [plotting](https://jtablesaw.wordpress.com/2016/07/30/new-plot-types-in-tablesaw/) / [graphics](https://jtablesaw.wordpress.com/2016/07/17/tablesaw-gets-graphic/)
