### ISSUE TITLE
CategoryColumn#size != CategoryColumn#toList()#size()

### ISSUE THREAD

**Issue by jorgaf** [jtablesaw/tablesaw#158]
I am not sure if this is an issue.

I have an object from CategoryColumn catColumn = table.categoryColumn(...) and when execute the catColumn.size() and catColumn.toList().size() each method show me different values.

I am thinking the method toList() is returning a list with unique values.

**Comment by lwhite1** [comment]
That's what it is doing. It's probably not what it should be doing. Let me
look into clearing this up

**Comment by lwhite1** [comment]
fixed in 0.9.2-SNAPSHOT

**Comment by lwhite1** [comment]
Thanks very much for the bug report. Sorry for the inconvenience!

**Comment by benmccann** [comment]
@jorgaf I've cut a new release for you
