### ISSUE TITLE
java doc build is failing with numerous errors

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#159]
error: cannot find symbol is occurring frequently in the build, with references to different symbols in different classes/methods.  Symbols include 'import' and 'public' among other things.

Related issue. the output of the javadoc phase is still written to the core/apidocs and plot/apidocs folders separately, rather than being combined in docs/apidocs

**Comment by benmccann** [comment]
There was only one error. I fixed it with the fix below:

    - * Returns a List<String> representation of all the values in this column
    + * Returns a List&lt;String&gt; representation of all the values in this column

**Comment by lwhite1** [comment]
thanks.

**Comment by benmccann** [comment]
`javadoc:aggregate` does the right thing. But it does seems like there's something that causes docs to be output to core/apidocs and plot/apidocs in some cases. I'm hoping I just fixed that as well.
