### ISSUE TITLE
Implement interface to DeepLearning4J as a separate module

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#161]
This project is at the "needs research/design" stage to see what would be involved, and how good we can make the integration.

**Comment by benmccann** [comment]
deeplearning4j/DataVec uses Tablesaw

**Comment by lwhite1** [comment]
Close if you like

**Comment by hswick** [comment]
@benmccann do you know of any examples using dl4j and tablesaw? dl4j-examples/datavec-examples only has examples for spark

**Comment by agibsonccc** [comment]
@hswick @benmccann Personally, what I'd like to see is a pandas like experience connecting nd4j to tablesaw. In this case, data frame -> a matrix would be pretty cool. For datavec..we still need to work on the datavec local module which allows tablesaw as a backend.

**Comment by lokinell** [comment]
@benmccann Do you have a plan to integrate tablesaw with h2o?

**Comment by benmccann** [comment]
Nope
