### ISSUE TITLE
Complete migration of docs to github

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#165]
The new docs are looking really good. We should finish migrating and then point [tablesaw.tech](http://tablesaw.tech) at them.

It looks like there's a few things we should consider migrating over first though:
* [the getting started](https://jtablesaw.wordpress.com/an-introduction/)
* [k-means](https://jtablesaw.wordpress.com/2016/08/08/k-means-clustering-in-java/) / [knn](https://jtablesaw.wordpress.com/2016/08/06/a-k-nearest-neighbors-classifier-in-java/)
* [plotting](https://jtablesaw.wordpress.com/2016/07/30/new-plot-types-in-tablesaw/) / [graphics](https://jtablesaw.wordpress.com/2016/07/17/tablesaw-gets-graphic/)

**Comment by lwhite1** [comment]
in general, yes, but the other docs were not written in a user guide format
so they need editing.

I've started editing the visualization documentation but its too
preliminary to add to the user guide TOC.
