### ISSUE TITLE
Inconsistent method naming max/minimum

### ISSUE THREAD

**Issue by jimmoores** [jtablesaw/tablesaw#166]
Should be either max/min or maximum/minimum but is max/minimum.  Would do a PR, but not sure which one you'd want to deprecate, or if there's some other reasoning I don't know about.

**Comment by lwhite1** [comment]
True.
Thanks, Jim. We'll deprecate minimum and go with the traditional min.

**Comment by lwhite1** [comment]
Sorry, could you point me to the methods in question (what class they're in)? I'm not finding it.

**Comment by jimmoores** [comment]
No problem. 
[https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/api/Table.java](https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/api/Table.java)
lines 1046-1052

**Comment by benmccann** [comment]
Fixed here: https://github.com/jtablesaw/tablesaw/commit/4c4c34c5b237da673b8a731727dc321f2e79f2b1

**Comment by benmccann** [comment]
Released as 0.9.5

**Comment by lwhite1** [comment]
I think the true fix here may be larger, requiring deprecation of min, max,
and other similar methods, with the summarize method. Not sure the existing
summarize method can handle multi-level sub groups, but seems like the way
to go

**Comment by benmccann** [comment]
I'm not sure I understand what multi-level sub groups are
