### ISSUE TITLE
Should toString() of Relation include the table's name?

### ISSUE THREAD

**Issue by jimmoores** [jtablesaw/tablesaw#167]
Genuine question.  I went to some lengths to generate a name for the table so was a bit disappointed when it wasn't printed out.

**Comment by lwhite1** [comment]
Seems like as good a place as any to have the broader conversation on toString()

I think Ben and I are of two minds on toString() for tables. I was using it as the traditional debugging tool, so it would display the variable names and their values.  There was a separate method called print() (now deprecated) that displayed the table as formatted text. This is what toString() returns now, except that it is limited to the first 50 rows of data.

while acknowledging that print() was a dumb name, I'd have preferred to rename it to show(), and otherwise keep things as they were. 

There are also two methods that display the contents of subsets of the table. 

`first(int nRows)` creates a table that is a copy of the receiver but contains only the first n rows.

If you did (first(50).print(), you would get the same result, I believe, as the new toString

last(int nRows);                 provides the obvious variation on that.

**Comment by jimmoores** [comment]
As a preamble, I'm not sure if Ben mentioned it, but Ben made some PRs to my library [quandl4j](https://github.com/jimmoores/quandl4j). He also suggested I consider using tablesaw instead of my home grown table class called TabularResult - I took a look and enthusiastically agreed, and I'm about to do a major new release which includes an optional tablesaw module with a couple of examples of using it.

What I did in my much more basic table class was to have a toPrettyPrintedString() that output the nicely formatted ASCII table, and keep toString() as a debugging tool.  But I can see advantages either way.

**Comment by lwhite1** [comment]
very cool. I will have to look into quandl in more detail.

**Comment by benmccann** [comment]
(Side note - `first(50).print()` isn't quite the same as the new `toString()`. The new `toString()` prints the first 25 and last 25 rows of the table with ellipses in between)

One concern I had with `print()` / `show()` is that the names don't really explain what they're doing. They both kind of sound like they're calling `System.out.println` themselves when they're really converting the object to a `String`.

We should test this out in BeakerX. It seemed a little easier to do:

    tornadoes.first(10);
    tornadoes.column("Fatalities").summary();

Than:

    tornadoes.first(10).print();
    tornadoes.column("Fatalities").summary().print();

But I haven't actually tested this in BeakerX yet so am not 100% sure that `tornadoes.first(10)` will work or if it will expect us to do `tornadoes.first(10).toString()`. If it requires the latter then perhaps `print()` is better after all.

Just this morning, BeakerX added a change that will make it possible to use newer versions of Tablesaw without us having to package up an uber-jar for them. When the next version of BeakerX is released we will be able to do:

    mvn (%classpath add mvn tech.tablesaw tablesaw-plot 0.9.3)

Perhaps we should leave this issue open until then and make sure to test with it?

**Comment by lwhite1** [comment]
the main reason for having first return a table is that you can then do
stuff with it besides print it.  It seemed like it might be useful enough
to justify the extra method in the chain.

but i'm fine with waiting if you like, and if we're not inconveniencing Jim
too much.

**Comment by benmccann** [comment]
The next version of BeakerX will be released next week, so we should be able to try it out then

**Comment by benmccann** [comment]
Hey guys, check out the updated BeakerX example and let me know what you think: https://github.com/twosigma/beakerx/pull/5954

**Comment by benmccann** [comment]
I think I like not having to call `print()`, but I think 50 rows is too much by default. Maybe 20 would be better. It would also be interesting to see what it looks like with the table name in the output as this issue suggests

**Comment by benmccann** [comment]
Here's what the output looks like currently:
```
 Flip  |  Median [Kelly]  |  Median [Kelly_0_5]  |  Median [Kelly_1_5]  |  Median [Kelly_2]  |
----------------------------------------------------------------------------------------------
    0  |             1.0  |                 1.0  |                 1.0  |               1.0  |
    1  |             0.7  |                0.85  |                0.55  |               0.4  |
    2  |           1.225  |             1.16875  |             1.16875  |               1.0  |
    3  |         2.14375  |           1.6070312  |           2.4835937  |               2.5  |
    4  |        1.500625  |           1.3659766  |           1.3659767  |               1.0  |
    5  |       1.0504375  |           1.1610802  |           0.7512872  |               0.4  |
    6  |       1.8382655  |           1.5964851  |           1.5964853  |               1.0  |
    7  |        1.286786  |           1.3570125  |          0.87806696  |               0.4  |
    8  |       2.2518754  |            1.865892  |           1.8658922  |               1.0  |
    9  |       1.5763129  |           1.5860083  |           1.0262407  |               0.4  |
  ...  |             ...  |                 ...  |                 ...  |               ...  |
   92  |       11330.786  |            1303.751  |           1303.7513  |         0.9999998  |
   93  |       7931.5537  |           1108.1888  |           717.06335  |        0.39999998  |
   94  |       13880.214  |           1523.7592  |           1523.7594  |         0.9999998  |
   95  |        9716.152  |           1295.1957  |            838.0678  |        0.39999998  |
   96  |       17003.262  |           1780.8932  |           1780.8937  |         0.9999999  |
   97  |       11902.287  |           1513.7599  |            979.4917  |        0.39999998  |
   98  |       20828.994  |           2081.4192  |           2081.4194  |         0.9999999  |
   99  |       36450.723  |           2861.9502  |            4423.014  |          2.499999  |
  100  |        25515.52  |            2432.659  |           2432.6592  |         0.9999999  |
```

Here's what the output would look like with the table name:
```
                                        Simulation summary                                    
 Flip  |  Median [Kelly]  |  Median [Kelly_0_5]  |  Median [Kelly_1_5]  |  Median [Kelly_2]  |
----------------------------------------------------------------------------------------------
    0  |             1.0  |                 1.0  |                 1.0  |               1.0  |
    1  |             0.7  |                0.85  |                0.55  |               0.4  |
    2  |           1.225  |             1.16875  |             1.16875  |               1.0  |
    3  |         2.14375  |           1.6070312  |           2.4835937  |               2.5  |
    4  |        1.500625  |           1.3659766  |           1.3659767  |               1.0  |
    5  |       1.0504375  |           1.1610802  |           0.7512872  |               0.4  |
    6  |       1.8382655  |           1.5964851  |           1.5964853  |               1.0  |
    7  |        1.286786  |           1.3570125  |          0.87806696  |               0.4  |
    8  |       2.2518754  |            1.865892  |           1.8658922  |               1.0  |
    9  |       1.5763129  |           1.5860083  |           1.0262407  |               0.4  |
  ...  |             ...  |                 ...  |                 ...  |               ...  |
   92  |       11330.786  |            1303.751  |           1303.7513  |         0.9999998  |
   93  |       7931.5537  |           1108.1888  |           717.06335  |        0.39999998  |
   94  |       13880.214  |           1523.7592  |           1523.7594  |         0.9999998  |
   95  |        9716.152  |           1295.1957  |            838.0678  |        0.39999998  |
   96  |       17003.262  |           1780.8932  |           1780.8937  |         0.9999999  |
   97  |       11902.287  |           1513.7599  |            979.4917  |        0.39999998  |
   98  |       20828.994  |           2081.4192  |           2081.4194  |         0.9999999  |
   99  |       36450.723  |           2861.9502  |            4423.014  |          2.499999  |
  100  |        25515.52  |            2432.659  |           2432.6592  |         0.9999999  |
```

**Comment by benmccann** [comment]
I added the table name as @jimmoores suggested.

I also renamed the method `print` and added back a simpler `toString` as @lwhite1 suggested now that we have the `tablesaw-beakerx` project
