### ISSUE TITLE
Consider how to better support Smile

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#168]
One improvement would be to make `ShortColumn`, `IntColumn`, `CategoryColumn`, and `BooleanColumn` all implement the same interface which defines a method `toIntArray()` (could call is something like `IntArrayConvertible`?). We could then simplify the tablesaw implementation by having one method which takes an `IntArrayConvertible` instead of having four different variants for short, int, category, and boolean. The `LogisticRegression` class is a good example of where this new interface would make things easier.

Another thing we could do would be to implement an `nCols` method. Right now we have:

    LogisticRegression model = LogisticRegression.learn(train.shortColumn(2), train.nCol("X"), train.nCol("Y"));

This could be simplified to:

    LogisticRegression model = LogisticRegression.learn(train.shortColumn(2), train.nCols("X", "Y"));

I also wonder at that point if we need Tablesaw's `LogisticRegression` class wrapping Smile's at all. It wouldn't be drastically harder for the user to call the underlying Smile library directly:

    LogisticRegression model = new LogisticRegression(train.shortColumn(2).toIntArray(), train.nCols("X", "Y").to2dArray());

Perhaps we could further simplify to something like:

    LogisticRegression model = new LogisticRegression(train.intArray(2), train.double2dArray("X", "Y"));

We'll have a very hard time wrapping every single Smile class and I'm not sure it's worth it for us to try at this point. Maybe in the future if we had some way to do it with an automatic code generator or something, but right now I think it could just cause more issues because there will always be so many underlying Smile calls that our wrapper doesn't support

**Comment by benmccann** [comment]
I tried to send a PR for this. I found a bit if difficulty creating a ConfusionMatrix in Smile directly. I'm going to try to address that in Smile first before coming back to this issue.

**Comment by lwhite1** [comment]
sorry i didn't respond earlier. I like the idea of simplifying the
interfaces by having a single interface type for categorical variables.
Factor might be a good name, however I'm not a big fan of removing the
smile wrappers. They do a number of things like translate model results
into tablesaw tables that I think are important from a usability
standpoint.

**Comment by lwhite1** [comment]
i should add also that if we support another ML library having a unified
api we control has a lot value.

**Comment by benmccann** [comment]
I pushed a couple commits to add an interface and cut down on the amount of code required. I'll leave this open for now to see what else we can do

**Comment by lwhite1** [comment]
ok. Thanks.

**Comment by lwhite1** [comment]
@benmccann, with your work here and in #174, do you think this can be closed now?
