### ISSUE TITLE
error parsing csv file

### ISSUE THREAD

**Issue by BadLuckRestaurant** [jtablesaw/tablesaw#169]
tablesaw-core 0.9.3

trying to open this csv file https://raw.githubusercontent.com/jtablesaw/tablesaw/master/data/whiskey.csv (note that the last two header fields contain spaces..)
with tech.tablesaw.api.Table.read().csv("/data/whiskey.csv");
i got the exception 

java.lang.ArrayIndexOutOfBoundsException: -1
	at tech.tablesaw.io.csv.AddCellToColumnException.<init>(AddCellToColumnException.java:48)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:315)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:30)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:18)
	at mytest.tablesaw.KMeansClustering.main(KMeansClustering.java:13)

in CSVReader read(CsvReadOptions options) method there's a mismatch between trimmed values of the columnNames array and not trimmed values of headerRow array so the following section of code

```
  for (int i = 0; i < columnIndexes.length; i++) {
                // get the index in the original table, which includes skipped fields
                columnIndexes[i] = headerRow.indexOf(columnNames[i]);
            }
```

generates -1 values in the columnIndexes array leading to an exception in the following loop

```
 while ((nextLine = reader.readNext()) != null) {
                // for each column that we're including (not skipping)
                int cellIndex = 0;
                for (int columnIndex : columnIndexes) {
                    Column column = table.column(cellIndex);
                    try {
                        **column.appendCell(nextLine[columnIndex]); //here cololumIndex = -1 => exception generation**
                    } catch (Exception e) {
                        throw new AddCellToColumnException(e, columnIndex, rowNumber, columnNames, nextLine);
                    }
                    cellIndex++;
                }
                rowNumber++;
            }
        }
        return table;
```

**Comment by lwhite1** [comment]
Thank's for the detailed report. Much appreciated. We'll look into it.

**Comment by lwhite1** [comment]
replicated on master

**Comment by lwhite1** [comment]
replicated on 0.7 branch as well

**Comment by lwhite1** [comment]
fixed on master.
