### ISSUE TITLE
Setup Codacy reporter for JaCoCo

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#171]
https://github.com/codacy/codacy-coverage-reporter#maven-plugin

We'll need to get the token (Project -> Settings -> Integrations -> Project API), [encrypt it](https://docs.travis-ci.com/user/encryption-keys/), and add as a secure env variable in the Travis build

**Comment by benmccann** [comment]
@lwhite1 I've tried to setup Codacy, but it looks like it's only setting it up for my fork of the project. I think either you'll need to add me as an admin or set up Codacy yourself.

To set it up, you just sign into https://www.codacy.com with your GitHub account and click on jtablesaw/tablesaw.

Then we'll also need to get the token (Project -> Settings -> Integrations -> Project API), [encrypt it](https://docs.travis-ci.com/user/encryption-keys/), and add as a secure env variable in the Travis build

Here's the dashboard for my fork if you want to see what it looks like: https://www.codacy.com/app/benmccann/tablesaw

**Comment by lwhite1** [comment]
ok. heading out for labor day bbq. will look at this tomorrow.

**Comment by lwhite1** [comment]
i made you an owner.

**Comment by benmccann** [comment]
Thanks! I just added the badge to the homepage showing our score and invited you as an admin on Codacy. I'll leave this issue open for a little longer as I still need to hook up the code coverage

**Comment by benmccann** [comment]
I've sent a couple commits for this, so it's pretty close now. It's not quite working yet though. At the end of Travis it tells me "com.codacy Failed to upload report: not found". It's working locally though...

**Comment by benmccann** [comment]
Got this fixed! Woo!!
