### ISSUE TITLE
Replace PackedLocalDate with milliseconds since epoch

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#172]
I was wondering if it'd be possible to replace `PackedLocalDate` with milliseconds since epoch. The milliseconds since epoch is much more standard and there are numerous methods built into Java to deal with milliseconds since epoch

Milliseconds since epoch would be more performant in some common circumstances. I frequently have millisecond timestamps and right now I often have to convert between them and `PackedLocalDate`. This change would save that computation in cases where I already have longs to begin with

Also, `PackedLocalDate` has a range of +/- 30,000 years while milliseconds since epoch has a range of +/-300,000 years.

**Comment by lwhite1** [comment]
> I was wondering if it'd be possible to replace PackedLocalDate with milliseconds since epoch. 

of course.

> The milliseconds since epoch is much more standard 

true.

> and there are numerous methods built into Java to deal with milliseconds since epoch. 

also true, but PackedLocalDate supports all the methods in LocalDate (i think). What else is needed?

> Milliseconds since epoch would be much more performant in some circumstances. I frequently have millisecond timestamps and right now I often have to convert between them and PackedLocalDate. This change would save that computation in cases where I already have longs to begin with

That's also true, but PackedLocalDate is more performant in some cases. For example, to get the year, you just grab the first 4 bytes, while millis requires a more elaborate calculation. Similarly to get the difference in days between two dates, or the month, or day of the week, you would first have to convert the millis to a date-like format. 

> Also, PackedLocalDate has a range of +/- 30,000 years while milliseconds since epoch has a range of +/-300,000 years.

I've never seen an app that did date calculations 1,000 years in the future so i think the benefit is mostly theoretical.  On the other hand, PackedLocalDate is an int, so you would always be trading off using twice as much memory for the ability to do date calcs 50,000 years from now. 

I think, overall, i would prefer to write a method that would do the conversion without needing to instantiate the intermediate objects Instant and java.time.LocalDate, which I'm guessing is what is taking so long. Is that the main issue?

**Comment by benmccann** [comment]
The main issue for me is that we have methods like `append(long dateTime)`, `append(LocalDateTime dateTime)`, `getLong(int index)` that expose the underlying implementation. I think we should encapsulate this and keep the implementation details hidden from the user. I expected `getLong(int index)` to return milliseconds since epoch because that's what I'm used to dealing with in Java and was surprised to find I got back a long in a proprietary format that wasn't easy for me to manipulate or deal with. It could be nicer to either remove `getLong` or have it return a milliseconds timestamp.

**Comment by lwhite1** [comment]
Ah, ok. It may be possible to reduce the visibility of those methods
without breaking anything, but they're needed to do things like copying a
column efficiently (i.e. without type changes). It's possible also that
they need to be part of an interface but the interface could maybe be
package local. I can look into it.

OTOH, if you want to use millis and to do your calculations with other java
libraries that work natively with millis, why not use the long column type?

**Comment by benmccann** [comment]
Unfortunately a `LongColumn` doesn't fulfill the need because it's still useful to treat the column as representing dates. E.g. I serialize my table to JSON and send it to the browser to draw charts. A `DateTimeColumn` gets serialized to a string in ISO 8601 date format where as a long gets serialized to a number. There's several other ways in which date columns offer different functionality than long columns as well that are important.

If we use milliseconds since epoch as the underlying storage then it doesn't matter so much that we expose it because we're exposing something that's a standard across the Java ecosystem instead of something that only Tablesaw knows how to deal with internally.

I'm not sure if there's a strong reason to use our own `PackedLocalDate` format? I think the main thing it provides is a bit faster performance in getting a certain field of a date (e.g. just the day), but I find that this is less common than using the whole date. E.g. it's common to say `date1.compareTo(date2)`, but not so common to do `date1.getDayOfMonth().compareTo(date2.getDayOfMonth())`. The latter wouldn't really be a useful operation. The only time I can think of where using just one field is beneficial is for bucketing. E.g. to bucket into years to draw a histogram or something. But I'm not sure this is so common that it's the use case we should optimize for

As far as I can find, other libraries that serialize dates/times to primitives also use millis. E.g. that's how the [FSTDateSerializer](https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/serializers/FSTDateSerializer.java) works as well as the [externalizor TimeExternalizer](https://github.com/qwazr/externalizor/blob/master/src/main/java/com/qwazr/externalizor/TimeExternalizer.java)

**Comment by lwhite1** [comment]
just so i'm clear, you're talking about the DateTimeColumn, not the
DateColumn, right? I think i misunderstood earlier.

**Comment by benmccann** [comment]
Yeah, `DateTimeColumn`

**Comment by lwhite1** [comment]
On further reflection, I'm thinking that all or nearly all date time
functions are more performant with packed date times than with millis. The
only exceptions I can see are importing and exporting to millis,
compareTo(), and subtracting the millis between two values. Even
serializing to a string is probably faster from packedDateTime, because you
would first have to convert the milliseconds value to a date.

Importing and exporting are things you do once per data set, but things
like calculating the average sales per month are pretty common i would
think.

in any case I've added a toEpochMillis() and ofEpochMillis() functions to
the PackedDateTime api. Let me know if that doesn't suffice.

**Comment by benmccann** [comment]
What do you think about renaming `DateTimeColumn.getLong()` to `getLongInternal()`?  That would solve my issue of getting confused about `getLong()` returning our internal representation instead of milliseconds as I expected.

**Comment by lwhite1** [comment]
sounds good
