### ISSUE TITLE
Plotting doesn't work in BeakerX

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#175]
I added @jimmoores Tablesaw Quandl example from the [Quandl4j README](https://github.com/jimmoores/quandl4j) to the BeakerX Tablesaw example: https://github.com/twosigma/beakerx/pull/5954

I couldn't get the charting to work though

**Comment by lwhite1** [comment]
my guess is that it's because the charts include windowing logic. If beakerX is like Jupyter, I would imagine that you need to either render in Javascript, or possible create an image that could be embedded. That said, I haven't looked at BeakerX since it was just plain Beaker.

**Comment by benmccann** [comment]
Yes, I think it referred to swing. If I'm remembering correctly it was a `ClassNotFoundException` for `javafx.embed.swing.JFXPanel`

I have Tablesaw working with AmCharts on a website. I'm not quite sure how to get that to work in BeakerX, but would be willing to contribute it. If anyone has an example of getting a JavaScript chart in Jupyter that would be helpful.

**Comment by jimmoores** [comment]
Could it be running against a Java 7 JRE? Seems unlikely but might be worth
a check...

**Comment by jimmoores** [comment]
Think the open jdk packaging is more likely cause. Could you install e.g.
an open jfx package if you're on Linux?

On 9 Sep 2017 06:47, "Jim Moores" <jim.moores@gmail.com> wrote:

Could it be running against a Java 7 JRE? Seems unlikely but might be worth
a check...

**Comment by lwhite1** [comment]
> I have Tablesaw working with AmCharts on a website. I'm not quite sure how to get that to work in BeakerX, but would be willing to contribute it.

That would be just fantastic. We'd have to update the license info for that module, and the main readme as well, but amcharts seems like a really fine library.

**Comment by benmccann** [comment]
I'm running Java 1.8.0_131 and have `libopenjfx-java` installed

Perhaps the best way to support charting in BeakerX is to use what's built-in to BeakerX https://github.com/jtablesaw/tablesaw/issues/190
