### ISSUE TITLE
IntBetween is not inclusive as expected

### ISSUE THREAD

**Issue by zhuangxududu** [jtablesaw/tablesaw#178]
I have a table with two columns and 6 million rows. The first column is the 0-based index, e.g. the first row is indexed with 0, the second row is 1, etc. The second column is real value. 
I want to select 1 million continuous records in the table from a certain record, so I do it as follow:
```
int step = 1000000;
Table t = Table.read().csv(CsvReadOptions.builder("output//channel_I_019.csv").header(false));
int rowCount = t.rowCount();
System.out.println("Row count of the table:" + rowCount);
int start = 999999;

Table table1 = t.selectWhere(new IntBetween(new ColumnReference("C0"), start, start + step));
System.out.println("Row count of the first table:" + table1.rowCount());

Table table2Low = t.selectWhere(new IntGreaterThan(new ColumnReference("C0"), start));
Table table2 = table2Low.selectWhere(new IntLessThanOrEqualTo(new ColumnReference("C0"), start + step));
System.out.println("Row count of the second table:" + table2.rowCount());
```
The outputs:
Row count of the table:6380000
Row count of the first table:5380000
Row count of the second table:1000000

It seems that the third parameter of the IntBetween does't work.

**Comment by lwhite1** [comment]
Hi, Sorry you're having trouble.

It would be a bit clearer if you could indicate what results you were
expecting.

thanks.

**Comment by zhuangxududu** [comment]
@lwhite1 
Dear Sir,
      I expect the following code should return a table consisting of records between 1,000,000 rows and 2,000,000 (include) rows:
`Table table1 = t.selectWhere(new IntBetween(new ColumnReference("C0"), start, start + step));`

So the row count of the first table should be 1,000,000.

**Comment by benmccann** [comment]
Hmm, yes, I would expect "between" to be inclusive. E.g. if I ask someone to pick a number between 1 and 10 then I would consider 1 and 10 valid responses

**Comment by benmccann** [comment]
Fixed here: https://github.com/jtablesaw/tablesaw/commit/71db077f948c5fba527d66ca6875b936b72d010c
