### ISSUE TITLE
Load Table from JSON URL

### ISSUE THREAD

**Issue by skanga** [jtablesaw/tablesaw#179]
Do you have the ability to create a table from a node in a JSON data structure? If not can this be requested as an enhancement? Or is there some other simple way to do it?

**Comment by benmccann** [comment]
If you serialize that node as a string, then it can be parsed by Tablesaw.

I'm not sure we'd want to expose the JSON parser we use because that seems like ti should be an internal implementation detail.

**Comment by skanga** [comment]
Thanks.

I ended up parsing the JSON into a CSV string using a StringBuilder. Then I used a Reader to wrap that string and passed it into the Table.read().csv() which worked fine (although a bit of a kludge)
