### ISSUE TITLE
Need of more code samples on http table build

### ISSUE THREAD

**Issue by adriens** [jtablesaw/tablesaw#182]
Hi,

i'm beginning to give a try to your lib, by loading a csv file served by http. Unfortunately, i could not manage to make run the code, i'm pretty sure i've missed the central thing.

```
departement;fromage;page_francaise;english_page;image;lait;geo_shape;geo_point_2d
Aube;Brie de Meaux;http://fr.wikipedia.org/wiki/Brie_de_Meaux;http://en.wikipedia.org/wiki/Brie_de_Meaux;https://public.opendatasoft.com/api/datasets/1.0/fromagescsv-fromagescsv/images/27008672bdd6146a34bc9dbea1b86699;Vache;"{""type"": ""Polygon"", ""coordinates"": [[[3.5451086778, 48.3345393871], [3.5431122736, 48.335916143], [3.5388776824, 48.3374920105], [3.5304680789, 48.3426134039], [3.5247651149, 48.3472633586], [3.5216361996, 48.3515958095], 
```

Please find below the code that gets the csv and tries to load it in a table :

```java
String location = "https://public.opendatasoft.com//api/records/1.0/download?dataset=fromagescsv-fromagescsv";
Table table;
InputStream input = new URL(location).openStream();
table = Table.read().csv(input, "fromages");
```

Then i get the following exception :

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
```
 
In the csv, i have urls, not only categorized strings, hence i don't know how to map them...maybe is it the cause of the exception ?

My goal is to parse the csv provided by https://public.opendatasoft.com/explore/dataset/fromagescsv-fromagescsv/?disjunctive.fromage

Once i will have been able to load the datas, i'll make unique sort, queries and other kind of things...

Any help would be greatly appreciated ;-p...if you have time to.

Thank you in advance.

Best Regards,

Adrien

**Comment by lwhite1** [comment]
That file is not a standard CSV (comma separated value) file, since the values are separated by semicolons. Try specifying that the separator is a semicolon using a CsvReadOptionsBuilder. Something like this:

`Table.read().csv(CsvReadOptions.builder(input, "fromages").separator(';'));`

**Comment by adriens** [comment]
Thanks a lot, i'll give it a try very soon, i'll let you know !

**Comment by adriens** [comment]
:+1:  it did the job !...but now i'm dealing with encoding issues on accented characters : when i want to have a look at the data sample, i get :

```
CorrÃ¨ze
```

instead of

```
Corrèze
```

I saw that you previously (https://github.com/jtablesaw/tablesaw/issues/107) add to deal with this kind of things...especially on windows 10 (which is my case at home) 

What would you recommand to sort this out ?

**Comment by adriens** [comment]
OK, 'got it ! We have to pass through a reader specifying the encoding and it perfectly does the trick :

```java
String location = "https://public.opendatasoft.com//api/records/1.0/download?dataset=fromagescsv-fromagescsv";
Table table;
InputStream input = new URL(location).openStream();
BufferedReader reader = new BufferedReader(new InputStreamReader(input, "UTF-8"));
table = Table.read().csv(CsvReadOptions.builder(reader, "fromages").separator(';'));
```

In fact, i've even used a BufferedReader.

Maybe should you have this to the code sample so it could be useful for other people...

Thanks a lot for your kind support and your reallly cool library !
