### ISSUE TITLE
Feature request > Iterate over a table

### ISSUE THREAD

**Issue by adriens** [jtablesaw/tablesaw#184]
Hi,

i've user tablesaw to aggregate, sort and it works perfectly fine, but now, i need to be able to fetch (like on a regular jdbc Resultset) to make some processing.

Is that feasible with the actual API ?...and, for each, row, get the attached column value ?

I'm aware that the library is designed to aggregate and sort, not to fetch, but i need to ask as it is the last thing i need in my journey in tablesaw ;-p

Thank you in advance for your answer or guidelines.

**Comment by adriens** [comment]
To do this, would you confirm that i should the the right index on the columns and fetch this way ?..i mean "manually by code" ?

**Comment by adriens** [comment]
If so, how can we get the value of a given column at the row i ? :

For example, i'd like to get the values of the first column of the table :

```java
int nbRows = table.rowCount();
        i=0;
        while (i < nbRows){
            System.out.println("col0 value : " + table.column(0).get(i));
            System.out.println("##################################");
        }
```

Any help would be greatly appreciated ;-p

**Comment by lwhite1** [comment]
Table is already iterable: 
`public class Table extends Relation implements IntIterable {
`

You can step through the indexes for each row using: 
`for (int rowNumber : table) {}
`
Then you can use the column accessors to get the value from the column(s) you want.

I hope that's clear enough.

**Comment by adriens** [comment]
Hi, thanks for the answer, and...yes ! It is exactly what i was looking for ! Thanks a lot for your kind support.
