### ISSUE TITLE
Add method to filter table by row index

### ISSUE THREAD

**Issue by YuanZhencai** [jtablesaw/tablesaw#185]

**Comment by lwhite1** [comment]
There should be the equivalent of a slice operation, but you have to use iteration for now. 

for (int i = 50; i < 100; i++) {
  // copy the results from your table, column by column
}

**Comment by benmccann** [comment]
Implemented here: https://github.com/jtablesaw/tablesaw/commit/cc72afd6a19265194ac7d7a2cd48b8ddc0a070f5
