### ISSUE TITLE
how to read excel

### ISSUE THREAD

**Issue by YuanZhencai** [jtablesaw/tablesaw#186]

**Comment by lwhite1** [comment]
Use Excel to export each sheet in a workbook (there may be only one) as a
CSV file. Then import the CSV file.

**Comment by benmccann** [comment]
If you want to do it programatically you may also use Apache Poi. However, that's outside the scope of this library

**Comment by R1j1t** [comment]
In the recent release you can read excel, below is an example:

```
import tech.tablesaw.api.Table;
import tech.tablesaw.io.xlsx.XlsxReadOptions;
import tech.tablesaw.io.xlsx.XlsxReader;
```
---
```
XlsxReadOptions options = XlsxReadOptions.builder("<excelFileName>.xlsx").build();
XlsxReader xlsxReader = new XlsxReader();
List<Table> tables=  xlsxReader.readMultiple(options);

```

This part i could not find the documentation though

**Comment by julian-goettingen** [comment]
Since is is still the top-google-result for how to read excel-files with tablesaw, I'll share a problem I had:

The snippet posted by R1j1t still works with 0.43.1 but you need to include the dependency `tablesaw-excel`, not just `tablesaw-core`.
