### ISSUE TITLE
Read csv file is very slowly when file size more than 300M

### ISSUE THREAD

**Issue by lokinell** [jtablesaw/tablesaw#187]
Dear @lwhite1 , I try to use tablesaw to read a large csv file which size is about 300M. 
My code like below:
`@Test
    public void readLarge() throws IOException {
        CsvReadOptions.CsvReadOptionsBuilder builder = CsvReadOptions
            .builder("/Users/admin/Downloads/Acquisition.csv");
        builder.separator('|');
        Table.read().csv(builder);
    }`

**Comment by lokinell** [comment]
By the way,  how to convert Column from category to int?

**Comment by lokinell** [comment]
I use 0.10.0 version

**Comment by lwhite1** [comment]
Hi @lokinell,
In the class CategoryColumn use the method: 

` public IntColumn toIntColumn();
`
In the future, please don't use the same issue for two different concerns. It gets confusing for us.
Cheers.
