### ISSUE TITLE
Rolling window calculations

### ISSUE THREAD

**Issue by volchemist** [jtablesaw/tablesaw#193]
A mechanism to easily perform rolling window calculations (rolling mean, standard deviation, sum, etc. over n rows) would be highly appreciated. An example usage to calculate the rolling 20-day mean could look like this:

`table.doubleColumn("sales").rolling(20).mean()`

Or like this:

`Rolling.mean(table.doubleColumn("sales"), 20)`

The result would be a new double column of the same length whose i-th row contains the mean value of the (i minus 19)-th to i-th row in the original column.

Here's a reference to the corresponding functionality in pandas:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html

**Comment by benmccann** [comment]
Here's another example of a possible API:
http://www.zavtech.com/morpheus/docs/analysis/statistics/#rolling-window-statistics

Source code that we could possibly leverage here:
https://github.com/zavtech/morpheus-core/blob/572190256143334992cc56a329c4d745da0f1204/src/main/java/com/zavtech/morpheus/reference/XDataFrameCalculate.java

**Comment by benmccann** [comment]
`table.doubleColumn("sales").rolling(20).mean()` works now. I've just added mean and sum for now

We should document this feature still

**Comment by benmccann** [comment]
Going to close this. Will open a new issue to remind us to document it
