### ISSUE TITLE
Dataframe.kt should not call deprecated APIs for createFromCsv and exportToCsv

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#195]
@lwhite1 maybe you could help with this one. I'm not familiar enough with Kotlin to know how a `companion object` is used

```
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/Col.kt: (32, 21) 'next(): Int!' is deprecated. Deprecated in Java
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/Dataframe.kt: (83, 35) 'createFromCsv(String!, Boolean, Char): Table!' is deprecated. Deprecated in Java
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/Dataframe.kt: (88, 48) 'exportToCsv(String!): Unit' is deprecated. Deprecated in Java
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/Dataframe.kt: (106, 62) 'minimum(String!): Minimum!' is deprecated. Deprecated in Java
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/IntCol.kt: (73, 27) The corresponding parameter in the supertype 'NumericCol' is named 'index'. This may cause problems when calling this function with named arguments.
[WARNING] tablesaw/core/src/main/kotlin/tech/tablesaw/kapi/IntCol.kt: (187, 19) 'next(): Int!' is deprecated. Deprecated in Java

```

**Comment by lwhite1** [comment]
I wonder if anyone is using the Kotlin API? It is certainly not finished. I
might be more inclined to remove it than to extend and maintain it.  What
do you think?

**Comment by jchildress** [comment]
I just started looking at Tablesaw.  It was mentioned on the Kotlin datascience channel on Slack.  I'm interested...

**Comment by lwhite1** [comment]
Cool.  I had no idea there was a kotlin data science channel.  I will take
a look.

**Comment by holgerbrandl** [comment]
@lwhite1 Even being not ready, the kotlin bits in jts helped me a lot to stay motivated to push my own  attempt for a kotlin data-frame api forward. See yourself https://github.com/holgerbrandl/krangl

**Comment by thomasnield** [comment]
You can always create a separate project that puts a Kotlin DSL around TableSaw, and simply make TableSaw a dependency. [RxKotlin](https://github.com/ReactiveX/RxKotlin) did this with [RxJava](https://github.com/ReactiveX/RxJava), and [TornadoFX](https://github.com/edvin/tornadofx) did this for [JavaFX](http://www.oracle.com/technetwork/java/javase/overview/javafx-overview-2158620.html).


Personally, I'd only introduce Kotlin to the TableSaw project itself if you like the idea of transitioning to a Kotlin (not Java) implementation.

**Comment by benmccann** [comment]
You can use the Java API from Kotlin, so I am curious what is gained from having the Kotlin wrapper. It doesn't look like we have made any of the APIs any nicer to call from Kotlin, but I'm not sure. I also wonder if we were going to keep it if we could make the class `Derived` to cut down on the amount of code required

**Comment by thomasnield** [comment]
Kotlin doesn't create "wrappers" in the traditional Java sense. But you can add extension functions/properties and receiver functions to types to make it more fluent. You can also make type-safe [Groovy-style builders](https://kotlinlang.org/docs/reference/type-safe-builders.html) for complex nested structures. 

I haven't dived deep enough in TableSaw to see if Kotlin language features provides any major gains, but I'll take a more thorough look later.

**Comment by lwhite1** [comment]
For someone fluent in java, there is little benefit  to a kotlin interface,
but for someone who is a data analyst rather than a programmer, kotlin
could be meaningfully easier.

The reason is that you could express data operations more naturally, and
with less boilerplate.  Java is tedious without awesome ide support. The
Kotlin experience could be more akin to python or R, and so easier in a lab
notebook environment.

**Comment by thomasnield** [comment]
@lwhite1 that's kind of the thoughts of the Kotlin community. I did a talk on Kotlin for Data Science at KotlinConf. 

https://github.com/thomasnield/kotlinconf-datascience-talk

Regarding the Kotlin interface and whether there is value in keeping it (rather than creating a separate DSL project), we'll take a look unless you've decided it's something you don't want to maintain.
