### ISSUE TITLE
Consider renaming splitOn to groupBy

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#196]
@lwhite1 would it be correct to call this method `groupBy`?

**Comment by lwhite1** [comment]
It is quite similar to group by although the overall query semantics are
not especially close to sql.  Statistical software has similar operations
but don't use the group by name. I was trying to be more consistant with
that terminology, iirc.

It's also similar to an operation in the reduce phase of map reduce but I
think they use a different term also.

**Comment by benmccann** [comment]
The reason I expected `groupBy` is because that's what Pandas and dplyr use. I think I understand now why you chose `splitOn`. Would it be fair of me to introduce a new `groupBy` method be an alias of `splitOn` then to make it easier for users like me coming from Pandas?

I'm curious to know of an example of software that users the `splitOn` terminology because I'd like to study that syntax some to help inform our API design.

**Comment by lwhite1** [comment]
Split apply combine is the terminology

https://ramnathv.github.io/pycon2014-r/explore/sac.html

**Comment by benmccann** [comment]
Thanks!
