### ISSUE TITLE
rationalize naming on methods appending a new cell to a column

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#201]
Some columns (`CategoryColumn`, for example) use `add("foo")`.
Other columns (`LongColumn`, for example) use `append(0);`
`appendString("foo")` in `CategoryColumn` does a column-wise append of `"foo"` to every cell in the receiver.
`appendCell("foo")` in `CategoryColumn` is approximately equivalent to `add("foo")`. This option should be eliminated. 

append is probably the right choice going forward, but there are other variations that should be sorted-out simultaneously.

note that numeric columns use "plus" for column-wise addition operations.

**Comment by benmccann** [comment]
We also should rationalize what happens if you `append`/`set` a `null` value. Does it add `MISSING_VALUE` or throw an `Exception`? Most columns explicitly disallow `null` and throw an `Exception`, but I saw one that uses `MISSING_VALUE`, which might be the better behavior.

**Comment by lwhite1** [comment]
closed. fixed.
