### ISSUE TITLE
RollingColumns should inherit from Column

### ISSUE THREAD

**Issue by hswick** [jtablesaw/tablesaw#207]
Tried calling top on a RollingCOlumn and it errored out. I was surprised by this. Feel like the api for RollingColumn should be similar to Column.

**Comment by benmccann** [comment]
I'm not sure how you'd expect `top` to behave. I don't think you can do this in Pandas, can you?

`max` would be a legitimate operation though

**Comment by benmccann** [comment]
I'm going to close this since there hasn't been any response. Please feel free to re-open and comment with more details still
