### ISSUE TITLE
CSVParser - "OutOfMemoryError: GC overhead limit exceeded" with large file

### ISSUE THREAD

**Issue by jo-wu** [jtablesaw/tablesaw#208]
my file has about 20,000,000 rows X 6 cols.

main code:
```
Table user = Table.read().csv("filename.csv");
out("Table name: " + user.name());
```

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.substring(String.java:1969)
	at com.opencsv.CSVParser$StringFragmentCopier.peekOutput(CSVParser.java:609)
	at com.opencsv.CSVParser$StringFragmentCopier.takeOutput(CSVParser.java:616)
	at com.opencsv.CSVParser.parseLine(CSVParser.java:421)
	at com.opencsv.CSVParser.parseLineMulti(CSVParser.java:309)
	at com.opencsv.CSVReader.readNext(CSVReader.java:338)
	at tech.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:430)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:161)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:59)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:55)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:35)
	at ReadCSV.main(ReadCSV.java:7)
```

when I set JVM: -Xms2g -Xmx2g -Xmn512M . 

problem exits still.

ps. my laptop has 12g memory. my Java jdk version is 8.

**Comment by benmccann** [comment]
This seems like an issue with the underlying CSV parser. We currently use opencsv

Perhaps another parser would work better:
* Univocity claims to be highly performant
* Jackson usually performs strongly as well
* CommonsCSV has a pretty nice API

Perhaps you should try parsing your file with these different parsers and see which work

**Comment by adriens** [comment]
the Apache commons is well maintained.

**Comment by lwhite1** [comment]
it might be easier to get OpenCSV to fix the bug, if it is theirs, than to
replace the CSV parser.

**Comment by lwhite1** [comment]
Actually, with 20 million rows, you may just need to up your available memory. IIRC correctly the strings created in reading a csv only live in a single loop of the reader so it's probably _not_ a parser issue. You may also get better results if you pass the column types into the CSV reader so it can skip the type inference work.

**Comment by lwhite1** [comment]
The more i reflect on this issue, the more i think it likely that our memory management has regressed. I can't see how this could use more than 2 GB memory.

**Comment by benmccann** [comment]
@jo-wu any chance you could share the CSV file you're using?

**Comment by benmccann** [comment]
I'm also wondering what version of Tablesaw you're using. We had a couple earlier versions where the memory handling wasn't as good as what's there now

**Comment by jo-wu** [comment]
@benmccann I was using <version>0.11.2</version> at that time,the problem is exits still, but I just try <version>0.11.5</version> with code:
```
Table user = Table.read().csv("filename.csv");
out("Table name: " + user.name());
```
it works well;
I will try more functions to do something analysis. 
think you.

**Comment by jo-wu** [comment]
@benmccann sorry, I delete the previous comment, because it seems to meet the same problem. 
the following is part of my data:
```
user_id,time,item_id,behavior_type,item_category,user_geohash,date,hour
492,2014-11-18 14,178412255,1,280,,2014-11-18,14
492,2014-11-18 14,213642652,1,7094,,2014-11-18,14
492,2014-11-18 14,213642652,1,7094,,2014-11-18,14
492,2014-11-18 14,335961429,1,12919,,2014-11-18,14
492,2014-11-18 14,374520755,1,280,,2014-11-18,14
492,2014-11-18 14,59758671,1,9363,,2014-11-18,14
492,2014-11-18 14,378421490,1,13374,,2014-11-18,14
492,2014-11-18 14,369206778,1,6000,,2014-11-18,14
```
about 23290000 rows.
I try 0.11.5 the newest version, which works well with 2300000 rows.
I will do some more testing.

**Comment by lwhite1** [comment]
The issue is related to CsvReaderOptions. Reader options has a variable called sample that defaults to true. It is passed into a method in CsvReader called detectColumnTypes() (or something like that), in a parameter called "skipSampling", i.e. when sample=true, sampling isn't used.

The detectColumnTypes() method stores in memory a list of List<String> for every row it looks at, so having sample=true, means that the entire file is read into memory. A simple fix is to change the logic in detectColumnTypes to reflect the CsVReader API. I'll make that change this weekend.

**Comment by lwhite1** [comment]
fixed.
