### ISSUE TITLE
MISSING float values printing as 'null' again

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#215]
i'm inclined to think the getString() methods should never return a null as this puts a burden on client code when an empty string covers most imaginable cases. There is a lot of existing code that depends on that functionality.

**Comment by benmccann** [comment]
It seems like it's working to me. Has this been fixed since you filed the issue?

    Table oneYear = Table.read().csv(
        "Date,1 Yr Treasury Rate\n"
            + "\"Nov 1, 2017\",1.56\n"
            + "\"Oct 1, 2017\",\n"
            + "\"Sep 1, 2017\",1.28\n",
        "1 Yr Treasury Rate");
    System.out.println(oneYear.columnTypes()[1]);
    System.out.println(oneYear.print());
    System.out.println(oneYear.floatColumn("1 Yr Treasury Rate").get(1));

One issue with treating nulls as empty strings is that you then can't differentiate between the two if you have both values present in a `CategoryColumn`.

**Comment by lwhite1** [comment]
The problem I saw is gone so i'll close this.  More generally, while the distinction between null and "" is important in computer science, from a data analysis standpoint there is no difference. I can't think of a use for an empty string other than to say "this value doesn't exist" or "this value may exist, but we don't know what it is". In either case, it's 'null'.

Also, you're reading data from a CSV file like: 
```
age,nick name,eye color
8,,blue
```
you could argue that nick name is 'null' from a coding standpoint, but if the file were in "official" CSV format, it would look like:
8, "", "blue"
and presumably we would be obligated to treat it as an empty string because it's explicitly an empty string in the source. 

So i won't press the issue, i just think it's unnecessary to use nulls and introduce the potential for NPEs.

**Comment by lwhite1** [comment]
Empty values print as "null" when calling **print()** on tables created by executing a **selectWhere()** on another table. The original table will print whitespace as expected.

**Comment by lwhite1** [comment]
Still having trouble recreating with a simple case, but this is what I'm seeing in the wild: 

```
    Date     |  Line Of Business  |  Reported Count  |  Order Count  |
----------------------------------------------------------------------
 2012-03-19  |          Clinical  |                  |            7  |
 2012-03-21  |          Clinical  |                  |            6  |
 2012-03-22  |          Clinical  |                  |            1  |
```

becomes:
```
    Date     |    Line Of Business    |  Reported Count  |  Order Count  |
--------------------------------------------------------------------------
 2012-03-19  |              Clinical  |            null  |            7  |
 2012-03-21  |              Clinical  |            null  |            6  |
 2012-03-22  |              Clinical  |            null  |            1  |
```
when the second table was made by a selectWhere that returns all the rows in the first table.

**Comment by benmccann** [comment]
I'm not seeing that. My test code and output below:

```
    @Test
    public void test215() throws IOException {
      Table table = Table.read().csv(CsvReadOptions.builder("test.csv")
          .columnTypes(new ColumnType[] { ColumnType.LOCAL_DATE, ColumnType.CATEGORY, ColumnType.INTEGER, ColumnType.INTEGER }));
      table = table.selectWhere(QueryHelper.column("Order Count").isGreaterThan(0));
      System.out.println(table.print());
    }
```

Output:
```
                               test.csv                               
    Date     |  Line Of Business  |  Reported Count  |  Order Count  |
----------------------------------------------------------------------
 2012-03-19  |          Clinical  |                  |            7  |
 2012-03-21  |          Clinical  |                  |            6  |
 2012-03-22  |          Clinical  |                  |            1  |
```

I ran this with the latest code in master

**Comment by lwhite1** [comment]
it has to be some insidious issue with my environment. I am closing again.

<walks away with head hanging down>
