### ISSUE TITLE
Columns 'set' methods is adding

### ISSUE THREAD

**Issue by antoine-guillou** [jtablesaw/tablesaw#216]
I was expecting the 'set' methods of columns (CategoryColumn, FloatColumn, ShortColumn...) to overwrite an existing value. But it appears that they are adding to the underlying data list.
Do you agree that this is not the expected behaviour and we should be calling the 'set' method of the underlying  list?

**Comment by lwhite1** [comment]
i expect it would overwrite existing values when the index referred to an existing value. Is this not happening?
e.g.
if the column has 4 values, set(0, 23423) would overwrite the first value with 23423. If you called set(4, 34), it would add a row and set that value. This is maybe also not desirable, but seems more correct than your description suggests.

**Comment by antoine-guillou** [comment]
No, it is not what is happening. The 'add' method of the underlying list is always inserting a new element at the specific position, thus increasing the size of the list (and the column). 

col = [ 1. , 2. , 3. , 4.]
col.set( 0 , 666. )
col = [ 666., 1. , 2. , 3. , 4.]

To my mind we should call the 'set' method of the underlying list.

**Comment by lwhite1** [comment]
Ok.  I will fix

**Comment by antoine-guillou** [comment]
Ok! If you want, I can give it a try and do a PR.

**Comment by lwhite1** [comment]
That would be great!

**Comment by benmccann** [comment]
Looks like this is fixed now
