### ISSUE TITLE
Display Table in TableView

### ISSUE THREAD

**Issue by antoine-guillou** [jtablesaw/tablesaw#218]
I wrote a component to display a Table in a JavaFX TableView:
![image](https://user-images.githubusercontent.com/5755073/34160978-f1a848ce-e4c6-11e7-97ae-83461bcaca51.png)

Is it something you would be interested in?
If so, where should I add it? With the plots?

I think it would be nice to have a simple UI to explore a Table, similar to:
https://github.com/bluenote10/PandasDataFrameGUI

**Comment by lwhite1** [comment]
I like it!. I think the plot component is the right place.

Is this OK with you, Ben?

**Comment by benmccann** [comment]
Nice! Yeah, plot sounds like the right place

We also have a very similar widget that you can use in Jupyter. You may want to check it out as well by installing [beakerx](http://beakerx.com) and following this example: https://github.com/twosigma/beakerx/blob/master/doc/groovy/Tablesaw.ipynb

**Comment by lwhite1** [comment]
Implemented
