### ISSUE TITLE
Add conditional update column methods: set(value, selection)

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#219]
I feel like maybe @benmccann has already added something like this, but if not, I will add (sometime soon) column methods, that do conditional updates. For example, for CategoryColumn: 

```
    public void set(String newValue, Selection rowSelection) {
        for (int row : rowSelection) {
            set(row, newValue); 
        }
    }
```
Example:
```
    myCatColumn.set("Dog", myCatColumn.isEqualTo("Cat")); // no more cats
```

**Comment by benmccann** [comment]
Nope. I haven't added anything like this

**Comment by lwhite1** [comment]
implemented.
