### ISSUE TITLE
Sorting on date column is broken

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#222]
See https://github.com/jtablesaw/tablesaw/commit/9433574bdfb339487fadd868ea410e5fee17e156

**Comment by benmccann** [comment]
The code below from `PackedLocalDate` seems to be invalid:

    public static int pack(LocalDate date) {
        short year = (short) date.getYear();
        byte byte1 = (byte) (year & 0xff);
        byte byte2 = (byte) ((year >> 8) & 0xff);
        return Ints.fromBytes(
                byte1,
                byte2,
                (byte) date.getMonthValue(),
                (byte) date.getDayOfMonth());
    }

If you split the year 1920 into bytes you get -128 & 7. Then you get a negative number from Ints.fromBytes

**Comment by benmccann** [comment]
@lwhite1 I think that the values for `byte1` and `byte2` are reversed. I think perhaps it should be:

    byte byte1 = (byte) ((year >> 8) & 0xff);
    byte byte2 = (byte) year;

What do you think?

**Comment by lwhite1** [comment]
ok. I will take a look.

**Comment by benmccann** [comment]
Nevermind @lwhite1. I figured out what my issue was. That fix does work after all. See https://github.com/jtablesaw/tablesaw/commit/4eb143d37cfd427a9bad8f97d370245e51b96f96

**Comment by lwhite1** [comment]
Just wasted two hours fixing the same issue. :(

**Comment by benmccann** [comment]
Sorry :-( I had a really stupid mistake and suddenly realized what I had done wrong

**Comment by lwhite1** [comment]
no problem. I'm already sorry I made that comment.

Happy New Year, btw.

**Comment by benmccann** [comment]
No problem. I appreciate you taking a look

Happy New Year to you too! (and Merry Christmas :-)
