### ISSUE TITLE
Extend support for selection by relationship between two columns

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#225]
You can select rows based on the relationship between the values in two columns. For example:

```
Table t = houseTable.selectWhere(column("living room color").isEqualTo(column("kitchen color")));
```
Right now, we've only implement isEqualTo selection, and greaterThan and lessThan selection for numeric types, but we need also before and after comparisons for date/time types. 

This code explains how to implement greaterThan support for double columns. Before and after date/time columns is analagous: 

- Implement a class like tech.tablesaw.filtering.columnbased.ColumnEqualTo called ColumnGreaterThan
- Add implementation of the isGreaterThan(DoubleColumn c) in DoubleColumn. 

```
// in ColumnReference
    public Filter isGreaterThan(ColumnReference reference) {
        return new ColumnGreaterThan(this, reference);
    }
```

**Comment by d-spirov** [comment]
I already can see tech.tablesaw.filtering.columnbased.Column.ColumnGreaterThan, is this issue already implemented?

**Comment by lwhite1** [comment]
It's been extended to include GT and LT. It could be further extended to include before and after dates or dateTimes.

**Comment by lwhite1** [comment]
now have good support for all column types
