### ISSUE TITLE
How can I do difference or some other aggFunction with groupBy?

### ISSUE THREAD

**Issue by ricklovelisa** [jtablesaw/tablesaw#227]
I am new to Java.
Now I have a question, How can I define a aggFunction and use it in Table with groupBy?
I want to do differece in a DoubleColumn with same Category.
for example.

|dim1|dim2|dim3|measure|
|:----:|:----:|:----:|:----:|
|1|aa|ccc|1.0|
|2| aa|bbb|1.3|
|2|    aa    |    ccc  |    1.9        |
|   1     |    cc    |    aaa  |    11.0      |
|   2     |    cc    |    aaa  |    7.0      |
|   1     |    aa    |    bbb  |    1.0        |

I want to group By dim2 and dim3, sort on dim1, then do differece or mean or sum on measure, return table like 

|dim1|dim2|dim3|difference|sum|mean|
|:----:|:----:|:----:|:----:|:----:|:----:|
|2|aa|ccc|0.9|2.9|1.45|
|2| aa|bbb|0.3|2.3|1.15|
|2| cc | aaa  | -4.0 |18.0|9.0|

Can I do that？

**Comment by lwhite1** [comment]
To use an aggregate function with groupby, you can use the summarize() method on table. 

```
table.summarize("numericColumnName", AggregateFunctions.median).by("SummaryColumnName");
```
if you want to define a new aggregate function you can implement the AggregateFunction interface, like this:

```
new AggregateFunction() {

        @Override
        public String functionName() {
            return "First";
        }

        @Override
        public double agg(double[] data) {
            return data.length == 0 ? Float.NaN : data[0];
        }
    };  
 
```
