### ISSUE TITLE
Can we support DoubleColumn filter?

### ISSUE THREAD

**Issue by ricklovelisa** [jtablesaw/tablesaw#228]
I found many filter ops are not support on DoubleColumn type，just like isGreaterThan ....

I can add one new column to tag something I want, and I can do some ops on tag column, but I don't think it's efficient.

In some situation, I have to use double type instead of float type, so can we add the support of filtering on DoubleColumn?

**Comment by lwhite1** [comment]
Hi @ricklovelisa, Sorry for the inconvenience, and to take so long to get back to you. 
The DoubleColumn supports isGreaterThan (a value) and isGreaterThan( a double column) 
in master, although they may not be in Maven Central yet. 

Hopefully, it will be available soon without building from source.
