### ISSUE TITLE
CrossTab.xTabCount change column type to CategoryColumn

### ISSUE THREAD

**Issue by jorgaf** [jtablesaw/tablesaw#229]
Hello,

Thanks for this great tool.

I have a Table with the number of tweets and retweets published by hour. I am using CrossTab.xTabCount to count the number de post by hour. My code looks something like this:
`Table tblTweetsByHour = CrossTab.xTabCount(tweetsByHourTable, colHour, tweetsByHourTable.categoryColumn("isRT"));`

Then, I tried to sort (asc) the table (tblTweetsByHour) using the hour (colHour), but no working. Trying to solve the problem, I noticed hour's column is now a Category column.

I think CrossTab.xTabCount does not should change the data type of the columns.

**Comment by lwhite1** [comment]
Hi, I just wanted to acknowledge the issue. It may take a while to fix as the code assumes categorical factors when it turns a count cross-tab into a percentage cross tab, but it would be better if it worked as you suggest.

**Comment by lwhite1** [comment]
fixed so that the first column argument (used to provide the row labels) keeps its original type in version 0.20.0. the above code should work. 

Values from the second column argument become the titles of the computed numeric columns, so they are strings.

**Comment by lwhite1** [comment]
this fix breaks column totals when the label column does not contain strings. having no totals for counts breaks the calculation of column percents

**Comment by lwhite1** [comment]
fixed the fix
