### ISSUE TITLE
Standardize available column constructors to pass existing data (list, array, arrayList)

### ISSUE THREAD

**Issue by numericOverflow** [jtablesaw/tablesaw#230]
Is there any particular reasoning behind the available column constructors for passing existing data?  They seem to vary quite a bit across each of the data types.  It seems like they should all have, at a minimum, the ability to accept an array, and possibly a list.  Here's what I've found for currently available constructors by column type:

    BooleanColumn  	- **None of: (List, Array, it.unimi.dsi.fastutil.booleans.BooleanArrayList)
    CategoryColumn 	- List & Array
    DateColumn	- ListOnly
    DateTimeColumn	- ListOnly
    DoubleColumn	- ArrayOnly   <- Missing it.unimi.dsi.fastutil.doubles.DoubleArrayList
    FloatColumn	- ArrayOnly & FloatArrayList
    IntColumn	- ArrayOnly & IntArrayList
    LongColumn	- ArrayOnly   <- Missing it.unimi.dsi.fastutil.longs.LongArrayList
    ShortColumn	- ArrayOnly   <- Missing it.unimi.dsi.fastutil.shorts.ShortArrayList
    TimeColumn	- ListOnly

Is it possible to add these missing column constructors?  Boolean seems to be the least robust (and the one I was after) but the others have varying capabilities as well.

**Comment by benmccann** [comment]
I think we should expose List and Array constructors. I prefer not to expose fastutil constructors if possible as I think it'd be better to keep that as an internal implementation detail

Pull requests welcome if you'd like to take a stab at this!

**Comment by numericOverflow** [comment]
@benmccann - That makes sense to skip fastutil types, I'd say List/Array are most common.

After some quick digging, it looks like [this change](https://github.com/jtablesaw/tablesaw/commit/1c602a1de8d1f0896006e22a4c564b51099cd50c#diff-98a4b28b9f4bfb75344679d189d9087b) added some better but still incomplete constructor support.

I was looking into the actual source code and noticing that my older version (0.11.2), and the API docs at https://jtablesaw.github.io/tablesaw/apidocs/index don't have the boolean[] constructor, but github source has it in v0.11.4.  There may be differences from my list above to the current source code, since I was going off the API docs - which should probably be updated to reflect recent changes?

 I'll try to check the source code and update that list above and see where we're at in latest version.

**Comment by lwhite1** [comment]
fixed.
