### ISSUE TITLE
isBetweenIncluding // isBetweenExcluding Filter not behaving as I thought?

### ISSUE THREAD

**Issue by MalteBahr** [jtablesaw/tablesaw#234]
Table res =  d.selectWhere(

                allOf(

                        column("seqname").isEqualTo("chr1"),
                       /*

                        column("start").isGreaterThanOrEqualTo(0),

                        column("start").isLessThanOrEqualTo(1000),

                        column("end").isGreaterThanOrEqualTo(0),

                        column("end").isLessThanOrEqualTo(1000)

                       */
                        column("start").isBetweenIncluding(0,1000),

                        column("end").isBetweenIncluding(0,1000)

                )
        );

I would expect both versions (the commented out and the uncommented version after that) to do the same thing, but the second version doesn't appear to be restricting the select in any way (all rows with seqname equal to chr1 are selected).
I'm not sure whether I don't understand what isBetweenIncluding is supposed to do or the method simply doesn't work at the moment. Either way, some documentation for the method would be helpful.

**Comment by benmccann** [comment]
You have the correct understanding of how the method should work. Seems like there's maybe a bug here

In fact, here's the source code for `IntBetweenInclusive`:

```
    public Selection apply(Table relation) {
        IntColumn intColumn = (IntColumn) relation.column(columnReference.getColumnName());
        Selection matches = intColumn.isGreaterThanOrEqualTo(low);
        matches.toBitmap().and(intColumn.isLessThanOrEqualTo(high).toBitmap());
        return matches;
    }
```

We'd welcome a pull request if you'd like to take a stab at fixing this and adding a test to prevent a regression

**Comment by lwhite1** [comment]
fixed.
