### ISSUE TITLE
Feature request: Cumulative sum, but where to put it?

### ISSUE THREAD

**Issue by numericOverflow** [jtablesaw/tablesaw#235]
I've got a use case where I need to find a [cumulative sum](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.cumsum.html) on a column.  I've put together the logic to operate on a column, but I can't decide where it would fit into tablesaw.  It's not really an aggregate (returns more than a single double value), and is not really a rolling function (since you can't calculate it in partitions the way rolling functions are implemented).

```
        public DoubleColumn cumsum(DoubleColumn columnData) {
            double csum = 0.0;
            DoubleColumn col = columnData.copy();

            for (int i = 0; i < columnData.size(); i++) {
                double value = columnData.get(i);

                if (!Double.isNaN(value)) {
                    csum += value;
                    col.set(i, csum);
                }
                else {
                    col.set(i, csum);
                }
            }
            return col;
        }

```

Thoughts?

**Comment by lwhite1** [comment]
I think it should be defined on NumericColumn, and operate on the column itself (i.e. an implementation should take no parameters). Without compiling and testing, something like this, maybe?

```
        public DoubleColumn cumSum() {
            double csum = 0.0;
            DoubleColumn col = new DoubleColumn(size());

            for (int i = 0; i < columnData.size(); i++) {
                double value = columnData.getDouble(i);

                if (!Double.isNaN(value)) {
                    csum += value;
                    col.set(i, csum);
                }
                else {
                    col.set(i, csum);
                }
            }
            return col;
        }

```
What do you think?

**Comment by numericOverflow** [comment]
I've coded up a version of cumSum that should work for this.  No unitTest - my Java-fu is pretty limited as I'm not a hardcore developer, just a scripter that dusts off java knowledge from college when called upon :) .
See pull request: #243
