### ISSUE TITLE
Allow subtraction between any two numeric columns types

### ISSUE THREAD

**Issue by ashvina** [jtablesaw/tablesaw#237]
Currently a `LongColumn` can be subtracted from a `LongColumn`. The api does not allow subtracting a `IntColumn` from a `LongColumn`. This limitation can result in additional data copies and steps. For e.g. To compute difference between `Salary (long)` and `Median-Salary`, one might do this:
```
NumericSummaryTable medians = table.median("Salary").by("ZipCode", "Gender")
```

Since medians is a `DoubleColumn`, it cannot be directly subtracted from the Salary column which is of type `LongColumn`. The user has to convert Salary to Double or Median to Long.

As discussed in #236, This issue can be solved in two phases
 1. Implement methods in `NumericColumns` to return `up-converted` values. For e.g. `ShortColumn` will implement `getInt()`, `getDouble` etc.
 1. Implement generic version of `subtract` method to return `up-converted` column types.

**Comment by lwhite1** [comment]
closed. implemented
