### ISSUE TITLE
Time series forecasting

### ISSUE THREAD

**Issue by mario-s** [jtablesaw/tablesaw#247]
I came accros an interesting article about forecasting based on time series dataset:
https://www.analyticsvidhya.com/blog/2018/02/time-series-forecasting-methods

There is also a Java   mplementation for some of those methods, released under GPL:
https://sourceforge.net/projects/openforecast/

I think it would be great, if such a feature exists in tablesaw.

**Comment by benmccann** [comment]
OpenForecast doesn't look very well maintained - 7 years since the last release. I'm not sure that we'd want to add a dependency on it

**Comment by lwhite1** [comment]
GPL is also kind of a non-starter.
