### ISSUE TITLE
is DateIsOnOrAfter should use long

### ISSUE THREAD

**Issue by lokinell** [jtablesaw/tablesaw#255]
Dear @lwhite1 , 

_public DateIsOnOrAfter(ColumnReference reference, int value)_ here value is **int**,
however, in _dateColumn.isOnOrAfter(value)_, this value is **long**.

I think this is a bug.

**Comment by lwhite1** [comment]
yup. I will fix over the weekend. thanks for the report.

**Comment by lwhite1** [comment]
fixed.
DateColumn uses ints internally. Its methods take an int.
DateTimeColumn uses longs internally. Its methods take a long.
The table filters and column filters for each are now consistent.
