### ISSUE TITLE
apidocs in main tablesaw folder are not being updated

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#262]
The docs in the individual projects are up-to-date, but the main folder docs are obsolete.

**Comment by benmccann** [comment]
I think this will work:
```
rm -rf docs/apidocs
mvn javadoc:aggregate
```

**Comment by lwhite1** [comment]
yup. didn't realize it needed a specific target since the the docs are generated for the child modules, but thanks. :)
