### ISSUE TITLE
Add aggregate functions that take values

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#276]
A variation like 

`StringAggregateFunction<String> 
`
defining:

`double summarize(column, T value);
`
An example use case: count the number of times the word 'foo' appears in a text column.

**Comment by lwhite1** [comment]
another way to approach this would be to use an intermediate column, writing instead:

```
StringColumn matches = strColumn.isEqualTo("foo");

double result = matches.count();
```

This is not too bad, especially if you inline the call to count():
`
double result = strColumn.isEqualTo("foo").count(); 
`

the alternative might look like:
`
double result = strColumn.countMatches("foo");
`

**Comment by benmccann** [comment]
Or another alternative that would allow counting contains, equals, or any other function you can think of would be to do something more like the Excel API:
```
double result = strColumn.countIf(str -> str.equals("foo"));
```

**Comment by lwhite1** [comment]
yeah. something like that might be much better.

**Comment by lwhite1** [comment]
implemented as:
```
    column.summarizeIf(Selection s, AggregateFunction f);
```
so you can count like:
```
    column.summarizeIf(column.endsWith("3"), AggregateFunctions.count);
```
