### ISSUE TITLE
IDEA support

### ISSUE THREAD

**Issue by thomashaselwanter** [jtablesaw/tablesaw#279]
IDEA has support for viewing dataframes in Python / pandas. Once tablesaw has a stable API (eg after the 0.2 release?), it would be nice if we could petition JetBrains to support this feature for tablesaw.

https://www.jetbrains.com/help/pycharm/viewing-as-array.html
https://www.jetbrains.com/help/pycharm/data-view.html

![](https://d3nmt5vlzunoa1.cloudfront.net/pycharm/files/2017/02/data_view.png)

**Comment by lwhite1** [comment]
I really like this idea. (no pun intended). I will make the request after we get 0.20 stable.

**Comment by thomashaselwanter** [comment]
Cool, let us know here when the feature request is live on the JetBrains tracker. We will want to vote for it so it gets more attention.
