### ISSUE TITLE
add min and max MAP functions

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#283]
c1.min(c2) -> returns c3, containing the element-wise minimum of c1 and c2.
c1.min(scalar) -> returns c3, containing scalar if it is less than the corresponding element of c1, or said element of c1.

**Comment by hallvard** [comment]
If Column implemented Comparator, as a way of comparing elements, we could provide a default implementation. This is easiest if Column itself is parameterised, i.e. class Column<T>, where e.g. DoubleColumn implements Column<Double> and hence also Comparator<Double>. See issue #285

**Comment by lwhite1** [comment]
I'm not sure I get this entirely. 
I believe all columns currently implement min and max over their elements. 
This issue is for an element-wise min between (a) two columns of the same type, or (b) a column and a scalar value. 

```
 a        b 
---     ---
 1        2
 0       -4
-1        0
```
so that
a.min(b) returns 
```
 a         
---     
 1         
-4
-1        
```
and a.min(0) returns
```
 a         
---     
 0         
 0
-1      
```

**Comment by hallvard** [comment]
Yes, I think I understood that. The signatur for min would be Column&lt;T&gt;.min(Column&lt;T&gt;) and could be implemented generically, if Column implements Comparator&lt;T&gt; and hence implements int compare(T, T). For DoubleColumn you would for performance reasons override the default one, but StringColumn would use it.

**Comment by lwhite1** [comment]
done
