### ISSUE TITLE
Replace CSV library with faster alternative

### ISSUE THREAD

**Issue by cc-cpo** [jtablesaw/tablesaw#284]
Hi,

I hacked an integration of FastCSV as an replacement for opencsv.

FastCSV is my preferred CSV implementation and I am co-maintaining the library.

Advantages that I see:
* small footprint (no dependencies, 16k jar size)
* nice performance results verified with JMH (see results https://github.com/osiegmar/FastCSV)
* dedicated and used in real-world ETL use cases

If you are interessted, see the diff of the required changes [here](https://github.com/cc-cpo/tablesaw/compare/v0.12.0...cc-cpo:use-fastcsv-v0.12.0?diff=split&name=use-fastcsv-v0.12.0).

let me know, how you feel about that

Regards
Stefan

**Comment by thomashaselwanter** [comment]
opencsv defenitely seems to be one of the slower ones. I appreciate this improvement suggestion a lot since in my use case CSV performance make a real difference.

I'd be curious how FastCSV compares to uniVocity. Unfortunately the FastCSV performance comparison and the uniVocity performance comparison each don't include the other parser and both claim to be the fastest.
https://github.com/uniVocity/csv-parsers-comparison
https://github.com/osiegmar/JavaCsvBenchmarkSuite

**Comment by benmccann** [comment]
I agree. I think if we were going to try to optimize by picking the fastest CSV library we should compare against jackson-dataformat-csv, univocity, etc.

The fastcsv comparison mainly benhcmarks against libraries we'd be unlikely to use. E.g. Javacsv hasn't been used updated in 10 years and super csv is no longer maintained either.

**Comment by lwhite1** [comment]
@cc-cpo Thanks very much for doing this. I would be interested in trying it out. I looked briefly at Univocity but never got around to making the changes. As @benmccann and @thomashaselwanter said, it would be great to see a comparison as Univocity, since that's the implementation other people have suggested; they're the ones to beat these days.  

@thomashaselwanter, regarding your CSV performance needs: It depends on the use case, but most  of the time now goes (i think) to guessing the column types. If you supply them to the csv import method you should get better performance. There's some assistance in the library for doing this. LMK if you aren't familiar.

**Comment by cc-cpo** [comment]
@thomashaselwanter I agree that there must be a physical limit around. my researches on that pointed to a similar direction (yet simpleflatmapper not univocity). The uniVocity benchmark you mention shows negligible differences (16%) between simpleflatmapper and univocity.

in order to make a profound decision with respect to tablesaw IMHO we need
1. a dedicated benchmark setup for tablesaw-related scenarios
2. a list of criterias other than performance to adhere (e.g. external dependencies, RFC compliance, API)

@lwhite1 although I am biased towards fastCSV, I could offer help to jump on the CSV topic - regardless if it will be uniVocity or something else

**Comment by benmccann** [comment]
Univocity suggests that fastcsv is not amongst the fastest csv libraries: https://github.com/uniVocity/csv-parsers-comparison/issues/20#issuecomment-383522768

**Comment by thomashaselwanter** [comment]
@cc-cpo Great to hear that you aren't religious about the use of FastCSV and willing to help even if it ends up being a different library. Currently it looks like uniVocity is probably the way to go?
I don't think a dedicated benchmark setup for tablesaw is worth the effort. If there is still doubt I suggest to create a pull request which includes the FastCSV library in this benchmark: https://github.com/uniVocity/csv-parsers-comparison (and vice versa include uniVocity in your own benchmark if you like)

**Comment by cc-cpo** [comment]
Hello @thomashaselwanter,

I tried to replace OpenCSV by uniVocity.

You can find the relevant changes here https://github.com/jtablesaw/tablesaw/pull/289

The code is not brushed on IMO not ready for merge and should only be used for discussion

Here are my points:
1. could you please check the lines marked with TODO
2. I did not quite understand the logic behind CsvWriteOptions.java and I thus was unfortunately not able to verify compatibility between the OpenCSV and Univocity implementation
2. commons-text must be version 1.1 and breaks the whole system with version 1.2/1.3
3. I introduced adapters in order to swap out different CSV implementations - IMHO we should consider to remove these adapters after the experiments or the migration respectively 
4. some of the tests fail on my machine due to different locale

Let me know, what your impression is.

Regards

Stefan

**Comment by thomashaselwanter** [comment]
That's great @cc-cpo, personally I think uniVocity is a good choice. I will have a look and give it a spin but I am just a simple user of tablesaw myself. @lwhite1 is more qualified to comment on your implementation and approve a merge. That being said, I'll give your code a test drive as soon as I have some free time.

**Comment by lwhite1** [comment]
> I did not quite understand the logic behind CsvWriteOptions.java and I thus was unfortunately not able to verify compatibility between the OpenCSV and Univocity implementation

I'm not sure what you found unclear. CsvWriteOptions just wraps the options presented by OpenCsv's com.opencsv.CSVWriter. It doesn't really have much logic of its own.

**Comment by benmccann** [comment]
OpenCSV has 4 dependencies. Univocity has 0. That might be another reason to switch

**Comment by benmccann** [comment]
I'm open to switching to Univocity. @lwhite1 do you think it's a good idea?

**Comment by lwhite1** [comment]
I like the idea generally.  I was thinking of checking the benchmarks again
to see how much faster it might be.  But it seems fine if it’s not too
hard.

**Comment by lwhite1** [comment]
Replaced OpenCSV with Univocity.  My testing suggests it is about 30% faster.

**Comment by thomashaselwanter** [comment]
Thanks, can't wait to try it.
