### ISSUE TITLE
Parameterize Column with element type

### ISSUE THREAD

**Issue by hallvard** [jtablesaw/tablesaw#285]
I suggest declaring Column as **class Column&lt;T&gt;** where T is the element type (same for CategoricalColumn), and fixing the API accordingly. This will allow cleaner and more generic code, but there are also some issues:
- overloading methods with native types, e.g. **set(int row, double value)** and **set(int row, Double value)** are allowed, but **double get(int row)** and **Double get(int row)** cannot co-exist, hence a different name may need to be invented for the generic methods
- missing values must be handled, e.g. null must be mapped to MISSING_VALUE by methods like set and append
I made a working implementation in an hour that passed all tests.

**Comment by lwhite1** [comment]
@hallvard I don't suppose you have that generic implementation and would be willing to submit a pull request? I wouldn't worry about it being out of date relative to the current master version. I just want to get a sense of the changes required.

**Comment by hallvard** [comment]
Certainly, see PR #312. I don't recall the details now (there's summer vacation time in Norway, now), but I think there were mainly two issues:
- You may need to introduce new methods when there's a clash between generic methods returning Double (for DoubleColumn implemts Column<Double>) and methods returning double.
- A copy method needed to switch on the element type.
Feel free to contact me about this.

**Comment by benmccann** [comment]
What's the advantage of this? Can you share an example of a type of problem you were trying to solve that this allowed you to address?

I'm worried that it will be much more cumbersome to deal with having `Column<?>` everywhere (vs. `Column`) and that it will be less performant to do so much typeboxing instead of just dealing with primitive `double`

**Comment by hallvard** [comment]
I want to write generic code when building Eclipse tool support for tablesaw. Being forced to write Column<?> just highlights (alerts you of) the fact that the element type is unknown/implicit.

The type-specific implementations like DoubleColumn can still have type-specific methods so you don't need boxing, similar to libraries that offer fast type-specific collections (for value types).

**Comment by benmccann** [comment]
Would it solve the problem if we did something like `DoubleColumn extends Column implements GenericColumn<Double>`? Then most users don't have to change their code, but you can still have generic support

It's still not clear to me what generic support allows you to do exactly. It might be helpful to see a snippet of code that you can write only with generic support for example

**Comment by lwhite1** [comment]
FWIW, my short-term interest in generic support is to be more "java-ish", generally, and perhaps to simplify the (re)introduction of other numeric types. Of course, some uses of generics are prohibitively expensive, but many column methods that use scalars as input or output could be genericized without notable performance penalty. 

```
intColumn.isGreaterThan(T i)
```
only needs to unbox one integer regardless how big the column is.

My longer-term expectation is we will see value types in Java that provide primitive-like performance with standard class-like semantics. At that time a Column<Int> will be the right way to go. How important that is now is obviously up for debate. 

On the other hand, it's also unclear how many users we actually have. (We definitely have no **_paying_** users ;)

**Comment by benmccann** [comment]
@hallvard [I parameterized `AbstractColumn`](https://github.com/jtablesaw/tablesaw/commit/d5c79fb39d9b42069cb13a721f8f8f4f78ef3d9e). Does that address what you were looking for? It made it pretty [easy for me to implement methods in a generic way](https://github.com/jtablesaw/tablesaw/commit/d4b44976db7e3a9a5a6b2877ad68739ef51ea8ff)

**Comment by benmccann** [comment]
I thought that `Column<Double>` or `Column<?>` would be more cumbersome for users. However, I've been thinking about this since seeing this issue and I find in practice that I never use `Column` as an end user anyway, so I'm not so concerned anymore. I usually use the specific typed columns like `StringColumn`, `DateColumn`, etc. as an end user because they have much more functionality

The one thing I think we should be a little careful of is how this interacts with `NumberColumn`. E.g. right now I have:

```
NumberColumn yearColumn = table.dateColumn("Date").year();
```

Will I need to always be doing the following?
```
NumberColumn<Double> yearColumn = table.dateColumn("Date").year();
```

I think we might need to change those methods to return `DoubleColumn` instead

**Comment by lwhite1** [comment]
>
> NumberColumn<Double> yearColumn = table.dateColumn("Date").year();
> I think we might need to change those methods to return DoubleColumn
>  instead
>

yeah. that sounds right.

**Comment by lwhite1** [comment]
Ok. I'm going to go ahead and make these changes.

**Comment by lwhite1** [comment]
done

**Comment by benmccann** [comment]
One issue I'm noticing that's tough with the methods implemented in a generic fashion on `Column` is that they return a `Column` which means you can't call a lot of methods on the return value. E.g. if you have a `Column<LocalDateTime>` then you can't call methods that would be on a `DateTimeColumn`. There are methods like `min()`, `countTrue()`, etc. that are only defined on certain column types

One way to fix this would be to override every generic method on every column:
```
    @Override
    public BooleanColumn subset(Selection selection) {
        return (BooleanColumn) super.subset(selection);
    }
```

Another would be to change the type parameter on Column:
```
class Column<T, COL extends Column<T>> {
  default COL subset(Selection selection) {
  }
}
```

I'm not sure it's worth addressing at the moment, but thought I'd share this observation

**Comment by hallvard** [comment]
You're right, you cannot call methods that are specific to the implementation of the interface (with type parameters). However, you can call generic methods with arguments specialised to the type parameters, e.g. min(Comparator<LocalDateTime>), which is defined in Column. Since Column now also implements Comparable, min could be implemented in Column, too.

Perhaps Selection also needs to be parameterised?

**Comment by lwhite1** [comment]
@benmccann I do think we should try to do something to minimize the amount of code needed. Most of the methods that return columns I think, do so just to facilitate chaining, which is hindered if you have to cast. (Of course you get that a lot with Streams, too).  

We could make the "chain-only methods" return void and override what remains. 

Does changing the type parameter get us past this? Is there any downside (aside from having unsightly type parameters? ;)

@hallvard, I'm not sure adding type params to Selection would work very well. It's often used without consideration of type (in table filtering for example). Also, there's a boatload of methods that would need to be changed, I think. And with the canned methods, it's not always clear what the user wants. You can create a selection in one type for filtering another. 
```
    country.where(gdp.isGreaterThan(x)) ;
```
presumably the selection type would be numeric here, but the return type would be string.
