### ISSUE TITLE
Discussion: Apache Arrow

### ISSUE THREAD

**Issue by thomashaselwanter** [jtablesaw/tablesaw#288]
Apache Arrow seems to be getting more track every day as a common format for columnar in-memory data as used for data frames. The main guy driving it is the original developer of pandas and has poured all the accumulated experience of what is wrong with pandas into the Apache Arrow project and will use it as a base for pandas2. Read this: http://wesmckinney.com/blog/apache-arrow-pandas-internals/

There is a native Java implementation. Could this project take advantage of it and how does it compare to what Tablesaw currently uses?

**Comment by lokinell** [comment]
Is a plan to support apache arrow to read .saw file?

**Comment by lokinell** [comment]
@lwhite1 thank your reply.
As I know, when use parquet, its schema do not support Chinese.  That means cannot use Chinese in table's header.

**Comment by thomashaselwanter** [comment]
@lwhite1 Thanks, I understand. As I don't have any experience with Arrow, I am not even sure if there would be significant benefits to using Arrow over the current datastructure in use (fastutil) in the Tablesaw specific use cases. Just seemed interesting and relevant.

Since it was mentioned here: Is the .saw binary storage format still supported? I can't find it in the current code base anymore.

**Comment by lwhite1** [comment]
I removed the .saw format in 0.20-SNAPSHOT because it made it harder to make the changes I wanted to make. I was not aware of anyone using it. I think you need 10s of millions of records before CSVs are too slow for interactive analysis.

**Comment by hudsonb** [comment]
Wouldn't arrow be a replacement for the in memory representation of tables rather than on disk like .saw and parquet?

**Comment by thomashaselwanter** [comment]
Yes Arrow is about the in-memory representation.

**Comment by benmccann** [comment]
Arrow's in-memory representations like [IntVector](https://arrow.apache.org/docs/java/org/apache/arrow/vector/IntVector.html) are much more limited than fastutil's collections which we utilize today. In particular, their size cannot be expanded like fastutil's `IntArrayList`, so I'm not sure it'd be a good fit for TableSaw's internal usage. I'm open to learning more though

@lwhite1 perhaps there'd be some value to importing / exporting data as Arrow. This could allow more efficient usage of data between TableSaw and other tools like Dremio and Spark perhaps. One thing I'm particularly interested in is whether we could have a single library for reading/writing columnar data shared by multiple libraries in the Java ecosystem. 

Dremio makes extensive use of Arrow. As Dremio reads data from different file formats (Parquet, JSON, CSV, Excel, etc) and different sources (RDBMS, Elasticsearch, MongoDB, HDFS, S3, etc), data is read into native Arrow buffers directly for all processing. If we could import Arrow then perhaps we would be able to support all of these different sources without having to create our own readers.

**Comment by benmccann** [comment]
It looks like the code that Dremio uses for these different data sources is below

https://github.com/dremio/dremio-oss/tree/master/sabot/kernel/src/test/java/com/dremio/exec/store

https://github.com/dremio/dremio-oss/tree/master/plugins

**Comment by lwhite1** [comment]
Switching to arrow is a great deal more work than I would be interested in
doing.

As far as importing from Arrow, I think we get a lot of inquiries about
importing from various sources, but afaict it's mostly all tire-kicking and
no real plans for usage.

**Comment by lwhite1** [comment]
Re-opening to add arrow support and get rid of saw support, assuming Arrow io is at least as fast.

**Comment by lwhite1** [comment]
Baseline support is added. It may be desirable/necessary to modify the interface to fit better with existing reader/writer framework, but that needs to be examined to understand the illegal reflection warnings/errors seen with more recent JDK versions
