### ISSUE TITLE
why table column name is case insensitive?

### ISSUE THREAD

**Issue by lokinell** [jtablesaw/tablesaw#292]
Dear @lwhite1 ,

I find column name of table is case insensitive. Can you make the column name case sensitive?

I find I can change Table class and Relation class to use equals replace equalsIgnoreCase method, then table column name will case sensitive. But I cannot make sure it will not bring side effects。

**Comment by lwhite1** [comment]
No. That is intentional so you don’t have to remember the case of column
names.
