### ISSUE TITLE
Table.ColumnCollector class not public, cannot be accessed from outside package?

### ISSUE THREAD

**Issue by mark27q1** [jtablesaw/tablesaw#294]
The Table documentation indicates there is a method called collectFromEachRow() which takes as a parameter a Table.ColumnCollector instance. The Table source contains a usage example (which doesn't make it into the javadoc, by the way) which would seem to imply that I should be able to instantiate a Table.ColumnCollector with a suitable override for the abstract method and use it to apply a function to each row of a table and construct a column containing the results. Unfortunately it seems the Table.ColumnCollector class is not public and so cannot be used outside the tablesaw library package. Is this intentional? Is Table.ColumnCollector only intended for internal use and not for use by end users? If so, should collectFromEachRow() perhaps be package private?

I implemented the function application I was after by using the doWithRows() method instead, by writing a class implementing the Consumer<Row> interface and using that instead. It works great but I'm left with curiosity about the collectFromEachRow() method. Is it a leftover from earlier versions? Supposed to be internal? Supposed to be usable by users (in which case I guess it not being public is a bug?) And what's the difference in intent between collectFromEachRow() and doWithRows()?

Thanks!

**Comment by lwhite1** [comment]
I would use doWithRows.  Not sure the collect method will make into the
release version

**Comment by mark27q1** [comment]
OK, thanks. Doing that, and it's working.
