### ISSUE TITLE
API inconsistency -- adding missing values to columns

### ISSUE THREAD

**Issue by mark27q1** [jtablesaw/tablesaw#295]
DateTimeColumn class has an addMissing() method that returns a DateTimeColumn.
NumberColumn class is missing an equivalent method and so falls back to the addMissing() method from the parent Column class.

The effect is that you can add a missing value (NaT) to a DateTimeColumn with:
`col = col.appendMissing();`

but if using a NumberColumn to add a NaN you need:
`col = (NumberColumn) col.appendMissing();`

I assume this will work (haven't got my code ready to test yet) but could an appendMissing() override be added to NumberColumn (and any other column types it is, um, missing from) to make the API consistent?

**Comment by lwhite1** [comment]
thanks very much Mark for these bug reports. They're super-helpful!
