### ISSUE TITLE
Document CrossTab

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#298]
It looks like there's some documentation in `tutorial.md`, but that page is linked to from anywhere in the user guide and I'm not sure the code would compile

**Comment by lwhite1** [comment]
I'm trying to catch up on documentation.

At present, there is one example at the end of gettingstarted.md that would
compile given an appropriate Table. (The example code is based on bush.csv,
but it's not shown.)

**Comment by lwhite1** [comment]
done. See the userguide

**Comment by benmccann** [comment]
thanks!!
