### ISSUE TITLE
Link changes_in_v_0.2 from docs

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#299]

**Comment by benmccann** [comment]
@lwhite1 I put the release notes on https://github.com/jtablesaw/tablesaw/releases. What do you think about this? We could delete the `changes_in_v_0.2.md` file and then add a link to https://github.com/jtablesaw/tablesaw/releases from `toc.md`

**Comment by lwhite1** [comment]
The release notes are definitely where they should be now - with the
release.  Thanks very much.

**Comment by benmccann** [comment]
Cool I updated https://jtablesaw.github.io/tablesaw/ with a link to the release notes
