### ISSUE TITLE
Iterator of row elements and row size

### ISSUE THREAD

**Issue by r2dong** [jtablesaw/tablesaw#300]
It seems currently one could only retrieve elements from rows using columns names. This seems a bit inconvenient. Would it be better if iterators of different types were provided? For instance, we could have 
- Iterator<String> stringIterator();
- Iterator<Double> doubleIterator();

**Comment by lwhite1** [comment]
This is a little vague, so I'm not sure I understand the issue.

You can't have a String iterator on a table without specifying a column, since you can easily have more than one StringColumn in the table. 

Any StringColumn will give you an` iterator<String>` if you ask it for one:  

```
    Iterator<String> strIter = sCol.iterator();
```
Same with the other column types.

If you want to iterate on more than one column at a time, use should use the Row class.

```
     for (Row row : table) {
         String s = row.getString("StringColumnName");  // returns each string in the named column
         double d = row.getDouble("NumberColumnName"); // etc.
     }

```
You still have to get the column by name, but that's close to inevitable.

**Comment by r2dong** [comment]
I am so sorry for the confusion. Let me clarify.

Suppose we have the following table

            example table             
 column 1  |  column 2  |  column 3  |
--------------------------------------
      1.0  |       4.0  |       7.0  |
      2.0  |       5.0  |       8.0  |
      3.0  |       6.0  |       9.0  |

And suppose the user wants to do something individually with each element of a row, say printing the sum. Currently, the user need the following to achieve this:

List<String> columnNames = table.columnNames();
for (Row row : table) {
         double sum = 0;
         for (String columnName : columnNames)
                 sum += row.getDouble(columnName);
         System.out.println("sum is " + sum);
}

which prints the following:

12.0
15.0
18.0

For this to work, the List<String> column names or the table itself need to be visible within the for each loop. Thus the above cannot be implemented as a method that takes a Row object as the single input - the column names or table needs to be passed in as another argument or stored elsewhere, which complicates code unnecessarily and makes it error-prone. 

Since data of a row exists no matter how each column is named, I think there should be a way to directly access data from the API of the row class. And I propose achieving this by implementing methods such as getStringIterator() and getDoubleIterator() for the Row class. Such iterators will return the next element of that row when next() method is called, instead of the columns. For example, suppose I have a row that looks like

----------------------------------
      1.0  |       4.0  |       7.0  |

Then the iterator returned by getStringIterator() of this row will return "1.0", "4.0", and "7.0" each time next() method is called.

**Comment by lwhite1** [comment]
Ah, OK. Now I get it. 

> For this to work, the List column names or the table itself need to be visible within the for each loop. Thus the above cannot be implemented as a method that takes a Row object as the single input - the column names or table needs to be passed in as another argument or stored elsewhere, which complicates code unnecessarily and makes it error-prone.

You could use a closure, but yeah.

Adding the Row class was a first step to improving support for row-wise operations, but it's still limited. I should add something to make this easier. Your solution looks like a good one, but I  would like to think a bit more about it. I've been thinking of adding positional column access as well. 

In the meantime, for your first example, you could use use a column-wise approach:

        NumberColumn sum =
                t.numberColumn(0)
                .add(t.numberColumn(1))
                .add(t.numberColumn(2));
        System.out.println("sum is " + sum.print());

 more generally, you could write a method like this: 

    private NumberColumn sum(NumberColumn ... columns) {
        int size = columns[0].size();
        NumberColumn result = DoubleColumn.create("sum", size);
        for (int r = 0; r < size; r++) {
            double sum = 0;
            for (NumberColumn nc : columns) {
                sum += nc.get(r);
            }
            result.append(sum);
        }
        return result;
    }
       
and call it like: 

     NumberColumn nc = t.sum(t.numberColumns());

note that table has methods like numberColumns() to get all the columns of a given type.

**Comment by lwhite1** [comment]
> For this to work, the List column names or the table itself need to be visible within the for each loop. Thus the above cannot be implemented as a method that takes a Row object as the single input - the column names or table needs to be passed in as another argument or stored elsewhere, which complicates code unnecessarily and makes it error-prone.

I have made Row implement columnNames(), so this is no longer the case. It was an obvious enhancement in hindsight. 

I will leave this open as I think I will at some point add the row-oriented iterators you've requested.

**Comment by lwhite1** [comment]
Actually, I made some more incremental changes that i think suffice for now, although I'd like to do more work here to support your use-case.

With the new version, you can do this:

    for (Row row : table) {
            double sum = 0;
            for (String columnName : row.columnNames())
                    sum += row.getDouble(columnName);
            System.out.println("sum is " + sum);
    }

or this 

    for (Row row : table) {
            double sum = 0;
            for (int i = 0; i < row.columnCount(); i++)
                    sum += row.getDouble(i);
            System.out.println("sum is " + sum);
    }
