### ISSUE TITLE
Consider adding back addColumn

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#301]
@lwhite1 what do you think about adding back the `addColumn` method? Calling `addColumns` to add a single column seems a bit unnatural. It also was one of the most common issues I hit with upgrading and would make the migration easier for our users. E.g. I had to change it 10 places in the BeakerX docs: https://github.com/twosigma/beakerx/pull/7669

**Comment by lwhite1** [comment]
I don't think so. addColumns(Column ... columns) with a single column is no more unnatural than addColumn() with an array argument. Having both is excessive, I think, and I prefer var-arg methods with plural names. 

It's not too hard to change using search/replace. In any case, everyone who's already made the change (like me) would have to go back. 

FWIW, this is the kind of thing I was referring to when I said I wanted to clean-up tablesaw without worrying about backward compatibility, even to the point of forking. It's kinda late to fork now, unless you want to revert 0.21.

**Comment by benmccann** [comment]
Ok. Fine with me. This was the only one I was wondering about. All the other changes made sense to me
