### ISSUE TITLE
Merge tables via a function ?

### ISSUE THREAD

**Issue by yellowbean** [jtablesaw/tablesaw#304]
in a case like : 
a data frame  with scores

  a1  |  Apples |  Oranges 
---- | ---- | ----
  A  |  12  |  42 

 a2  |  Apples |  Oranges 
---- | ---- | ----
  A  |  20 |  10

If user can create 2 tables with information above.

Is there a quick way to "sum" them into a table like 

 a  |  Apples |  Oranges 
---- | ---- | ----
  A  |  32 |  52

Much appreciated and great work on tablesaw !!

**Comment by lwhite1** [comment]
There are several ways to do it, but nothing in one step:
```
        Table t1 = Table.read().csv("../data/bush.csv");
        Table t2 = Table.read().csv("../data/bush.csv");
        Table t3 = t1.emptyCopy();
        t3.column("a").append(t1.column("a"));
        t3.column("Apples").append(t1.numberColumn("Apples").add(t2.numberColumn("Apples")));
```
or  
```
        t3 = Table.create("sum", t1.stringColumn(0).copy());
        for (int i = 1; i < t1.columns().size(); i++) {            
            NumberColumn nc1 = t1.numberColumn(i);
            NumberColumn nc2 = t2.numberColumn(i);
            NumberColumn nc3 = nc1.add(nc2);
            t3.addColumns(nc3);
        }

```

**Comment by lwhite1** [comment]
closing. @yellowbean LMK if this didn't answer your question.

**Comment by yellowbean** [comment]
thanks while

I think it can be solved if I read more documentation.  Basically: rename a1 & a2's first column to "a"
    Table a3 = a1.append(a2)
     a3.summarize( ["Apples", "Oranges"]  [sum ]).by("a")
