### ISSUE TITLE
QUESTION: Are there any gotchas to using Indexes in multiple threads?

### ISSUE THREAD

**Issue by mark27q1** [jtablesaw/tablesaw#308]
Title says it all really. I'm imagining a situation where I create an Index on a data set which I wish to do many queries on. I then create an index on said data set. I then fire off a bunch of threads and pass each one a reference to the data set and to the index I created. Can these threads then concurrently use the Index to find rows in the data set and expect not to get weird answers? Or does each thread need its own index? (Note no modifications to the data set here, except maybe summarisation operations that will create a copy of the data anyway, to which the index would not refer anyway).

**Comment by lwhite1** [comment]
As long as you only create the index in a single isolated thread you can
use it with relative safety in multiple threads.
More specifically, there's only a single shared variable in the index that
is not updated after construction. The underlying object is not marked as
thread safe in its source, but it seems ok. None of it's shared variables
should be modified in a read-only scenario.

The bigger concern is that depending on the query, an index could construct
a large selection, so you need to watch your memory usage.

**Comment by mark27q1** [comment]
Perfect, thanks.
