### ISSUE TITLE
keep published javadoc consistent with releases

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#309]
core currently at tablesaw-core 0.20.0

**Comment by benmccann** [comment]
I think we should run the following as the release process:
```
mvn release:prepare
rm -rf docs/apidocs/
mvn javadoc:aggregate
git add docs/
git commit -m "Release updated javadocs" docs/
mvn release:perform
```

Next time I cut a release, I'll test if it works to put this all in a release script. I just tested it by manually running the commands right now, so let me know if you see any issues

**Comment by benmccann** [comment]
Hmm. It looks like it didn't quite look like I wanted. The version number in the apidocs is `0.23.2-SNAPSHOT`. It might take me a few tries to figure out how to get it to be a non-snapshot version

**Comment by lwhite1** [comment]
OK. This will be great to have.

**Comment by benmccann** [comment]
The [javadoc all exists on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ctablesaw). I'll have to look at how the Maven site plugin and others work. I wonder if we should use the compiled javadoc jars created during the release process

**Comment by benmccann** [comment]
I found a good solution. They're automatically hosted on javadoc.io. All we have to do is cut a release and javadoc.io will automatically grab them from Maven Central. One of the really nice things about this compared to the way we were doing it before is that they let you navigate the javadoc for every release we've ever had

It also keeps the release process really easy. It's just:
```
mvn release:prepare
mvn release:perform
```

**Comment by lwhite1** [comment]
@benmccann This is really awesome, but I'm having some issues running it. It seems that I need to use a git@github.com public key in maven because of the scm config settings in the pom. I've been using my larryBlah@github.com for all my usual work. 

My question is, is it safe for me to create a new git@github.com key and use it? I'm wondering how git feels about supporting two such keys, since you obviously have one with that label.

**Comment by benmccann** [comment]
@lwhite1 I'm not quite sure what you mean by `git@github.com` key or why you think it's necessary. Can you provide more details?

During the release process you do need a key for GPG Maven, but this is separate from the ssh key used by GitHub. See https://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/ for details. You need to generate a key and upload it to a key server if you haven't. The file signing is all setup to happen automatically already

**Comment by lwhite1** [comment]
I thought I had it. My git config was setup to use https instead of ssh, but I'm still getting the same error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project tablesaw-parent: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
[ERROR] git@github.com: Permission denied (publickey).
[ERROR] fatal: Could not read from remote repository.
[ERROR]
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
```
My first thought was that since the pom says: 

```
    <scm>
        <connection>scm:git:git@github.com:jtablesaw/tablesaw.git</connection>
        <developerConnection>scm:git:git@github.com:jtablesaw/tablesaw.git</developerConnection>
        <url>git@github.com:jtablesaw/tablesaw.git</url>
        <tag>v0.23.4</tag>
    </scm>

```
that git is expecting me to have an ssh key with the label: git@github.com (from the developerConnection element), while I have been using one associated with my git username (lwhite1@github.com). 

Anyway, if nothing jumps out, don't sweat it. It's probably a configuration issue on my end. i will keep digging. 

--
@smarks No, we use codacy for integration tests and that's it.

**Comment by benmccann** [comment]
@lwhite1 you can add an SSH public key to your github account (see docs below), which will probably solve that error. It's also really nice outside of the release process because you never have to type in your password when push code to github

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by lwhite1** [comment]
Issue was resolved.  Thanks
