### ISSUE TITLE
Incorrect column data and DateFormatException when using TableSlices

### ISSUE THREAD

**Issue by eflopez** [jtablesaw/tablesaw#313]
Hello! 

I've found a couple of problems when using table slices.

- When obtaining columns by name, the slice returns the column from the underlying table rather than the slices filtered table. Work around is to get the column by index instead.
- When filtering by date, then slicing and trying to do something with the slice I get a date format exception. This only seems to happen when the original table was loaded via the database. Work around is to remove the formatter on the date column after filtering the table, before slicing.

This forces tablesaw to re-evaluate the date formatters on the filtered table.

I've attached a small maven project reproducing the problems.
[tablesaw23bugs.zip](https://github.com/jtablesaw/tablesaw/files/2215814/tablesaw23bugs.zip)

Thanks!

**Comment by lwhite1** [comment]
thanks for the report and the example code. 
The first issue is fixed on master. I'll try to fix the other tomorrow and get it onto maven central if time allows.

**Comment by lwhite1** [comment]
Fixed on master.
Thanks again for the report. So very helpful.
