### ISSUE TITLE
write().csv() closes its writer in all circumstances

### ISSUE THREAD

**Issue by mark27q1** [jtablesaw/tablesaw#316]
If a CsvWriter object is created using CsvWriteOptions.Builder initialised with a file name, I can understand why the CsvWriter closes its writer when finished. However, if CsvWriteOptions.Builder is initialised with an OutputStream, the caller may want to use the stream for something else afterward, so I'd like to suggest that the CsvWriter not automatically close the writer when done in that instance. Flush it, by all means, but don't close it. (Might need in that case to make it possible for the client to extract the writer so it can be closed later, or provide a separate close() method).

The context here is I have a large number of Table objects being generated at unpredictable intervals, and I wish to dump each one in turn to a single file as each becomes available. Merging all the results into one table before dumping is not practical because of the sheer size of the final results, and because it would mean waiting until the very end before I get any results at all to look at. 

I choose to achieve this by having the Table objects dump to standard output, and in the calling shell I redirect standard output to the output file. As things stand only the first table is dumped, as Table.write().csv() opens a writer on the passed-in OutputStream and closes it when done, which closes the System.out PrintStream...

I work around it by instead passing a ByteArrayOutputStream to Table.write().csv() (or more accurately to the CsvWriteOptions.Builder constructor) and then doing System.out.print(stream.toString()) when done. The OutputStream that gets "closed" by Tablesaw is then the ByteArrayOutputStream, which doesn't give a monkey's if someone tries to close it. But it does raise the question of whether Tablesaw should really be closing an OutputStream it did not open...

**Comment by lwhite1** [comment]
> t does raise the question of whether Tablesaw should really be closing an OutputStream it did not open...

No it shouldn't. It may take me a few days to get to this, but it should be fixed

**Comment by lwhite1** [comment]
@benmccann I took a longer look at this code, and was thinking I would make the following changes:

- if we create a stream on an object that isn't a stream (e.g., on a File provided to the options builder, or a File we instantiate from a fileName), we will close that stream when we are done with it.
- if we create a stream on another stream, and that original stream was provided as a parameter in CsvReadOptions, we would not close the stream.

Does this seem correct behavior to you? 

This is the code in question:

```
        // All other read methods end up here, make sure we don't have leading Unicode BOM
        InputStream stream = options.reader() != null
                ? new ByteArrayInputStream(bytes)
                : new FileInputStream(options.file());

        UnicodeBOMInputStream ubis = new UnicodeBOMInputStream(stream);
        ubis.skipBOM();

        CSVParser csvParser = new CSVParserBuilder()
                .withSeparator(options.separator()).build();

        try (CSVReader reader = new CSVReaderBuilder(new 
                      InputStreamReader(ubis)).withCSVParser(csvParser).build()) {
            Table table = Table.create(options.tableName());
...
         }
```
So, in this code, we close the reader automatically via try with resources.  I would change the code so 'reader' is closed only if we create the underlying stream.

**Comment by benmccann** [comment]
Sounds good to me

**Comment by lwhite1** [comment]
fixed
