### ISSUE TITLE
Make jsplots work in JavaFx web viewer

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#318]
@jasrodis has succeeded in getting a JavaFx Web View component to render Plot.ly. 

See https://github.com/jasrodis/javafx-dataviewer

Add a project for a WebView based component that will enable Tablesaw jsplot project to work in a similar fashion.

**Comment by jasrodis** [comment]
Note: JavaFX does not support WebGL. (for plotly.js 3D plots for example)

**Comment by jasrodis** [comment]
@lwhite1 javafx-dataviewer is outdated. 
See https://github.com/jasrodis/javafx-dataviewer-wrapper

**Comment by lwhite1** [comment]
> @lwhite1 javafx-dataviewer is outdated.
See https://github.com/jasrodis/javafx-dataviewer-wrapper

@jasrodis Good to know. Thanks.

**Comment by lwhite1** [comment]
This is not important enough to do
