### ISSUE TITLE
Remove unneeded dependencies in core

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#319]
@benmccann has eliminated a bunch of dependencies by re-organizing the code. This makes Tablesaw more easily used in complex projects. The jar is still pretty big, though.

It may be possible to eliminate a couple more:
- apache commons lang is probably only used for a few string ops
- apache commons math is probably only used for a few statistical ops
Both of those may be replaced by re-implementing the methods we use.

I can never remember what com.google.code.findbugs is used for, but I think it may be necessary. 

I wonder if the dependency on jsoup can be made optional like Ben did with Smile.

**Comment by lwhite1** [comment]
Good point about jsoup.

**Comment by benmccann** [comment]
Hmm, interesting. OpenCSV has 4 dependencies. Univocity has 0. That might be another reason to switch as had been suggested in https://github.com/jtablesaw/tablesaw/issues/284 whether or not we try to remove apache lang

**Comment by lwhite1** [comment]
It could be.  I almost have the column-specific parsing code straightened
out (I made quite a mess of it over the years). When that's done I would
feel better about replacing OpenCSV.

**Comment by lwhite1** [comment]
removed openCSV and and apache lang. I'mma call this done.
