### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#327]
Description	Resource	Path	Location	Type
The value of the field Change.changeLine is not used	Change.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/components	line 5	Java Problem
The value of the field Change.fillColor is not used	Change.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/components	line 6	Java Problem
The value of the field Increasing.changeLine is not used	Increasing.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/components	line 5	Java Problem
The value of the field Increasing.fillColor is not used	Increasing.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/components	line 6	Java Problem
The value of the local variable sum is not used	TableTest.java	/tablesaw-core/src/test/java/tech/tablesaw/api	line 290	Java Problem

Edit: Removed the issues that have been addressed - lw.

**Comment by benmccann** [comment]
Also TableTest.testRollWithNrows2 has no asserts and an unused variable `sum`

**Comment by lwhite1** [comment]
finished these. closed until the next one.
