### ISSUE TITLE
Bug in date inference code

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#354]
The date `9/4/63` is converted to `9/4/2063` when reading the file below instead of `9/4/1963` as I would expect

```
    SIMPLE_UNSORTED_DATA(new String[]{"Name", "IQ", "City", "DOB"},
            new ColumnType[]{ColumnType.STRING, ColumnType.DOUBLE, ColumnType.STRING, ColumnType.LOCAL_DATE}, "../data/unsorted-simple-data.csv"),
```

**Comment by benmccann** [comment]
Nevermind. Looks like a bug just on my branch

**Comment by benmccann** [comment]
Turns out there's already a test that discovered this and was disabled:

```
    @Test(expected = ComparisonFailure.class)
    public void testAscendingWithPlusSignNegative() {
``

**Comment by lwhite1** [comment]
From the docs: “Year: The count of letters determines the minimum field width below which padding is used. If the count of letters is two, then a reduced two digit form is used. … For parsing, this will parse using the base value of 2000, resulting in a year within the range 2000 to 2099 inclusive.
