### ISSUE TITLE
Stick with ints for crosstabs?

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#358]
I had been debating the change in https://github.com/jtablesaw/tablesaw/commit/4d4b5a67ddbbacac5958614c0660d44733c90fec myself. Initially I started to do it, but then I decided ints might be better. I think that cross tabs only counts the number of rows? And I think the underlying columns can only store an integer number of rows? In which case using longs for crosstabs would use extra memory without benefit I think

**Comment by lwhite1** [comment]
reverted
