### ISSUE TITLE
add support for graph operations

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#360]
big enhancement. needs research

**Comment by jbduncan** [comment]
What does "graph" mean in this context? So you mean node-and-edge (mathematical) graphs, or charts, or something else? :)

**Comment by lwhite1** [comment]
mathematical graphs, yes.

**Comment by lwhite1** [comment]
I would probably model the implementation on one or more of those
libraries, so standard things like weighted shortest path, cycle detection
and so on.

I think the implementation will have to wait for someone who is interested
enough to work on it.

**Comment by StephenOTT** [comment]
+1 on this.  Would love to see this added.

**Comment by lwhite1** [comment]
It won't happen very soon, but it is something I would like to do this year. After:
- Documentation cleanup
- Test cleanup (and more tests)
- Join issues (#383 and #381)

**Comment by lwhite1** [comment]
closing
