### ISSUE TITLE
add support for formatted output in CSV write options

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#362]
Should use the PrintFormatters some/most columns support

Since this often includes commas for numeric data, quotes or escaping are needed.

**Comment by gregorco** [comment]
Just ran into this need.  I had set the PrintFormatter for my DateColumn, but when the CsvWriter wrote the csv file, it ignored the PrintFormatter and used the default yyyy-MM-dd format.  I'll take a stab at implementing it.

**Comment by lwhite1** [comment]
this is fixed now
