### ISSUE TITLE
add support for joining on multiple columns. 

### ISSUE THREAD

**Issue by gregorco** [jtablesaw/tablesaw#367]
Hello,

I've been leveraging the features of tablesaw recently as I've been converting some python DataFrame code to java. I have need for performing an inner join on multiple columns, and as I understand it that feature is not yet supported.  I've been studying and preparing an implementation upon Larry's suggestion a little while ago when I first asked about it.  Is anyone else already working on this?  Should I go forward with a pull request?  Anything in particular I should be aware of before continuing?  This would be my first contribution on GitHub, so I'm reviewing the recommended documentation on submitting a proper pull request. 

Gregor

**Comment by gregorco** [comment]
Been trying to figure out how to label this as a Question.  Documentation says to look for a checkbox next to the issue, then check it, then choose a label for it.  I haven't been able to detect the checkbox.  What am I missing?

**Comment by benmccann** [comment]
Only project maintainers can add labels. Where is the documentation you're referring to?

I don't believe anyone is working on multi-column joins

**Comment by gregorco** [comment]
I’ll have to find the exact page, but it appeared to be from a github page on standard procedure.  Maybe it forgot to say that it required a certain user role to do so.

So no objections to submitting a pull request then?

Gregor

**Comment by lwhite1** [comment]
No objections

**Comment by gregorco** [comment]
While running junit tests for my implementation I found that the join on multiple tables did not appear to work.  This inner method: 

`    public Table inner(boolean allowDuplicateColumnNames, Table... tables) {
        Table joined = table;
        for (Table table2 : tables) {
       		joined = inner(table2, columnNames, allowDuplicateColumnNames);
        }
        return joined;
    }
`

appears to not include the "joined" result into the next call of inner() such that the final version of the "joined" variable only holds the result of the last table joined.  I didn't see a junit test to verify the behavior.  Do you agree that this behavior is incorrect?  If so, should I create a separate pull-request to submit a proposed fix?  Or should I include my proposed fix along with my proposed multi-column join change/update?

**Comment by lwhite1** [comment]
@gregorco When you say join on multiple columns, I assume you're doing something similar to this SQL operation:

SELECT * 
FROM table_a a
JOIN table_b b
ON a.userid = b.userid AND a.listid = b.listid;

Is that correct?

**Comment by gregorco** [comment]
Correct.

**Comment by benmccann** [comment]
I think that the current method interface only lets you do something like the below:

```
SELECT *
FROM table_a a
JOIN table_b b, table_c c
ON a.userid = b.userid AND a.userid = c.userid;
```

But yes, from your description of it, it sounds like it's not working as intended, so a fix would be welcomed

**Comment by gregorco** [comment]
Sounds good.  Would it be recommended to create separate pull-requests?  One to fix the inner() method that is not successfully joining on multiple tables; and another pull-request to implement the multiple column join feature?

**Comment by lwhite1** [comment]
that sounds like a good approach

**Comment by gregorco** [comment]
@lwhite1, @benmccann - I submitted the pull request for the multiple table join issue.  It might not be the simplest, most elegant solution, but it appears to work so far.  I saw that Codacy flagged some coding standards violations which I then corrected and recommitted.  How does it look?

**Comment by lwhite1** [comment]
Thank you @gregorco.  Much appreciated!

This can be closed now, right?

**Comment by gregorco** [comment]
Yes.  Sorry for the delay.  Thanks.
