### ISSUE TITLE
why "NumberColumn" does not have create function? 

### ISSUE THREAD

**Issue by shen00001** [jtablesaw/tablesaw#368]
![image](https://user-images.githubusercontent.com/9640834/44646704-65dc4a80-aa0e-11e8-8e06-6ed4c0c52d45.png)

**Comment by lwhite1** [comment]
if you are working off master,  I would recommend that you use the latest version from maven central instead.
On master, NumberColumn is abstract. It may stay that way, but there are a number of changes still being considered before it's released.

**Comment by lwhite1** [comment]
Sorry, I hadn't realized those changes were published.

**Comment by shen00001** [comment]
Ok,Thanks for you answers.  Um....., Could you please tell me  what's the latest version?  And how long  you can fix it?

**Comment by lwhite1** [comment]
0.25.2 is the latest release. Using DoubleColumn is correct so you're doing
fine. I don't recall now whether NumberColumn is abstract or an interface,
but it isn't meant to be instantiated. I misunderstood the issue earlier.

The next version is probably about a week away.  I'm not yet sure how the
API will change, but you should be fine going with DoubleColumn.
