### ISSUE TITLE
Is there a easy method  can convert "list<bean>" to a dataframe?

### ISSUE THREAD

**Issue by Jungle666** [jtablesaw/tablesaw#369]
It's difficult to convert long field list<bean> to dataframe, I believe there is a easy way.

**Comment by lwhite1** [comment]
Longer answer tomorrow but there’s a package under io for sql using jdbc
result sets

**Comment by benmccann** [comment]
I had been thinking this might be a nice feature

The way I would implement this would be to use a library like Jackson to serialize the bean to json and then use something like [json-flattener](https://github.com/wnameless/json-flattener) to flatten the json. You could then iterate over the json properties and read it into a Table

If you knew that the bean had no nested properties then you could [convert the list to csv](https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv) and then use Tablesaw's built-in csv reader. This solution wouldn't work in the general case, but might be easier for you to implement if you knew that you wouldn't have to deal with nested properties

**Comment by lwhite1** [comment]
I'm not sure I would get into the beans / objects to json business. That
seems like something client code could do easily, and perhaps better.

Reading from JSON seems useful, and the flattener seems like a good
approach to generalizing it. It would check a box on IO support that we
haven't yet checked. It would also make it easy to use tablesaw with the
results of a REST call.

OTOH, I don't think anyone has ever asked for JSON IO support. (Even this
request isn't for that specifically.)

Jackson is more powerful than GSON, I think, but I've always preferred GSON
when it was up to the task at hand.

**Comment by lwhite1** [comment]
Here's an example reading the results of a SQL query into a table:

```
    private Table loadTableFromDB() throws SQLException {

        Connection connection = DriverManager.getConnection("jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1");

        ResultSet resultSet = connection.createStatement().executeQuery("SELECT * FROM country_sales");

        return Table.read().db(resultSet, "sales_from_db");
    }

```

**Comment by Jungle666** [comment]
Thanks for you advice , This could be a solution.

**Comment by lwhite1** [comment]
closing this as answered with the SQL solution. Created a new issue #374 for adding a JSON input capability
