### ISSUE TITLE
IntColumn and others are missing from latest release

### ISSUE THREAD

**Issue by robertperrotta** [jtablesaw/tablesaw#370]
I used gradle to add tablesaw's latest release to my project.

```
compile group: 'tech.tablesaw', name: 'tablesaw-core', version: '0.25.2'
```

I can see and use DoubleColumn (for example) but not IntColumn. Other's are missing, too. I looked a the source code attached to the release and the same files are missing from the zip and tar files as from the gradle resources. For example, the `api` folder contains the following files.

```
BooleanColumn.java     DateColumn.java        NumberColumn.java      Table.java
CategoricalColumn.java DateTimeColumn.java    Row.java               TimeColumn.java
ColumnType.java        DoubleColumn.java      StringColumn.java
```

Is this intentional? Are those features not yet released?

**Comment by lwhite1** [comment]
Those classes are not in 0.25.2. There is only one concrete numeric class in that version: DoubleColumn.

We've done a great deal of re-work over the past 6 months or so to stabilize and standardize the API, and simplified the column types as part of that effort. This should be coming to an end soon. There will be more numeric column types in the next release. The main advantage of other numeric types, though, is for better memory management, so unless you're tables are really big, it shouldn't affect you much.

Or so we hope.

**Comment by robertperrotta** [comment]
Okay, thanks for your response. I was worried I was just doing something wrong. Or that I was going crazy!
