### ISSUE TITLE
Is there a easy function can add two colunms ‘s value to new colunm.

### ISSUE THREAD

**Issue by Jungle666** [jtablesaw/tablesaw#372]
In python ,we can do this:
df["new"] = df["a"] + df["b"]
Is there a method help me to do this?

**Comment by lwhite1** [comment]
yes.
it's a map function defined on number columns
x.addColumns(x.doubleColumn("a").add(x.doubleColumn("b"));

i think this should do it but i haven't checked the syntax. If you're using
an IDE like Idea or eclipse, you should be able to see all the methods
defined on any object. In this case, the add() method on DoubleColumn
computes the sum and the the addColumns() method on tables is used to add
the resulting column to the original table,

**Comment by Jungle666** [comment]
Nice solution!
This help me a lot.
