### ISSUE TITLE
How to join two tables by key(or colunm)？

### ISSUE THREAD

**Issue by Jungle666** [jtablesaw/tablesaw#373]
in pandas：
T3 = T1.join(T2)by same index name.
for example:
T1.colunm：{“a”，"b"，"c"}
T2.colunm：{“a”,"d","f"}
after join
T3.colunm : {"a","b","c","d","f"}
This is like sql:
select * from T1,T2 where T1.a =T2.a

**Comment by Jungle666** [comment]
![image](https://user-images.githubusercontent.com/9640834/44854637-a997b400-ac9b-11e8-8d4c-423684169f51.png)
I Saw this in your doc，Do you have some example？

**Comment by lwhite1** [comment]
Look at the Tests in DataFrameJoinerTest. They show numerous variations.
The inner join example does the equivalent of your example.
