### ISSUE TITLE
DataFrameWriter.csv does not copy the specified separator

### ISSUE THREAD

**Issue by KarlAnderssonBremen** [jtablesaw/tablesaw#375]
When exporting to CSV, even if I specify ';' as separator, I get the default ','.

Method
tech.tablesaw.io.DataFrameWriter.csv(CsvWriteOptions)
does not transfer the option "separator" to the 
com.univocity.parsers.csv.CsvWriterSettings.CsvWriterSettings() (Format)

**Comment by KarlAnderssonBremen** [comment]
Great, thanks for the quick reaction!

**Comment by lwhite1** [comment]
fixed one remaining case and test written.
