### ISSUE TITLE
SQL type NUMBER(5,0) interpreted as both Double and BigDecimal

### ISSUE THREAD

**Issue by gregorco** [jtablesaw/tablesaw#378]
Within the past 2-3 weeks there appears to have been a change that is causing a failed conversion.  I had been successfully populating a Table with a java.sql.ResultSet  where a column in the result set was defined in Oracle as a NUMBER(5,0), and now as I'm stepping through the tablesaw code I see that at one point the ResultSet metadata causes tablesaw to create a DoubleColumn for that particular column, but then shortly afterward it tries to populate that column with a BigDecimal.   The SqlResultSetReader.read(Resultset resultSet, String tableName) first loops on the metaData and for each column calls:

`ColumnType type = SQL_TYPE_TO_TABLESAW_TYPE.get(metaData.getColumnType(i));`

and then loops on the resultSet and calls:

`column.appendObj(resultSet.getObject(i));`

to populate the column.  In this second loop the appendObj throws an exception because the DoubleColumn type is unable to appendObj(BigDecimal).  

I'm looking at the history of the changes in the past two weeks to see what could be the culprit but wanted to see if you have any idea.   I recognize that the table I'm importing would be simpler to import if the column was typed as a simple INTEGER, or SMALLINT, but it is defined as NUMBER(5,0) which I cannot change.

**Comment by gregorco** [comment]
Think I see what changed.  The version that I had been running against when the table was successfully imported had been calling `DoubleColumn.appendCell()` and was taking as input a String, and using a `StringParser` to `parseDouble()`, and since then changes for stricter typing have been implemented such that the `DoubleColumn.appendObj()` is now being called with a `BigDecimal` instead of a String, and failing to accept it as a double.   

I'll be looking for a workaround solution but if you have any suggestions please let me know.

**Comment by lwhite1** [comment]
It should not be using bigDecimal.  Feel free to fix

**Comment by gregorco** [comment]
The BigDecimal is being returned from the ResultSet.getObject() which appears to agree with the JDBC specs, so it looks like a subsequent step might need to be added to convert that BigDecimal to a Double before passing it to DoubleColumn.appendObj?  Or the appendObj() could convert it itself?

Gregor

**Comment by gregorco** [comment]
@lwhite1 @benmccann I've been using git for just under a year but am not yet sure what the best option is for submitting a pull request for this issue.   I created one fork to work on my first pull request, which was accepted a few days ago, then yesterday submitted a second pull request #377 that is not yet completed/accepted.  My master branch therefore is not yet "free" to submit a third pull request for the changes to the source code for this Issue #378.  This Issue #378 is completely separate from the changes in PullRequest #377 so it could be submitted separately before or after the #377 change.  Would making a new fork be the only way I could get a clean master to use while my current fork's master is not yet accepted into the upstream master?

**Comment by gregorco** [comment]
Thank you.   Good information.   I'll do that - wait until the current PR is completed and then make changes on new branches moving forward.

**Comment by lwhite1** [comment]
@gregorco I'm happy to take this one.  Thanks for all your help here and elsewhere

**Comment by lwhite1** [comment]
fixed.
