### ISSUE TITLE
com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 512

### ISSUE THREAD

**Issue by deviant-studio** [jtablesaw/tablesaw#379]
I have exception when trying to parse my csv with TableSaw. The file is valid since i able to parse it with Univocity:
```
val settings = CsvParserSettings()
settings.format.setLineSeparator("\n")
val parser = CsvParser(settings)
parser.iterate(csvFile)
    .forEachIndexed { i, it -> /* ... */   }
```

My question is: how to use `CsvParserSettings()` with TableSaw? Is it possible?

**Comment by deviant-studio** [comment]
Looks like `CsvReadOptions` has `lineEnding` field. But there is no way to set it with the Builder.
I've tried to fill the field via reflection and the exception is gone.
So, could you please add `lineEnding(...)` method to the `CsvReadOptions.Builder`?

**Comment by lwhite1** [comment]
yes

**Comment by lwhite1** [comment]
fixed
