### ISSUE TITLE
Join prevented on some column types

### ISSUE THREAD

**Issue by gregorco** [jtablesaw/tablesaw#380]
@benmccann My app used to be able to join on a DoubleColumn, but now as I'm integrating recent changes into it, I'm seeing a failure that the DoubleColumn I'm trying to join on can't be cast to a CategoricalColumn. I know I had the join working in the past. At what point was that ability changed/restricted? Is there any workaround to allow a join on a DoubleColumn?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gregorco** [comment]
I had started this question in PullRequest#377 when I should have started it in a new Issue.  
@lwhite1 replied with:
"""
it changed in master, i think.

(btw, I think this should be in a separate issue because it has nothing to
do with joining on multiple columns)

There was a concern that joining on double was a bit dangerous due to
rounding issues. We added joining on doubles when we didn't have any other
numeric column types. Usually people want to join on an int column.

Do you need to join on double or can your data be stored in an int column
before joining?

i'm not sure we should really prevent people from trying to join on double.
I'm also a bit uncertain that we should prevent people from joining on
booleans, because if they blow up their app it's on them. Perhaps we should
allow joining on any column type. Fewer special cases are better.
"""

**Comment by gregorco** [comment]
I need to join on temperature values which are double, but only to 2 decimal places.  I don't doubt that there might be some concerns about performance regarding joining on some column types, but I agree that with a warning to the user the user could take the risk.  If possible, I might need to convert my Double column to an Integer, join, and then convert back to a Double, but that would not be my ideal solution.

**Comment by gregorco** [comment]
I'm guessing now that when my app used to successfully join on a column having double values, that the version I was using did not yet have the new DoubleColumn type integrated, and that that old version was relying on NumberColumn type?  Just wanted to clarify my first post where I inaccurately stated that the DoubleColumn used to join just fine - I'm questioning now whether at that time it was actually a NumberColumn instead of a DoubleColumn.   

I experienced this failure last night as I was testing my changes to Issue#378.  For Issue#376 I'm having the SqlResultSetReader take a closer look at the metadata to more accurately choose the closest java numeric type to use when defining the column.  I had gotten the junit test to show my changes were behaving as expected, and then wanted to verify that the changes would hold up in my own app.  I had to update my own app which wasn't yet updated for the stricter column type changes, and found that the double column I have was no longer accepted as a join column.

**Comment by gregorco** [comment]
Would updating the DoubleColumn class declaration to implement CategoricalColumn<Double> be the main change I'd need to make to try to have it accepted as a join column?  Don't yet know how many other changes would be needed.  Just curious to see if I could get my app back to working order with a customized version if need be.

**Comment by benmccann** [comment]
I think that when joining on a double we would want to support some notion of precision when checking for equality (similar to junit asserts for example)

**Comment by gregorco** [comment]
Comparing floats/doubles is certainly reason to be cautious.  In my case my double values have 1 decimal precision and I didn’t see any failures or issues.  

Still testing my experiment of simply declaring DoubleColumn to implement CategoricalColumn - made it through to end of app without exceptions but not sure if the join results are correct yet. 

Gregor

**Comment by benmccann** [comment]
It might be preferable to data DataFrameJoiner work on Column rather than making DoubleColumn implement CategoricalColumn

**Comment by gregorco** [comment]
You mean change the type of the DataFrameJoiner's `columns` field from:
`private CategoricalColumn<?>[] columns;`

to

`private Column<?>[] columns;` ?

**Comment by lwhite1** [comment]
yes, i think that's what @benmccann is suggesting. It moves us towards a
general solution.

**Comment by gregorco** [comment]
Got it.  I'll give it a try.  Thanks.

**Comment by gregorco** [comment]
Correction - the column that I thought was a double type that I was successfully joining on, was in fact not double, but integer.  I had confused the type when working with the older version of tablesaw that didn't yet have the stricter column type implementation.

That said - I just experimented by *only* replacing any and all references to CategoricalColumn (in DataFrameJoiner.java) with the more general Column type, and everything still compiled and all 68 junit tests passed.  The junit tests don't try to join on a float or double, but do try to join on boolean and get the expected exception when the BooleanColumn type is not supported.  

Is it worth opening a PR to replace all references to CategoricalColumn type (in DataFrameJoiner.java) with Column type?  Or should that change wait until it accompanies deeper changes for implementing  joining on all types?

**Comment by lwhite1** [comment]
@gregorco Is it the case now that Float, Double and Boolean don't work, and all the other column types do?

**Comment by gregorco** [comment]
From what I can tell, yes, trying to join on Float, Double, or Boolean fail, but the integral, string, and date/time types work.  

Gregor

**Comment by lwhite1** [comment]
ok. I'm going to push a partial fix for this today that handles those, with
luck.

Text columns also don't work, but i haven't looked into them.

**Comment by lwhite1** [comment]
All column types now support joins. Use real number and boolean joins at your own risk.
