### ISSUE TITLE
[Question] Cannot change default colors 

### ISSUE THREAD

**Issue by lucas-avila** [jtablesaw/tablesaw#382]
Hi, I am trying to change the default colors but I can't figure it out by myself.
According to what the documentation says in the code: 

> * Sets the colorscale and only has an effect if `marker.color` is set to a numerical array.
         * The colorscale must be an array containing arrays mapping a normalized value to an rgb, rgba, hex, hsl, hsv,
         * or named color string.

But marker.color is a String[], shouldn't it be a Double[] or something similar? 
I've tried to set:
`Marker.builder.colorScale(Marker.Palette.VIRIDIS).color(Array("0", "1", ..etc))`

But it doesn't work. What am I doing wrong? Is there any example I can refer to?
Thank you in advance

**Comment by lwhite1** [comment]
The implementation here is incomplete, so that it currently only supports strings, i.e. "#4286f4". 
I will look into supporting your use case when i can find the time. I have another change to make first.

**Comment by lwhite1** [comment]
Any chance this was fixed in #444? 
Need to revisit

**Comment by lwhite1** [comment]
fixed, finally. Sorry it took so long
