### ISSUE TITLE
Joins are too slow

### ISSUE THREAD

**Issue by deviant-studio** [jtablesaw/tablesaw#383]
Hi guys!
I'm trying to migrate from `python`+`pandas` to `kotlin`+`tablesaw`.
Some parts of my code are already working fast (like csv parsing, x2 times faster than in pandas)
But also i've noticed that `inner join` operation is pretty slow (~ 2 times slower than in pandas)

Then i tried to optimize my code and use `isIn` Selection instead of simple join. Unfortunately it uses `strings.toArray(new String[0])` under the hood for input parameter collection. It would be more sense to use HashSet to quicker lookup. So i wrote my own predicate:
```kotlin
val customersSet = customers.toHashSet()    // for faster lookup
val idColumn = transactions.stringColumn("customer_id")
idColumn.eval { it in customersSet }
```
Which is x15 times faster than original inner join. At least on my huge dataset. Of course this is much simpler than `join` operation since i haven't appended columns etc. But still the difference is huge.
I didn't investigate joins code yet, but i hope there is space for improvements there.
My key point is: kotlin+jvm should be at least not slower than python+pandas
What do you guys think?

ps: do you use hash indexing on table columns?

**Comment by lwhite1** [comment]
> Hi guys!
I'm trying to migrate from python+pandas to kotlin+tablesaw.
Some parts of my code are already working fast (like csv parsing, x2 times faster than in pandas)
But also i've noticed that inner join operation is pretty slow (~ 2 times slower than in pandas)

> Then i tried to optimize my code and use isIn Selection instead of simple join. Unfortunately it uses strings.toArray(new String[0]) under the hood for input parameter collection. It would be more sense to use HashSet to quicker lookup. So i wrote my own predicate:

Good point. This is a quick fix. I will open a separate bug for this. 

> 
> val customersSet = customers.toHashSet()    // for faster lookup
> val idColumn = transactions.stringColumn("customer_id")
> idColumn.eval { it in customersSet }
> Which is x15 times faster than original inner join. At least on my huge dataset. Of course this is much simpler than join operation since i haven't appended columns etc. But still the difference is huge.

The join logic is quite simple. I'm sure there are opportunities for improvement. We need to profile it first to see where the time is going. Most likely it is in table copying, but it could be elsewhere. 

> I didn't investigate joins code yet, but i hope there is space for improvements there.
> My key point is: kotlin+jvm should be at least not slower than python+pandas

Agreed. It always makes me sad to see something like this. 
OTOH. They have a lot more people helping :) 

> What do you guys think?
> 
> ps: do you use hash indexing on table columns?

The String index uses a Map<String, IntArrayList>, where the intArrayList contains the indexes. As with join, the logic here could be more sophisticated, but my guess again is that the time spent in joining is mostly spent elsewhere. 

Do you have plenty of memory relative to the size of your table? GC can cause slowness if it's running a lot. 

If you would like to take a shot at optimizing joins we would love a PR.

**Comment by deviant-studio** [comment]
Thanks for detailed answer!
I'll try to play with jvm memory settings. Also i'm going to dive into the implementation details when i have more free time.

**Comment by ddl19901201** [comment]
> > Hi guys!
> > I'm trying to migrate from python+pandas to kotlin+tablesaw.
> > Some parts of my code are already working fast (like csv parsing, x2 times faster than in pandas)
> > But also i've noticed that inner join operation is pretty slow (~ 2 times slower than in pandas)
> 
> > Then i tried to optimize my code and use isIn Selection instead of simple join. Unfortunately it uses strings.toArray(new String[0]) under the hood for input parameter collection. It would be more sense to use HashSet to quicker lookup. So i wrote my own predicate:
> 
> Good point. This is a quick fix. I will open a separate bug for this.
> 
> > val customersSet = customers.toHashSet()    // for faster lookup
> > val idColumn = transactions.stringColumn("customer_id")
> > idColumn.eval { it in customersSet }
> > Which is x15 times faster than original inner join. At least on my huge dataset. Of course this is much simpler than join operation since i haven't appended columns etc. But still the difference is huge.
> 
> The join logic is quite simple. I'm sure there are opportunities for improvement. We need to profile it first to see where the time is going. Most likely it is in table copying, but it could be elsewhere.
> 
> > I didn't investigate joins code yet, but i hope there is space for improvements there.
> > My key point is: kotlin+jvm should be at least not slower than python+pandas
> 
> Agreed. It always makes me sad to see something like this.
> OTOH. They have a lot more people helping :)
> 
> > What do you guys think?
> > ps: do you use hash indexing on table columns?
> 
> The String index uses a Map<String, IntArrayList>, where the intArrayList contains the indexes. As with join, the logic here could be more sophisticated, but my guess again is that the time spent in joining is mostly spent elsewhere.
> 
> Do you have plenty of memory relative to the size of your table? GC can cause slowness if it's running a lot.
> 
> If you would like to take a shot at optimizing joins we would love a PR.

Now,data of 53*3021's  inner join takes 2s, i think it's too slow ,is there anyhing to make it fast??

**Comment by lwhite1** [comment]
I Don’t suppose you can provide the actual data?  If not can you at least
print

Table.shape();

And
Table.structure();

And share those?

Also provide the code for the join so I can see what columns you’re joining
on

**Comment by ddl19901201** [comment]
> I Don’t suppose you can provide the actual data? If not can you at least print Table.shape(); And Table.structure(); And share those? Also provide the code for the join so I can see what columns you’re joining on
> […](#)
Here is the code,I use the column of "VC_STOCK_NO" to make inner join,
and gStockinfo.rowCount()=53
gPflstockstrial.rowCount()=3021, this takes almost 2s.

Table joined =(gPflstockstrial.join("VC_STOCK_NO").inner( gStockinfo));

Here is the log:
join:
2019-01-16-08:37:28:505
2019-01-16-08:37:30:131

**Comment by ddl19901201** [comment]
gPflstockstrial:
3021 rows X 83 cols
             Structure of t_pflstock              
 Index  |      Column Name       |  Column Type  |
--------------------------------------------------
     0  |                L_DATE  |      INTEGER  |
     1  |              L_GZDATE  |      INTEGER  |
     2  |      C_PORTFOLIO_TYPE  |       STRING  |
     3  |        L_PORTFOLIO_NO  |         LONG  |
     4  |         C_INVEST_TYPE  |       STRING  |
     5  |           VC_STOCK_NO  |       STRING  |
     6  |           EN_QUANTITY  |        FLOAT  |
     7  |             EN_AMOUNT  |        FLOAT  |
     8  |               EN_COST  |        FLOAT  |
     9  |              EN_PRICE  |        FLOAT  |
   ...  |                   ...  |          ...  |
    74  |          VC_FUND_CODE  |       STRING  |
    75  |         EN_HOLD_YIELD  |       DOUBLE  |
    76  |       VC_TRADE_MEMBER  |       STRING  |
    77  |  L_POSITION_DIRECTION  |        SHORT  |
    78  |   EN_TRAN_QUANTITY_IN  |        FLOAT  |
    79  |    EN_TRAN_BALANCE_IN  |        FLOAT  |
    80  |  EN_TRAN_QUANTITY_OUT  |        FLOAT  |
    81  |   EN_TRAN_BALANCE_OUT  |        FLOAT  |
    82  |        EN_BEGIN_YIELD  |       DOUBLE  |
gStockinfo:
53 rows X 14 cols
          Structure of t_stockinfo           
 Index  |    Column Name    |  Column Type  |
---------------------------------------------
     0  |      VC_STOCK_NO  |       STRING  |
     1  |      L_MARKET_NO  |        SHORT  |
     2  |    VC_STOCK_CODE  |       STRING  |
     3  |    VC_STOCK_NAME  |       STRING  |
     4  |     VC_FULL_NAME  |       STRING  |
     5  |      VC_SRC_CODE  |       STRING  |
     6  |     C_STOCK_TYPE  |       STRING  |
     7  |         C_LISTED  |       STRING  |
     8  |    L_LISTED_DATE  |      INTEGER  |
     9  |    C_STOCK_CLASS  |       STRING  |
    10  |   VC_CUSTOM_TYPE  |       STRING  |
    11  |   VC_ISSUER_CODE  |       STRING  |
    12  |  VC_CONVERT_CODE  |       STRING  |
    13  |     L_ISSUE_TYPE  |        SHORT  |

> > I Don’t suppose you can provide the actual data? If not can you at least print Table.shape(); And Table.structure(); And share those? Also provide the code for the join so I can see what columns you’re joining on
> > […](#)
> > Here is the code,I use the column of "VC_STOCK_NO" to make inner join,
> > and gStockinfo.rowCount()=53
> > gPflstockstrial.rowCount()=3021, this takes almost 2s.
> 
> Table joined =(gPflstockstrial.join("VC_STOCK_NO").inner( gStockinfo));
> 
> Here is the log:
> join:
> 2019-01-16-08:37:28:505
> 2019-01-16-08:37:30:131

gPflstockstrial:
3021 rows X 83 cols
             Structure of t_pflstock              
 Index  |      Column Name       |  Column Type  |
--------------------------------------------------
     0  |                L_DATE  |      INTEGER  |
     1  |              L_GZDATE  |      INTEGER  |
     2  |      C_PORTFOLIO_TYPE  |       STRING  |
     3  |        L_PORTFOLIO_NO  |         LONG  |
     4  |         C_INVEST_TYPE  |       STRING  |
     5  |           VC_STOCK_NO  |       STRING  |
     6  |           EN_QUANTITY  |        FLOAT  |
     7  |             EN_AMOUNT  |        FLOAT  |
     8  |               EN_COST  |        FLOAT  |
     9  |              EN_PRICE  |        FLOAT  |
   ...  |                   ...  |          ...  |
    74  |          VC_FUND_CODE  |       STRING  |
    75  |         EN_HOLD_YIELD  |       DOUBLE  |
    76  |       VC_TRADE_MEMBER  |       STRING  |
    77  |  L_POSITION_DIRECTION  |        SHORT  |
    78  |   EN_TRAN_QUANTITY_IN  |        FLOAT  |
    79  |    EN_TRAN_BALANCE_IN  |        FLOAT  |
    80  |  EN_TRAN_QUANTITY_OUT  |        FLOAT  |
    81  |   EN_TRAN_BALANCE_OUT  |        FLOAT  |
    82  |        EN_BEGIN_YIELD  |       DOUBLE  |
gStockinfo:
53 rows X 14 cols
          Structure of t_stockinfo           
 Index  |    Column Name    |  Column Type  |
---------------------------------------------
     0  |      VC_STOCK_NO  |       STRING  |
     1  |      L_MARKET_NO  |        SHORT  |
     2  |    VC_STOCK_CODE  |       STRING  |
     3  |    VC_STOCK_NAME  |       STRING  |
     4  |     VC_FULL_NAME  |       STRING  |
     5  |      VC_SRC_CODE  |       STRING  |
     6  |     C_STOCK_TYPE  |       STRING  |
     7  |         C_LISTED  |       STRING  |
     8  |    L_LISTED_DATE  |      INTEGER  |
     9  |    C_STOCK_CLASS  |       STRING  |
    10  |   VC_CUSTOM_TYPE  |       STRING  |
    11  |   VC_ISSUER_CODE  |       STRING  |
    12  |  VC_CONVERT_CODE  |       STRING  |
    13  |     L_ISSUE_TYPE  |        SHORT  |

**Comment by lwhite1** [comment]
You have four tables listed, but it looks like that's a copy paste error. I'm assuming there are two. 

I will try to look at performance over the weekend.  It's probably not a quick fix in any case.  How fast does it need to be?

Most of the time probably goes to data copying since you have a total of 96 columns. If you can reduce the width of the table(s) by eliminating columns not needed downstream you may save time.

My second suggestion would be to try doing the join manually:
- start with the biggest table
- sort on the join column(s)
- add the extra columns
- step through the larger file and update the extra columns using the column specific set operations 

there are other optimizations you could make but that's the general idea. 

If that's not possible, you may find that joining in a database is the best short term solution.

**Comment by ddl19901201** [comment]
> You have four tables listed, but it looks like that's a copy paste error. I'm assuming there are two.
> 
> I will try to look at performance over the weekend. It's probably not a quick fix in any case. How fast does it need to be?
> 
> Most of the time probably goes to data copying since you have a total of 96 columns. If you can reduce the width of the table(s) by eliminating columns not needed downstream you may save time.
> 
> My second suggestion would be to try doing the join manually:
> 
> * start with the biggest table
> * sort on the join column(s)
> * add the extra columns
> * step through the larger file and update the extra columns using the column specific set operations
> 
> there are other optimizations you could make but that's the general idea.
> 
> If that's not possible, you may find that joining in a database is the best short term solution.

Thanks a lot,i will try.

**Comment by lwhite1** [comment]
@ddl19901201 Try reversing the join order so the smaller table comes first. E.G., this: 

```
Table joined =(gStockinfo.join("VC_STOCK_NO").inner(gPflstockstrial));
```
instead of
```
Table joined =(gPflstockstrial.join("VC_STOCK_NO").inner( gStockinfo));
```
In tests I see about a 6x performance boost when joining tables that look like this:

table 1: 59826 rows X 11 cols
table 2: 51 rows X 2 cols

Your results will be different, I'm sure, and probably not as dramatic, but it's easy and may help. 

I can change the code to do this automatically and re-order the columns at the end of the join routine. I think the reordering will be quick. 

Thanks.

**Comment by benmccann** [comment]
Nice find Larry!

> I can change the code to do this automatically and re-order the columns at the end of the join routine. I think the reordering will be quick.

That would be a great enhancement :-)

**Comment by lwhite1** [comment]
Note to self. Next attempt should be to run the logic for renaming and removing columns twice, once to do the work as is done today, and once, up-front, to build a data structure containing all information necessary to rename and reorder the columns as needed after the join is complete.

**Comment by ryancerf** [comment]
I would like to work on improving join performance.

I ran some performance tests with the following schema:
- A customers table with 1,000 rows. (PK customerId)
- An orders table with 1,000,000 rows. customerId is a FK that is uniformly distributed among the 1,000 customers.

I found one big culprit (especially when the large table is on the left side of the join) 

```java
Table table2Rows = table2.where(rowBitMapMultiCol);
```

Under the covers table2.where is copying all the columns in the table. This can get very slow with large numbers of columns. All the columns are then copied for a second time while calculating the cross product.

In one test where the orders table (large table) was on the left side of the join and the customers table had six columns the join took about ~10 seconds to complete of which ~8 seconds was taken up by `Table table2Rows = table2.where(rowBitMapMultiCol);`.

I am going to work on a PR that will.
- Speed up joins in the worst case.
- Make the join speed less sensitive to which table is first (I was seeing differences of 20x)
- Reduce unnecessary copying of columns.
- Change the join algorithm rather than fiddling with the renaming and reorder column logic.

@lwhite1 Let me know if you have any thoughts.  Also let me know if want me to submit my performance tests.

**Comment by lwhite1** [comment]
yes, please!
@benmccann did the original join work so maybe he would like to add
something more substantial.

**Comment by benmccann** [comment]
Sounds good to me. I didn't spend any time profiling and was just trying to get a naive implementation done. Glad to see people are using it! Thanks for digging into this!

**Comment by ryancerf** [comment]
A left join with a schema similar to the one laid out above by @deviant-studio ddl19901201 now runs in about 300ms with PR #562
