### ISSUE TITLE
Table.read().csv(...) broken starting ver 0.25.1?

### ISSUE THREAD

**Issue by smpawlowski** [jtablesaw/tablesaw#386]
Hi,

I started having problems with csv parsing starting with version 0.25.1. The simple test below passes with 0.25.0, but not with 0.25.1 or later:

	@Test
	public void testCsvParsing() throws IOException {
		String csvStr = "A,B,C\n"+
		                "1.,2.,3.\n"+
		                "4.,5.,6.\n";
		InputStream stream = new ByteArrayInputStream(csvStr.getBytes(StandardCharsets.UTF_8));
		CsvReadOptions csvReadOptions = CsvReadOptions.builder(stream,"TABLE1")
		                                              .header(true)
		                                              .build();
		Table t = Table.read().csv(csvReadOptions);
		System.out.println(t.printAll());
		Assert.assertEquals(3, t.columnNames().size());
		Assert.assertTrue(Math.abs(2.-t.doubleColumn("B").get(0))<1.0E-16 );
	}

I noticed CsvReadOptions.Builder doesn't support setting lineEnding and the default is null.

Was this possibly already fixed in #379 and just didn't make it to a release yet?

Could you advise?

Best regards
Slawomir

**Comment by lwhite1** [comment]
Line endings are fixed on master. Are you on Windows? That's where we were having issues.

**Comment by lwhite1** [comment]
ok. Handling for many files on windows was broken when we switched to the
Univocity parser, which is much faster than Open CSV, but less forgiving.
The ability to change line endings is on master, and there was another
commit to use file-system-specific endings, but honestly i'm not sure if
that's for reads.

If you find your problem persists please lmk and I'll investigate further.

Sorry for the inconvenience.

**Comment by lwhite1** [comment]
I'm going to close this for now. We can re-open if the issue occurs with the next release.
