### ISSUE TITLE
Precision of number types imported from query ResultSet

### ISSUE THREAD

**Issue by gregorco** [jtablesaw/tablesaw#388]
@lwhite1  In my work, all the numeric columns defined in our database (Oracle) are defined with the general NUMBER(precision,scale) type, rather than using any of the convenient pre-defined number types like INTEGER.  This being the case, when I populate a tablesaw Table with one of our tables the current SqlResultSetReader interprets all these NUMBER columns as ColumnType.DOUBLE types after a cursory look at the ResultSet metadata that maps the NUMBER column to either java.sql.Types.NUMERIC or java.sql.Types.DECIMAL types.  

Many of our NUMBER columns are in fact integers of varying size, so I'm proposing an update to the SqlResultSetReader.java to look more closely at the metadata, the precision and scale values to try to map to the best fitting java numeric type.   Any objections?

**Comment by gregorco** [comment]
Given that, I'm not sure if my changes would still be relevant or useful.  I could attach my SqlResultSetReader.java file to this Issue388 for you to see what I have working so far.  I had included support for Float type before finding it caused problems in my app where I tried to call some method(s) on a FloatColumn that didn't exist.  Should I attach it here first, or go through with a PR for it to be reviewed?

**Comment by lwhite1** [comment]
I don’t think I’d merge a pr until my changes are in so maybe just attach
it here

**Comment by gregorco** [comment]
Sure.  Thanks.  Tried with the .java extension, but received an error when trying to drag/drop it, so renamed to .txt extension.
[SqlResultSetReader.txt](https://github.com/jtablesaw/tablesaw/files/2371209/SqlResultSetReader.txt)

**Comment by gregorco** [comment]
Just saw your PR #389 and understand better what you were mentioning before.  Your changes might make my changes simpler so I'll incorporate your changes when they're merged and reassess any changes I'll need to make.

**Comment by gregorco** [comment]
I understand your point.  Db design has multiple ways to define the same type of number, and in my company's case the original decision was to rely solely on Oracle's  NUMBER(precision,scale) type for all integers and floating point types for maximum size/precision control instead of Oracle's convenient pre-defined types like INTEGER, LONG, FLOAT, or DECIMAL.  Oracle doesn't appear to have a SMALLINT or TINYINT type.  

When the java.sql.ResultSet's metadata is examined to determine the column type, and it interprets NUMBER as java.sql.Types.NUMERIC which tablesaw currently maps to Double, I understand that it's the default/safe mapping to make.  I will be able to add workarounds to convert DoubleColumn to IntegerColumn where necessary, but wondered if tablesaw could recognize integer types automatically whether it would be a useful feature.  In my experiment, I had SqlResultSetReader.java determine this automatically with what I believe could be considered trivial logic.   If a flag were to be provided when pulling in a database ResultSet, then maybe that could be a compromise as to when to apply this automatic integer detection/mapping?  

Don't know how common it is for database designs to use NUMBER instead of pre-defined integer types, but if it's not that common then I agree this feature would not be that useful.

**Comment by gregorco** [comment]
Maybe eventually a DbReadOptions class, inspired by the CsvReadOptions class could be available when reading in a ResultSet, and in that DbReadOptions the caller could have more control over mapping.  Just a thought.

**Comment by gregorco** [comment]
Now understand that Oracle doesn't actually have a built-in type for INTEGER.   Was misinformed by SQLDeveloper's convenience of offering a new column type as INTEGER while Oracle internally represents it as a NUMBER without a scaling factor.  Seems Oracle internally represents all numerics with NUMBER type. https://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#SQLRF00213   Will this mean that all jtablesaw Table columns created by importing from Oracle result-sets should be forced into DoubleColumn types?

**Comment by lwhite1** [comment]
Leave it to oracle to encourage weak type constraints and discourage ANSI compliance. INTEGER as you say is just a numeric without a scaling factor, but it's much clearer to say integer than number.  Anyway. if you want to go ahead with your changes, I will review. Where are you now in terms of completion?

**Comment by gregorco** [comment]
In my project I'm still working with the same proposed version of SqlResultSetReader.java that I attached earlier.  I understand that with your pending PR#389 that I would need to reassess the changes I'm proposing though, so I'll have to do that once PR#389 is merged.   If it makes sense, this change could include an option when invoking the DataFrameReader's db(ResultSet, String) method to possibly add a new parameter that flagged whether to do this automatic interpretation for NUMBER types or not.  The default behavior obviously could be to do nothing different to avoid breaking existing calls that have been accepting the current behavior of receiving DoubleColumn types.

**Comment by lwhite1** [comment]
Ok. I’ll try to review over the weekend.  I’ve been swamped lately.

**Comment by gregorco** [comment]
Thanks.  I'll try to submit it before this weekend.

**Comment by lwhite1** [comment]
sounds good. thanks.

**Comment by lwhite1** [comment]
closed fixed
