### ISSUE TITLE
StringColumn.asObjectArray() returns unexpected result

### ISSUE THREAD

**Issue by jln-ho** [jtablesaw/tablesaw#392]
```java
final StringColumn sc = StringColumn.create("sc", Arrays.asList("a", "b", "c", "a"));
System.out.println(Arrays.toString(sc.asObjectArray()));
System.out.println(Arrays.toString(sc.asList().toArray()));
```

Prints

```
[a, b, c]
[a, b, c, a]
```

It seems like `StringColumn.asObjectArray` returns all values in the column's lookup table, which only contains a single entry for each unique string appearing in the column. The `TextColumn` class doesn't do this (as it doesn't use a lookup table) and behaves as expected:

```java
final TextColumn tc = TextColumn.create("sc", Arrays.asList("a", "b", "c", "a"));
System.out.println(Arrays.toString(tc.asObjectArray()));
System.out.println(Arrays.toString(tc.asList().toArray()));
```

Prints

```
[a, b, c, a]
[a, b, c, a]
```

**Comment by lwhite1** [comment]
On Tue, Sep 18, 2018 at 9:27 AM Julian Howes <notifications@github.com>
wrote:

> final StringColumn sc = StringColumn.create("sc", Arrays.asList("a", "b", "c", "a"));System.out.println(Arrays.toString(sc.asObjectArray()));System.out.println(Arrays.toString(sc.asList().toArray()));
>
> Prints
>
> [a, b, c]
> [a, b, c, a]
>
> It seems like StringColumn.asObjectArray returns all values in the
> column's lookup table, which only contains a single entry for each unique
> string appearing in the column. The TextColumn class doesn't do this (as
> it doesn't use a lookup table) and behaves as expected:
>

The "values" in the lookup table is an array of keys. It *should* have an
entry for each value in the column. There are other data structures that
map from the keys to values and vice versa. Those structures contain one
entry for each unique value.  So, IDK yet what's wrong, but it's not quite
what you suggest. It seems that the **values** implementation is broken
somehow. I will look into it and hopefully post a fix today.  Thank you for
providing an excellent bug report. That helps a lot.

**Comment by lwhite1** [comment]
fixed
