### ISSUE TITLE
Dataframe to array?

### ISSUE THREAD

**Issue by jrvanalstine** [jtablesaw/tablesaw#393]
Is there a method to go from Table to java array? I'm thinking of something similar to pandas dataframe to numpy array.

**Comment by lwhite1** [comment]
Nothing that will do it all in one step for an arbitrary data frame, but
there are some utilities that may help in a class called doublearrays in
utils. And some in io for. interfacing with smile.

I’m away from my computer or I would be more precise

**Comment by benmccann** [comment]
I think you can call `.to().doubleMatrix()`

**Comment by jrvanalstine** [comment]
Ah. I found it. The method is actually Table.as().doubleMatrix(). Thx you two.

**Comment by benmccann** [comment]
Hmm. That should only be required for `.as().smileDataset`

**Comment by janicebloc** [comment]
Is there a convenient way in tablesaw to discretize a number column (i.e. a continuous variable) so that you can chunk it as an ordinal variable?

**Comment by janicebloc** [comment]
I am really struggling with the tablesaw internal implementation for decision tree.  It isn’t working for me.  Does anyone have code that can help to illustrate how it and its parameters are supposed to work?    I could give up and use smile separately, weka, or something like that, but I thought it would be nice to stay within tablesaw.

**Comment by lwhite1** [comment]
The floating point column types implement roundInt(). Not sure if that
meets your needs. If not, you can always implement a floor/ceiling/other
round function by iterating over the column or table.

**Comment by lwhite1** [comment]
Tablesaw doesn't implement any ML wrappers anymore. All you can do is
convert the dataframe to Smile format and use Smile.
