### ISSUE TITLE
It's impossible to parse CSV file with more than 512 columns

### ISSUE THREAD

**Issue by Ebalaitung** [jtablesaw/tablesaw#395]
I try to parse feature index file into Table (it's about 2000x36000 matrix).
I try to use:
`Table t = Table.read().csv(csv);`
but got error from com.univocity.parsers.csv.CsvParser (log is attached [512-ERROR.txt](https://github.com/jtablesaw/tablesaw/files/2419490/512-ERROR.txt)) that there is more than 512 columns.
I've checked sources and found out that you create CsvParser  with default settings, and there is no option to change some how this settings from your API.

I think there should be some way to change com.univocity.parsers.csv.CsvParserSettings from Table.read()  place, or at least change columns size limit.

**Comment by benmccann** [comment]
I wonder if we should just hardcode `parserSettings.setMaxColumns(Integer.MAX_VALUE)`. I don't really understand why there would be a column limit

**Comment by Ebalaitung** [comment]
> I wonder if we should just hardcode `parserSettings.setMaxColumns(Integer.MAX_VALUE)`. I don't really understand why there would be a column limit

I also thought about it.

**Comment by lwhite1** [comment]
> I wonder if we should just hardcode parserSettings.setMaxColumns(Integer.MAX_VALUE). I don't really understand why there would be a column limit

Seems reasonable. Anyone want to submit a pull request?

**Comment by Ebalaitung** [comment]
> > I wonder if we should just hardcode parserSettings.setMaxColumns(Integer.MAX_VALUE). I don't really understand why there would be a column limit
> 
> Seems reasonable. Anyone want to submit a pull request?

Will do...

**Comment by Ebalaitung** [comment]
Need possibility to configure max amount of columns to parse, as default value is just 512

**Comment by Ebalaitung** [comment]
Added corresponding PR, please review.
