### ISSUE TITLE
Allow to read malformed CSV

### ISSUE THREAD

**Issue by deviant-studio** [jtablesaw/tablesaw#396]
I would like to skip invalid csv rows (or do some other processing).
Since we can't use univocity api directly in the tablesaw, it is impossible to do fine grained tuning like this:
https://stackoverflow.com/a/38693310/926568

It would be great if we have some kind of error handler in `CsvReadOptions`

**Comment by lwhite1** [comment]
If you provide a good pull-request, I'd be happy to add that. I think it should go in ReadCsvOptions.

**Comment by ChangzhenZhang** [comment]
@lwhite1 Hi, I pull a [request](https://github.com/jtablesaw/tablesaw/pull/901) for this issue.
I add an option `ignoreInvalidRows` to skip invalid csv rows. And I want to make sure that if this change fixes the issue.
Thanks!
