### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by jennifergreenberg** [jtablesaw/tablesaw#397]
Hi, this is a question that I have, not an actual issue. 
I have never used maven before and am unable to get the examples in tablesaw to run and wanted to see if someone was willing to help walk me through this. 
Thanks in advance!

**Comment by lwhite1** [comment]
I generally run them from within an IDE. Some have too many side-effects to make good tests (and no actually testing inside them.) Since they generally include a main() method, I just highlight the file for the example (in Intellij IDEA) and click run.

**Comment by lwhite1** [comment]
Closing for now. If you need more help @jennifergreenberg, lmk

**Comment by jennifergreenberg** [comment]
Hi Larry, 
I tried to run them in Intellij and it still wouldn't work for me. This is my first time ever using maven so I am probably making a mistake there. Do you have any other tips?

**Comment by jennifergreenberg** [comment]
@lwhite1 would you mind doing a screen share with my screen?

**Comment by spaces-X** [comment]
Same question. I tried to run examples in eclipse and i got a error ’selection doesn't contain a main type‘ . However, it does have a main() method in these examples.

**Comment by benmccann** [comment]
I left a comment explaining the problem on https://github.com/jtablesaw/tablesaw/issues/402

**Comment by lwhite1** [comment]
I'll take care of it. I want to do a little cleanup first.
