### ISSUE TITLE
Alternative to Column/Create in 0.20 ?

### ISSUE THREAD

**Issue by yellowbean** [jtablesaw/tablesaw#399]
Hello !

Thanks for your contribution on this project ,it works great so far in my project !

While I'm trying to upgrade my dep to 0.25.2, I found that _Column/Create_ is left out, may I have some clue how to implement same feature with alternative method ?

My use case is , passing a column name and a type , a function will create a Column base on them.
I tried with an instance of SkipColumnType and call _create_ but it raised exception : 

Thanks again and much appreciation on advise

**Comment by lwhite1** [comment]
you can call a similar method on the Columntype class (its subclasses,
actually).

See Column<?> create(String name);
