### ISSUE TITLE
 Anything can be done to fill missing value with backfill method or frontfill method?

### ISSUE THREAD

**Issue by anphy** [jtablesaw/tablesaw#401]
I'm dealing with a bunch of time serial tables with many missing values to be filled with backfill(backward) method like pandas in python, but I can only find method of Class Column to fill them with default value. Any suggestion about this?

**Comment by lwhite1** [comment]
I don’t understand what you mean by forward or backward method. Can you
 explain what you want without comparing to pandas?

**Comment by anphy** [comment]
@lwhite1 
Thank you for your reply, and apologize for my not being clear. I reedited it and make it clearer as follows: backfill(backward) means filling  missing/empty values (plural means many) with the next valid value, and on the contrary,  frontfill(forward) means filling them with the last valid value.

**Comment by anphy** [comment]
I've made a way to do fronfill method, would anyone make a check on it?
```
            String nanStr = String.valueOf(Double.NaN);
            for (Column column : other.columns()) {
                if (column.countMissing() == 0) {
                    continue;
                }
                int row = -1;
                for (Object item : column) {
                    String i = item.toString();
                    if (i.isEmpty() || i == nanStr) {
                        column.set(row + 1, column.get(row));
                    }
                    row++;
                }
            }
```

**Comment by benmccann** [comment]
@anphy I wanted to let you know that we just added this feature and it will be included in the next release
