### ISSUE TITLE
Can not run examples

### ISSUE THREAD

**Issue by spaces-X** [jtablesaw/tablesaw#402]
I tried to run examples in eclipse and got an error ‘**selection does not contain a main type**’.  However, it does have a main method in these examples. How to fix this problem?

**Comment by benmccann** [comment]
It looks like this is because the examples are not under the standard `src/main/java` or `src/test/java` folders.

I think that we might need to move the tests to live under `src/test/java`. Would you be okay with this @lwhite1 or do you have other ideas on solutions?

**Comment by spaces-X** [comment]
@benmccann Nice, it works. Thanks a lot for your helpful advice.
