### ISSUE TITLE
Dropping Rows Based on Filter

### ISSUE THREAD

**Issue by okaljuvee** [jtablesaw/tablesaw#410]
Is there a plan to add a method to drop rows based on a filter (much like pandas allows)?  Thanks!

PS  Exciting project!  I'm evaluating the API and if it works for a few requirements I have, I would love to contribute as well.

**Comment by benmccann** [comment]
See `dropWhere`

**Comment by okaljuvee** [comment]
Thanks!  I'm looking for conditional filters on values.  Selection just operates on int ranges.  For example, I'd like to drop all rows where "Foo" column is null (or na) or where the value is "N/A".  In Pandas it would look something like this:

`clean = data.drop(data[pd.isna(data.Foo) | (data.Foo == "N/A")].index)`

**Comment by benmccann** [comment]
`Selection` is returned by a filter: https://jtablesaw.github.io/tablesaw/userguide/filters

**Comment by okaljuvee** [comment]
OK, thank you--make sense now.  Didn't see the user guide before.
