### ISSUE TITLE
Creating a heatmap using a Matrix

### ISSUE THREAD

**Issue by rahabwairimu05** [jtablesaw/tablesaw#417]
The current function of heat map in Table saw, only accepts two columns of data. Is there a function that accepts like 10 columns ? I want to look at correlation in a huge data set with different columns

**Comment by lwhite1** [comment]
No, there's no facility for creating a matrix of heat maps (or any other
chart) currently.

**Comment by rahabwairimu05** [comment]
Then how does one create a heatmap with more than two columns ? any ideas ? The only function I seem to see only accepts two, is there a heatmap function that accepts more than two? or which is the other alternative ?
Figure myHeatmap = Heatmap.create(title, table, categoryCol1, categoryCol2);

**Comment by lwhite1** [comment]
The standard heatmap currently only plots takes two categorical columns and
plots  (as the color) the number of values in each pair of categories. If
you look at the underlying HeatmapTrace class, you can see that it also
takes two categories, but allows you to provide arbitrary numeric values as
for the color dimension.

If you want to get fancier than that, you could look at the implementation
of HeatmapTrace (as an example) and see if you can create from the
available components a similar class that does what you want.

**Comment by rahabwairimu05** [comment]
I checked at the implementation of the  HeatmapTrace, but it still takes two columns. Its hard to manipulate the entire class to  come up with my own inorder to plot the heatmap. Will look for other options available to use in Java. Thank you!

**Comment by lwhite1** [comment]
I'm going to open an issue for supporting plot matrices and close this specific issue.
