### ISSUE TITLE
Converting Table  to double[][]

### ISSUE THREAD

**Issue by rahabwairimu05** [jtablesaw/tablesaw#418]
Is there a way to easily convert a Table saw Table ( which contains columns with Integers and  doubles) to a double Multidimensional array ? ( double [] [])

**Comment by lwhite1** [comment]
yes. See tech.tablesaw.util.DoubleArrays.

**Comment by rahabwairimu05** [comment]
Currently checking the class , but I have not seen a function  of return type double[][] thats takes Table as a parameter. Is it possible to point to the exact function ?
https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/util/DoubleArrays.java

**Comment by benmccann** [comment]
It's easiest to call `table.as().doubleMatrix()` (I'm not at my computer so am not sure that's the exact API, but should be close)

**Comment by lwhite1** [comment]
On Mon, Nov 26, 2018 at 11:05 AM Ben McCann <notifications@github.com>
wrote:

> It's easiest to call table.as().doubleMatrix() (I'm not at my computer so
> am not sure that's the exact API, but should be close)
>
It's
table.as().doubleMatrix();

**Comment by rahabwairimu05** [comment]
Both of them  worked perfectly only that the first one  was  DoubleArrays.to2dArray(table.numberColumns()); . Thank you

**Comment by rahabwairimu05** [comment]
Both of them worked perfectly only that the first one was DoubleArrays.to2dArray(table.numberColumns()); instead of  DoubleArrays.to2dArray(table.numericColumns()); 
And the second one ,  table.as().doubleMatrix(); .Thank you!
