### ISSUE TITLE
stringcolumn get null value or MissingValue with different input

### ISSUE THREAD

**Issue by yetantai** [jtablesaw/tablesaw#419]

**Comment by yetantai** [comment]
val table1 = Table.create("table1", StringColumn.create("id", Array("1", "2", "3", "4", null)))
println(table1.stringColumn("id").get(4))  // output null

val table2 = Table.create("table2", StringColumn.create("id", Array("1", "2", null, "", "5")))
println(table2.stringColumn("id").get(2)) // output ""

**Comment by lwhite1** [comment]
fixed on master
