### ISSUE TITLE
Converting  a StringColumn to String []

### ISSUE THREAD

**Issue by rahabwairimu05** [jtablesaw/tablesaw#421]
Is there a function in the StringColumn class that returns String [] of  the String Column?  I  do not want to use  asObjectArray() function since I require String Array to be specific,  I am typecasting it to String [] but it  is not giving the output I require

**Comment by lwhite1** [comment]
The only way currently is to get the contents as a list and then convert the list to a String[].

` column.asList().toArray(new String[0])`

or to create the list and manually populate from the column, one row at a time in a loop

**Comment by lwhite1** [comment]
closed fixed by adding asStringArray() methods to StringColumn and TextColumn
