### ISSUE TITLE
userguide example does not work

### ISSUE THREAD

**Issue by svlandeg** [jtablesaw/tablesaw#423]
Hi,

Thanks for creating and supporting this nice framework! I am experimenting with it a little and ran into the following issue:

The first example using a builder on https://jtablesaw.github.io/tablesaw/userguide/importing_data has the code `CsvReadOptions.builder()` which I suppose should be `CsvReadOptions.builder("myFile.csv")` or something such. 

Best,
Sofie

**Comment by lwhite1** [comment]
Fixed.  Thanks for the report.
