### ISSUE TITLE
Reading values from Hive bigInt column fails when values do not end in a decimal

### ISSUE THREAD

**Issue by Voomer** [jtablesaw/tablesaw#426]
Hello,

I am using 		

```Java
Table myTable = Table.read().db(resultSet, "dataset");
```

To read in data from a Hive database.  One of the columns in Hive is set to bigint, which looking at source code

```Java
 private static Map<Integer, ColumnType> initializeMap() {
        return new HashMap<>(
                new ImmutableMap.Builder<Integer, ColumnType>()
                ...
                .put(Types.TINYINT, ColumnType.SHORT)
                .put(Types.BIGINT, ColumnType.DOUBLE)
```

The value in my table is something like 102768, which the resultset returns as a Long object. Which fails when trying to map to the DoubleColumn because the column only accepts objects of Double and BigDecimal.

```Java
public DoubleColumn appendObj(Object obj) {
        if (obj == null) {
            return appendMissing();
        }
        if (obj instanceof Double) {
            return append((double) obj);
        }
        if (obj instanceof BigDecimal) {
            return append(((BigDecimal) obj).doubleValue());
```

Maybe instance instanceof Numerical and less restrictive would be acceptable here instead?

**Comment by lwhite1** [comment]
Fixed by changing the mapping to LongColumn rather than DoubleColumn. Let me know if you still have an issue
Thanks for the bug report
