### ISSUE TITLE
Circular dependencies in Columns/ColumnTypes can lead to unpredictable behavior

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#430]
A null value is sometimes returned by a ColumnType constant. Whether or not the value is null depends on the order in which other code is executed.

To recreate, I built an array of ColumnTypes and printed the array. Sometimes the values are all initialized correctly, sometimes not:

Correct:

```
[STRING, LOCAL_DATE_TIME, INTEGER]
```
Incorrect:

```
[STRING, null, INTEGER]
```
The different results can be had by adding or removing a line of code just before printing. The correct result is printed when the line is removed.

Here is the main class with the offending line included:

```
class DummyClass {

    public static void main(String[] args) {
        long missing = DateTimeColumn.MISSING_VALUE;
        new DummyPrinter().printColumnTypes();
    }
} 

```
When I comment out line 1 in main, the code works as expected. Also, the code that implements printing must be in a separate class for the error to occur. Here's that class:

```
class DummyPrinter {

    void printColumnTypes() {
        System.out.println(Arrays.toString(columnTypes));
    }

    private static final ColumnType[] columnTypes = {
        STRING,
        LOCAL_DATE_TIME,
        INTEGER,
    };
}

```
The array itself is a literal constant. The values inserted into the array are also constants. They are declared in the ColumnType interface in the line shown below:

```
DateTimeColumnType LOCAL_DATE_TIME = DateTimeColumnType.INSTANCE;
```

In that line, the values are provided by a constant (INSTANCE) declared in DateTimeColumnType.

Here is the code from that class where INSTANCE is created:

```
public static final DateTimeColumnType INSTANCE =
        new DateTimeColumnType(BYTE_SIZE, "LOCAL_DATE_TIME", "DateTime");

```
The line of code that turns the error on and off causes the class DateTimeColumnType to load in a different order when it's present than it does when absent.

**Comment by lwhite1** [comment]
Trying to remove the pointer from columnType to column would be a big help if possible. It's used to provide a factory method for the column.

**Comment by jon-hanson** [comment]
I'm experiencing this bug as well. In my case something as simple as:

    return DateColumn.create(name)

is giving rise to a DateColumn object with a null type. If i precede it with:

    final DateColumnType ct = ColumnType.LOCAL_DATE;

then the null type is prevented (but I'm guessing the issue then moves elsewhere).

As you say, the cause seems to be circular dependencies between the static initialisation of various classes related to ColumnTypes.

**Comment by lwhite1** [comment]
I will try to make a real fix for this over the weekend.

**Comment by lwhite1** [comment]
I made some changes that are not a complete and robust solution, essentially replicate what I did in DateTimeColumn that fixed the problem I saw. Can you see if they help with your DateColumn issue.

**Comment by lwhite1** [comment]
@benmccann I think the best fix here is to combine the ColumnType and Column hierarchies, which may be a pretty big change internally, and may affect some client code (though that is probably pretty simple code like 

```
    if (column.type().equals(StringColumnType.INSTANCE) {
...
    }
```
The cause of the cyclic reference is that ColumnTypes implement a create() method that returns an instance of their specific Column. It's used in things like CSV Parser when the parser detects a "columnType" based on the data it's seeing.  I didn't want columnType to be an enum because then you can have client code that implements novel column types. 
 
Any thoughts?

**Comment by jon-hanson** [comment]
Tried checking out the trunk and building with (Oracle) JDK 1.8.0_131, but some of the tests fail:

```
testSortOn(tech.tablesaw.api.DateColumnTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalStateException: Column prefix: D is unknown.
	at tech.tablesaw.api.Table.sortOn(Table.java:484)
	at tech.tablesaw.api.DateColumnTest.testSortOn(DateColumnTest.java:154)
[...]
testLocalDateDetectionEnglish(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionEnglish(CsvReaderTest.java:170)
[...]
testLocalDateDetectionFrench(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionFrench(CsvReaderTest.java:227)
[...]
testReadFailure2(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.IllegalArgumentException: Column Test is not present in table read_failure_test2.csv
	at tech.tablesaw.api.Table.columnIndex(Table.java:278)
	at tech.tablesaw.table.Relation.shortColumn(Relation.java:430)
	at tech.tablesaw.io.csv.CsvReaderTest.testReadFailure2(CsvReaderTest.java:392)
[...]
test_JavaBehaviour(tech.tablesaw.io.csv.UnicodeBomHandlingTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<ï»¿1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.csv.UnicodeBomHandlingTest.test_JavaBehaviour(UnicodeBomHandlingTest.java:34)
[...]
html(tech.tablesaw.io.DataFrameWriterTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...></td></tr>
</tbody>[]
> but was:<...></td></tr>
]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.DataFrameWriterTest.html(DataFrameWriterTest.java:58)
```
I can see that the project is building in Travis. Are there any special steps for building the project?

**Comment by jon-hanson** [comment]
I took a look at the first test failure. It looks like the CSVReader is consuming everything up to the comma on the second line as the first "cell" of the first line. I.e. it's not respecting line endings. If I change the CsvReadOptions line to explicitly set the lineEnding then it the test passes:

```
        CsvReadOptions options = CsvReadOptions.builder(stream, "")
                .header(header)
                .separator(delimiter)
                .sample(useSampling)
                .locale(Locale.ENGLISH)
                .lineEnding("\n")
                .build();
```
I suspect that the CsvReadOptions.Builder class should be setting a default value of "/n" for lineEnding - at present it defaults to null.

Not sure how this succeeds in Travis.

**Comment by lwhite1** [comment]
Hmmm. I will take a look.

**Comment by jon-hanson** [comment]
> 
> 
> Hmmm. I will take a look. Are you running this on Windows?

Yep (Win10 64bit).

**Comment by lwhite1** [comment]
It works in Travis because Travis runs on linux. Looking at it in a debugger, we don't set a line ending unless one is set in the builder, yet on OSX a line ending is set by Univocity. 

Univocity has a flag called setLineSeparatorDetectionEnabled which defaults to false, but again, on OSX it's doing something. I tested with that flag to true, but then the code breaks if you pass in a line ending explicitly. 

I opened a ticket with Univocity to see if we're doing something wrong. If this is blocking you I can try conditionally setting the detection enabled flag. LMK what you'd like to do.

**Comment by lwhite1** [comment]
Actually, I'm pretty sure just the tests are broken.  These tests create tables as a stream and explicitly use unix (/n) line endings. I will replace them with System.lineSeparator() and hopefully that will fix the issue.

**Comment by lwhite1** [comment]
I pushed a fix for the line separator. Hopefully, this will be resolved on Windows and you can retest the original issue.

**Comment by jon-hanson** [comment]
That has fixed that test, but the other tests I mentioned are still failing. I will comment them out for now, as that particular issue (tests broken on Windows) is unrelated to the original issue.

**Comment by lwhite1** [comment]
Can you give me the full list of all failing tests and the output (unless the above list is complete and the error messages have not changed)?  thanks

**Comment by jon-hanson** [comment]
The failing tests and the error message are in [my comment above](https://github.com/jtablesaw/tablesaw/issues/430#issuecomment-453922874).

The jsplot sub-module also experiences several test failures:

centerBuilder(tech.tablesaw.plotly.components.threeD.CenterTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{[
    x: 1.0,
    y: 2.0,
    z: 3.0,]
}> but was:<{[
    x: 1.0,
    y: 2.0,
]
}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.plotly.components.threeD.CenterTest.centerBuilder(CenterTest.java:17)
[...]

Running tech.tablesaw.plotly.components.threeD.EyeTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
eyeBuilder(tech.tablesaw.plotly.components.threeD.EyeTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{[
    x: 1.0,
    y: 2.0,
    z: 3.0,]
}> but was:<{[
    x: 1.0,
    y: 2.0,
]
}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.plotly.components.threeD.EyeTest.eyeBuilder(EyeTest.java:17)
[...]
Running tech.tablesaw.plotly.components.threeD.UpTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
upBuilder(tech.tablesaw.plotly.components.threeD.UpTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{[
    x: 1.0,
    y: 2.0,
    z: 3.0,]
}> but was:<{[
    x: 1.0,
    y: 2.0,
]
}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.plotly.components.threeD.UpTest.upBuilder(UpTest.java:17)
[...]

**Comment by jon-hanson** [comment]
On a more positive note, the circular-dep/static-initialisation fix does appear to work for my simple use case.

**Comment by lwhite1** [comment]
Notes on the various errors. Comments follow each error message. 

**First Error**
```
testSortOn(tech.tablesaw.api.DateColumnTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalStateException: Column prefix: D is unknown.
	at tech.tablesaw.api.Table.sortOn(Table.java:484)
	at tech.tablesaw.api.DateColumnTest.testSortOn(DateColumnTest.java:154)
[...]
```
This error suggests that the column names were not read correctly.  The sort routine can't find a column that matches the one specified in the request:

        Table sorted = unsorted.sortOn("Date");
so it drops into the code that looks for a + or - sign prepended to the name. It gets the D from Date because there is no prepended sign. 

Looking at the test code, it's hard to see how the name could be read incorrectly since it's the first column and the delimiting comma follows immediately. 

```
        Table unsorted = Table.read().csv(
                "Date,1 Yr Treasury Rate" + System.lineSeparator()
```
A quick check showed no invisible characters in the header string.

**Second and Third Error**
```
testLocalDateDetectionEnglish(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionEnglish(CsvReaderTest.java:170)
[...]
```
```
testLocalDateDetectionFrench(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionFrench(CsvReaderTest.java:227)
[...]
```
These two errors have the same cause. In both cases we should see an array containing the columnType LOCAL_DATE, but the array is empy. (I think we'd see the word null printed if there was a null value. 
This seems like it might be related to the cyclic relationship issue, except that other manifestations throw an NPE reading the ColumnType array rather than completing and returning the wrong result. 

The code below suggests that can't be the issue, because the return value of detectedType is tested on the next line for equality so it isn't null. The method returns an array constructed on the last line so it executes to completion. Best guess is that the table is parsed incorrectly so that the entire thing is read as the header (which is skipped), no lines are passed to the type detector and the method returns without really doing anything. That gets us back to some kind of parsing error.

```
        for (List<String> valuesList : columnData) {
            ColumnType detectedType = detectType(valuesList, options);
            if (detectedType.equals(StringColumnType.STRING) && rowCount > STRING_COLUMN_ROW_COUNT_CUTOFF) {
                HashSet<String> unique = new HashSet<>(valuesList);
                double uniquePct = unique.size() / (valuesList.size() * 1.0);
                if (uniquePct > STRING_COLUMN_CUTOFF) {
                    detectedType = TEXT;
                }
            }
            columnTypes.add(detectedType);
        }
        return columnTypes.toArray(new ColumnType[0]);

```

**Fourth Error**
```
testReadFailure2(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.IllegalArgumentException: Column Test is not present in table read_failure_test2.csv
	at tech.tablesaw.api.Table.columnIndex(Table.java:278)
	at tech.tablesaw.table.Relation.shortColumn(Relation.java:430)
	at tech.tablesaw.io.csv.CsvReaderTest.testReadFailure2(CsvReaderTest.java:392)
[...]
```
This has the same underlying cause as the first error, I think. This time the code reads the table from a file with comma delimiters separating columns, but somehow it fails to create the first column. Could we be getting errors on windows reading commas?  

**Fifth Error**
```
test_JavaBehaviour(tech.tablesaw.io.csv.UnicodeBomHandlingTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<ï»¿1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.csv.UnicodeBomHandlingTest.test_JavaBehaviour(UnicodeBomHandlingTest.java:34)
[...]
```
This is a unicode bom error, so it's a different Windows disease from the line ending issue.

**Sixth Error**
```
html(tech.tablesaw.io.DataFrameWriterTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...></td></tr>
</tbody>[]
> but was:<...></td></tr>
]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.DataFrameWriterTest.html(DataFrameWriterTest.java:58)
```
I can't tell which test is failing, and the expected results don't look like they could be produced by either test.

**Comment by benmccann** [comment]
I'm not sure I understand what the root cause of this error is. I also don't understand why we're doing lazy initialization of the column types

**Comment by lwhite1** [comment]
@benmccann 

When using the library in another project, depending on the order classes are used, you can end up in a situation where the value of INSTANCE set in the code below could return null. 

````
public static final DateTimeColumnType INSTANCE = new DateTimeColumnType(...);
```
I hadn't realized this was possible, but it is. It seems to be the case that it can only happen where there are multiple static variables in different classes that are related. I didn't dig into it too far, but my impression are that the class loader could have trouble consistently following the dependency graph. 

I eliminated some gratuitous static final variable references to column types as general cleanup, and switched to the lazy initialization to ensure the singleton is returned initialized regardless of when the class is loaded.

**Comment by lwhite1** [comment]
I should add that simply changing a line or two in the client code could make the issue appear or disappear so it was difficult to be sure that it's completely resolved. It might be that moving the references in ColumnType to the singletons would alleviate or eliminate the issue, but again I don't know how to test that.

**Comment by lwhite1** [comment]
Closing this and moving the test problem to new issue #441
