### ISSUE TITLE
Bug: TimeSeriesPlot cannot override date column name

### ISSUE THREAD

**Issue by KarlAnderssonBremen** [jtablesaw/tablesaw#432]
The plotting integration with plotly looks very nice and is easy to use. :+1:  :-)

Small thing that looks like a bug to me:
`tech.tablesaw.plotly.api.TimeSeriesPlot.create(String title, Table table, String dateColX, String yCol, String groupCol)`

contains a hardcoded value for the dateColumn. Line
`Table t = tableList.get(i).sortOn("date");`
(I have a table from Oracle, so I cannot name my columns "date")
should probably change into
`Table t = tableList.get(i).sortOn(dateColX);`

Looks like this works on my test. Can you please verify that? Thanks!

**Comment by lwhite1** [comment]
fixed. Thanks for the bug report.
