### ISSUE TITLE
class SqlResultSetReader's function read use ResultSet.getObject funtion ,it makes errors.

### ISSUE THREAD

**Issue by ddl19901201** [jtablesaw/tablesaw#433]
class SqlResultSetReader's function read use ResultSet.getObject funtion ,it makes errors.

 if (column instanceof ShortColumn) {
                    column.appendObj(resultSet.getObject( i ,Short.class));
                }
shoule change to 
                    column.appendObj(resultSet.getShort( i ));

**Comment by lwhite1** [comment]
@ddl19901201 Can you test against master and see if the issue is resolved? 
Thank you.

**Comment by ddl19901201** [comment]
> @ddl19901201 Can you test against master and see if the issue is resolved?
> Thank you.

It's OK now,thanks.

**Comment by lwhite1** [comment]
closing.
