### ISSUE TITLE
Support for multiple plots within single html file

### ISSUE THREAD

**Issue by deveborn** [jtablesaw/tablesaw#434]
I would like to plot several charts in a single document. That is not supported by now (as I understand it). I was wondering what would be the preferred road to go in order to make multiple plots possible (without embedded web server). Do I have to dive into templates and such things or could I find some other easier work around? It would be great if it was a built in way to style the document with custom css also!

Moreover I have find a possible bug and some potential errors in the documentation but I post them as separate issues later on. I really appreciate this library! What I wish most is better documentation (for a hobbyist it can be a bit tricky to get into it).

**Comment by lwhite1** [comment]
It shouldn't be hard to put multiple plots in one document. The library just doesn't support the creation of plot matrices using Plotly. 

Look at the **Plot** class. It creates an image by embedding a **Figure** in an HTML file. You should be able to make your own HTML file and do something similar, but with multiple figures. 

You create a *Figure* by combining a trace (or several traces) and a layout.  This example is from the Histogram class, but they are all similar. 

```
    public static Figure create(String title, double[] data) {
        HistogramTrace trace = HistogramTrace.builder(data).build();
        return new Figure(standardLayout(title), trace);
    }
```

The **traces** package contains trace builders for each supported plot type. Take a look at the **HistogramTrace** class, and also at the **Histogram** class in the **api** package that uses it. **Histogram** just creates a Figure that combines a HistogramTrace and a basic layout. Plot takes the figure and puts it in an HTML page. 

In **resources**, there's a basic HTML page template called page_template.html. It just defines a div to display the image and the generated JavaScript that does the rendering.  You want to create a div for each image. The JavaScript for a figure can be had by calling asJavascript on the figure:

```
    figure.asJavascript(divName)
```
Note that you pass in the divName (id, really) for the div where the plot should be rendered.

Plot uses a class called Page that makes sure the div name referenced in the JavaScript matches the div name in the HTML file.  You could write code to do that. Basically you just need an HTML page with "div1" and "div2", and the generated javascript from two figures:

```
<html>
<head>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <div id='div1' ></div>
    <div id='div2' ></div>

<!-- generated javascript from your figures -->

</body>
</html>
```

Tablesaw uses the Pebble template library to insert the javascript. You can use this if you want, but that's up to you. 

```
        <dependency>
            <groupId>io.pebbletemplates</groupId>
            <artifactId>pebble</artifactId>
            <version>2.6.0</version>
        </dependency>
```

Please do post the issues you've found.

**Comment by lwhite1** [comment]
I added an example class that shows how to do this. You can find it at:

https://github.com/jtablesaw/tablesaw/blob/master/jsplot/src/examples/java/tech/tablesaw/plotly/MultiPlotExample.java

I should write a doc file, but will leave that for another day.

**Comment by deveborn** [comment]
Great, thank you very much for all the details! I did not expect you to help me out completely with examples and everything. I have some notes on the possible issues I found earlier. I want to review them again before I get back (so that I can give you good feedback on it). 

The simplicity of the current Plot functions is really good! But have you ever thought about possibility to pass several Figures into them? Or support several writes to the same file in order to create multiple plots i one document? That was my first try (before I started to review the code behind the potting functions) :-). Thanks again for your help!

**Comment by lwhite1** [comment]
It would be easy enough to make Plot handle multiple figures if all you
want to do is display them in a column in the HTML, but I'm not sure that's
very useful. I would think most people would want to add text and
formatting to any multi-plot document.

When I do multiple plots for exploratory analysis, I just create them
separately in the method and the browser opens each in it's own tab.

**Comment by deveborn** [comment]
Maybe you are right. In my use case I wanted to aggregate plots that were related to the same raw data (measures from a particular site). Much easier to have them collected (and share with others). Your code example made it easy for me to extend the Plot class with a function that accept as many figures you want.
