### ISSUE TITLE
How to update value of the table ?I use function "set",but errors all the time...

### ISSUE THREAD

**Issue by ddl19901201** [jtablesaw/tablesaw#435]

**Comment by lwhite1** [comment]
Sorry you're having trouble, but that's not a very helpful error
description. You have to provide example code and exactly what errors
you're seeing or I need to close this.

**Comment by ddl19901201** [comment]
Here is the error:
The method set(Selection, Column<capture#47-of ?>) in the type Column<capture#47-of ?> is not applicable for the arguments (Selection, double),
here is my code :
Selection condition = pflasset.numberColumn("l_portfolio_no").isEqualTo(l_portfolio_no_p)
        			 .and(pflasset.stringColumn("c_portfolio_type").isEqualTo(c_portfolio_type_p)
        			 .and(pflasset.numberColumn("l_date").isEqualTo(l_date_p))) ;
        	 
        	 pflasset.numberColumn("en_td_share_in").set(condition, en_amount_p );

**Comment by ddl19901201** [comment]
Sorry ,i figure it out,
code like this works well, but i don't know why....
FloatColumn dC = pflasset.floatColumn("en_td_share_in");
        	Float fTempshare = (float) (Float.valueOf(tableOfasset.get(0, 0).toString())+en_amount_p);
        	
        	dC.set(condition,fTempshare);

**Comment by lwhite1** [comment]
Here's my best guess.  In the first example I think you should have written:
```
pflasset.floatColumn("en_td_share_in").set(condition, en_amount_p );

```
Assuming "en_td_share_in" is a FloatColumn, and you converted en_amount_p to a float. The error message says it's a double. You can't put a double in a FloatColumn.

In the working example, I would have used the column's type-specific get() method. Every column has a version of get() that returns the correct type. Or I would have been specific and used getFloat(), but for either you have to get the column as a FloatColumn.

Doing that should let you avoid all that string manipulation. If you declare en_amout_p as a float to begin with, you could skip that cast as well.   

```
FloatColumn dC = pflasset.floatColumn("en_td_share_in");
Float fTempshare = tableOfasset.floatColumn("columnName").get(0) + (float) en_amount_p;
dC.set(condition, fTempshare);

```
