### ISSUE TITLE
default to fat columns

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#437]
@benmccann 
What do you think about my adjusting the CSV reader code to use wider columns by default and including a **narrowColumns** flag for when people really need to conserve space? This would make it easier for newbies and casual users, but still let people do big jobs when needed.

By fat columns, I mean defaulting to DoubleColumn for floating point and IntColumn for integrals. (I think defaulting to LongColumn would have it's own issues.

TextColumns could also be used only when **narrowColumns** is set to true.

String columns grow their backing data structures as needed so nothing necessary there. 

Thoughts?

**Comment by benmccann** [comment]
Sounds fine to me

**Comment by lwhite1** [comment]
implemented by adding option 

minimizeColumnWidths(boolean b) to options.Builder.
