### ISSUE TITLE
Removing rows which contain null values

### ISSUE THREAD

**Issue by rahabwairimu05** [jtablesaw/tablesaw#440]
Is there a simpler way to remove the rows that contain null & empty values in a huge data set apart from looping through the entire data set?

**Comment by lwhite1** [comment]
Table has a method that returns a copy of the table containing only those records that have no columns with missing values:

     public Table dropRowsWithMissingValues() {...

**Comment by rahabwairimu05** [comment]
Thank you Larry. I must have missed that.

**Comment by rahabwairimu05** [comment]
A huge concern is actually the fact that the nulls are not recognized in this function  (dropRowsWithMissingValues()), when I run the function in the table, the resulting table still have rows with nulls. but when I  use (removeColumnsWithMissingValues())  columns containing null are removed. Advise on this? The nulls are just printed as empty spaces in my console

**Comment by lwhite1** [comment]
How do the nulls get into the table? 
When a table is loaded from a CSV file, empty cells should be replace with whatever the definition of MISSING_VALUE is for the specific column type. AFAICR, only Text columns can have nulls in them because all the other column types use primitives.

**Comment by rahabwairimu05** [comment]
Basically, before even loading the CSV using table saw function , the NaNs are represented as "NA" in the data set. 
Table HousePrices_Train  = Table.read().csv("DataSets/HousePrices.csv");
But if I print the last rows and the contain null in the console, they are just empty. Is there anything I am missing out ?
I have also tried loading the dataset using the following approach
Table HousePrices_Train = Table.read().csv(CsvReadOptions
		    .builder("DataSets/HousePrices.csv")
		    .missingValueIndicator("NA"));
But still no success.

**Comment by lwhite1** [comment]
If this data is not proprietary and not huge, can you attache it? If it is big, can you drop a small subset that includes some lines with missing values that aren't going away?

**Comment by rahabwairimu05** [comment]
[Hse Price data.zip](https://github.com/jtablesaw/tablesaw/files/2774477/Hse.Price.data.zip)
There is a sample of the data set. Record 2, has a Na at Alley Column

**Comment by lwhite1** [comment]
In this sample, there don't seem to be any rows with values for all columns, so the second println() below displays an empty table.  The first println() displays 20 lines as expected. 

```
        Table test = Table.read().csv(
                CsvReadOptions.builder("../HousePrices.csv")
                        .missingValueIndicator("NA")
                        .build());
        Table result = test.dropRowsWithMissingValues();
        System.out.println(test.print(20));
        System.out.println(result.print(20));
```
Are you assigning the result of the .dropRows call to a new table and working with that?

**Comment by rahabwairimu05** [comment]
Thank you , the problem is with assigning the result to a new table. I was just calling the function against the table and then printing the table later.
