### ISSUE TITLE
Some unit tests fail on Windows 

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#441]
We need someone with a Windows machine who can fix and test this issue. Help would be greatly appreciated.

**Comment by lwhite1** [comment]
Notes on the various errors. Comments follow each error message. I'm not sure which one was fixed. 

**First Error**
```
testSortOn(tech.tablesaw.api.DateColumnTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalStateException: Column prefix: D is unknown.
	at tech.tablesaw.api.Table.sortOn(Table.java:484)
	at tech.tablesaw.api.DateColumnTest.testSortOn(DateColumnTest.java:154)
[...]
```
This error suggests that the column names were not read correctly.  The sort routine can't find a column that matches the one specified in the request:

        Table sorted = unsorted.sortOn("Date");
so it drops into the code that looks for a + or - sign prepended to the name. It gets the D from Date because there is no prepended sign. 

Looking at the test code, it's hard to see how the name could be read incorrectly since it's the first column and the delimiting comma follows immediately. 

```
        Table unsorted = Table.read().csv(
                "Date,1 Yr Treasury Rate" + System.lineSeparator()
```
A quick check showed no invisible characters in the header string.

**Second and Third Error**
```
testLocalDateDetectionEnglish(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionEnglish(CsvReaderTest.java:170)
[...]
```
```
testLocalDateDetectionFrench(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[LOCAL_DATE]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at tech.tablesaw.io.csv.CsvReaderTest.testLocalDateDetectionFrench(CsvReaderTest.java:227)
[...]
```
These two errors have the same cause. In both cases we should see an array containing the columnType LOCAL_DATE, but the array is empy. (I think we'd see the word null printed if there was a null value. 
This seems like it might be related to the cyclic relationship issue, except that other manifestations throw an NPE reading the ColumnType array rather than completing and returning the wrong result. 

The code below suggests that can't be the issue, because the return value of detectedType is tested on the next line for equality so it isn't null. The method returns an array constructed on the last line so it executes to completion. Best guess is that the table is parsed incorrectly so that the entire thing is read as the header (which is skipped), no lines are passed to the type detector and the method returns without really doing anything. That gets us back to some kind of parsing error.

```
        for (List<String> valuesList : columnData) {
            ColumnType detectedType = detectType(valuesList, options);
            if (detectedType.equals(StringColumnType.STRING) && rowCount > STRING_COLUMN_ROW_COUNT_CUTOFF) {
                HashSet<String> unique = new HashSet<>(valuesList);
                double uniquePct = unique.size() / (valuesList.size() * 1.0);
                if (uniquePct > STRING_COLUMN_CUTOFF) {
                    detectedType = TEXT;
                }
            }
            columnTypes.add(detectedType);
        }
        return columnTypes.toArray(new ColumnType[0]);

```

**Fourth Error**
```
testReadFailure2(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.IllegalArgumentException: Column Test is not present in table read_failure_test2.csv
	at tech.tablesaw.api.Table.columnIndex(Table.java:278)
	at tech.tablesaw.table.Relation.shortColumn(Relation.java:430)
	at tech.tablesaw.io.csv.CsvReaderTest.testReadFailure2(CsvReaderTest.java:392)
[...]
```
This has the same underlying cause as the first error, I think. This time the code reads the table from a file with comma delimiters separating columns, but somehow it fails to create the first column. Could we be getting errors on windows reading commas?  

**Fifth Error**
```
test_JavaBehaviour(tech.tablesaw.io.csv.UnicodeBomHandlingTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<ï»¿1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.csv.UnicodeBomHandlingTest.test_JavaBehaviour(UnicodeBomHandlingTest.java:34)
[...]
```
This is a unicode bom error, so it's a different Windows disease from the line ending issue.

**Sixth Error**
```
html(tech.tablesaw.io.DataFrameWriterTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...></td></tr>
</tbody>[]
> but was:<...></td></tr>
]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at tech.tablesaw.io.DataFrameWriterTest.html(DataFrameWriterTest.java:58)
```
I can't tell which test is failing, and the expected results don't look like they could be produced by either test.

**Comment by paulk-asert** [comment]
I looked at one of the test failures. Windows inserts a BOM for UTF-8 files:
```
   Structure of read_failure_test2.csv   
 Index  |  Column Name  |  Column Type  |
-----------------------------------------
     0  |      ï»¿Test  |        SHORT  |
     1  |        Month  |        SHORT  |
     2  |      MonthId  |      INTEGER  |
     3  |            A  |       STRING  |
     4  |            B  |       STRING  |
     5  |            C  |       STRING  |
     6  |            D  |       STRING  |
     7  |            E  |       STRING  |
     8  |            F  |       STRING  |
     9  |            G  |       STRING  |
    10  |            H  |       STRING  |
    11  |            I  |       STRING  |
    12  |            J  |       STRING  |
```
It is present in the file:
```
$ head read_failure_test2.csv | hd
00000000  ef bb bf 54 65 73 74 2c  4d 6f 6e 74 68 2c 4d 6f  |...Test,Month,Mo|
...
```
You seem to have an unused BOM class in UnicodeBomHandlingTest. Did you have plans for BOM handling in production code somewhere?
You probably want something like what we do in Groovy:
https://github.com/apache/groovy/blob/master/src/main/java/org/codehaus/groovy/control/io/FileReaderSource.java#L57

**Comment by paulk-asert** [comment]
Running this test in the GroovyConsole:
```
@Grab('tech.tablesaw:tablesaw-core:0.34.1')
import tech.tablesaw.api.*

rows = Table.read().csv('/path/to/read_failure_test2.csv')
println rows.columnNames()[0]
rows = Table.read().csv(new File('/path/to/read_failure_test2.csv').newReader())
println rows.columnNames()[0]
```
yields:
```
ï»¿Test
Test
```

**Comment by lujop** [comment]
I've I had some time I will try to help.
Because I encountered this working on a PR while verifying tests that there are about 20 that fail.
