### ISSUE TITLE
Setting Marker Color Doesn't Work

### ISSUE THREAD

**Issue by lewisdawson** [jtablesaw/tablesaw#444]
Looking at the output HTML/JavaScript, the marker color value isn't rendered properly:

![image](https://user-images.githubusercontent.com/5010504/51515664-6dd7c500-1dc9-11e9-97a1-8a65f22b11df.png)

**Comment by lwhite1** [comment]
fixed

**Comment by benmccann** [comment]
I've released a new version with this fix
