### ISSUE TITLE
Unused variables in HistogramTrace

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#448]
The value of the field HistogramTrace.HistogramBuilder.barMode is not used	HistogramTrace.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/traces	line 74
The value of the field HistogramTrace.HistogramBuilder.histFunction is not used	HistogramTrace.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/traces	line 75
The value of the field HistogramTrace.HistogramBuilder.histNorm is not used	HistogramTrace.java	/tablesaw-jsplot/src/main/java/tech/tablesaw/plotly/traces	line 76

**Comment by lwhite1** [comment]
fixed
