### ISSUE TITLE
Capability to export table to json format

### ISSUE THREAD

**Issue by DareUrDream** [jtablesaw/tablesaw#450]
Currently DataFrameWriter only supports csv and html. Any plans for Capability to export table to json format ?

**Comment by benmccann** [comment]
Actually, I'll leave the read and write as separate tickets. I'm about to add support for reading JSON, so will close the reading ticket and leave this one open.

Reading JSON will support both reading arrays of arrays and arrays of objects. What format would you want the table to be exported as? I'm less certain that it makes as much sense to support output to JSON because there's so many potential formats that a user might want

**Comment by lwhite1** [comment]
Without looking into it, I would assume that as is the case with CSV files, handling character escaping is kind of a dark art. My guess is a safer route is to use a reputable library that does JSON encoding and pass it strings

**Comment by benmccann** [comment]
Ok. I've added this. You can do this calling `table.write().json()`.  You can also output the data as an array or arrays with or without a header row by changing various options.  The default matches your output

**Comment by DareUrDream** [comment]
Awesome. Thanks

Cheers !!
DareUrDream

**Comment by bharathmurs** [comment]
Hey @benmccann, When i do write().json() all date columns are being printed as 
`"dueDate": {
                                    "year": 2018,
                                    "month": "OCTOBER",
                                    "chronology": {
                                        "id": "ISO",
                                        "calendarType": "iso8601"
                                    },
                                    "dayOfMonth": 10,
                                    "dayOfWeek": "SATURDAY",
                                    "era": "CE",
                                    "dayOfYear": 283,
                                    "leapYear": false,
                                    "monthValue": 10
                                }`
is there a way to flatten this out? Like `10-10-2018`
Thanks.

**Comment by benmccann** [comment]
Recommend creating a new column with this computed value

**Comment by jjbursik** [comment]
@benmccann what version is write().json() available in?  I'm trying 34.2 and not finding it?

**Comment by lwhite1** [comment]
I suspect you need to import the json sub-project.  if that doesn't work,
let me know.

**Comment by jjbursik** [comment]
```
    compile group: 'tech.tablesaw', name: 'tablesaw-core', version: '0.34.2'
    compile group: 'tech.tablesaw', name: 'tablesaw-json', version: '0.34.2'
```

Both packages are imported however no write().json() option.

**Comment by lwhite1** [comment]
I've never used it, but these test methods could provide some guidance, perhaps.

```
  @Test
  public void arrayOfArraysWithHeader() throws IOException {
    String json =
        "[[\"Date\",\"Value\"],[1453438800000,-2.144],[1454043600000,-2.976],[1454648400000,-2.9541]]";
    Table table = Table.read().string(json, "json");
    StringWriter writer = new StringWriter();
    table
        .write()
        .usingOptions(JsonWriteOptions.builder(writer).asObjects(false).header(true).build());
    assertEquals(json, writer.toString());
  }

  @Test
  public void arrayOfArraysNoHeader() throws IOException {
    String json = "[[1453438800000,-2.144],[1454043600000,-2.976],[1454648400000,-2.954]]";
    Table table = Table.read().string(json, "json");
    StringWriter writer = new StringWriter();
    table
        .write()
        .usingOptions(JsonWriteOptions.builder(writer).asObjects(false).header(false).build());
    assertEquals(json, writer.toString());
  }

  @Test
  public void arrayOfObjects() {
    String json =
        "[{\"a\":1453438800000,\"b\":-2.144},{\"a\":1454043600000,\"b\":-2.976},{\"a\":1454648400000,\"b\":-2.954}]";
    Table table = Table.read().string(json, "json");
    String output = table.write().toString("json");
    assertEquals(json, output);
  }

````

**Comment by lwhite1** [comment]
should have left this closed, i guess. Closing again

**Comment by malaccan** [comment]
this is a little late, but am responding with my comments on the issue raised by @jbursik 

i assume the code `write().json()` relates to `table.write().json()` - which is what we normally use for csv. looking at the latest code (for v0.43.1), it looks like DataFrameWriter hasn't been updated for this json support.

it would be great to have this json() method added to DataFrameWriter, as it would be a more intuitive usage (and less boiler plate code).

so the way to output to json without DataFrameWriter, is to import tablesaw-json-0.43.1.jar first, and making the write calls yourself using the JsonWriter class.

```
import tech.tablesaw.api.Table;
import tech.tablesaw.io.Destination;
import tech.tablesaw.io.json.JsonWriter;
import java.io.StringWriter;

Table table = Table.create("some table"); // ie: your table
JsonWriter jsonWriter = new JsonWriter();
StringWriter writer = new StringWriter();
jsonWriter.write(table, new Destination(writer));
String jsonString = writer.toString();
System.out.println(jsonString);
```

this should output the json string to console.
