### ISSUE TITLE
Importing db via SQLite?

### ISSUE THREAD

**Issue by samdarcy42** [jtablesaw/tablesaw#451]
Hello, I am attempting to create a Table from a local db using the documentations example: 

   
       String url = "jdbc:sqlite:" + db;

       Connection conn = DriverManager.getConnection(url);

        try (Statement stmt = conn.createStatement()) {
             String sql = "SELECT * FROM " + table;

        try (ResultSet results = stmt.executeQuery(sql)) {
             entries = Table.read().db(results, table);
        }

With db being the file path to my local db. I am receiving the following error: java.sql.SQLFeatureNotSupportedException
at org.sqlite.jdbc4.JDBC4ResultSet.getObject(JDBC4ResultSet.java:339)

After doing some research my inclination is to assume it is due to my jdbc driver not having the feature necessary to create a Table object. Is Tablesaw compatible with sqllite db's? Am I using an incorrect jdbc driver? Any help would be greatly appreciated!

**Comment by lwhite1** [comment]
I don't know of anyone using SQLite, but the error indicates that the JDBC driver you're using doesn't support `getObject()`. Is there a newer (or more complete) driver you could try?

**Comment by benmccann** [comment]
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java#L339

**Comment by benmccann** [comment]
Thhe untyped version is in the superclass: https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L610

Maybe you can send them a PR to implement it in `JDBC4ResultSet.java` simply by calling `type.cast(super.getObject(columnIndex))`? 

You should be able to use the sqlite driver today with numbers. It's dates and strings where `getObject` would be called. I'm not sure how sqlite handles `Date` support or if that's something you need.  I only saw:
```
    public static final int SQLITE_INTEGER    =  1;
    public static final int SQLITE_FLOAT      =  2;
    public static final int SQLITE_TEXT       =  3;
    public static final int SQLITE_BLOB       =  4;
    public static final int SQLITE_NULL       =  5;
```
But I'm guessing that it's currently failing on reading a `String`. In which case you should be able to patch the driver pretty easily

**Comment by lwhite1** [comment]
I'm closing this as it seems very likely to be a SQLite driver issue.
