### ISSUE TITLE
What is `out()`?

### ISSUE THREAD

**Issue by garretwilson** [jtablesaw/tablesaw#453]
I'm trying to get started with the tutorials. Starting at https://jtablesaw.github.io/tablesaw/gettingstarted I'm already perplexed by the first code snippet:

```java
double[] numbers = {1, 2, 3, 4};
DoubleColumn nc = DoubleColumn.create("Test", numbers);
out(nc.print());
```

What is `out()`? Is that a special Tablesaw method, requiring some special static import? Or is it a typo for `System.out.println()`? Or is this pseudocode?

I looked for a demo program that would have imports, which would give me the answer without needing to file a ticket. I really recommend a demo program. Where can I find one?

**Comment by garretwilson** [comment]
Oh, so after I find the superscript, it leads me to a footnote saying:

> The method shown does not actually “produce” any output For that you would call `System.out.println()`. For brevity, this “faux” output will be shown indented by one tab beneath the code that produced it.

Ah, so this was pseudocode? But why? Why not just use `System.out.println()` so the first code snippet will actually work?

I hope you find this ticket useful as an illustration of what a new user encounters when trying to use the library. I mean this to be constructive. I'm actually really excited to try out this library.

**Comment by lwhite1** [comment]
The example code usually inherits from a class called AbstractExample which
implements a method called out(). It makes the code less cluttered. It is
difficult to write code that's legible in markdown because of the limited
control you get over font size and line width.

If I'm doing actual analytic work, I also usually write out() so I don't
have to keep typing System.out.println().

If you would like to improve the documentation we would love the help.

**Comment by garretwilson** [comment]
> If you would like to improve the documentation we would love the help.

Believe me, I'm actually dying to help, if this library is what I'm looking for. Please take this all as constructive, even though it is frustrating.

But I'm majorly stuck at #454 — I can't get anything to work. Just a simple little demo I could run would be soooooooo helpful.

**Comment by garretwilson** [comment]
> The example code usually inherits from a class called AbstractExample which implements a method called out().

Fine, but it turns out that `AbstractExample` doesn't even seem to be part of the dependency! To get that to work, I actually have to clone the repository and get the test file. (Tip: you could provide a [test jar](https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html) on Maven Central. Maybe you do already; I haven't checked yet.)

If a new user is wanting to get up to speed quickly, they expect to use the examples as they are given, using only the dependency JARs indicated, especially when the readme says:

> Second, you need to add the dependency to your pom file. It’s available on Maven Central.
> …
> That’s it for setup.

When they find out that this _isn't_ "it" for setup, might be frustrating. 😃

**Comment by benmccann** [comment]
Since there's only one place the docs where we use `out()` it might be easier to replace it with `System.out.println` and remove the footnote

**Comment by garretwilson** [comment]
Thanks again for being so attentive and addressing this so quickly.
