### ISSUE TITLE
Major problems trying out plots; everything breaks.

### ISSUE THREAD

**Issue by garretwilson** [jtablesaw/tablesaw#454]
Maybe I'm looking in the wrong place, but it doesn't seem like there is sufficient information for a newcomer to get plotting working—and this is the main reason I'm looking at this library.

1. First of all, a suggestion: the page https://jtablesaw.github.io/tablesaw/userguide/introduction says nothing at all about the dependency needed for plotting. One has to know to look back at https://github.com/jtablesaw/tablesaw to figure this out. But this is a minor issue.

2. Much bigger is that the first code at https://jtablesaw.github.io/tablesaw/userguide/Introduction_to_Plotting does not work. Not even close. It won't even compile. It doesn't even have balanced parentheses. Fixing the parentheses still won't get it to compile, and certainly won't show the plot that was promised.

```java
Figure fig = BubblePlot.create("Average retail price for champagnes by year and rating",
                champagne,					// table name
                "highest pro score",		// x variable column name
                "year",						// y variable column name
                "Mean Retail"				// bubble size
               ));
```

3. So I skip the "introduction" page and go straight to the "real" code at https://jtablesaw.github.io/tablesaw/userguide/BarsAndPies .

> First we load the Tornado dataset:

```java
Table tornadoes = Table.read().csv("Tornadoes.csv");
```

What is "the Tornado dataset" and where can I find it? An earlier paragraph mentioned, "we’ll use a Tornado dataset from NOAA", so I went to the [NOAA site](https://www.spc.noaa.gov/wcm/) and downloaded the most promising looking data file named `1950-2017_all_tornadoes.csv`. I tried loading that in Tablesaw:

```
…
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 10000 out of bounds for length 10000
	at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:327)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:176)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:560)
	... 7 more
```

(So you are using the uniVocity parsers. I'm familiar with them. But they aren't so "plug-and-play" as they make them out to be, as you can see here.)

I searched the web for "Tornadoes.csv". One unrelated site implied that `2018_torn_prelim.csv` might be more promising, but that didn't work. https://gist.github.com/darrenjaworski/5874227 mentioned a `tornadoes.csv`, and it was some Google spreadsheet, which I downloaded to a CSV file, but that gave me:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot add column with duplicate name Short column: state number to table tornadoes.csv
	at tech.tablesaw.api.Table.validateColumn(Table.java:161)
	at tech.tablesaw.api.Table.addColumns(Table.java:144)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:147)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
	…
```

I finally realized you that this GitHub repository has some "tornado" CSV files. I downloaded and renamed `tornadoes 1950-2014.csv`, but no go:

```
Exception in thread "main" tech.tablesaw.io.csv.AddCellToColumnException: Error while adding cell from row 41658 and column Crop Loss(position:10): Error adding value to column Crop Loss: For input string: "0.4"
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:244)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:156)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
	…
Caused by: java.lang.NumberFormatException: Error adding value to column Crop Loss: For input string: "0.4"
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:353)
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:27)
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:242)
	... 5 more
```

This is frustrating. This is what a new user is faced with.

If this turns out to be a good library, believe me I'll pitch in and help with the documentation and probably even the code. But I'm stuck just in the first lines! Could someone help me?

**Comment by lwhite1** [comment]
The jsplot example code was moved last week so please work with Master for this. 

In the test source code under the jsplot project, you can find examples that compiles and runs.  This one does the a bunch of scatterplots including the champaigne example:

```
package tech.tablesaw.examples;

import tech.tablesaw.api.Table;
import tech.tablesaw.plotly.Plot;
import tech.tablesaw.plotly.api.BubblePlot;
import tech.tablesaw.plotly.api.Scatter3DPlot;
import tech.tablesaw.plotly.api.ScatterPlot;

public class ScatterVisualizations extends AbstractExample {

    public static void main(String[] args) throws Exception {

        Table wines = Table.read().csv("../data/test_wines.csv");
        out(wines);
        out(wines.structure().printAll());
        out(wines.column("varietal").unique().print());
        out(wines.column("region").unique().print());
        out(wines.column("wine type").unique().print());

        wines.column("year").setName("vintage");

        Table champagne =
                wines.where(
                        wines.stringColumn("wine type").isEqualTo("Champagne & Sparkling")
                            .and(wines.stringColumn("region").isEqualTo("California")));

        Plot.show(ScatterPlot.create("Champagne prices by vintage", champagne, "mean retail", "vintage"));

        Plot.show(BubblePlot.create("Average retail price for champagnes by vintage and rating",
                champagne,
                "highest pro score",
                "vintage",
                "Mean Retail"));

        Plot.show(BubblePlot.create("Average retail price for champagnes by vintage and rating",
                champagne,
                "highest pro score",
                "vintage",
                "Mean Retail",
                "appellation"));

        Plot.show(Scatter3DPlot.create("Average retail price for champagnes by vintage and rating",
                champagne,
                "highest pro score",
                "vintage",
                "Mean Retail",
                "appellation"));

        Plot.show(Scatter3DPlot.create("Highest & lowest retail price for champagnes by vintage and rating",
                champagne,
                "vintage",
                "highest retail",
                "lowest retail",
                "highest pro score",
                "appellation"));

        Plot.show(Scatter3DPlot.create("Average retail price for champagnes by vintage and rating",
                champagne,				    // table
                "highest pro score",  	// x
                "vintage", 			// y
                "Mean Retail")); 		// z

        Plot.show(ScatterPlot.create("Wine prices and ratings", wines, "Mean Retail", "highest pro score", "wine type"));

        Plot.show(Scatter3DPlot.create("Champagne (prices, ratings, vintage, appellation) ",
                champagne,
                "vintage",
                "highest pro score",
                "mean retail",
                "appellation"));
    }
}

```

Similarly, in the core project, under test, there is a class called TornadoExample. This also works.

**Comment by garretwilson** [comment]
> Similarly, in the core project, under test, there is a class called TornadoExample. This also works.

Yeah, but the `TornadoExample` is about rewriting CSV files, not about plotting, and I'm trying to get the simplest of simplest examples at https://jtablesaw.github.io/tablesaw/userguide/BarsAndPies.html working.

The good news is that by examining `TornadoExample` I found that there is a CSV file that works: `tornadoes_1950-2014.csv`. (I had tried `tornadoes 1950-2014.csv` but not `tornadoes_1950-2014.csv`. All those file are really confusing—and someone even accidentally committed a backup file of one.)

And (drumroll) … the `HorizontalBarPlot` demo on https://jtablesaw.github.io/tablesaw/userguide/BarsAndPies.html now works! Woohoooo! How exciting!

OK, thanks for the pointers. Let me see how much further I can get with this.

**Comment by benmccann** [comment]
It looks like the file with space in the name has an extra column compared to the one with the underscore. I've removed the backup file.

**Comment by benmccann** [comment]
It's tricky to know if the docs are broken since they're not compiled. We should probably make sure to put pointers to the example code as being a potentially more reliable source

**Comment by lwhite1** [comment]
@garretwilson. There is example code in the jsplot examples folder for doing bar and pie charts also. I just gave you the champaign bubble plot because that was the first snippet of code you pasted in this issue.

**Comment by benmccann** [comment]
The tornadoes file with the space in the name was unused, so I've deleted it as well

**Comment by benmccann** [comment]
Here's a PR for a couple other changes: https://github.com/jtablesaw/tablesaw/pull/455

**Comment by garretwilson** [comment]
I am on Windows indeed: Windows 10 64-bit.

**Comment by garretwilson** [comment]
I do notice now that the tornadoes file is using `CRLF` (the "default" on Windows), while my file is using `LF`. I'm guessing that there was a bug that "assumed" `CRLF`? Oh, the multitude of problems ([JGit `.gitattributes`](https://bugs.eclipse.org/bugs/show_bug.cgi?id=342372) is just one example) this debacle has caused for decates. Was this part of the tablesaw lookahead "guesswork" that it does, I suppose? Because I'm pretty sure uniVocity is fine with `LF` or `CRLF` (as it should be).

Yep, sure enough! I changed my line endings to `CRLF` and it parsed the file.

This is a pretty big bug. (And on another day I will discuss the decision to consider column names on a case-insensitive basis—that's just asking for trouble—just like the mountains of trouble Windows has caused by choosing to have a case-insensitive filename OS. But I don't want to get off topic here.) I would recommend you release a new version as soon as possible.

OK, I'll keep plodding along here.

**Comment by garretwilson** [comment]
It would be rough today; I've spent extra hours on this, and I need a break. But the more important question: did you make a unit test for this with two test files, one with `LF` and other other with `CRLF`?

**Comment by benmccann** [comment]
There may be a test for that already, but I've created one just in case https://github.com/jtablesaw/tablesaw/pull/456. I'll let Larry weigh in on whether it's a new test or we already had one

**Comment by garretwilson** [comment]
I'm going to call today a success. I managed to create both a sum and an average horizontal bar chart for real data that I produced in a CSV file of over 4 million rows as input forTablesaw. The resulting chart seems to be what was expected. So I was successful in proving it worked, and I'm really excited about the possibilities of using Tablesaw!

I'm really impressed and appreciative with how quick you both got back to me on the problems I faced today. I hope to go forward and see what I can do with Tablesaw. Currently my code has a lot of things taped together just to get everything to function, so tomorrow I can take a breath, tidy up what I have now, and then go forward.

I guess you can close this ticket if you like, as I am now over the hump of everything breaking straight out of the box.

Thanks again.

**Comment by lwhite1** [comment]
Opened an issue for removing code from documentation. #457.
Closing this one.

**Comment by benmccann** [comment]
I've released a new version with the line ending bug fix
