### ISSUE TITLE
How to filter table or update rows based on another column

### ISSUE THREAD

**Issue by DareUrDream** [jtablesaw/tablesaw#460]
How to filter table or update rows based on another column ? I have situation where I want to perform join only when another column in the table has a specific value. 

Cheers !!

**Comment by lwhite1** [comment]
I don't understand exactly what you're trying to accomplish when it comes to filtering. A standard inner join will only join records where both tables have the join column(s) values in common. 

If you're saying you only want to join tables A and B when A has certain values in a column that's not the join column, you can filter A first into a temp table and join that with B. 

To update rows selectively, you can use a version of set(), defined on columns, that takes a selection as a parameter. For example, this replaces the value 999 in the age column with the missingValueIndicator for that column:

```
        age.set(age.isEqualTo(999), DoubleColumnType.missingValueIndicator());

```

**Comment by DareUrDream** [comment]
But then how do I filter table A into a temp table such that column X in A
has a specific value.

Cheers !!
DareUrDream

**Comment by benmccann** [comment]
https://jtablesaw.github.io/tablesaw/userguide/filters.html
