### ISSUE TITLE
Creating Table with columns of different sizes defaults size to smallest array.

### ISSUE THREAD

**Issue by rosenjcb** [jtablesaw/tablesaw#463]
So I have a few ArrayLists that I fill with data and later return as arrays. I then use those to create columns for a table. Problem is that some ArrayLists are not filled at all (WIP and essentially placeholder columns until I do some transformations later on). This results in a table with zero rows. The only way I was able to catch this was by reading the documentation.

"All columns in the table must have the same number of elements, although missing values are allowed."

Proposed Solution:
Throw an exception when you try to pass columns of different values and specify which columns conflict. If that's not acceptable, then at least note this in the documentation. I was only able to infer this bug from the statement above. The documentation should at least state the bug explicitly like, "If the columns are of different sizes, then the table will have rows equal to the smallest column size."

**Comment by benmccann** [comment]
Or maybe we should fill the smaller columns with empty cells to match the size of the largest column? I agree the current behavior might not be intuitive

**Comment by rosenjcb** [comment]
@benmccann Should I go about and make a pull request then? I think that shouldn't be too trivial to do.

**Comment by benmccann** [comment]
I would want @lwhite1 's opinion as well

**Comment by lwhite1** [comment]
I worry that it would make it harder to detect coding errors where you
think all of the columns are the same size, but they’re not. Your analysis
is hosed but you can’t tell.

My preferred solution I think would be to throw an exception if not all the
columns are the same size (on addColumns) and provide a new method that
works like addColumns but explicitly fills any short columns with missing
value.

How does that sound?

**Comment by rosenjcb** [comment]
@lwhite1 I was looking at how Pandas and Spark might handle creation of dataframes with different row/column lengths and it looks like Pandas definitely does throw an error if the length doesn't match the index:
`ValueError: Length of values does not match length of index | Pandas DataFrame.unique()`

I don't know what Spark does I'm thinking it throws some equivalent error. I think this is preferred because the last thing I want to see are null and zero values being passed to my rows without me knowing (and only to find out when the data doesn't look right).

**Comment by benmccann** [comment]
Throwing an exception sounds fine to me

**Comment by lwhite1** [comment]
i will take care of it.

**Comment by lwhite1** [comment]
fixed
