### ISSUE TITLE
Best way to create a column by existing columns

### ISSUE THREAD

**Issue by homura** [jtablesaw/tablesaw#464]
I want to do something like this

```SQL
  select (column1 + column2 + column3 ) from X
```

Now I implement it in this way

```java
DoubleColumn c1;
DoubleColumn c2;
DoubleColumn c3;

var iter = c1.iterator();
var iter = c2.iterator();
var iter = c3.iterator();

List<Double> list = Lists.newArrayList();
while(c1.hasNext()) {
  var d1 = c1.next();
  var d2 = c2.next();
  var d3 = c3.next();

  list.add(d1 + d2 + d3);
}

```

Is there a simple way to create a new column like   
```java
Table.addColumnByExsitingColumns(
  "column1",
  "column2", 
  "column3", 
 (Double c1, Double c2, Double c3) -> ... )
```

**Comment by lwhite1** [comment]
You can use the add method

DoubleColumn c4 = c1.add(c2.add(c3));

This adds every element in c2 to the corresponding element in c3, and adds
the resulting column to c1;

If you want, you can put the result into a table using Table's addColumns()
method.

t.addColumns(c4);
