### ISSUE TITLE
NoClassDefFoundError when using Tablesaw jars

### ISSUE THREAD

**Issue by Awatif** [jtablesaw/tablesaw#465]
Hi 
I tried to import data from a CSV file and it keeps giving me a runtime error:
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable

Then I thought to use static data, to check if I will get the same error:
 I tried to run this simple code "from the online guide":

```
String[] animals = {"bear", "cat", "giraffe"};
double[] cuteness = {90.1, 84.3, 99.7};
Table cuteAnimals = Table.create("Cute Animals").addColumns(StringColumn.create("Animal types", animals),DoubleColumn.create("rating", cuteness));
```

I am using Eclipse as IDE+ Not maven project but I have added jars(tablesaw-jsplot-0.30.4   +    tablesaw-core-0.30.4  + tablesaw-smile-0.12.0)

the error appears at the line where I used Table.....;

**Comment by benmccann** [comment]
How did you add the jars? It looks like you did not add the jars of the dependencies

The other possibility would be that you added other libraries and one had a conflicting version of a dependency

**Comment by lwhite1** [comment]
The tablesaw-smile project is no longer supported. It may contain references that break things.

**Comment by benmccann** [comment]
Oh, good catch. I didn't notice `tablesaw-smile` was being imported. Yes, that definitely should be avoided

Use `smile-core` directly. You can use Smile in the latest versions by calling `table.smile()`: https://nbviewer.jupyter.org/github/benmccann/nbviewer-test/blob/master/Tablesaw.ipynb

**Comment by Awatif** [comment]
Thank you guys for your reply,
Unfortunately, it did not work :(

When I created another maven project it does work, but I was hoping to have it within the actual project that I am working on


Thank you again for your quick answer and support

**Comment by lwhite1** [comment]
If you need to work with jars, you might try creating a shaded tablesaw
core jar that would include all of its dependencies. Tablesaw core has the
shade plugin so you could probably do it with maven pretty easily.

otherwise you could try debugging by looking at at the maven dependency
tree.


   1. mvn dependency:tree -Dverbose -Dincludes=commons-collections

**Comment by lwhite1** [comment]
I'm going to close this as we don't really support using Jars directly. Using Jar files is often very difficult which is why we use maven.

**Comment by lwhite1** [comment]
oddly enough. I'm now getting the same error trying to compile from within Idea. It's probably a system configuration thing on my part, but the timing is odd.

**Comment by lwhite1** [comment]
and oddly enough, my issue seems to have gone away on it's own after making and reverting some POM changes. Closing again. Hopefully for good.
