### ISSUE TITLE
[Announcement] Advanced regression kaggle kernel using tablesaw

### ISSUE THREAD

**Issue by cnuernber** [jtablesaw/tablesaw#472]
https://github.com/cnuernber/ames-house-prices/blob/master/ames-housing-prices-clojure.md

I apologize this is inappropriate but I wanted to let everyone know that we tested out several different column stores before choosing tablesaw and then buliding an ETL pipeline on top of it.  Tablesaw is rock solid, well designed, and fast.  

Thanks a ton for this project!

**Comment by lwhite1** [comment]
Thanks very much. We really appreciate the positive feedback. Let us know
if you have any issues or questions.

Also very nice to see some JVM love in Kaggle land. :)

--Larry

**Comment by lwhite1** [comment]
closing (to keep our issue count down). Thanks again.
