### ISSUE TITLE
Add set methods to Row class

### ISSUE THREAD

**Issue by owlz84** [jtablesaw/tablesaw#473]
The Row class has getters for the various different column types, allowing a user to iterate through the rows of the table and read out values. Why not add setter methods to complement these?

Example from the docs:

```
for (Row row : aTable) { 
    String s = row.getString("s");			       
    LocalDate d = row.getDate("d");
    System.out.println(s + " happened on " + d);   
}
```

Could then also include:
```
    ...
    row.setDate("d", d.plusDays(1))
    ...
```

I can fork and work on it if it fits with the project's principles?

**Comment by benmccann** [comment]
Seems reasonable to me, but I'd want to get @lwhite1's thoughts as well

**Comment by lwhite1** [comment]
That could be really handy. Have at it.

**Comment by lwhite1** [comment]
Merged. Thanks very much @owlz84
