### ISSUE TITLE
Customise locating templates

### ISSUE THREAD

**Issue by hallvard** [jtablesaw/tablesaw#479]
I would like to support using tablesaw and plotly in offline mode, and this requires replacing page_template.html with one that locates the plotly library using a file location rather than an http url. The Pebble engine locates templates using a Loader, and tablesaw hardcodes using a ClasspathLoader. Instead it should allow specifying a different implementation (several are available), e.g. one that looks in the context (Eclipse workspace) of the files that are in use or something similar. There are also other reasons for wanting to use different templates, so the template locations should be configurable.

One possibility is adding constructors for Component and its sublclasses that takes a Loader argument (or a PebbleEngineFactory, that creates the engine, instead of the static TemplateUtils method).

**Comment by benmccann** [comment]
You may be able to use `File.toURI` to concert to a url: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#toURI()

I'm fine with what you're suggesting, but Larry really knows the jsplot code far better, so I'll defer to him

**Comment by lwhite1** [comment]
Sounds like you're trying to solve two different problems. The plot.ly js file issue could be solved by a simple change to the Page class, and a modification to the template that makes that location a variable to be filled in by the template. 

The second issue is you want to provide a custom template location. Adding a constructor to Component seems painful. You'd have to specify the engine's loader many times if you wanted to use the same loader for every component, (and you probably would). 

What about specifying the Loader in some type of environment object which defaults to the current resource-folder, but which you change for every engine-using-class by setting it one time to something else?

**Comment by hallvard** [comment]
Yes, the plotly.js location can likely be set without using an alternative template. E.g. using 
<script src="{{plotlyJsLocation}}"></script>, adding a plotlyJsLocation property to Page (and to PageBuilder) and calling context.put("figureScript", plotlyJsLocation);

Currently, Component gets its own PebbleEngine and Loader by calling a static method in TemplateUtils during initialization. You'll need some "global" factory instance that creates the Engine and its Loader that can be set before creating a plot (and reset afterwards), some injection mechanism or a way of passing it in during the initialization or when running asJavascript. I'm not sure what's more elegant. Global state isn't nice, but as you say, adding (an argument to) a Constructor is painful.

**Comment by lwhite1** [comment]
You can provide a default, and let people override it by component by adding an additional statement to each builder. Then no one has to bother with loaders if they don't want to override the default, but you could still use templates from multiple locations if you need to. 

I guess if you go that route, than the default doesn't need to be a true "global" since you can just make it the default by initializing it in each builder, but some way to change them all at once would be nice to have. 

I would prefer not to impose dealing with Loader's on a newbie who just wants to plot something. Pebble itself is an implementation detail that should remain hidden as much as possible, since it's nice to use but not the liveliest project.

**Comment by hallvard** [comment]
There's already an implementation of a delegating loader, so it's easy to support a custom Loader (or a Supplier<Loader> of one) in addition to the default one. BTW, does really each component need its own PebbleEngine and Loader? The engine includes a cache, so when new ones are created all the time, it kind of defeats the purpose. If the PebbleEngine is global, then it's easier to allow customising it and its loader (you don't need to introduce a Supplier of it).

If we want to hide details of the Pebble implementation, we could add API just for setting search path locations (prefixes), e.g. setCustomTemplateLocations(String... prefixes). This way, Pebble classes won't contaminate the API.

**Comment by lwhite1** [comment]
closing. Thanks for the enhancements @hallvard
