### ISSUE TITLE
improve html table formatting control

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#494]
The HTML table is pretty basic, but in earlier versions the <table> tag was left off. so that you got just `<thead>` and `<tbody>` sections. This made it possible to set table classes by wrapping the output in <table> elements that included classes, like: 

```
            <table class="table table-hover table-sm">
```
This was at best a partial solution but it made the output more useful. (The current 'fixed' version broke my tables in my current work project, so i will have to replace the table elements using string substitution.)
It would be nice if we could pass classes for the table (at least), and ideally for `<tr>` by column.

**Comment by lwhite1** [comment]
i think i will take a shot at adding a builder option for this that provides some control over the output.

**Comment by benmccann** [comment]
We should probably also make sure we do html escaping. I'm guessing the current code might break if there's something resembling an html tag in one of the cells and there's probably a security issue around the possibility of injecting malicious scripts

**Comment by benmccann** [comment]
It might be nice to allow users to pass an input that allows them to set any attribute on the HTML tag. Maybe we could use something like j2html?

**Comment by benmccann** [comment]
@lwhite1 if you want, I might be able to take a stab at it over the weekend. Don't want to step on your toes if you've already started something though

**Comment by lwhite1** [comment]
If you have time that would be great. I haven't started, and probably won't
unless it's blocking my work work. (For now my users can deal with poorly
formatted tables :)

FWIW, the main use cases I have in order of importance:
1. setting the class attributes of the <table>.
2. setting the class attributes of <td> elements *by column*, so that I can
make all the values in my numeric columns align right.
3. formatting the actual values from numeric columns as we do with printing
to text (so I can make all my doubles have two decimal places).

beyond that setting class attributes of <thead> and <tr> would be nice. I
can imagine wanting to have some rows in bold or whatever... Control over
date formats would be nice.

I can't imagine wanting to handle arbitrary <td> elements, it would
probably be easier to just hand code if that were necessary.

**Comment by benmccann** [comment]
I sent https://github.com/jtablesaw/tablesaw/pull/500 which covers your first two use cases. We'd need another option for the third use case. I'll leave that one for someone else

**Comment by lwhite1** [comment]
@benmccann IDK why i never tried this, but use case 3 is already handled by setting a formatter on the column. It works the same way as for text. 
```
        table.doubleColumn(2).setPrintFormatter(NumberColumnFormatter.fixedWithGrouping(2));
```

**Comment by lwhite1** [comment]
regarding the security issues you mentioned, perhaps we can make escaping an option, with no escaping being the default. That could be a separate effort

**Comment by benmccann** [comment]
It's not just a security issue. It's also a display issue. There's a lot of characters that won't display correctly if not escaped

Anyway, it works correctly now that we're using jsoup to build the html

I think we can close this one since it looks like all the issues raised here have been addressed. Let me know if you have other suggestions
