### ISSUE TITLE
Is there any possibility to develop pandas-like api ? 

### ISSUE THREAD

**Issue by cstfb** [jtablesaw/tablesaw#495]
it will be very nice having pandas-like api to use . it can provide similar experience to pandas.
and it is easy to learn based on knowledge with pandas.
such as DataFrame(), DataFrame.merge/join , DataFrame.groupBy.sum()

**Comment by lwhite1** [comment]
anything is possible, but it's hard to see it happening. It would be an
enormous amount of work.
