### ISSUE TITLE
toString() should be more fault tolerant

### ISSUE THREAD

**Issue by hallvard** [jtablesaw/tablesaw#496]
I'm debugging some code where columns in a table can be of different sizes. To help diagnose the problem I'm printing the table. However, Relation's toString() method, that uses a DataFramePrinter, throws an IndexOutOfBoundsException because the frame.size() is based on the first column's size, while others are shorter. A toString-method should be very careful to not throw exceptions, since it's typically used during debugging. I suggest making DataFramePrinter more fault tolerant when fetching column values, e.g. in line 192:
`data[i][j] = frame.getString(i, j);`

**Comment by hallvard** [comment]
E.g.
`Column<?> col = frame.column(j);
data[i][j] = (col.size() > i ? col.getString(i) : "?");`

**Comment by lwhite1** [comment]
Columns should not be different sizes. It’s a fundamental assumption of the
library. They can be filled with missing values if needed

**Comment by hallvard** [comment]
I agree, but a toString() method should still take care not to throw Exceptions when assumptions aren't
true, since it's often used for debugging.

**Comment by lwhite1** [comment]
That’s a valid point.

I also think it might be worthwhile to add a table method that calls
appendMissing() on every column, then people can use set() methods to
provide non-missing values where needed

**Comment by hallvard** [comment]
You mean a method that makes the column sizes the same (= max of column sizes) by calling appendMissing on the columns that are too short? What should it be called, ensureColumnSizes?

**Comment by lwhite1** [comment]
Actually, i think adding a column to a table with a different row count
should always throw an exception. When you append records to columns to
make the table larger, the columns are of necessity different sizes
temporarily. In my own tablesaw use, I sometimes forget to call
appendMissing() on columns that have no value for the new row.

My suggestion is that maybe a table method called appendMissing() would
append a single missing value to each column, and you could then call set()
to fill in the ones that have values.

I guess an option would be to have appendMissing() have an int param that
specified the number of rows to add, but that may be overkill, since I
suspect appends tend to happen in a loop anyway.

**Comment by hallvard** [comment]
What about **padColumnsWithMissing(int i)**. It adds max i missing values to the columns of this table to make them the same size. If more than i is needed, an **IllegalStateException** is thrown, the idea being that then it is considered a bug that otherwise would be masked. -1 can be used as no limit.

**Comment by benmccann** [comment]
My thought would probably be to throw an exception when adding a column if it's not the same size. But maybe we could also have an `addColumnAndPad` that would add the necessary padding to the column (or table if the column is longer)

**Comment by hallvard** [comment]
The original problem was when columns already in a table end up having different sizes, e.g. due to (bugs in) the process of extending them with new data. If you know this can happen, a method for padding shorter columns with missing values, as suggested above, does make sense. We could still throw an Exception if columns are added to a table and some sizes differ. And perhaps provide a method for padding them to the same size. I'll make a PR that you can comment on.

**Comment by lwhite1** [comment]
for what it's worth, I saw this quote on a blog post about Tablesaw:

> Internally, a data frame (called Table) is a collection of column objects that contain the data. It’s not very easy to add a partial row to the table, you need to manually iterate over all columns and add null values (or call appendMissing()) for all the columns that you don’t have a value for (yet). It would be nicer if the Table has a call appendRow() that would give access to a new, empty row object on which you can call setters.

This is what I was suggesting, but appendRow() is a better name.

**Comment by lwhite1** [comment]
In the interest of making the user experience dead-simple, I think i might also add a column method called setLast(value), that is just:

```
public void setLast(value) {
   set(size() - 1, value); 
}

```
then the whole thing is just:
```
table.appendRow();
col1.setLast(4);
col2.setLast("howdy");
```
etc.

**Comment by hallvard** [comment]
I think I understand now. Instead of adding values to individual columns, you add a whole row of missing values and overwrite. Given the existing fluid api it would make more sense to do something like this (using the existing Row class):
table.emptyRow().setInt("age", 4).setString("name", "Hallvard").append()
This somehow overloads the use of Row, but I prefer preparing the whole row and appending, instead of adding an empty one and "patching".
BTW, I've already been toying with subclasses of Table and Row for a specific set of columns. The subclasses are generated from a list of column names and types. Having an overridable emptyRow method in Table would make it possible to write
table.emptyRow().setAge(4).setName("Hallvard").append()

**Comment by lwhite1** [comment]
@hallvard I don't see the utility of subclasses of Table or Row for a specific set of columns. I must be missing something. Row is essentially zero overhead so there's no performance / memory gain. I'll be interested in seeing what you come up with.  

> table.emptyRow().setAge(4).setName("Hallvard").append()

This looks pretty good. What do you think, @benmccann?

**Comment by hallvard** [comment]
You get a custom and nice api to your table, and hence completion and type-safety. From the list of columns and types I currently generate custom Table and Row subclasses:
- Table column accessors, e.g. getAgeColumn() will be declared as returning IntColumn
- Row methods, e.g. getAge() and setAge(int) correctly typed
- Table.emptyRow() returns the same (custom) Table type
- Table.append(Row) method takes the custom Row type as argument
- Table.rows() gives you an Iterable specialised to the custom row class

**Comment by lwhite1** [comment]
Ooooh.  Nice

**Comment by benmccann** [comment]
I might have `emptyRow` append the new row so that you just have `table.emptyRow().setAge(4).setName("Hallvard")`

**Comment by benmccann** [comment]
I'm very interested in adding more type safety. The nicest I've seen is Spark's Datasets. I like that it can deal with POJO

Would it make sense to do something like `table.addRow(new Person().setAge(4).setName("Hallvard"))`. The benefit of this is that you can then use the `Person` class throughout your code in other places without introducing any dependency on Tablesaw. It'd also be easier to create the Person object code because your IDE can generate a POJO for you or you can use Lombok whereas there's not going to be tooling for extending `Row` in the same way

Internally `addRow` would use reflection to set table columns based on field names. Have to be a bit careful when writing reflection code to keep it fast. Some [tips here](https://stackoverflow.com/questions/19557829/faster-alternatives-to-javas-reflection) and caching can help in some cases as well

**Comment by hallvard** [comment]
> I might have `emptyRow` append the new row so that you just have `table.emptyRow().setAge(4).setName("Hallvard")`
That's actually how it is, since the Row doesn't store data itself, it needs to add missing values to the Table's columns and overwrite. So emptyRow() appends missing values, creates a new Row and sets it to point to the newly created row.

**Comment by hallvard** [comment]
> I'm very interested in adding more type safety. The nicest I've seen is Spark's Datasets. I like that it can deal with POJO
> Would it make sense to do something like `table.addRow(new Person().setAge(4).setName("Hallvard"))`. The benefit of this is that you can then use the `Person` class throughout your code in other places without introducing any dependency on Tablesaw. It'd also be easier to create the Person object code because your IDE can generate a POJO for you or you can use Lombok whereas there's not going to be tooling for extending `Row` in the same way

This is nice, but not very type safe, since you rely on column names.

One could use a design similar to serialisers, where you have dedicated object mappers that extract data from the objects that are to be serialised. Different mappers use different strategies for extracting data, a PojoMapper would use reflection, whereas a JsonMapper would use Json logic. You register the necessary object mappings (on the table or individual columns) and feed data into the table. E.g.
`table.registerMapper(new PoJoMapper(), Object.class); // default mapper, could be pre-registered`
`table.registerMapper("age", Person::personAge, Person.class); // used only for age column`
`table.appendRows(personIterator); // combines mappers to extract data from Iterator<Person>`

**Comment by lwhite1** [comment]
I think this should be it's own issue/thread. This is pretty far removed
from fixing a toString problem.

**Comment by lwhite1** [comment]
closed by @hallvard pull request
