### ISSUE TITLE
Issue with exporting saw format to disk

### ISSUE THREAD

**Issue by chetansaini39** [jtablesaw/tablesaw#499]
The table.write.toFile() method seems to be working a bit odd. I am getting null pointer exception. if I use csv instead of tofile, everything works fine

**Comment by benmccann** [comment]
Can you share the stack trace? What parameters are you passing to `toFile`? If there's code you can share with us to reproduce that would help as well

**Comment by benmccann** [comment]
I tried this myself and didn't encounter any error. I will leave this open for a bit longer, but we'll end up closing this unless you're able to provide some additional details

**Comment by lwhite1** [comment]
closing since there was no response
