### ISSUE TITLE
Parallel CSV file imports

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#5]
CSV imports are orders of magnitude slower than Saw file loads. Try to speed things up by opening multiple importers and loading separate columns with each. (ActivityMonitor suggests that CSV imports are bound on CPU, and that it only uses one currently).

**Comment by lwhite1** [comment]
While this is still a significant issue: 500_000_000 row load perf times:
csv: 14-15 minutes
saw: 20-25 seconds
CSV load times are about 40% of what they were when this was written.

**Comment by batterseapower** [comment]
In my experience the univocity CSV parser is up to twice as fast as opencsv. This might be an easy way to improve performance.

The best way to use parallelism would be with an approach like paratext, where you split the file into chunks and read each chunk individually: https://github.com/wiseio/paratext. This is obviously a bit tricky though, and I don't think there is any existing Java lib that will help you with this.

**Comment by tischi** [comment]
Could you let us know what "Saw" files are?
We may have some big tables and would like to load them as fast as possible.
Currently we are using tab delimited text files.
Do you think there is another file format that could be faster?
Thank you very much for the help!

**Comment by lwhite1** [comment]
Saw files are a proprietary binary format for Tablesaw. They would make the
loading faster, but have some drawbacks:
- it's non-standard
- you have to get the files into saw format for them to be read.
- I may replace the saw format in the future with Apache Arrow formatted
files. This will probably be faster than text, but not as fast as Saw, at
least initially. It's not definitively going away, so you may want to try
it if you really need the greatest speed possible.

You may want to check out the 3rd party library that can be used to load
data from Parquet. It's mentioned on the README.md.

For Parquet (and later Arrow) you would find that they support many column
types not supported by Tablesaw, so you have to be careful which column
types you use for your data.
