### ISSUE TITLE
Converting column type

### ISSUE THREAD

**Issue by ana29** [jtablesaw/tablesaw#504]
How can I convert the type of a column?
I have an double column, but I need that the data  be an int after  manipulation.

**Comment by lwhite1** [comment]
asIntColumn() will do it, but you don't control the rounding (it just casts double to int), which i think is the same as calling Math.round(), except you get ints rather than longs.

 If you need a specific rounding you would need to do that yourself first.

**Comment by lwhite1** [comment]
I'm going to assume this addresses your question and close this issue. If that's not the case feel free to re-open. Cheers.
