### ISSUE TITLE
CSV parser cannot parse all date time formats Java can

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#506]
Since we take a format string as the parameter in ReadOptionsBuilder, we cannot use the additional options available in Java via DateTimeFormatter. For example:

options.dateTimeFormat("dd-MMM-yy") 

can parse "04-Apr-19", but not "04-APR-19".

To parse the latter, you need to use the parseCaseInsensitive() option on DateTimeFormatter, e.g:

            DateTimeFormatter format = new DateTimeFormatterBuilder()
                .parseCaseInsensitive()
                .appendPattern("dd-MMM-yy")
                .toFormatter(); 

There is currently no way to pass a DateTimeFormatter object to the ReadOptionsBuilder.

Suggested Fix: 
Deprecate existing options and replace them with options that take a constructed DateTimeFormatter argument instead. This would be done for Date, Time, and DateTime columns.

**Comment by lwhite1** [comment]
@benmccann Hi Ben, If I understood correctly from our earlier conversation, we need to up the revision on core before this can be implemented in the HTML, JSON, and Excel sub projects. Is that correct?

**Comment by benmccann** [comment]
Yes, but I think I have a way to change it to make that no longer true. I'm working on something now. Give me half an hour :-)

**Comment by benmccann** [comment]
Ok, now that the registries are in place I was able to remove the circular dependency. If you do a pull hopefully you can finish the change you were working on without having to cut a release

**Comment by lwhite1** [comment]
Cool. Thanks!

**Comment by lwhite1** [comment]
fixed
