### ISSUE TITLE
escaping of html content in table

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#507]
Hi @benmccann,

Did you recently add something that automatically escapes string content in tables when creating html output?  If so, how can i disable it?

thanks.

**Comment by benmccann** [comment]
Not explicitly, but it happened as a side effect of using jsoup to write the html

I'm curious what the use case is for writing non-escaped content?

**Comment by lwhite1** [comment]
i have links between tables in different pages (e.g. a table of summary information where each row links to a table of detailed information about that row).
I also formatted the content of some table cells as lists to make them more legible, but presumably other formatting might be useful as well in some circumstances.

**Comment by lwhite1** [comment]
I will take a shot. It looks like making this substitution might do it:

```
    private static Element row(int row, Table table, ElementCreator elements) {
        Element tr = elements.create("tr", null, row);
        for (Column<?> col : table.columns()) {
          tr.appendChild(elements.create("td", col, row)
             .appendChild(new DataNode(String.valueOf(col.getString(row)))));
              //.appendText(String.valueOf(col.getString(row))));
        }
        return tr;
    }

```
if this works, i will add a "no escape" option to HtmlWriteOptions.

**Comment by benmccann** [comment]
Sounds good to me.

**Comment by lwhite1** [comment]
closing
