### ISSUE TITLE
[Bug?] When Summary a table

### ISSUE THREAD

**Issue by yellowbean** [jtablesaw/tablesaw#511]
Hi, there ,great work for jtablesaw !! Thank you very much

I have a table like this :

 dates     |  balance   |  principal  |       interest       |  prepayment  |  default  
-----------|-----------|------------|-----------------|--------------|-----------
 2017-03-20  |  112000.0  |        0.0  |                 0.0  |         0.0  |      0.0  
 2017-06-20  |  112000.0  |        0.0  |  1981.777  |         0.0  |      0.0  
 2017-09-20  |  112000.0  |        0.0  |  1981.777  |         0.0  |      0.0  
 2017-12-02  |  112000.0  |   112000.0  |              1568.0  |         0.0  |      0.0  

I want to sum up principal & balance in same date

            Summarizer smr = combined_cf.summarize("balance","principal", AggregateFunctions.sum);
        return smr.by("dates");

But it will raise error like 

     at tech.tablesaw.aggregate.NumericAggregateFunction.isCompatibleColumn (NumericAggregateFunction.java:17)
    tech.tablesaw.aggregate.Summarizer.getAggregateFunctionMultimap (Summarizer.java:214)
    tech.tablesaw.aggregate.Summarizer.summarize (Summarizer.java:199)
    tech.tablesaw.aggregate.Summarizer.by (Summarizer.java:138)

When I debug it turns out that `isCompatibleColumn ` is usingi null value which originated from :  

    // Summarizer:183
     Column<?> column = this.temp.column(name);
    // the IDE shows me that name="balance" ,but column variable is Null
    // the IDE shows that the `this.temp` table looks good , it has a column named "balance"

My question is ,how come Table.column would work ? as in the doc for 0.30.2, Table.column( int columnIndex) instead of a column name in String . Isn't `name` a `column` function should be an index instead of a column name string ?

Thank you very much

**Comment by lwhite1** [comment]
Hi.  
Sorry you're having trouble. Can you provide a mini version of your data file? Just a couple lines will do.

**Comment by lwhite1** [comment]
I created the table from what you pasted, but I don't see any issue.
My code:
```
        Table test = Table.read().csv("../data/testdata.csv");
        Summarizer summarizer = test.summarize("balance", "principal", sum);
        Table result = summarizer.by("dates");
        System.out.println(result.printAll());
```
The output:

```
                testdata.csv summary                
   dates     |  Sum [principal]  |  Sum [balance]  |
----------------------------------------------------
 2017-03-20  |              0.0  |       112000.0  |
 2017-06-20  |              0.0  |       112000.0  |
 2017-09-20  |              0.0  |       112000.0  |
 2017-12-02  |         112000.0  |       112000.0  |

```
I'm not sure why you're having issues, but i don't think it's a tablesaw bug. 

Regarding your question.  You can reference columns by either name or index, but the ability to use each form is not supported across every function.  Using name is helpful if you might restructure the table by adding or removing columns, as that could make the indexes change. It's also more readable. I

**Comment by lwhite1** [comment]
i'm going to close this since I can't recreate the issue. Please reopen if you're still having difficulty.
