### ISSUE TITLE
Add an InstantColumn

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#516]
I'm interfacing with code which takes a `Date` or an `Instant` and it's cumbersome to specify a time zone anytime I want to use a value from the column. Databases are a typical use case for loading data since they usually return an `Instant` or a similar class such as `java.sql.Timestamp`.

There's also a possibility someone would request a `ZonedDateTimeColumn` in the future, but I would defer that for now.

**Comment by lwhite1** [comment]
I've been waiting for this request :)
just for my education, why instant over ZonedDateTime?

**Comment by benmccann** [comment]
`Instant` is an instant in time. It does not include a time zone. It's roughly equivalent to `java.util.Date` and `java.sql.Date`, but was introduced in Java with the `java.time` package and is preferred over those classes due to newer API. `ZonedDateTime` is an instant in time + time zone.

 If you just care when something happened and not in which time zone it happened then `Instant` is a better fit. Quite a few data sources utilize a `java.sql.Date` or `java.util.Date` (e.g. loading data from a database or my stock broker's API for example), so `Instant` is easier to work with in those cases because you don't need to specify a time zone. You may end up converting to a `ZonedDateTime` if you want to display to the user in their time zone

**Comment by benmccann** [comment]
Another thing I realized is that `ZonedDateTime` and `LocalDateTime` are somewhat equivalent. They both represent an instant in a particular time zone. It's just that `ZonedDateTime` stores what time zone that is while `LocalDateTime` does not.
