### ISSUE TITLE
DoubleColumn should not use Epsilon Notation while printing or written as CSV

### ISSUE THREAD

**Issue by anandmuthu-vnix** [jtablesaw/tablesaw#517]
In a table with a DoubleColumn that is holding large values like 23625000.0 is getting printed or written in Epsilon Notation as 2.3625E7

The issue is that DataFramePrinter is using getString of the value causes the issue. We should be formatting the double before printing it.

> value.toBigDecimal().toPlainString()

OR 

> val df = DecimalFormat("0", DecimalFormatSymbols.getInstance(Locale.ENGLISH))
> df.maximumFractionDigits = 340
> df.format(maxValue)

**Comment by lwhite1** [comment]
good point.
Whoever does this work, please do not use the BigDecimal option presented above unless you have fully investigated the memory requirements. BigDecimals are, well, very big.

**Comment by benmccann** [comment]
`getString` has a `printFormatter` in it. It sounds like perhaps we need a better default `printFormatter`?

**Comment by anandmuthu-vnix** [comment]
@benmccann Yes. I'm using printFormatter for formatting the data for printing in logs.
Apparently, formatter is used in stats printing by print method whereas csv write method is using getUnformatted() to fetch the values for writing. We need to use the same formatter is both the print and write or should introduce writeFormatter specifically for writing outputs.

**Comment by lwhite1** [comment]
This is fixed, with the caveat that the displayed decimal numbers may appear to have more precision than they actually do.

 E.G: 
33.333333333333328 -> displays as ->"33.3333333333333"
or, for a float:
9007199254.1f -> displays as -> "9007199232"
