### ISSUE TITLE
Reading incorrect column type

### ISSUE THREAD

**Issue by edgar131** [jtablesaw/tablesaw#519]
I'm using tablesaw to get tabular data from a postgres database.  Currently getting the following 

> error: org.postgresql.util.PSQLException: Bad value for type short : -744443
>        at org.postgresql.jdbc.PgResultSet.toShort(PgResultSet.java:2807)
>	at org.postgresql.jdbc.PgResultSet.getShort(PgResultSet.java:2047)
>	at com.zaxxer.hikari.pool.HikariProxyResultSet.getShort(HikariProxyResultSet.java)
>	at tech.tablesaw.io.jdbc.SqlResultSetReader.read(SqlResultSetReader.java:147)
>	at tech.tablesaw.io.DataFrameReader.db(DataFrameReader.java:111)

Which stems from me doing a simple Table read on a resultSet:

`return Table.read().db(preparedStatement.executeQuery());`.

For some reason it seems to be misinterpreting certain numeric columns as shorts even though they have data larger than that.

Update:
The actual issue is that by default NUMERIC types in Postgres do not have a precision or scale.  This results in them being treated as a short column since the code checks for the precision being <=4 and assigning it that way.  This then leads to an error when translating the data since it tries to retrieve the values of that column as shorts even though the data may have values that don't fit as a short type.

A workaround is to ensure that the database columns you query have an explicit precision specified ie. "NUMERIC(20)".  You can also cast those columns inline to bypass the issue ie.
```SELECT column_a::NUMERIC(20)```

The solution would probably be to have a specific case of if the precision is 0 (which is technically an invalid precision) to treat it like a DOUBLE to ensure that it is more likely the data fits properly.

**Comment by lwhite1** [comment]
what's the actual PG column type?

**Comment by edgar131** [comment]
> what's the actual PG column type?

Numeric

**Comment by lwhite1** [comment]
Pg doesn’t support the precision operation in its drivers.  It always
returns 0. We’ll need to work around that.  I guess that means you’ll
always get a long.

There is a static method on sqlresultsetreader that lets you specify the
col type for a resultset type tho. You can try that in the meantime

**Comment by edgar131** [comment]
I'll give that a try tomorrow and see if that works, thanks.

> Pg doesn’t support the precision operation in its drivers.  It always
returns 0. We’ll need to work around that.  I guess that means you’ll
always get a long.

> There is a static method on sqlresultsetreader that lets you specify the
col type for a resultset type tho. You can try that in the meantime

**Comment by edgar131** [comment]
I updated my original comment with more information on the issue.  Pg DOES support the precision operation in its drivers it is just that for NUMERIC types, unless a precision was specified for that column, it will return 0.  Using the static method on SqlResultSetReader is not useful since the code doesn't even use that if the metadata for the column returns that it is a numeric or decimal type.  My solution was to cast the column in my queries as NUMERIC(20) to ensure the precision was treated as a larger number to avoid it coming up as a short.

> Pg doesn’t support the precision operation in its drivers. It always returns 0. We’ll need to work around that. I guess that means you’ll always get a long. There is a static method on sqlresultsetreader that lets you specify the col type for a resultset type tho. You can try that in the meantime
