### ISSUE TITLE
Static class builder shouldn't be 'protected' in JsonWriteOptions.java

### ISSUE THREAD

**Issue by rookdomain** [jtablesaw/tablesaw#526]
static class Builder extending WriteOptions.Builder is currently created as follows in
 JsonWriteOptions.java:
`protected static class Builder extends WriteOptions.Builder {`
It should probably be public, not protected:
`public static class Builder extends WriteOptions.Builder {`

As of now, when it is used as shown below, it causes an error 'The type JsonWriteOptions.Builder is not visible'.
```
StringWriter writer = new StringWriter();
table.write().usingOptions(JsonWriteOptions.builder(writer).asObjects(false).header(false).build());
```

**Comment by benmccann** [comment]
Thanks for reporting. Fixed here: https://github.com/jtablesaw/tablesaw/commit/1783b475fcbcf829ac0dff872017afc09f46e074
