### ISSUE TITLE
Reduce dependencies of tablesaw-core

### ISSUE THREAD

**Issue by AhmetBilgin** [jtablesaw/tablesaw#537]
I have a requirement to use a DataFrame java library which is small in size.
I would like to use jtablesaw but the **tablesaw-core** library which is about **500KB** in size has (transitive) **dependencies** which are about **25MB** in size.
The **project** in which I want to use tablesaw-core is about **2MB** and therefore I was not allowed to bloat the size of the project through the transitive dependencies of tablesaw-core.

It seems that **fastutil** has a significant impact on the dependency size with about **18MB**.
Are there any plans to reduce the size of your dependencies?

**Comment by benmccann** [comment]
We've done a lot of work to strip out unnecessary dependencies. It would be hard to make it much smaller. Fastutil is heavily utilized and is used to store the data in memory, so would be hard to remove.

What's your use case that size is important? Is it a mobile app? Maybe there's something fastutil could do to make their library smaller?

**Comment by AhmetBilgin** [comment]
Hi @benmccann,
the requirement for the smaller library size is not a technical one, but in terms of proportionality.
I will have a look into your fastutil dependencies in order to request a smaller fastutil-light library, but I have no big hopes that fastutil will be cut smaller on my request.

Best regards,
Ahmet

**Comment by benmccann** [comment]
It's not clear to me why we'd invest time in reducing the library size if there's no technical benefit
