### ISSUE TITLE
How to set the plot's (diagram) width and height?

### ISSUE THREAD

**Issue by shuangxixu** [jtablesaw/tablesaw#547]
How to set the plot's (diagram) width and height when I call Plot.show method?

thanks,

**Comment by lwhite1** [comment]
You need to create a Figure with a custom Layout object:

```
        Plot.show(new Figure(layout, traces));
```
The layout object has methods for setting height and width.

please see the examples in the test code folders for jsplot. 
tablesaw/jsplot/src/test/java/tech/tablesaw/examples/

The example class ablesaw/jsplot/src/test/java/tech/tablesaw/examples/HorizontalBarExample.java includes setting the height.

**Comment by shuangxixu** [comment]
Got it. Thank you.
