### ISSUE TITLE
Some DateTime map functions no longer return DateTimeColumn 

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#553]
Since the TemporalMap interface was introduced some functions like plus() no longer return DateTimeColumn. They return Column<LocalDateTime>, requiring a cast. 

It would be nice for these to return DateTimeColumn, since other methods often require DateTimeColumn rather than Column<LocalDateTime>. 

Or, I suppose, it might be possible to switch everything to Column<>.

**Comment by benmccann** [comment]
We should probably override in the subclasses so that they return the appropriate type. I.e. DateTimeColumn or InstantColumn

**Comment by lwhite1** [comment]
fixed by overriding.
