### ISSUE TITLE
Code format standards

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#566]
Having thought more on the google format option, I would propose this:

- We switch over to using the google format tool, including going back to 2 spaces. Staying with 4 spaces would mean people having to configure the tool in various ways depending on whether or not they're using a plugin.
- We publish it as the standard way to format code
- We don't force occasional submitters to use it. We can run on the source as a whole for an occasional cleanup.  It's fine to recommend it, though.
- We discontinue comments on formatting in code reviews, unless it's something that's outside of the google format yet is still important (but I can't imagine what that might be).

thoughts?

**Comment by benmccann** [comment]
That sounds good to me

> We don't force occasional submitters to use it. We can run on the source as a whole for an occasional cleanup. It's fine to recommend it, though.

I saw a plugin that will set it as a git pre-commit hook. Then it would be done automatically and we wouldn't have to tell people about it as an extra step

**Comment by lwhite1** [comment]
Perfect

**Comment by lwhite1** [comment]
I'm going to call this issue closed.
