### ISSUE TITLE
BigQuery support?

### ISSUE THREAD

**Issue by samdfonseca** [jtablesaw/tablesaw#572]
I'm working on building some basic support for importing data out of BigQuery and I'm curious if there's anything I should know ahead of time. Would this be something you'd consider merging?

**Comment by lwhite1** [comment]
Hi @samdfonseca,

We place specialized IO code in sub-projects, e.g. html, json, excel. We could do the same for BigQuery if you provide a PR. 

I'm not sure what you need to know ahead of time, as that would depend on how much data you're importing and what you want to do with it. I'm happy to answer questions as you go.

**Comment by benmccann** [comment]
You can also have it in your own repo and we can link to it from the readme or docs. All the readers are in separate projects as Larry mentioned, so there's really no reason it would have to live in this repo. We don't necessarily know BigQuery very well so probably wouldn't maintain it well compared to you

**Comment by samdfonseca** [comment]
Sounds good! Thanks for the quick response on this. I should have something ready in the next week or so, and I'll keep you posted.

**Comment by lwhite1** [comment]
I'm going to close this. @samdfonseca, please feel free open another for any specific issue
