### ISSUE TITLE
IntColumn.asDoubleColumn() does not convert missing values

### ISSUE THREAD

**Issue by albalkum** [jtablesaw/tablesaw#577]
If I have an IntColumn and try to convert it to a DoubleColumn with asDoubleColumn(), all missing values are instead converted to a double representation of Integer.MIN_VALUE.  Example:
```
IntColumn intColumn = IntColumn.create("intColumn");
intColumn.append(1);
intColumn.appendMissing();
System.out.println(intColumn.asList());		    
System.out.println(intColumn.asDoubleColumn().asList());
```
Output:
```
[1, null]
[1.0, -2.147483648E9]
```

Is this the intended output?  I'd prefer that the null values would carry thru to the converted column.  The documentation in IntColumn says "A missing value in the receiver is converted to a missing value in the result"...

Thanks!

**Comment by lwhite1** [comment]
fixed.
Thanks for the bug report, @albalkum
