### ISSUE TITLE
Support Analytic/Window functions

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#582]
This requires some research. This is just some initial thoughts. I would like to work on this and am happy to do the heavy lifting.

## Analytic Functions

Analytic functions are one of the most powerful features of SQL. [BigQuery has some good docs.](https://cloud.google.com/bigquery/docs/reference/standard-sql/analytic-function-concepts) The short version is that they allow you to split the data set into partitions, order each partition, define a window (relative to the current row) and then operate over that window.

## Example

```
          Sales By Region          
    date     |  region  |  sales  |
-----------------------------------
 2018-01-01  |      US  |     10  |
 2018-02-01  |      US  |     40  |
 2018-03-01  |      US  |     20  |
 2018-01-01  |  Europe  |     30  |
 2018-02-01  |  Europe  |     50  |
 2018-03-01  |  Europe  |     40  |
```

### Cumulative Sales By Region
```sql
SELECT date, region,
SUM(sales) over(PARTITION BY region ORDER By DATE ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ytdSales
```

```
| date       | region | ytdSales |
|------------|--------|----------|
| 2019-01-01 | Europe | 30       |
| 2019-02-01 | Europe | 80       |
| 2019-03-01 | Europe | 120      |
| 2019-01-01 | US     | 10       |
| 2019-02-01 | US     | 50       |
| 2019-03-01 | US     | 70       |

```

Operate over trailing two runs. (There is a lot of flexibility in choosing this syntax)

```sql
// Sum trailing 2 rows. No partition.
SELECT date, region,
SUM(sales) OVER (ROWS BETWEEN 2 PRECEDING AND 1 PRECEDING) AS precedingWindow
```

```
| date       | region | precedingWindow |
|------------|--------|-----------------|
| 2019-01-01 | US     | null            |
| 2019-02-01 | US     | 10              |
| 2019-03-01 | US     | 50              |
| 2019-01-01 | Europe | 60              |
| 2019-02-01 | Europe | 50              |
| 2019-03-01 | Europe | 80              |
```

## Thoughts on Syntax (Almost exactly like SQL)

We create a similar functionality, but with an `accept(Consumer<Row[]> consumer)` method that adds flexibility.

#### Calculates ytd Sales
```java
 table.over()
      .partitionBy( "region")
      .orderBy("date", ASC)
      .rowsBetween().unboundedPreceding().andCurrentRow()
      .sum(sales)
      .execute();
```

#### Applies `Consumer<Row[]>` to two preceding rows.

```java
 table.over()
      .rowsBetween().preceding(2).andPreceding(1)
      .apply(myConsumer)
      .execute();
```

**Comment by ryancerf** [comment]
@lwhite1 @benmccann 

I have been working on this for a little while and it is getting pretty close. I would like to get your feedback before I do much more. Can I send a PR to a separate branch so you could fork it and try it out? All changes are contained within a new package called `analytic` in core.

The API is built using a fluent interface. I like it, but think it could be improved and would like to get feedback before I attempting to fine tune it.

Once we decide how to move forward I will:
* Add code samples here
* Add a few of my ideas on how the API can be improved.
* Start a discussion on how we can incorporate consumers into the API. `Consumer<Iterable<Row>>`

**Comment by ryancerf** [comment]
### Proposed API

SQL's native grammar allows for a diverse set of Analytical SQL statements. I am proposing to support a subset of the possible analytical statements using a fluent api + builder patter. Below is a graphviz of three possible paths down the API, but first here are a few notes.

#### Valid Queries

All queries created following one of these paths will be pretty much valid. With the possible exception of an invalid window frame such as `Rows between 4 Preceding AND 2 Preceding`

#### .rowsbetween()...`
The `.rowsbetween()...` node  is short for building an entire window frame. Something like:

```java
.rowsBetween().unboundedPreceding().andUnBoundedFollowing()
```
OR

```java
.rowsBetween().currentRow().andFollowing(5)
```

#### `.sum("col1")`
 The `.sum("col1")` node does not have to be `sum`. It could be any analytic aggregate function (`sum`, `max`, `min`, `count` etc)

#### `.rank("col1")`
* The `.rank()` node does not have to be rank. It could also be any analytic numbering function (`rank`, `denseRank` or `rowNumber`) 

![image](https://user-images.githubusercontent.com/7135877/63214510-d243d400-c0cd-11e9-8fd2-591146ae1b50.png)

**Comment by lwhite1** [comment]
This sounds good. I'm very excited to see this in action. Just a few questions:
(1)
```
.rowsBetween().unboundedPreceding().andUnBoundedFollowing()
```
you mention that this is one place where a person could construct an invalid query. At what point would an invalid range be discovered? On build(), execute(), or before?

It's a small issue but I'm wondering if something like this wouldn't be ok
```
.rowsBetween(rangeStart, rangeEnd) {
   Preconditions.check... etc.

```
(2)
why is sort order required in the center path? I only ask because unlike SQL, tablesaw functions will generally return rows in the order they appear in the input table. 

(3)
If green is optional and red is required, what is white?
 
(4)
Where's the "over" clause?

(5) 
What does the consumer do? Is that an extension to the standard Analytical Function syntax? 

(6) 
Given that this is based on SQL, is it safe to assume the result of executing a query is a table?

**Comment by ryancerf** [comment]
(1)
> .rowsBetween().unboundedPreceding().andUnBoundedFollowing()
> you mention that this is one place where a person could construct an invalid query. At what point would an invalid range be discovered? On build(), execute(), or before?

The invalid range is discovered on `.build()`. There are only a few ways to put in an incorrect range (most of them can be avoided using the fluent api). One of them is Rows between 3 Preceding AND 5 Preceding (notice how the window end (5 preceding) is before the the window start (3 Preceding). That is invalid. Really no way around this.

> It's a small issue but I'm wondering if something like this wouldn't be ok

```
.rowsBetween(rangeStart, rangeEnd) {
   Preconditions.check... etc.
```

I think this makes it a bit harder to handle the unbounded preceding, unbounded following and current row functionality, but maybe that would make sense for "quick analytic" path. I call these kinds of windows "sliding" windows.

(2)

> why is sort order required in the center path? I only ask because unlike SQL, tablesaw functions will generally return rows in the order they appear in the input table.

Rank and Dense Rank compare entire rows and need a comparator. These kinds of functions are called numbering functions and all SQL engines require order.

This is a bit of a tangent, but with the improvements we made to TableSlice any order by clause in the analytical query will not affect the underlying table. Executing an analytic query will not make a copy of or modify the underlying table.

The bottom line is that the rows returned by executing an analytic query will be in the same order as the original table whether or not the query contained an order by! I think this will be clear when you see the PR.

(3)
If green is optional and red is required, what is white?

The green is an optional **varargs**. Meaning you could pass `partitionBy()` and it will move on to the next step in the fluent API without actually partioning the data. The red nodes would not let you pass `orderBy()` with no params. This can be inforced at compile time with the fluent API. The white nodes are regular methods where all their arguments are required.

(4)
Where's the "over" clause?

The whole thing is kinda of an over clause. Over is made up of partition order by and window frame definition. Maybe we should use the word over somewhere.

(5)
What does the consumer do? Is that an extension to the standard Analytical Function syntax?

This is a proposed Tablesaw specific extension. It is a mix of the `steppingIteator` work Ben did and an analytic query. Here you would be able to define much more complicate windows. I am not implementing this in my first pass and will need your help thinking this through. More to come.

(6)
Given that this is based on SQL, is it safe to assume the result of executing a query is a table?

Yes the result is a table. We could have a `.execute()` method which returns a table containing the output columns (and maybe the partition by and order by columns). We could also add a `.executeInPlace()` method that would add the columns to the original table. This is more or less what SQL does.

Thanks for the comments!

**Comment by lwhite1** [comment]
> (4)
> Where's the "over" clause?
> The whole thing is kinda of an over clause. Over is made up of partition order by and window frame definition. Maybe we should use the word over somewhere.

There are many moving parts right now, but it's my assumption that this will fit into a future "sql-style" API, in the sense that you could do something like 

    select(). from(_myAnalyticQuery_).where(.....) etc.

or 

    AnalyticQuery.query().from(_myStandardSqlTypeQuery_)....

I don't especially love the term "over" but i want to make sure that when you read code like this the differences are clear. 

In terms of the naming of things overall, the BigQuery docs say:

> **Analytic functions** are also called "**(analytic) window functions**" in the SQL standard and some commercial databases... In some other databases, they may be referred to as **Online Analytical Processing (OLAP) functions**.

I notice we have chosen none of these for the top-level naming (Although there are analytic functions, they're a subpart of an AnalyticQuery, produced by an AnalyticQueryEngine). Was that what we have here is too different from the standard? How do you see this playing with standard queries in the future?

If we're not completely comfortable with the naming or integration with a future query builder, should we annotate the new classes with the @Beta annotation? I'm planning on doing that for my DeferredFunction work since I'm neither entirely happy with it, nor sure it really fits well into the big picture. 

But the real reason I'm focusing on naming is that I want to make sure how i should present this when I write my dzone article about this cool new feature :)

**Comment by ryancerf** [comment]
> There are many moving parts right now, but it's my assumption that this will fit into a future "sql-style" API, in the sense that you could do something like

This is a really good point and something I have not thought about. Until you brought this up I guess I was assuming regular SQL queries and analytic Queries would be separate. I need to give this more thought.

> I notice we have chosen none of these for the top-level naming (Although there are analytic functions, they're a subpart of an AnalyticQuery, produced by an AnalyticQueryEngine). Was that what we have here is too different from the standard? How do you see this playing with standard queries in the future?

I am not at all happy with the top level naming either and I think we can improve it. As a side note the way I Implemented the analytic function query builder makes it easy to rewrite the API (as long as we have not released it of course.)

> If we're not completely comfortable with the naming or integration with a future query builder, should we annotate the new classes with the @beta annotation? I'm planning on doing that for my DeferredFunction work since I'm neither entirely happy with it, nor sure it really fits well into the big picture.

I think we should go one step farther and make it package private and invisible to users all together while we work on #576 and get the bigger picture figured out.

> But the real reason I'm focusing on naming is that I want to make sure how i should present this when I write my dzone article about this cool new feature :)

Awesome. Looking forward to that, but I think we have a bit of work to do first (including improving our docs).
