### ISSUE TITLE
Please hold this release for additional testing

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#584]
@benmccann I would like to be able to spend some time using this code before we cut a formal release. I want to be sure the changes regarding deferred columns are well designed. Thanks.

**Comment by benmccann** [comment]
Sounds good

**Comment by ryancerf** [comment]
I agree. I think we should wait to release this until we have worked out a bit more of the details of #576.

**Comment by benmccann** [comment]
What are you guys thinking in terms of timing for the next release? I noticed that @lwhite1 marked the saw reader as `@Beta`. Perhaps we should do the same thing with the analytical query stuff if we want to make it available for people to test out without us having to worry about getting everything just right?

**Comment by lwhite1** [comment]
I think Ryan May have done that already.

But I would be happy to go ahead as you suggest.

**Comment by ryancerf** [comment]
Yes. All the public entry points to start building an analytic query are marked with the `@Beta` annotation. I plan to write some documentation for analytic functions soon.

**Comment by benmccann** [comment]
It looks like something's broken in the release process with the docs:
```
[INFO] [ERROR]     * Missing: no sources jar found in folder '/tech/tablesaw/tablesaw-docs/0.35.0'
[INFO] [INFO] tablesaw-docs ...................................... FAILURE [02:09 min]
```

**Comment by benmccann** [comment]
I think I got it fixed and cut a new release: https://github.com/jtablesaw/tablesaw/commit/255507b5889cae47d0b7422d14263bb128eae9fa

It takes an hour for a release to show up in Maven Central, so hopefully we can confirm soon

**Comment by benmccann** [comment]
It looks like the last attempt didn't work. Hopefully third time's the charm: https://github.com/jtablesaw/tablesaw/commit/35c8f470560c787353a699b92100a80cc5f8aa32
