### ISSUE TITLE
NumberColumn.MISSING_VALUE does not seem to exist as per guide

### ISSUE THREAD

**Issue by hmf** [jtablesaw/tablesaw#585]
In the Guide here:

https://github.com/jtablesaw/tablesaw/blob/107b41139ec9db652d16c15a42367f74ce58b82e/docs/userguide/Histograms.md

we have:

```
NumberColumn sqft = property.numberColumn("sq__ft");
sqft.set(sqft.isEqualTo(0), NumberColumn.MISSING_VALUE);
```
but I looked for `NumberColumn.MISSING_VALUE` and did not find it. Does it exists? If not will a Double.NaN do?

  Using version `0.34.2`

**Comment by lwhite1** [comment]
Depends on what you’re doing.
The missing value indicators are moving to DoubleColumnType and the like.

Generally better to use a isMissingValue method.  If you use your own
method be sure to test that value != value, rather than value ==NaN

**Comment by lwhite1** [comment]
use `DoubleColumnType.isMissingValue(aDouble)` to test

**Comment by benmccann** [comment]
Docs fixed here: https://github.com/jtablesaw/tablesaw/commit/160fee0b09cedc3b00d6e9eca8ea81e441a0e528
