### ISSUE TITLE
NullPointerException when reading json array with incomplete rows

### ISSUE THREAD

**Issue by daveknave** [jtablesaw/tablesaw#588]
Hello everyone, reading a list of objects with differing attribute sets results in a
```
Exception in thread "main" java.lang.NullPointerException
	at tech.tablesaw.io.json.JsonReader.convertArrayOfObjects(JsonReader.java:106)
	at tech.tablesaw.io.json.JsonReader.read(JsonReader.java:51)
	at tech.tablesaw.io.json.JsonReader.read(JsonReader.java:21)
	at tech.tablesaw.io.DataFrameReader.usingOptions(DataFrameReader.java:103)
```
In the previous code block in JsonReader, each field name in every row is added to the `colNames` set. However, afterwards at line 106, it is just assumed that the respective node has all the attributes stored in `colNames`, which leads to this exception being thrown.

Here is a minimal reproducible example. The expected behavior for me would be to treat A and C as missing values in the respective row in which they are actually missing. This occurred and is reproducible in tablesaw-json v0.34.2.:
```
String s = "[" +
    "{\"A\" : \"123\", \"B\" : \"456\"}," +
    "{\"B\" : \"789\", \"C\" : \"123\"}" +
    "]";

JsonReadOptions.Builder builder = JsonReadOptions.builderFromString(s);

try{
    JsonReadOptions options = builder.build();
    DataFrameReader dfr = Table.read();
    Table t = dfr.usingOptions(options);
} catch (IOException e){ }
```
Best,
David

PS: I like tablesaw a lot, it is one of the reasons why I can actually use java for my research projects. I am used to working with python/pandas and R data frames and the lack of such easy-access API in Java is incomprehensible to me. I'd like to contribute to this project, where possible.

**Comment by lwhite1** [comment]
@daveknave 
Thank you for the bug report. 

>PS: I like tablesaw a lot, it is one of the reasons why I can actually use java for my research projects. I am used to working with python/pandas and R data frames and the lack of such easy-access API in Java is incomprehensible to me. I'd like to contribute to this project, where possible.

I'm glad you find it useful. We welcome any help.
