### ISSUE TITLE
CsvWriter always trims strings when writing data.

### ISSUE THREAD

**Issue by jglogan** [jtablesaw/tablesaw#603]
Currently the Tablesaw CsvWriter leaves the Univocity CsvWriterSettings for ignoreLeadingWhitespaces and ignoreTrailingWhitespaces to true, which means that if I try to write a text field with the value " " to CSV, it gets reduced to the empty string.

I don't see any CsvWriteOption settings to change the behavior.

Is there a workaround for this, aside writing my own class?  Since CsvWriter is final, extending the class to override the createSettings() method isn't an option.

**Comment by lwhite1** [comment]
if you submit a PR we could add the feature.   I don’t believe there are
any easy work arounds.

**Comment by jglogan** [comment]
Thank you for the very prompt response!  I've gone with a workaround for now by chucking rows into OpenCSV.

Getting set up on my end to contribute is non-trivial, even for small enhancements like this one.  I still need to see whether Tablesaw is the best fit for what I'm working on.  If so, it shouldn't be a problem to start providing some PRs.

**Comment by lwhite1** [comment]
sounds good. we'll leave the issue open and someone will fix it eventually.
thanks for giving us a try!

**Comment by sd1998** [comment]
@lwhite1 Can I work on this?

**Comment by lwhite1** [comment]
fixed

**Comment by jglogan** [comment]
@sd1998 thank you!  This should do the trick.  When it hits a release I'll replace my workaround.
