### ISSUE TITLE
Use Interface to make sure the deferred filtering methods and regular filtering methods stay in sync

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#609]
The current implementation of DeferredStringColumn makes it possible for the filtering methods on StringColumn to drift out of sync with their equivalent methods on DeferredStringColumn. This applies to all column types.

We can extract these methods into a common generic interface to make sure they stay in sync.

```java
public interface StringFilterSpec<T> {
  T isEmptyString();
  ...
```

**Comment by lwhite1** [comment]
done
