### ISSUE TITLE
consider using structure tables to specify types

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#618]
table.structure() produces a table with ColumnType info that can be used on subsequent reads of the original table so that column types don't need to be inferred. The current approach using arrays of ColumnType is more obscure, and more manual.

**Comment by benmccann** [comment]
I'm not sure I understand the proposal for this one

**Comment by lwhite1** [comment]
You're right. I just wanted to get the idea down. I'm not sure it's really good, anyway.
One way to speed up the reading of a csv file is to provide an array of column types. This is also how you can tell tablesaw to skip reading some columns. 

A practical problem with that approach is that it can be tedious.  I often work with files that have more than 100 columns. There are two utilities that can help buried in the csv reader code. One returns a column type array. The other prints one as a string in a format that makes it easier to cut and paste it into your code so you can specify the type more easily. (Obviously it has to read the file once to get this far, but if you read the same report over and over this can help). It's an ugly hack though. 

At work I wrote a script that writes out the results of table.structure(), which also has the column types. Then when I want to reload the file, I have another script that will read the structure table and get the column type from that. So there's no messing around with string array writing, manually or otherwise.

In hindsight, I'm not sure writing the file is the cleanest approach. I think it's a little too general in that it only works with tables in the form structure() creates them. Perhaps it would be fine if it was called a "column type file" in the code/documentation and the fact that it's a table with a particular structure isn't emphasized.

**Comment by lwhite1** [comment]
This isn't really much better than the current approach. Not enough of an improvement (if it is an improvement to add as a features.
