### ISSUE TITLE
Consider supporting Orc as a file format

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#620]
Orc is an apache column store (C++) focused on Hadoop, but has a Java library that can be used for the local file system.

Rumor has it, that it is better documented than Parquet (see #221). Parquet is also a column store focused on Hadoop, from Apache, but written in Java. Unfortunately, using it on a local file system has not been a focus, and seems to be possible, but not to be well documented. It would be nice to support one or the other.

**Comment by benmccann** [comment]
Documentation for Java: https://orc.apache.org/docs/core-java.html

**Comment by murtuza-ranapur** [comment]
Hello @lwhite1 / @benmccann 
So i went through the documentation of ORC file, understood there supported datatypes and also created a mapping table specifying there types against Tablesaw column types. 

ORC Type | Tablesaw type
-- | --
Boolean | BooleanColumn
Date | DateColumn
double | DoubleColumn
float | FloatColumn
int | IntColumn
string | StringColumn
timestamp | DateTimeColumn
Tinyint (-128 to   127) | ShortColumn
smallint | ShortColumn
bigint | LongColumn
decimal | DoubleColumn
varchar | StringColumn
char | StringColumn
array | ?
binary | StringColumn(Suggestion)
map | ?
struct | ?
uniontype | ?

I am struggling with some of the complex datatypes that they support, such as array, map, struct. Do i need throw an exception if any of them are present? or Should the be silently ignored by just skipping those columns. Could you give any suggest on how they should be handled.

**Comment by benmccann** [comment]
Throwing an exception sounds fine to me as a starting point

**Comment by lwhite1** [comment]
inactive, and I don't really want any new file formats.
