### ISSUE TITLE
implement dictionary encoding for date column

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#622]
[this is mainly here as food for thought]

date columns use an int per date. A dictionary encoding like the one used for strings could reduce that amount by approximately half. For example: 
4 bytes * 1M records = 4MB
2 bytes * 1M records  + 10K unique dates * 18 bytes = 2.18MB
Note that 10K unique dates is equal to every day for 27 years, so most large data sets would see about 2x improvement per date column. 
Before a short would be inadequate, data would have to include every day for 175 years.

Much of the logic for a dictionary encoding already exists in StringColumn and its supporting classes. 

Complications: If you had more than 175 years worth of unique dates, you would be better off not using encoding. In string column, where this kind of things is more likely, we switch to a specialized class: TextColumn. That would certainly be overkill. 

Instead, the best solution might be to implement as in StringColumn, without a special class for handling data sets with  > 65,000 unique dates. They would just get the same old class, even though their memory performance would be considerably worse than it would with the current solution. 

My guess is that almost no dataset has that many unique dates, so it would improve memory use for 99.9% of users with big files. Small data sets may only have one record per day, and their memory usage would also be worse, but they would be unlikely to notice. 

This is not as big a savings as going from a java LocalDate to a tablesaw local date, which is a 4x improvement, but it's not bad.

**Comment by benmccann** [comment]
You need duplicate dates in the dataset for this to be a savings right? My most common datasets are timeseries where each date appears only once and I think in that case it'd be more expensive both in terms of memory and cpu

**Comment by lwhite1** [comment]
i don't think you could have enough rows in a one-record-per-day time series for it to matter.

**Comment by lwhite1** [comment]
not worth the trouble
