### ISSUE TITLE
Return null when value is missing

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#636]
When we call `get` I would expect it to return `null` for missing values instead of the underlying data

```
    Float[] floats = new Float[] { 2.5f, null, 4.0f };
    FloatColumn floatColumn = FloatColumn.create("floats", floats);
    assertEquals(null, floatColumn.get(1));  // fails. NaN is returned
```

**Comment by lwhite1** [comment]
Not sure I agree.  Then we would need to check for null sometimes and
isMissingValue other times

**Comment by ryancerf** [comment]
I agree with Larry. I expect it to return  FloatColumnType.missingValueIndicator()

**Comment by benmccann** [comment]
I would have expected missing value indicator to be used internally only. But I'll close this since it seems that's not the expectation you guys have
