### ISSUE TITLE
Backfilling data

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#663]
I'd like a way to backfill data. Is there any reasonably straightforward way to do this today? If not, I would be happy to add such a method

Use case: I have a column where only every third value is present (quarterly data in a monthly table). I'd like to backfill this column to just use the last value that was present

We'd gotten a previous request for this as well: https://github.com/jtablesaw/tablesaw/issues/401

**Comment by benmccann** [comment]
It looks like Pandas calls these methods `backfill` and `pad` or `bfill` and `ffill`. I like that `bfill` and `ffill` are consistent with each other in terms of naming, but prefer more explanatory names, so would propose the methods to be called `backfill` and `frontfill`

**Comment by lwhite1** [comment]
I think this is a common need in time series especially.  Most libraries in
that space support different methods of interpolation.  It would be nice if
we could put this behind an interface that let us swap in other approaches

**Comment by benmccann** [comment]
> It would be nice if we could put this behind an interface that let us swap in other approaches

Can you clarify?

**Comment by lwhite1** [comment]
I’m on my phone now, but this covers your approach and a couple simple
interpolation algos

**Comment by lwhite1** [comment]
https://towardsdatascience.com/how-to-interpolate-time-series-data-in-apache-spark-and-python-pandas-part-1-pandas-cff54d76a2ea

**Comment by benmccann** [comment]
Are you suggesting that instead of putting methods like `backfill` and `frontfill` directly on the column we group these methods together in another class? I.e. make the API look more like `col.interpolate().backfill()`, `col.interpolate().frontfill()`, `col.interpolate().linear()`,  `col.interpolate().nearest()`, etc?
