### ISSUE TITLE
Is there any way to get a List<Row> from the table?

### ISSUE THREAD

**Issue by adamsiembida** [jtablesaw/tablesaw#674]
Is there any way to get a `List<Row>` from the table?

I'm trying to populate a JavaFX `TableView`, and the `TableView` needs a `List` as its data model.

I could use `tableSawTable.iterator()` and use that to create a new `List<Row>`, but then I would be managing two separate data models in my application--both the JavaFX `TableView` model, as well as the tablesaw model. Some users might import large datasets into the program, and this might cause memory inefficiencies as well.

Thanks for any help.

**Comment by lwhite1** [comment]
Row is more like a curser than a true row so you can’t create a list of
rows easily.

There used to be a javafx table viewer in the code, but it was removed when
we stopped supporting native java charts. If I can find the old code I’ll
provide a pointer.

**Comment by lwhite1** [comment]
I don't know if this helps at all, but the code I was referring to above is in the repo:

https://github.com/jtablesaw/plot

The class is here.
https://github.com/jtablesaw/plot/blob/master/src/main/java/tech/tablesaw/api/plot/TableView.java

**Comment by adamsiembida** [comment]
Thanks, this is helpful. The useful code was in both the `TableView.java` class that you linked, and also the [FxTable.java](https://github.com/jtablesaw/plot/blob/b1c07feaf08e7870143c5236a2a661da8e41b596/src/main/java/tech/tablesaw/plotting/fx/FxTable.java) class.

I need to look it over a bit closer still to make sure I am understanding it properly. But it seems that the trick is that the actual model in the `TableView` is just an integer index, which is then used to index the tablesaw table from within the `CellValueFactory`. I didn't know you could refer to data outside of the `TableView` model like that.

**Comment by adamsiembida** [comment]
I got it to work, thanks again.
