### ISSUE TITLE
[Question] Getting first row of each group using Table.splitOn() when table contains text columns?

### ISSUE THREAD

**Issue by jglogan** [jtablesaw/tablesaw#677]
Hi,

I've tried updating from 0.34.2 to 0.36.0 and am getting tripped up by a regression when I run the following code to create a table consisting of the first row of each slice:

```
final Table outputTable = table.emptyCopy();
table.splitOn(groupColumnNames).forEach(s -> outputTable.append(s.asTable().first(1)));
```

The problem is that Table.splitOn is now converting TextColumn to StringColumn in each slice, so column type checking fails when I try to append a row from the slice to outputTable.

Is there a better way for me to achieve the same functionality, or will I need to implement a workaround in the above code where I convert types back to text before I append?

Thanks for your help!  John

**Comment by lwhite1** [comment]
Is the text column a grouping column?

**Comment by jglogan** [comment]
No, the way I'm calling it, it is not a grouping column.

But it looks like the [TableSliceGroup constructor](https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/table/TableSliceGroup.java#L55) tries convert all text columns to string columns as of 0.35.

**Comment by lwhite1** [comment]
Yeah. The underlying code deals only with columns of a fixed byte length.
There’s no way to do that with free form text. I think you’ll need to
either do this without using slices or by doing the column conversions

**Comment by jglogan** [comment]
Got it, I can figure out a workaround, no problem.  Thank you for the prompt response!
