### ISSUE TITLE
Add table constructor that accepting a list of columns[enhancement]

### ISSUE THREAD

**Issue by yellowbean** [jtablesaw/tablesaw#680]
Great jobs for tablesaw ! Thank you all for the fantastic work !

I'm wondering the possibility adding one more  Table constructor with signature below ?

    Table(String name, List<Column<?>>)

the use case is little bit wired that I had a subclass from `Table`

    Cashflow extend Table {}

 instance of `Cashflow` call a method from `Table` every time, the method will return a `Table` instance, so each time I have to convert them back to `Cashflow` . so in my file

    public Cashflow extend Table {
       public Cashflow(String name){
             super(name);
    }
       public Cashflow(String name, List<Columns> cols){
             super(name, cols)     // it won't work
    }
       public Cashflow CALCULATION ( Cashflow cf){
           Table x = ...... // some calcualtion which produce a Table

            return new Cashflow(x.name, x.columns);  // here is the problem
      }

    }

**Comment by lwhite1** [comment]
You can pass the columns as an array.

**Comment by yellowbean** [comment]
thank you very much Mr.Larry
