### ISSUE TITLE
 Question: Create histogram that shows Percentage, rather than count on y axis?

### ISSUE THREAD

**Issue by PWCSeanEgan** [jtablesaw/tablesaw#681]
I'm new to using tablesaw and I've managed to make a histogram with both:

- HistogramTrace.builder and;
- Histogram.Create

I am struggling with the customisation, how do I create histogram that shows Percentage, rather than count on y axis?

I'm sure I could get there in a very manual fashion by doing the categorization and counting manually and converting to a percentage, but I assume this functionality exists somewhere in the trace/chart configuration as a default behaviour.

**Comment by lwhite1** [comment]
I'm afraid it does not. It would be easier to add it than to work around
it, I believe.

The histogram trace needs a new property called histnorm. This is the js
that needs to be rendered.

var trace = {
...
type: 'histogram', histnorm: 'probability', ....
There would need to be updates to the HistogramTrace class and its builder,
and the template file trace_template.html.

This is the plot.ly js documentation for histnorm:

histnorm <https://plot.ly/javascript/reference/#histogram-histnorm>
*Parent:* data[type=histogram]
*Type:* enumerated , one of ( "" | "percent" | "probability" |
"density" | "probability
density" )
*Default:* ""

Specifies the type of normalization used for this histogram trace. If "",
the span of each bar corresponds to the number of occurrences (i.e. the
number of data points lying inside the bins). If "percent" / "probability",
the span of each bar corresponds to the percentage / fraction of
occurrences with respect to the total number of sample points (here, the
sum of all bin HEIGHTS equals 100% / 1). If "density", the span of each bar
corresponds to the number of occurrences in a bin divided by the size of
the bin interval (here, the sum of all bin AREAS equals the total number of
sample points). If "probability density", the area of each bar corresponds
to the probability that an event will fall into the corresponding bin
(here, the sum of all bin AREAS equals 1).

**Comment by PWCSeanEgan** [comment]
Thanks for the response.

I'm **very** new to Java and the code that I write looks like spaghetti made by a toddler. I would struggle to make the adjustments to histogram trace in tablesaw myself and if I managed it the code would not be robust or efficient.

For my problem I guess I will work around it manually, unless it's likely that this capability would be added to Tablesaw soon.

**Comment by lwhite1** [comment]
I don't imagine it will be soon enough for whatever you're working on, but
sometime in the next few weeks is probably a reasonable guess. I have a bit
too much on my plate right now to jump in and fix it in the next few days.

**Comment by PWCSeanEgan** [comment]
That's no hassle. 

A few weeks should be fine as I've got enough to work on that I may be able to park this problem for the update and use the count plot while waiting.

**Comment by lwhite1** [comment]
In PR #700 this feature is implemented. I will get it onto master today.

**Comment by lwhite1** [comment]
Closing. This was fixed a long time ago
