### ISSUE TITLE
Question: How do I create a calculated column?

### ISSUE THREAD

**Issue by lucasvwamp** [jtablesaw/tablesaw#687]
How do I use tablesaw to create a calculated column?

For example, in SQL I could write `SELECT SUM(col1) + SUM(col2) AS groupsum FROM table GROUP BY id`, but I have not been able to figure out how to do that with tablesaw.

**Comment by lwhite1** [comment]
@lucasvwamp 
There's more than one way, but you can do this:

```
Table result = table.summarize("col1", "col2", AggregateFunctions.sum).by("id");
```
where col1, col2, and id are the respective column names. 
As with the SQL version you get a new table with the aggregated columns and the groups, rather than a single calculated column.

**Comment by lucasvwamp** [comment]
@lwhite1 
If I'm not mistaken, that will result in the table
`id, sum (col1), sum (col2)`

Is there a way to sum the two columns together?

**Comment by lwhite1** [comment]
result.numberCol("sumCol1").add(result.numberCol("sumCol2"))

**Comment by lwhite1** [comment]
closing. Please reopen if this answer was not sufficient
