### ISSUE TITLE
How can I join tables with different columns type?

### ISSUE THREAD

**Issue by lusnyaktah** [jtablesaw/tablesaw#688]
For example, the first table column is an integer type and the second table column is a long type, and I want to join tables with those columns. Now I am getting the following error:

`Exception in thread "main" java.lang.ClassCastException: tech.tablesaw.index.FloatIndex cannot be cast to tech.tablesaw.index.IntIndex`

**Comment by benmccann** [comment]
You can convert one of the columns to be the same type as the other before doing the join

**Comment by lusnyaktah** [comment]
Thanks for your answer, but there isn't a method to set the type of column. How should I convert the type?
