### ISSUE TITLE
Table transpose()?

### ISSUE THREAD

**Issue by jackie-h** [jtablesaw/tablesaw#696]
I'm looking for a way to transpose a table. Similar to Panda's DataFrame.transpose().
Is there currently an easy way to do this?

**Comment by benmccann** [comment]
I'm not aware of a method for it. We'd be open to a PR :-)

**Comment by lwhite1** [comment]
May not be what you’re looking for but take a look at the support for
pivoting.  IIRC there’s a method on table called pivot.

**Comment by lwhite1** [comment]
Having looked at pivot, it doesn't do simple transposing. We should probably add transpose(). 
The difficulty, of course, is that all the resulting columns must have a single type, which should probably be the "least common denominator" type for the given table, defaulting to StringColumn (or perhaps TextColumn), if the types are disparate.

**Comment by benmccann** [comment]
Closing as implemented
