### ISSUE TITLE
implement the "cast" and "melt" tidy operations

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#698]
The classic paper on Tidy Data describes two operations that help make messy data tidy. We should probably implement those as they look pretty handy and not too difficult. The paper is attached
[tidy-data (1).pdf](https://github.com/jtablesaw/tablesaw/files/3784742/tidy-data.1.pdf)

**Comment by benmccann** [comment]
This looks similar to `transpose` (https://github.com/jtablesaw/tablesaw/issues/696) where the operation is easiest to apply if all columns are the same type

**Comment by lwhite1** [comment]
more detailed paper on the operations attached[
[Reshaping Data with the reshape Package.pdf](https://github.com/jtablesaw/tablesaw/files/5850038/Reshaping.Data.with.the.reshape.Package.pdf)
](url)

**Comment by lwhite1** [comment]
basic implementations of Cast and Melt are done. There's room for improvement/extension no doubt, but I will close this
