### ISSUE TITLE
Column.mapInto does not append

### ISSUE THREAD

**Issue by emilianbold** [jtablesaw/tablesaw#704]
The `Column.mapInto` documentation claims:

> Maps the function across all rows, appending the results to the provided Column

Except it doesn't seem to append data, just replace data. Particularly, creating an empty column to map something into will fail because `into.set` is called but `into.size() == 0`.

We could claim the name is correct as `into` might suggest replacing values, not appending.

Still, `Column` needs some way to convert the data type too. We have `map(Function<? super T, ? extends T> fun)` which does not allow, eg. a `String` to `double` conversion.

I suggest at least changing the Javadoc and showing an example as to how to covert types.

**Comment by benmccann** [comment]
I'd probably prefer changing the javadoc rather than the behavior since the method's been around awhile

**Comment by emilianbold** [comment]
Fixed by PR #705
