### ISSUE TITLE
Paging to disk ?

### ISSUE THREAD

**Issue by jackie-h** [jtablesaw/tablesaw#706]
Is there, or would it be possible to add a paging to disk option, for operating in low memory environments (desktop) with large files ?
This is something we have in our in-house C++ framework that we are trying to replace. TableSaw is looking very promising on a number of fronts, but this is a feature we would need to complete the replacement (I appreciate it is non-trivial to implement!).

**Comment by benmccann** [comment]
TableSaw uses [fastutil](http://fastutil.di.unimi.it/) internally to store data. As far as I know, this isn't a feature they support.

**Comment by lwhite1** [comment]
@jackie-h 
Depending on your OS, it may be possible to use disk as virtual memory, but I don't see us making such a significant change.

**Comment by jackie-h** [comment]
Our current framework is able to use memory mapped files and keep process memory usage under a few hundred Mb which is a cool feature, but I appreciate that's non-trivial without changes to the collections backing TableSaw

**Comment by lwhite1** [comment]
I don't see us making a change like this.
