### ISSUE TITLE
Suggestion: Table.summary() should ideally return a Table

### ISSUE THREAD

**Issue by jackie-h** [jtablesaw/tablesaw#707]
It would be nice to have a feature on the Table that mirrors the Pandas Dataframe.describe() feature.
Column.summary() is the equivalent on a column, but it would be nice if Table.summary() brought the column summaries together into a table that can then be used as a Table (similar to Dataframe.describe()).
Today Table.summary() returns a string, but instead you could do Table.summary().print() to get the String version and keep that feature. 
I'm looking for feedback on this suggestion. If it sounds like a good one, I might attempt the pull request.
For context - I am translating some Python ML code into Java, and looking for equivalent methods

**Comment by benmccann** [comment]
That sounds reasonable to me. @lwhite1 is more familiar with the `summary` method than I am, so I'd probably want his feedback as well

**Comment by benmccann** [comment]
Closing as implemented. I really like this change!
