### ISSUE TITLE
Question: count rows by multiple columns

### ISSUE THREAD

**Issue by dkulczycki** [jtablesaw/tablesaw#711]
How do I use tablesaw to count rows by multiple columns. 
For example something like 
SELECT A, B, COUNT(*) FROM X GROUP BY A, B

**Comment by dkulczycki** [comment]
ok, i have column named GROUP and i got IllegalArgumentException

_Exception in thread "main" java.lang.IllegalArgumentException: Cannot add column with duplicate name String column: GROUP to table  summary_

`Table x = tableMain.summarize("GROUP", count).by("CATEGORIZATION_DATE", "GROUP");`

after changing the column name everything is fine

**Comment by lwhite1** [comment]
> Scatter3DPlot.create("3D plot", data, "x", "y", "z")
Yeah this is unfortunate, but summarize creates a column called group  that holds the names of the groups.

I assume you were able to get the results you wanted. If not please feel free to reopen.
