### ISSUE TITLE
Plotly - set autoSize in LayoutBuilder

### ISSUE THREAD

**Issue by smpawlowski** [jtablesaw/tablesaw#712]
Hi,

I would like to use Plotly autosize=True, but it cannot be set in [LayoutBuilder](https://github.com/jtablesaw/tablesaw/blob/master/jsplot/src/main/java/tech/tablesaw/plotly/components/Layout.java): 

```
private final boolean autoSize = false;
```

Do you think it could be exposed?
Best regards!

**Comment by emilianbold** [comment]
If you are comfortable with building tablesaw yourself, could you test PR #713 and see if it fits your needs?

**Comment by smpawlowski** [comment]
Thanks! I tested with this and Chrome:
```
	public static void main(String[] args) {

		int n = 500;
		double[] x = new double[n];
		double[] y = new double[n];

		for(int i=0; i<n; i++) {
			x[i]=i;
			y[i]=i;
		}

		Layout layout = Layout.builder("title", "X", "Y").autosize(true).build();
		ScatterTrace trace = ScatterTrace.builder(DoubleColumn.create("X",x),
				DoubleColumn.create("Y",y)).build();
		Figure fig = new Figure(layout, trace);

		Plot.show(fig);

	}
```

This doesn't work out of the box. I got correct resizing after following changes to html:

1. Remove height and width from layout.
2. Define `<div id='target' style="width:100%;height:100%;"></div>`
3. Remove first line `<!DOCTYPE html>`. <- quite weird that this is required ...

I attach fixed html. Just open in browser to see what happens. You may need to reload after resizing browser window.
[fix2.zip](https://github.com/jtablesaw/tablesaw/files/3814353/fix2.zip)

**Comment by emilianbold** [comment]
Thanks for looking into it!

What you are noticing happens because `builder(String title)` does
`Layout.builder().title(title).height(DEFAULT_HEIGHT).width(DEFAULT_WIDTH)`
and thereby sets the width/height.

You need to painstakingly build the layout like this:

```java
Layout layout = Layout.builder()
                        .title("title")
                        .xAxis(Axis.builder().title("X").build())
                        .yAxis(Axis.builder().title("Y").build())
                        .autosize(true)
                        .build();
```

and `autosize` will work.

I didn't want to go in all the places the dimensions are set since
obviously existing users assume that. Maybe some Javadoc would help to
clarify the default width/height.

--emi

**Comment by emilianbold** [comment]
PS: I wonder if given this tradition of default width / height it
wouldn't make sense for autosize(true) to reset the existing width
height? Users would still be able to set the height by calling it
*after* autosize, eg. .autosize(true).width(xx);

--emi

**Comment by smpawlowski** [comment]
Hey, @emilianbold with your suggestion width is adjusted, but not height. This is because 1. is addressed, but not 2. and 3.

**Comment by emilianbold** [comment]
Not sure this is a good use case. `autosize` with `Plot.show` seems like a
way to make a full screen chart. But for exploratory viewing it doesn't
matter.

`autosize` makes sense where you have a more complex webpage and you just
insert the Figure. In that case the surrounding div is out of the control
of Tablesaw...

--emi

joi, 7 nov. 2019, 11:15 smpawlowski <notifications@github.com> a scris:

**Comment by smpawlowski** [comment]
Use case is extremely simple - I create some complex chart and I would like to view it in full screen using Plot.show(fig). Generating a tab with full screen chart is also useful for complex charts with a lot of data.

I can use lower level functions to achieve the above, but it would be nice if tablesaw could just do it out of the box. This PR is obviously already helpful.

**Comment by emilianbold** [comment]
I not entirely sure why 2. and 3. are needed and they seem to be needed for a narrow usecase so I'm reluctant to change the PR. You are free to try a PR particularly for this though.

The way I see it, the div has an `id` so you could set the dimensions to 100% via CSS/JS if you would have a larger HTML page where the figure is just inserted. So, replacing the clean `<div id=` with `<div id= style="width:100%;height:100%;"` looks wrong to me.

The div is generated in `Figure.divString` if you want to prepare a PR.

As for `DOCTYPE html`, that looks even stranger. It's part of `page_template.html` if you want to prepare a PR.

**Comment by smpawlowski** [comment]
Sure, fair enough on separate PR.

**Comment by lwhite1** [comment]
Moving this to the new plotly.java repo: https://github.com/jtablesaw/plotly.java/issues/9
