### ISSUE TITLE
Provide documentation via javadoc

### ISSUE THREAD

**Issue by gayathri-krishnan** [jtablesaw/tablesaw#714]
I was looking at tablesaw for some data manipulations I need to do for my application. I am used to java doc, as a source for figuring out what a piece of code does, other than looking at the code itself. Can we introduce javadoc for the java code?

**Comment by lwhite1** [comment]
There is javadoc. https://www.javadoc.io/doc/tech.tablesaw/tablesaw-core/0.36.0/index.html

If you would like to help improve it that would be great.

**Comment by gayathri-krishnan** [comment]
Thanks Larry. I would love to. Let me add on and raise a PR.
