### ISSUE TITLE
display a table itself

### ISSUE THREAD

**Issue by CharlieXu** [jtablesaw/tablesaw#715]
I am new here, And, I find this package is awesome. 
Hi, I want to know if we can display a table itself on the webpage ? 
I want to see some data at the same time with the graph plotted. 

if not, do we have some plan to display the data itself ? 

Thank,

**Comment by benmccann** [comment]
I know it's supported in the BeakerX Jupyter notebooks. I haven't used the jsplot stuff before, so will let someone else chime in there

**Comment by lwhite1** [comment]
We don't support Plotly tables, but the HTML sub-project can output tables as HTML. 
e.g.
```
   String output = table.write().toString("html");
```
