### ISSUE TITLE
Simple API Changes for jsplot-plotly

### ISSUE THREAD

**Issue by nielsgron** [jtablesaw/tablesaw#716]
I would like to suggest some simple API changes to the jsplot-plotly classes which will slowly help in the direction proposed in issue #693.  If these suggestions sound acceptable, I can work on a PR.

1) Figure.java : Add methods .setTraces(Trace[]), .setLayout(Layout) & .setEventHandlers().

2) Figure.java : Change methods buildContext(), plotFunction(), eventHandlerFunction to "protected" instead of "private" so that they can be overridden.

3) For all Plot classes in tech.tablesaw.plotly.api.*, extend the classes to Figure.java.

4) Make the constructor of Heatmap (tech.tablesaw.plotly.api) public.

5) For all *Plot classes create constructors with parameters that match the static create() methods of each class, with an added Layout object.  The constructors would do the same as the static methods except that it would setXXX() the layout, trace and eventhandlers instead of creating a new Figure.

If these changes are made, then the following will be true :

a) It will not break the current API.
b) It will allow users of Tablesaw to set a custom Layout object for each of the Plot classes.
c) It will allow users of Tablesaw to take advantage of inheritance and create classes which extend the Plot classes and override the underlying methods, so that they can make enhancements or changes to the current implementation.
d) It will allow users of Tablesaw to contribute their enhancements to the Tablesaw project, but still use their custom enhancements and the latest Tablesaw release while waiting for the acceptance of the enhancements and a new release with the changes.

**Comment by xcjusuih** [comment]
Is these suggestions acceptable? I see some of them are accepted in master and I can make pr for the rest if you accept them.

**Comment by lwhite1** [comment]
moved to new ploty.java repo. See https://github.com/jtablesaw/tablesaw/issues/716
