### ISSUE TITLE
Question: Timestamp in TimeSeriesPlot

### ISSUE THREAD

**Issue by edgar131** [jtablesaw/tablesaw#722]
I am currently mapping ResultSet's directly to Table objects and I have multiple Timestamp columns.  These Timestamp columns are being mapped to a InstantColumn, which in general is fine.  My problem lies in the fact that I would like to create a TimeSeriesPlot based on those columns, however it appears TimeSeriesPlot require that the columns be a DateColumn.  Is there any way to handle this gracefully or do I need to somehow create a new table where I convert the InstantColumn into a DateColumn for consumption of the plotly library?

**Comment by benmccann** [comment]
You'd probably want to map to `DateTimeColumn` which looks to be accepted as well

I haven't worked on the jsplot stuff at all, but it sounds like extending it so that it works with `InstantColumn` could make sense

**Comment by lwhite1** [comment]
fixed
