### ISSUE TITLE
Responsive Charts

### ISSUE THREAD

**Issue by chetansaini39** [jtablesaw/tablesaw#723]
How  to generate responsive charts

**Comment by benmccann** [comment]
https://www.chartjs.org/docs/latest/general/responsive.html

**Comment by benmccann** [comment]
Sorry. I got this confused with the other open source project I'm currently working on :-)  Please ignore my last comment

**Comment by chetansaini39** [comment]
Thanks a lot. It was a weird problem.
I tried the modify the JS returned from the java function to fit into https://plot.ly/javascript/responsive-fluid-layout/
but even that didnt work.
Appreciate you looking into.

**Comment by lwhite1** [comment]
This will be fixed in 1.0.
