### ISSUE TITLE
Cumulative sum by group

### ISSUE THREAD

**Issue by chuckol-work** [jtablesaw/tablesaw#727]
Assuming numeric data, I know you can get a cumulative sum column from a numeric Column. 
I also know that you can get a total sum of groups of data using summarize().by().
But, I don't think I can get a cumulative sum of only grouped data. That is, instead of a single aggregate value for a group of data, I want a sub-column or a column section for that group of data.
For example, given:

OrderName|DeliveryDay|AmountOrdered|AmountDelivered
------------|------------|----------------|------------------
Order1|2|30|3
Order1|3|30|13
Order1|4|30|14
Order2|3|10|5
Order2|4|10|5
Order3|3|20|18
Order3|4|20|2

What I want is the ability to, say, have another column that contains the computed cumulative sum by each order, like:

OrderName|DeliveryDay|AmountOrdered|AmountDelivered|CumulativeDelivered
------------|------------|----------------|----------------|----------------------
Order1|2|30|3|3
Order1|3|30|13|16
Order1|4|30|14|30
Order2|3|10|5|5
Order2|4|10|5|10
Order3|3|20|18|18
Order3|4|20|2|20

I want a sum row for each data row, accumulating AmountDelivered by OrderName. I don’t want a single row sum for all rows of the same OrderName (as summarize().by() would give me).

Is this possible? If not, I think it would make a useful addition to Tablesaw.

**Comment by J4nJ4nsen** [comment]
try the following:

1. `Table someTable = Table.create("someTable");`
2. then, add data a column `col` to table and import some data.
3. `NumericColumn<?> cumSumColumn = col.cumSum();`

this will do exactly what you want i guess.

**Comment by lwhite1** [comment]
I'm going to close this as the conversation seems to have lapsed, but I will add a column. 

If you want to make a cumulative sum using grouped data, I believe it can be readily done in two steps. 
1. use summarize().by() or equivalent to get group sums
2. step through the resulting table and calculate the result. 

There may be easier ways (including what is suggested above) but i didn't test it.
