### ISSUE TITLE
 java.lang.NoSuchMethodError: 'int it.unimi.dsi.fastutil.bytes.Byte2IntOpenHashMap.addTo(byte, int)'

### ISSUE THREAD

**Issue by GiovanniLeo** [jtablesaw/tablesaw#730]
Hi, I have tried this simple code:

`public class Test {`
    `public static void main(String[] args) {`
        `Table tb = Table.create("Test");`

```java
    String[] animals = {"bear", "cat", "giraffe"};
    StringColumn anim = StringColumn.create("Animal types", animals);
    
    tb.addColumns(anim);
    int colNumber = tb.columnCount();
    System.out.println(colNumber);

    System.out.println(tb.print());
    anim.append("tiger");
    System.out.println(tb.print());
}
```

`}`

But when I execute it I have this:

``Exception in thread "main" java.lang.NoSuchMethodError: 'int it.unimi.dsi.fastutil.bytes.Byte2IntOpenHashMap.addTo(byte, int)'`
	`at tech.tablesaw.columns.strings.ByteDictionaryMap.append(ByteDictionaryMap.java:217)`
	`at tech.tablesaw.api.StringColumn.append(StringColumn.java:423)`
	`at tech.tablesaw.api.StringColumn.<init>(StringColumn.java:116)`
	`at tech.tablesaw.api.StringColumn.create(StringColumn.java:72)`
	`at bolts.test.main(test.java:11)``
Line 11 is: ```StringColumn anim = StringColumn.create("Animal types", animals);```

I use this dependency:
```
        <dependency>
            <groupId>tech.tablesaw</groupId>
            <artifactId>tablesaw-core</artifactId>
            <version>0.36.0</version>
        </dependency>
```
Can someone help? Thanks a lot.

**Comment by benmccann** [comment]
Do you have any other dependencies? My guess is that another dependency specifies a different version of the fastutil library

**Comment by GiovanniLeo** [comment]
Yes, I use many dependencies because is a big project, but I specify this version of fastutil in my dependencies:
```
        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
            <version>8.3.0</version>
        </dependency>
```
Could be this the problem?

**Comment by GiovanniLeo** [comment]
I solved the problem, and I think that the problem was in my pc because I have formatted my pc and I have reinstalled Windows 10 and all seem works. Thanks a lot.

**Comment by benmccann** [comment]
Closing this since it was solved
