### ISSUE TITLE
After some test the problem is still here java.lang.NoSuchMethodError: 'int it.unimi.dsi.fastutil.bytes.Byte2IntOpenHashMap.addTo(byte, int)'

### ISSUE THREAD

**Issue by GiovanniLeo** [jtablesaw/tablesaw#731]
The code is this 
```
    public static void main(String[] args) {
        String[] animals = {"bear", "cat", "giraffe"};
        double[] cuteness = {90.1, 84.3, 99.7};

        Table cuteAnimals =
                Table.create("Cute Animals")
                        .addColumns(
                                StringColumn.create("Animal types", animals),
                                DoubleColumn.create("rating", cuteness));

        String[] animals2 = {"bear", "cat", "giraffe", "dog"};
        double[] cuteness2 = {90.1, 84.3, 99.7, 99.0};
        Table cuteAnimals2 =
                Table.create("Cute Animals2")
                        .addColumns(
                                StringColumn.create("Animal types", animals2),
                                DoubleColumn.create("rating", cuteness2));
    }
```
The result will be this:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'int it.unimi.dsi.fastutil.bytes.Byte2IntOpenHashMap.addTo(byte, int)'
	at tech.tablesaw.columns.strings.ByteDictionaryMap.append(ByteDictionaryMap.java:217)
	at tech.tablesaw.api.StringColumn.append(StringColumn.java:423)
	at tech.tablesaw.api.StringColumn.<init>(StringColumn.java:116)
	at tech.tablesaw.api.StringColumn.create(StringColumn.java:72)
```

I have tried the same code in a stand-alone project with the same and different versions of fast util and all work fine but in my project, that is a project were a lot of people have worked on it,  i have this problem.

Then I ran this command for print dependencies tree for the big project :
 `mvn dependency:tree -Dverbose -Dincludes=commons-collections`

And the result is:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DiMe ---
[INFO] com.unisa:DiMe:jar:1.0-SNAPSHOT
[INFO] +- com.opencsv:opencsv:jar:5.0:compile
[INFO] |  \- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |     \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] \- org.apache.storm:storm-core:jar:2.0.0:compile
[INFO]    \- org.apache.storm:storm-server:jar:2.0.0:compile
[INFO]       \- (commons-collections:commons-collections:jar:3.2.2:compile - omitted for duplicate)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.907 s
[INFO] Finished at: 2019-12-07T20:22:58+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by benmccann** [comment]
`mvn dependency:tree -Dverbose -Dincludes=commons-collections` is the wrong command to run. Can you post the results of `mvn dependency:tree -Dverbose -Dincludes=fastutil` instead?

**Comment by GiovanniLeo** [comment]
Yes, the result is this :
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DiMe ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.974 s
[INFO] Finished at: 2019-12-08T00:41:44+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by benmccann** [comment]
Hmm. That's not very useful as there's no output. Perhaps `mvn dependency:tree -Dverbose -Dincludes=*:fastutil`? You want it to print how fastutil is being pulled into your project. I'm guessing you're using some library that's using an old version of fastutil (<= 5.0.9)

**Comment by GiovanniLeo** [comment]
The result is this:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DiMe ---
[INFO] com.unisa:DiMe:jar:1.0-SNAPSHOT
[INFO] +- it.unimi.dsi:fastutil:jar:8.3.0:compile
[INFO] \- tech.tablesaw:tablesaw-core:jar:0.36.0:compile
[INFO]    \- (it.unimi.dsi:fastutil:jar:8.2.1:compile - omitted for conflict with 8.3.0)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.012 s
[INFO] Finished at: 2019-12-08T15:44:43+01:00
[INFO] ------------------------------------------------------------------------
```
but i have run also:
`mvn clean install -U`
and the problem is still here.
Then I deleted the folder `C:\Users\$USERNAME\.IntelliJIdeaX.X ` then the indexing and download
have been done again, and also with the conflict that I have reported before all seems work,
but I'd like to know how this is possible. Moreover, if this can be a way to solve this problem,
this can be inserted into some sections of the documentation?  This only to help other developers. 
Thanks a lot for the support and I'm sorry if I disturb you.

**Comment by benmccann** [comment]
Ok. I just want to be 100% sure since the command you ran wasn't included in your last post - the command you ran that printed that output was `mvn dependency:tree -Dverbose -Dincludes=*:fastutil`?

Can you remove `it.unimi.dsi:fastutil:jar:8.3.0` from your project and just use the version of fastutil that Tablesaw supplies and see if that helps?

**Comment by GiovanniLeo** [comment]
Yes the output that I post before was obtained from this command `mvn dependency:tree -Dverbose -Dincludes=*:fastutil`. Yes I can remove `it.unimi.dsi:fastutil:jar:8.3.0` and I will do some test.

**Comment by GiovanniLeo** [comment]
All seems to work well, then I have another question. Is there a function that given two tables for example:
```
       Cute Animals        
 Animal types  |  rating  |
---------------------------
         bear  |    90.1  |
          cat  |    84.3  |
      giraffe  |    99.7  |

       Cute Animals2       
 Animal types  |  rating  |
---------------------------
         bear  |    90.1  |
          cat  |    84.3  |
      giraffe  |    99.7  |
          dog  |      99  |
```
give the possibility to make the difference between these two Tables as in the set theory, so I want that the resulting Table is this: 
```
    Resulting Table    
 Animal types  |  rating  |
---------------------------
          dog  |      99  |
```

**Comment by benmccann** [comment]
Ok, I will close this since you said it works well now

I don't think a method like that exists. You would have to write your own
