### ISSUE TITLE
Question : about casting InstantColumn to DateTimeColumn (& a TimeSeriesPlot weird behavior)

### ISSUE THREAD

**Issue by bobrayEden** [jtablesaw/tablesaw#736]
Hello,

I'm currently trying to use a ResultSet to produce a TimeSeriesPlot (as in Issue#722) directly from my database's webapp.
When reading my data from the ResultSet, tablesaw map a column configured as Datetime in SQL to an InstantColumn. I tried to find a workaround to cast the instantcolumn to the required type, but didn't succeed... 

EDIT : i finally succeeded in manipulating columns and datatypes, but the TimeSeriesPlot seems to not accept DateTime, but only Date

On a side note, with this InstantColumn, I still can make a TimeSeriesPlot like this:
`Figure figure = TimeSeriesPlot.create(
                    "plot-title",
                    tablename,
                    "xcol",
                    "ycol");`

but can't use the grouping attribute to display 2 or more sets of Datas refering to the same instants:
`Figure figure = TimeSeriesPlot.create(
                    "plot-title",
                    tablename,
                    "xcol",
                    "ycol",
                     "groupingCol");`
as it returns the error (class tech.tablesaw.api.InstantColumn cannot be cast to class tech.tablesaw.api.DateTimeColumn).

Thanks for your reading!

**Comment by benmccann** [comment]
I suppose `TimeSeriesPlot` should be updated to work with `InstantColumn`. In the meantime you can call `asLocalDateTimeColumn()` on the `InstantColumn` to get the appropriate type

**Comment by bobrayEden** [comment]
Thanks for your answer Ben. I'll try this call to refactor my code.

About the TimeSeriesPlot, i ended up modifying a method from the class (actually, merging two methods in one)  to allow the display of several sets of DateTime datas by grouping on an attribute.

    public static Figure custom(String title, Table table, String xTitle, Integer dateTimeColumnIndex, String yCol, String groupCol) {
        TableSliceGroup tables = table.splitOn(new CategoricalColumn[]{table.categoricalColumn(groupCol)});
        Layout layout = Layout.builder(title, xTitle, yCol).build();
        ScatterTrace[] traces = new ScatterTrace[tables.size()];

        for (int i = 0; i < tables.size(); ++i) {
            List<Table> tableList = tables.asTableList();
            Table t = ((Table) tableList.get(i)).sortOn(new String[]{xTitle});
            traces[i] = ScatterTrace.builder(t.column(dateTimeColumnIndex),
                    t.numberColumn(yCol)).showLegend(true).name(((Table) tableList.get(i)).name()).mode(ScatterTrace.Mode.LINE).build();
        }

        return new Figure(layout, traces);
    }

Not graceful but it worked and suited my direct needs.
