### ISSUE TITLE
Exporting to XLSX

### ISSUE THREAD

**Issue by gavioto** [jtablesaw/tablesaw#737]
Documentation says that it is possible to export to excel. It is really possible. 
I couldn't found nothing in the repo or internet about how to export to Excel . 

Is it really possible? I other case, I think docs should be updated.

https://jtablesaw.github.io/tablesaw/userguide/importing_data.html

Regards

**Comment by benmccann** [comment]
Yes, that should be updated, you can only import from Excel at the moment.

**Comment by benmccann** [comment]
Fixed https://github.com/jtablesaw/tablesaw/commit/8a99fa1c1a3e287edc28c8f748381b0299d14b1a

**Comment by gavioto** [comment]
Thank you. 

I'm interested in this functionality, so I think I can advance or crate some kind of prototype for this. 
My idea is to reuse the export CSV when possible with an initial "string" for all columns approach.

Any suggestion?

**Comment by benmccann** [comment]
Sounds fine to me. @hallvard wrote the Excel integration

**Comment by hallvard** [comment]
The structure of the exported sheet should be easy to create, the most difficult aspect is preserving type info. But I guess you can reuse some logic from the import code. You could try to extract some common logic into a class shared by import and export code.
