### ISSUE TITLE
BoxBuilder's name(String) method returns TraceBuilder instead of BoxBuilder

### ISSUE THREAD

**Issue by Traderjoe95** [jtablesaw/tablesaw#740]
The `name` method on the `BoxBuilder` class fails to return a `BoxBuilder` again, but returns the inherited `TraceBuilder` instead, which does not have a `build()` method and thus breaks the fluent builder pattern.

I think the method should be overwritten in `BoxBuilder`.

**Comment by lwhite1** [comment]
fixed in PR #763

**Comment by lwhite1** [comment]
fixed.
