### ISSUE TITLE
Static members in column type

### ISSUE THREAD

**Issue by axkr** [jtablesaw/tablesaw#749]
Shouldn't this kind of comparator definitions be static or am I missing something?
https://github.com/jtablesaw/tablesaw/blob/6fc6a4d013e4cb92b5a8dc13d2d5e2fc62ec1460/core/src/main/java/tech/tablesaw/api/DoubleColumn.java#L34

**Comment by benmccann** [comment]
Yeah, probably. PR welcome :-)

**Comment by lwhite1** [comment]
I'm going to close this. I agree that these should probably be static, but i don't see any practical benefit as the comparators all either return a singleton or, as in this case, simply call a static method on another class. 

If someone feels that i'm wrong about this, or finds the status quo unacceptable, please feel free to re-open or submit a PR.
