### ISSUE TITLE
CSV writer always closes output streams

### ISSUE THREAD

**Issue by Traderjoe95** [jtablesaw/tablesaw#750]
At the moment, when CSV data is written to an output stream via `table.write.csv(outputStream)`, the stream is closed afterwards. That will, in some cases be unwanted behavior, for example when writing to a ZIP file, as in my case.

I am currently using the following workaround:
```java
ByteArrayOutputStream baos = new ByteArrayOutputStream();
data.write().csv(baos);
archiveOut.write(baos.toByteArray());
```

In my opinion, that workaround is fine, but the library should generally not close streams it hasn't opened itself.

I found that my issue is similar to #316 which is closed as resolved, but I am still (or maybe again?) experiencing the same issue in version 0.37. If you have fixed it in one of the releases between 0.37 and 0.37.3, please go ahead and close this.

**Comment by benmccann** [comment]
#316 was from 2018, so I'm guessing there's been a regression since then. Please feel free to send us a fix if you'd like. Probably no one will have time to address it otherwise

**Comment by lwhite1** [comment]
@benmccann Is it safe to say we want to only close when the user provides a filename string or a file, and not under other circumstances? 

I'm not sure what to do with Options since the user can specify a file or name, and separately pass writeOptions, but alternatively, they could bundle the destination into the options and just give us that.

**Comment by benmccann** [comment]
> Is it safe to say we want to only close when the user provides a filename string or a file, and not under other circumstances?

I think so. I'm assuming the other circumstances would be a `Reader` or a `Stream`
