### ISSUE TITLE
Get problem with JoinOn performance

### ISSUE THREAD

**Issue by Friendwork** [jtablesaw/tablesaw#752]
My company is developing an ETL tool which use tablesaw as DTO between "nodes". 
I am trying to join 2 tables around 15M records, it takes ~15 min to process.  Are there any parallel mechanisms such as streaming to speed up?  
And another operator gets the same problem when process large amount of data.

**Comment by benmccann** [comment]
This might be the largest use case we've had yet. We haven't really spent time optimizing for joins of this size though some optimization work did happen in https://github.com/jtablesaw/tablesaw/issues/383. Please feel free to investigate further. All the maintainers are pretty wrapped up at the moment, so probably we won't have time to investigate

**Comment by civic-networks** [comment]
@Friendwork, 

You may want to check how much GC is going on.
 
if you're sure your application has sufficient memory for a job of this size, but it's still slow, you will probably need to write the join by hand (sorting the tables and stepping through them should be reasonable quick, and amenable to parallelization if it's still needed).

**Comment by lwhite1** [comment]
@Friendwork 
Can you provide more info about the issue? It would be helpful to better understand the specifics. 
- do both tables have 12 million records
- is the join on a single column in each, or on multiple columns
- what type is the join column
- how wide are the tables (column counts)
- how big are they (memory) if they're CSV files, what's the size on disk 
- what does the relationship between columns look like? (1 to 1, 1 to many). 
- if it's one to many, do you have any information about the distribution of the relationships

I'm also curious if you've tried joining them in a database and how that performed.

thanks.

**Comment by Friendwork** [comment]
@lwhite1 I tried again and there is the test result:
1.  Both tables have 100k records.
2. Join on a single column
3. Type of the join column is String
4. Each table have 5 columns, so the result will be 10 columns
5. Around ~ 200MB
6. 1 to many
7. I have no idea about the distribution of the relationships, cuz the join column is chosen by end-user.

Some time i got out of memory exception, even the heap size is set to 6GB

**Comment by lwhite1** [comment]
This seems like a completely different problem from the one you first reported.

originally
joining 12 M records too slow.

now
joining 100,000 records causing OOM error.

Looking at the second problem. 
If the join column is chosen by the user they could choose to join things that cause a significant growth in the resulting table.

For example:
table 1 has 4 rows and n columns. Join column contains the values A,A,B, B.
table 2 has 4 rows and n column. Join column contains the values A, A, B, B.

Join table gets 8 rows and all the columns in both tables, so it's twice as big as the the two original tables.

If you have 100,000 rows in each table and only two values (half A and half B), you'd get 
50,000^2 rows + 50,000^2 = 50 billion rows.

So I don't even know if there's a problem here without a concrete example.

**Comment by lwhite1** [comment]
closing as inactive. (and vague)
