### ISSUE TITLE
Join with an empty table adds garbage values

### ISSUE THREAD

**Issue by shadabk96** [jtablesaw/tablesaw#754]
If I perform a full outer join between table1 containing some rows and table2 which is empty, the columns present in table2 and not in table1 have -2147483648 as value for each row from table1. 

Is it possible to provide a default value for such cases or some other workaround?

**Comment by benmccann** [comment]
-2147483648 is 11111111111111111111111111111111 in binary. I.e. the minimum integer that will fit in 32 bits. `IntColumnType.missingValueIndicator` is `Integer.MIN_VALUE`. So basically it's sticking a missing value there, which seems like it's the right thing to do.

You can check for missing values before using the value from the table, which hopefully will address the issue for you. I also noticed that in our number columns we don't do this check for you automatically when we call `get`, so I've changed that (https://github.com/jtablesaw/tablesaw/commit/cbddcfb03f98b29787f882f1ceddaa0fe6896fef) and the improvement will be in the next release. But in the meantime you can do the check yourself.
