### ISSUE TITLE
Example file BarExample.java resulting in multiple Errors

### ISSUE THREAD

**Issue by noufanpmc** [jtablesaw/tablesaw#755]
Hi!

I am new to java and I'm trying to learn to built charts using tablesaw. This tool is really awesome. Has all kind of charts and graph for visualization. So I tried to see how it works and executed  the example file provided. But unfortunately I am getting errors. Please help me on this. I'll describe what I tried to do and also the error I got. 

I've tried to run the exact code which were used by you in the BarExample.java file. But it's showing erros. I've done all the importing and also used the same tornadoes_1950-2014.csv file as my dataset.

The error I'm getting are:
1) In this line:-
IntColumn scale = table.intColumn("scale");
The error shown:-
The method intColumn(String) is undefined for the type Table. 

2) Also in the next line:-
scale.set(scale.isLessThan(0), IntColumnType.missingValueIndicator());
The error shown:- 
The method isLessThan(int) is undefined for the type IntColumn

3)Another  one in this line:-
Table summaryTable = table.summarize("fatalities", "log injuries", sum).by("Scale");
The error shown:-
sum cannot be resolved to a variable.

Even after doing the suggested error resolve factors by eclipse I am not able to get the bar chart which I am trying to implement.
This is the final error I am getting:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'tech.tablesaw.api.NumberColumn tech.tablesaw.api.Table.numberColumn(java.lang.String)'
at BarChart.main(BarChart.java:32)

Hope you understand my concern and help me on this issue.

Thanks in advance.

Have a nice day

**Comment by noufanpmc** [comment]
Hi!

Even after doing the suggested error resolve factors by eclipse I am not able to get the bar chart which I am trying to implement.
This is the final error I am getting:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'tech.tablesaw.api.NumberColumn tech.tablesaw.api.Table.numberColumn(java.lang.String)'
	at BarChart.main(BarChart.java:32) 

Hope you understand my concern and help me on this issue.

Thanks in advance.

Have a nice day

**Comment by benmccann** [comment]
Make sure you are using the latest release TableSaw 0.37.3

Are you using Maven or Gradle or some other build system?

This really isn't an issue in TableSaw, but is just an issue with the basics of setting up a Java project. Is there an experienced developer you could ask for help in person?

**Comment by noufanpmc** [comment]
Thank you so much for the reply.

Yes I'm using latest version of tablesaw and using maven as well.

Let me see about this basic issue of java with someone.

Thanks and regards


Le jeu. 13 févr. 2020 à 15:30, Ben McCann <notifications@github.com> a
écrit :

**Comment by noufanpmc** [comment]
Hi!
I just have one more query.
Do I have to download the entire git file for tablesaw and  do add project
in eclipse? Or does maven helps in adding all the dependencies by adding
the provided code in pom.xml file?

Thanks and Regards

**Comment by noufanpmc** [comment]
Haaa...Thank god It worked finally.

Thanks for your help.

Now I've to built charts using my dataset. I don't whether it'll be
possible. Because all the charts depends on the fields/column we choose
right.

I've to built using Titanic dataset.

Hope you'll be able to help me if I'm stuck at some point. :)

Thanks and Regards

**Comment by lwhite1** [comment]
IIUC, this initial issue is resolved. Please let us know if you have other trouble.
