### ISSUE TITLE
Example for using a customer ColumnType?

### ISSUE THREAD

**Issue by axkr** [jtablesaw/tablesaw#757]
Is there an example available how I can use my own customer ColumnType?

For example if tablesaw detects a String or Text column, which I would like to parse to another column type?

**Comment by benmccann** [comment]
You can call `.map` or `.mapInto` on a column and provide a function that applies any transformation you wish

**Comment by lwhite1** [comment]
To add to @benmccann's response, if what you really want is an Object of type Customer, you would need to have your conversion code output a List<Customer> and work outside of tablesaw after the conversion completes.

**Comment by benmccann** [comment]
I'm going to consider this as solved. Let us know if you still have questions
