### ISSUE TITLE
jsplot's TemplateUtilsTest is order sensitive, due to static field initialisation problem

### ISSUE THREAD

**Issue by hallvard** [jtablesaw/tablesaw#761]
TemplateUtilsTest has two test methods, testDefaultTemplateLocation tests that the default template lookup works, testCustomTemplateLocation tests that setting a custom location works. If they run in this order, the second fails, as is does on my mac after a fresh clone and running `mvn test`. However, it works when run alone (or in a fresh VM).

The problem has to do with initialisation of static fields, `templateLocations` in `TemplateUtils` and `engine` in `Component`. The `engine` field captures the value of `templateLocation`, so later changes doesn't affect it. And since that static `engine` field is used by Page (while some other Components have non-static engine field), you must set the custom template location before using any Component. This clearly isn't realistic...

I would create a PR, but here I'm not sure what solution is preferred. Personally, I would avoid the static engine field in Component.

**Comment by benmccann** [comment]
Ah, I'd just disabled the test because it was failing on my machine (https://github.com/jtablesaw/tablesaw/commit/90087bb0e5a87eaf84c807024aa62cdcf30eab66). I figured it was some kind of environment issue. Glad you figured out what was going on

+1 to removing static fields

**Comment by emilianbold** [comment]
Interesting. The static modifier was introduced in my JSON commit as a minor improvement. I think the test was passing locally but failed once remote? I thought it was a fluke. Thanks for looking into it.

**Comment by benmccann** [comment]
Fixed by https://github.com/jtablesaw/tablesaw/pull/762
