### ISSUE TITLE
Link to etablesaw

### ISSUE THREAD

**Issue by hallvard** [jtablesaw/tablesaw#770]
Are there any links to projects using tablesaw? I'd be grateful if you could link to tablesaw @ https://github.com/hallvard/etablesaw since it's now in a shape to be useful.

**Comment by benmccann** [comment]
I think https://github.com/jtablesaw/tablesaw#integrations would be a good place to put it

I'd love to learn more about it :-) It'd be cool to make a demo video or something if you ever get the time

Thanks for sharing!

**Comment by axkr** [comment]
I've tried to reimplement your Eclipse tablesaw editor plugin in my Eclipse EASE extension:
- https://github.com/axkr/ease_symja

just to be sure to use the same tablesaw libraries as the Symja computer algebra language:
- https://github.com/axkr/symja_android_library/issues/169

some "work in progress" after the following line
- https://github.com/axkr/symja_android_library/blob/00654cf157620148afdd1f01da28acfc5f14dd09/symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/LowercaseTestCase.java#L18964

The used function names are similar to those used by Mathematica.

I'm not sure if this is the best way or if we should use the same set of Eclipse plugins?

**Comment by lwhite1** [comment]
done, belatedly.
