### ISSUE TITLE
Question: Suggestions for improving multi-column join performance?

### ISSUE THREAD

**Issue by chuckol-work** [jtablesaw/tablesaw#774]
Doing joins on multiple columns seems extremely slow. For example, I have a Table1 of 22 columns (mostly strings and ints) and ~40k rows and Table2 of 4 columns (2 ints, 2 strings) and ~38k rows. When I do a 

`Table1.joinOn("col1", "col2", "col3").leftOuter(Table2)`

The operation takes about 55 seconds on my machine.

I have other examples where it takes even longer when the scale is higher.
Looking through the issues list, I know that not a ton of time has been spent on join performance. That said, can you give any suggestions for improving performance in cases like this?

**Comment by lwhite1** [comment]
Not really, unfortunately.

At one point, switching the order of the tables could make a difference if
they were different sizes. Might be worth a try.

**Comment by lwhite1** [comment]
the order-switching has been implemented.
