### ISSUE TITLE
Implement a Date timeseries chart

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#78]
Tablesaw uses several libraries to produce charts (currently XChart, the Javafx chart library, and some of the Smile plots). 

We use XChart for scatter plots and line charts. See classes Scatter and Line in the api.plot package.
XChart supports a variation on these that has dates (or datetimes, or both) as the x axis variable. 

There are examples here:
https://github.com/timmolter/XChart/tree/3531c004e683ea8a099cef8fc5a9f547d5f05986/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/date

We need to add support for this kind of chart. They should work in a similar fashion to the way LineCharts are handled in tablesaw. To understand LineCharts see these three classes:

com.github.lwhite1.tablesaw.api.plot.Line.java (This is the public tablesaw API)
com.github.lwhite1.tablesaw.api.plot.LinePlotExample.java 
com.github.lwhite1.tablesaw.plotting.xchart.XchartLine.java (This has the Xchart specific code)

There should be an analogous set of classes for this.

The API (that is, com.github.lwhite1.tablesaw.api.plot.TimeSeries) should be include a method that takes a DateColumn as X-axis and a NumericColumn as Y axis, like this. 

```
  public static void show(String chartTitle, NumericColumn x, NumericColumn y) {
    XchartTimeSeries.show(chartTitle, x, y);
  }
```

Ideally, there should be show() methods for both DateColumn and DateTimeColumn, and variations on the API call that include passing X and Y axis Labels.

**Comment by benmccann** [comment]
This would be great for the BeakerX Tablesaw demos using Quandl
