### ISSUE TITLE
Column indexOf method

### ISSUE THREAD

**Issue by islaterm** [jtablesaw/tablesaw#786]
I was trying to get the first index that matched a certain value (like Java List's indexOf method) and I couldn't find anything like that in the column's implementation.

Is that functionality not implemented?

For now I'm transforming the column into a List to use the method, but I think it's too much work for something that shouldn't be so complicated.

If it's actually a missing feature I think that the same implementation as Java Lists would work:

```java
public int indexOf(Object o) {
  Objects.requireNonNull(o);
  for (int i = 0, s = size(); i < s; i++) {
    if (o.equals(get(i)) {
      return i;
    }
  }
  return -1;
}
```

**Comment by benmccann** [comment]
If you just want to find if the value is present, we do have a method `anyMatch`. But if you actually want the index returned that's not a method we have yet. Feel free to send a PR if that's a method you'd like still

**Comment by islaterm** [comment]
Ok! I'll make a PR then.
