### ISSUE TITLE
The equals implementation for BooleanColumn is dangerous

### ISSUE THREAD

**Issue by lucasvwamp** [jtablesaw/tablesaw#788]
The implemenation of the equals method for tech.tablesaw.api.BooleanColumn is dangerous. It does not check column name, and so it returns true for any BooleanColumns with the same data.

This is especially problematic when removing columns. If I have two columns, BoolCol1 and BoolCol2, and call table.removeColumns("BoolCol1"), it will remove both columns.

**Comment by lucasvwamp** [comment]
Looks like this is a dup of #689

**Comment by benmccann** [comment]
Ah, looks like that fix hasn't been released yet. We have a fair number of fixes in since the last version, so should probably cut a release soon. Thanks for finding the dup

**Comment by benmccann** [comment]
I just cut a release with the fix. It may take up to an hour to appear
