### ISSUE TITLE
IllegalArgumentException: Cannot append java.sql.Time to TimeColumn

### ISSUE THREAD

**Issue by brainbytes42** [jtablesaw/tablesaw#789]
Hi there,

first of all: thanks for this great library (which I am currently using in v0.37.3, tohether with java 8)!
Over all, it works perfectly in discovering column-types, but recently, I ran into an issue with a Time-column in a MySQL-Database, getting the following Exception:
`IllegalArgumentException: Cannot append java.sql.Time to TimeColumn`.

There is one column of (SQL-)type `TIME` which needs to be excluded in my select-statement, then everything is fine again. Based on that finding, I digged deeper into that column and it's discovery by tablesaw... What I found:
The column is of Type TIME and the JDBC-Driver (v8.0.19) provides me, querying the ResultSet for it's metadata, with the following info: `... mysqlType=11(FIELD_TYPE_TIME), sqlType=92 ...`
This fits `java.sql.Types.TIME`, which also equals to 92.
Using the ResultSet directly, I have no problems reading the queried data. But when I pass the ResultSet to `Table.read().db(results, "Test");`, it fails throwing the mentioned Exception.

Digging into tablesaw's code, I found in class `SqlResultSetReader` the `SQL_TYPE_TO_TABLESAW_TYPE`-Map, which maps `Types.TIME` to `ColumnType.LOCAL_TIME`. This leads to `TimeColumn`'s `create(name)`-Method, creating a TimeColumn, which finally fails on adding the data, as `java.sql.Time` is not satisfying the condition `obj instanceof LocalTime` in method `appendObj(.)`.

Without reinventing the wheel (injecting own implementation of ColumnType, Column, ... into SqlResultSetReade's Map), I found no way to inject some sort of converter (like `if time instanceof Time ... time.toLocalTime()`), as the customParser isn't used in appendObj()... Maybe that would be a solution? Or just include such a conversion into TimeColumn's appendObj() natively?

Thanks in advance!

**Comment by benmccann** [comment]
It looks like in `InstantColumn` we have a `if (obj instanceof Timestamp)` check in `appendObj` and in `DateColumn` we have a `if (obj instanceof java.sql.Date)` check in `appendObj`, so I think adding `if (obj instanceof Time)` to `TimeColumn` would make sense. If you want to send a PR, I'm happy to review it

**Comment by brainbytes42** [comment]
Following your hint about how to fix the issue, I submitted a PR (#791).
