### ISSUE TITLE
set cells like the way appendCell works would be helpful

### ISSUE THREAD

**Issue by trago** [jtablesaw/tablesaw#793]
For columns, rows, etc, we have the method `appendCell` which use a default parser when you want to append a value from a string. However, lets say you don't want to append but to set a value in some location index of the column. As far as I can see, the way to do this is to figure out the type of the column, then build a parser and use the `set(row, string, parser)` method. In my opinion this is a very long way.

Perhaps I don't see the short way, if some of you guys have it please let me know it. But if there is not a short way, then would be helpful to have a short way in the api.

## Ideas
 1. add some thing like a `setCell` method with an string argument, just like appendCell exists
2. add an interface to get the default parser from `Column<<?>>` or `Row` so we don't have to test for every type, cast it to the right column type and get the `DEFAULT_PARSER` of that column.

This is a very good job what are you doing and the community thanks a lot.

**Comment by benmccann** [comment]
`appendCell` taking a parser is meant to be used by data readers such as the CSV reader and isn't necessarily something I envisioned users having much use for. I'm curious what your use case is where you have a `string` to be passed to `set`

**Comment by trago** [comment]
Hi @benmccann 

Well, I'm building a data frame from a JSON (I know there is a JSON reader in tablesaw but this JSON has an special structure meaning for us) where each column is an attribute of the JSON and there are numeric, boolean and string attributes, but, all values in the JSOn are saved as string values, i.e, value 1.0 is saved as "1.0". 

Each column of the table was created with the right type of the attribute, so when adding a value we need to parse the string value from the JSON to the actual column type. To solve these the only way if found was some thing like:
```java
for(final var attribute: node.getAllAttributes().entrySet()){
    final var row = table.row(node.getId());
    final var columns = row.columnNames();
    if(columns.contains(attribute.getKey())){
        var type = row.getColumnType(attribute.getKey());
        switch (type.name()){
            case "STRING":
                   row.setString(attribute.getKey(), attribute.getValue());
                   break;
            case "FLOAT":
                    row.setFloat(attribute.getKey(), Float.parseFloat(attribute.getValue()));
                    break;
             case "TEXT":
                    row.setText(attribute.getKey(), attribute.getValue());
                    break;
             case "INTEGER":
                    row.setInt(attribute.getKey(), Integer.parseInt(attribute.getValue()));
                    break;
             case "DOUBLE":
                     row.setDouble(attribute.getKey(), Double.parseDouble(attribute.getValue()));
     }
}
```

That is way I though that would be helpful to have some thing like
```java
if(columns.contains(attribute.getKey())){
   row.setCell(attribute.getKey(), attribute.getValue();
}
```
where `getValue()` returns a string.

**Comment by benmccann** [comment]
Why don't you use `appendCell` like the other readers?

**Comment by trago** [comment]
well, is more an update operation than creation.

Any way, I see  is a minor request, I just wanted to write less code, I'm very used with python data frames that's why I missed write less code.

Thanks a lot any way, this tablesaw is my best option in Java and recognize the good job.

 I appreciate your attention.
