### ISSUE TITLE
responsive chart attribute in config

### ISSUE THREAD

**Issue by emilianbold** [jtablesaw/tablesaw#794]
Plotly has an out of the box responsive flag: https://plotly.com/javascript/configuration-options/#making-a-responsive-chart

We just need to add a boolean `responsive` to the Config class.

**Comment by avirlrma** [comment]
Hey, 
Can I take this up?

**Comment by emilianbold** [comment]
Of course!

--emi

vin., 15 mai 2020, 18:03 Aviral Verma <notifications@github.com> a scris:
