### ISSUE TITLE
Select a range of columns

### ISSUE THREAD

**Issue by ridwannaibi** [jtablesaw/tablesaw#797]
I am looking for a way to select a range of columns  using a range of indexes in a table but I have not been able to do that. I have seen ways to select an indices for columns and specific columns but there is no support for range: like say 0-5 or am I missing something?

**Comment by lwhite1** [comment]
There’s no direct support but you should be able to write a one or two line
method that accepts the range endpoints and does that

**Comment by ridwannaibi** [comment]
@lwhite1 Thanks
