### ISSUE TITLE
Issues with get() methods on numeric columns.

### ISSUE THREAD

**Issue by chuckol-work** [jtablesaw/tablesaw#798]
It looks like missing values are handled slightly differently with v.38.0. This change breaks code that previously worked in 0.37.3. Specifically, returning a null instead of the actual Integer.MIN_VALUE value (in IntColumns) causes a lot of Null Pointer Exceptions where operations are done on numeric columns where there are, indeed, missing values. 

I've attached a small sample that illustrates code that worked in 0.37.3 but throws an exception in 0.38.0. In this example, I try to drop duplicate rows that have column values that are missing. When Tablesaw tries to compare the missing column values (using get(), which now returns a null), it throws an NPE.

I am also seeing new issues when trying to use set(Selection, Column<T>) where the source column contains missing values. The root cause is the same as in the code example: the get() returns null for missing values. 

    Table t1 = Table.create("T1");
        
    t1.addColumns(IntColumn.create("Id"),
                  StringColumn.create("Name"),
                  IntColumn.create("ChildId"));
        
    // Add 4 rows to the table, two of which are duplicates and have missing values.
    t1.intColumn("Id").append(0);
    t1.intColumn("Id").append(1);
    t1.intColumn("Id").append(2);
    t1.intColumn("Id").append(1);
        
    t1.stringColumn("Name").append("Joe");
    t1.stringColumn("Name").append("Jay");
    t1.stringColumn("Name").append("Mike");
    t1.stringColumn("Name").append("Jay");
        
    t1.intColumn("ChildId").append(100);
    t1.intColumn("ChildId").appendMissing();
    t1.intColumn("ChildId").append(101);
    t1.intColumn("ChildId").appendMissing();
        
    // Try to drop the duplicates. NPE gets thrown.
    t1.dropDuplicateRows();

**Comment by benmccann** [comment]
Thanks for this report and the test!

There was a lot of inconsistency in the APIs before regarding what happened when you called `get` and there was a missing value. 0.38.0 attempted to standardize that.

`dropDuplicateRows` worked with number columns before, but based off your report I'm sure it was broken for other column types that did return `null`, so we should fix it to handle `null` values. I sent a PR for that: https://github.com/jtablesaw/tablesaw/pull/799

Can you also share a test case for the issue with`set`?

**Comment by chuckol-work** [comment]
A case with set() is below:

    // Create 3-column table
    Table t1 = Table.create("T1");
                
    t1.addColumns(IntColumn.create("Id"),
                  StringColumn.create("Name"),
                  IntColumn.create("ChildId_1"),
                  IntColumn.create("ChildId_2"));
        
    t1.intColumn("Id").append(0);
    t1.intColumn("Id").append(1);
    t1.intColumn("Id").append(2);
    t1.intColumn("Id").append(3);
      
    t1.stringColumn("Name").append("Joe");
    t1.stringColumn("Name").append("Jay");
    t1.stringColumn("Name").append("Mike");
    t1.stringColumn("Name").append("Larry");
        
    // Note this column has 2 missing values.
    t1.intColumn("ChildId_1").append(100);
    t1.intColumn("ChildId_1").appendMissing();
    t1.intColumn("ChildId_1").appendMissing();
    t1.intColumn("ChildId_1").append(103);
        
    // And this column has 2 missing values.
    t1.intColumn("ChildId_2").append(200);
    t1.intColumn("ChildId_2").append(201);
    t1.intColumn("ChildId_2").appendMissing();
    t1.intColumn("ChildId_2").appendMissing();
        
    // Try to replace missing values in 'ChildId_1' column with values from 'ChildId_2'
    // Throws NPE because some of the source values are missing (i.e. get() returns null).
    t1.intColumn("ChildId_1").set(t1.intColumn("ChildId_1").isMissing(), t1.intColumn("ChildId_2"));

**Comment by benmccann** [comment]
Ok, I fixed that one in https://github.com/jtablesaw/tablesaw/pull/800. Please let me know if you encounter any other issues

**Comment by benmccann** [comment]
I'll release 0.38.1 with the fixes. It'll take an hour for it to show up Thanks for reporting
