### ISSUE TITLE
CSV ParsingConfiguration object

### ISSUE THREAD

**Issue by richiethom** [jtablesaw/tablesaw#80]
I have created a [`ParsingConfiguration`](https://github.com/richiethom/tablesaw/blob/parseconfiguration/src/main/java/com/github/lwhite1/tablesaw/api/ParsingConfiguration.java) class with a fluent interface with a builder, allowing all the CSV parse options to be encapsulated into a single class. I have also changed the CsvReader.read() in order to accept ParsingConfiguration. Existing versions of the read() method are still there and now construct a ParsingConfiguration object.

I can imagine that this would be a good basis for implementing #53.

Currently you can specify:
- the name of the table
- the name of the file
- the delimiter
- whether there is a header or not
- explicit column types (useful when appending one table to another: the data in the first CSV file might cause Tablesaw to choose type A for a column, whereas the data in the second file causes type B to be chosen; this results in an Exception while appending the second table to the first)
- explicit date formats for date columns (this avoids incorrect format detection when the date could be day or month first, only falling over on later rows when certain dates are illegal in the chosen format)

There is also a clone method which allows the same configuration to be used to parse another file.

The functionality is almost finished, but so far I haven't added any unit tests.

I would appreciate your input to see if it is something you would like to incorporate, and, if you do want to incorporate it, what changes you think are necessary before I create a pull request.

**Comment by lwhite1** [comment]
Sorry, I haven't had much time to work on tablesaw in the past few days. I
will try to give this some time in the next couple.

Thanks

**Comment by benmccann** [comment]
Not a bad idea. This is what commons-csv does:

https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html

**Comment by lwhite1** [comment]
yeah, I would like to replace the variety of table constructors that read
from a CSV with a single constructor using this kind of object. My initial
lack of enthusiasm for this was because I want to allow for interactive
use. I've come since then to think that the Kotlin API is better suited to
that so the Java API could be simplified this way.

**Comment by benmccann** [comment]
The commons-csv way of doing it is nice because they have presets like `CSVFormat.EXCEL`, `CSVFormat.MYSQL`, etc. so you don't have to construct the configuration object yourself 99% of the time.

**Comment by lwhite1** [comment]
I like it. I will do that.
