### ISSUE TITLE
LongColumn print formatter doesn't print correct long value

### ISSUE THREAD

**Issue by krico** [jtablesaw/tablesaw#802]
Please see unit test on #801 that demonstrates the issue, namely

A long value of              `1588838400007002844L` 
is formatted to a string `1588838400007002880`

**Comment by benmccann** [comment]
It looks like it's because `getPrintFormatter().format(value)` in `LongColumn` is converting the value from a `long` to a `double`

**Comment by benmccann** [comment]
Fixed in https://github.com/jtablesaw/tablesaw/commit/ae52d999e0ee1152012ff6e18ac9bd031eacfea4
