### ISSUE TITLE
Display real time chart

### ISSUE THREAD

**Issue by toriacht** [jtablesaw/tablesaw#803]
Hi,

Can I use tablesaw to display real time data i.e. update on interval or via web socket etc?
Is there a simple example?

Thanks

**Comment by benmccann** [comment]
https://github.com/nagix/chartjs-plugin-streaming

**Comment by benmccann** [comment]
Oh. I'm also a contributor to chartjs and assumed this was a question in that project :-)

Still you could use chartjs with that plugin and have your web api serialize a tablesaw table to json in the expected format. I'm afraid I don't have more of an example to share

**Comment by toriacht** [comment]
Hi @benmccann 

Thank you for the quick reply and the suggestion of `chartjs`, While I could force myself to learn `JS`!, The main reason I'm looking at `tablesaw `is that I'm looking (hoping) for a Java solution that supports OHLC charts.

I have an existing java server side app and I was hoping to use tablesaw to visualise.

Is it possible to re-open the issue in case anyone else has an idea?

**Comment by benmccann** [comment]
I'm not quite sure what you're hoping to do because you mentioned you have a "java server side app". But if you have a web server, it's almost impossible to display a streaming chart without using JavaScript because JavaScript is the language that runs in web browsers

**Comment by toriacht** [comment]
:-) I'm aware of that conundrum!

I am also aware you can do live streaming with [plotly](https://github.com/plotly/Streaming-Demos) and i just discovered `tablesaw `yesterday which describes itself as a  java wrapper around `plot.ly`. The examples are great and I got a few demos up and running in my IDE which produces the static chart

My hope/thinking was that there was also a a way to build on this and deploy as a jar or war or ....  on a webserver/servlet container/ etc and supply it with live data.

**Comment by benmccann** [comment]
The Tablesaw plotly integration mainly exports a table to a file containing the HTML and Javascript to render a chart locally for personal use. You might be able to use it to make it easier to do the server-side JSON serialization. I'm not quite sure. But it doesn't have any streaming support yet, so that's something new that would have to be built.
