### ISSUE TITLE
Issue Parsing DateTime in CSV file for OHLC chart

### ISSUE THREAD

**Issue by toriacht** [jtablesaw/tablesaw#804]
Hi,

The simple example provided in the codebase works well with the provided `ohlc.csv` dataset and the following code correctly reads in one Date Column and a number of DoubleColumns

```
            Table priceTable = Table.read().csv("data/ohlc.csv");
            priceTable.numberColumn("Volume").setPrintFormatter(NumberColumnFormatter.intsWithGrouping());
            Plot.show(OHLCPlot.create("Prices", priceTable, "date", "open", "high", "low", "close"));
            Plot.show(CandlestickPlot.create("Prices", priceTable, "date", "open", "high", "low", "close"))
```

This works  as the date/ data is of the format:

```
Date,Open,High,Low,Close,Volume,Adj Close
2009-03-31,17.83,18.79,17.78,18.37,92095500,17.81
```

My OHLC file is slightly different in that the date is a `Date Time` but the method ` priceTable = Table.read().csv(fileLocation);` always reads the date column as a `String` and then proceeds to error out with a class cast exception on `Plot.show` .

my data looks like:

`2020-05-14T15:04Z,8970.1,8970.1,8962.3,8962.3,5.15412904`

As the date has been parsed as a String Column i cannot set the DateTimeFormat as in the commented line in  snippet below as i will predictably enough  get another class cast exception. 

     
            priceTable = Table.read().csv(fileLocation);  priceTable.numberColumn("Volume").setPrintFormatter(NumberColumnFormatter.intsWithGrouping());
           // priceTable.dateTimeColumn("Date").setPrintFormatter(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm'Z'")); -->also classcastexception 
            Plot.show(CandlestickPlot.create("Prices", priceTable, "date", "open", "high", "low", "close"));

Any help/pointers appreciated.

**Comment by toriacht** [comment]
By building table like so:

```
            CsvReadOptions.Builder builder =
                    CsvReadOptions.builder(fileLocation)
                            .dateFormat(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm'Z'"));  				// the date format to use.

            CsvReadOptions options = builder.build();

             priceTable = Table.read().usingOptions(options);
```

The classcast exception, goes away, but the chart is mangled, all data is merged into one

![image](https://user-images.githubusercontent.com/435552/81992717-11db2480-963c-11ea-8e70-d0c37642fa13.png)

If I remove the 'Z' at the end of the date and build like so

```
CsvReadOptions.Builder builder =
                    CsvReadOptions.builder(fileLocation).header(true)
                            .dateFormat(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
```
 Then I get a DateTimeColumn to DateColumn class cast exception (previous were String to Date)

**Comment by toriacht** [comment]
The issue  when using the builder like:

   ```
        CsvReadOptions.Builder builder =
                    CsvReadOptions.builder(fileLocation)
                            .dateFormat(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm'Z'"));  				// the date format to use.

            CsvReadOptions options = builder.build();
             priceTable = Table.read().usingOptions(options);
```

is that it appears to put all the 5 min candles into one. It does not realize they are 5 min candles. So i'm guessing it is treating DateTimes as Dates?

![image](https://user-images.githubusercontent.com/435552/82026895-4b874c00-968b-11ea-8feb-452394683932.png)

**Comment by toriacht** [comment]
If i convert to LocalDateTime (removing the 'z') and use `ColumnTypes`  option this doesn't help as  `Plot.show(...)` ultimately tries to render as a `Date` instead of a `DateTime` and throws a `DateTime can;t be cast as a Date exception  `        

```
             ColumnType[] types = {LOCAL_DATE_TIME, DOUBLE, DOUBLE,DOUBLE,DOUBLE,DOUBLE};

            CsvReadOptions.Builder builder =
                    CsvReadOptions.builder(fileLocation).header(true)
                            .columnTypes(types);
                     .dateTimeFormat(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
```

**Comment by lwhite1** [comment]
@toriacht 
Sorry it took so long, i've been stupid busy with other things for a long time.  I'm guessing you've found another solution by now.

On the parsing, I'm not sure there is a bug, per-se. The parser has a set of date formats it tries, but it cannot try every possible format, so sometimes it gets it wrong. As you saw, you can specify a format to match your data.

On the plot failing due to the column type. I added support for DateTime and Instant columns (in an open pull request). However, the OHLC and Candlestick plots assume a granularity of a day. This means that the plot renders correctly now with DateTimes, but only if you have one row per day. This may be a plotly default as I'm not specifying that day should be the granularity. If you could spare some small subset of your data (maybe enough for two days) I could try to figure it out.
