### ISSUE TITLE
Java cannot access tech.tablesaw.io.source error

### ISSUE THREAD

**Issue by R01NDev** [jtablesaw/tablesaw#805]
Getting the following errors when compiling my code and trying to import and XLSX file 
![image](https://user-images.githubusercontent.com/49044625/82105646-162f3c80-9725-11ea-94a8-acadab9965a9.png)

and I have
import tech.tablesaw.api.Table;
import tech.tablesaw.io.xlsx.XlsxReadOptions;
import tech.tablesaw.io.xlsx.XlsxReader;

**Comment by lwhite1** [comment]
This looks like a standard java compilation issue related to a classpath problem and not something specific to Tablesaw.
