### ISSUE TITLE
Column suffix for table join with same column names

### ISSUE THREAD

**Issue by amitoverflow-ui** [jtablesaw/tablesaw#811]
Provide option to add suffix/prefix while joining tables when column names are same.

Something similar like below:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html

Currently T2, T3 is prefix in the joined table for columns with same headers.

**Comment by lwhite1** [comment]
Closing without implementing.  The Pandas implementation only deals with two-table joins. An implementation in Tablesaw would be complicated by the multi-table join logic (and more importantly, would further complicate that logic).  

The workaround is a loop over the column names and some simple string manipulation. 

#wontfix
