### ISSUE TITLE
is it possible to auto fill the missing column when import csv with columns of different sizes?

### ISSUE THREAD

**Issue by starli-sl** [jtablesaw/tablesaw#812]
Issue:
When import a csv file with column of diffrent sizes, it will return an AddCellToColumnException.
Do the same opreation in pandas, it will fill the missing column with 'NaN' automatically.

Error message:
tech.tablesaw.io.AddCellToColumnException: Error while adding cell from row 551 and column time(position:0): Row number 551 contains 2 columns. 5 expected.
Caused by: java.lang.IndexOutOfBoundsException: Row number 551 contains 2 columns. 5 expected.
	at tech.tablesaw.io.FileReader.addRows(FileReader.java:161)

Test data:
time,c1,c2, c3,c4
2018/7/25 14:30,6,2.57,8.5,10.41
2018/7/25 16:30,9,3.58,6.5,11.41
2018/7/25 18:30,122.5
2018/8/4 8:30,155

Suggestion:
Add a option to auto fill the missing column when import csv.

Thanks

**Comment by ChangzhenZhang** [comment]
@lwhite1 Hi, I pull a [request](https://github.com/jtablesaw/tablesaw/pull/937) for this issue.
I add an option `autoFillMissingColumn` to fill the missing column with the Missing Value when import file with columns of different sizes automatically. And I want to make sure that if this change fixes the issue.
Thanks!

**Comment by lwhite1** [comment]
Closing as "won't fix"
