### ISSUE TITLE
Unable to Format Date on Export 

### ISSUE THREAD

**Issue by KhalifaAlqaatri** [jtablesaw/tablesaw#814]
Hi How can i format the date on export with CSVWriteOptions ? i havent found any reference in the api docs , 
For example ,  given the following export code 

`        CsvWriteOptions builder = CsvWriteOptions.builder(pathname).header(false).build();
          myTable.write().usingOptions(builder);
`

it would be great if i can do 

`        CsvWriteOptions builder = CsvWriteOptions.builder(pathname).dateFormat(DateTimeFormatter.ofPattern("yyyyMMdd")).header(false).build();
        myTable.write().usingOptions(builder);
`

i understand it is possible format the dates on import using CSVReadOptions Builder like the example below , but how about exports ? your help is much appreciated , thank you  . 

`CsvReadOptions.Builder builder =
                    CsvReadOptions.builder(fileLocation)
                            .dateFormat(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm'Z'"));  				
            CsvReadOptions options = builder.build();
             myTable = Table.read().usingOptions(options);`

**Comment by lwhite1** [comment]
This would make a good enhancement. 
If you want to submit a PR I would be happy to take a look at it.

**Comment by lwhite1** [comment]
Implemented date formatting for both DateColumn and DateTimeColumn. 
It remains to be done for TimeColumn and InstantColumn, but I think this is enough to close this as fixed.
