### ISSUE TITLE
read double/float values from BigDecimal will lose precision

### ISSUE THREAD

**Issue by justforxm** [jtablesaw/tablesaw#823]
at **tech.tablesaw.io.jdbc.SqlResultSetReader.java** when the result is BigDecimal column use resultSet.getDouble or resultSet.getFloat will lose precision,i think it should use resultSet.getBigDecimal and use BigDecimal's getFloatValue() or getDoubleValue()

**Comment by justforxm** [comment]
when i write like this 
![image](https://user-images.githubusercontent.com/6621689/87378275-11212900-c5c0-11ea-9e5e-8a3bd6e1edb2.png)
it work ok，but the AggregateFunctions.sum is sitll wrong

**Comment by lwhite1** [comment]
Hi Justforxm,

It's the nature of BigDecimal to double conversion that you lose precision. What evidence do you have that BigDecimal's floatValue or doubleValue are more precise than ResultSet getFloat or getDouble?

Thanks, 
larry

**Comment by lwhite1** [comment]
To follow up, good bug reports are an important contribution, but this one is missing two things:

First: it needs to show there's a difference between the results returned currently and what you expect (what you got with your change). In particular, it needs actual values for doubles that have been imported using the two different methods. IDK how it works behind the scenes but I wouldn't create BigDecimals as an intermediate type if I could avoid it, as that will create a lot of GC overhead. OTOH, if you can demonstrate it's more accurate it's probably worth doing.

Second: it needs to explain the statement "it work ok，but the AggregateFunctions.sum is sitll wrong" IDK what you mean by wrong. Again, you need to show specific numbers.  The sum function is pretty accurate I think, within the constraints of what doubles and floats can do. 

Thanks.
