### ISSUE TITLE
BooleanNumericFunction misses a correct returnType() implementation

### ISSUE THREAD

**Issue by Traderjoe95** [jtablesaw/tablesaw#825]
The `BooleanNumericFunction` aggregate type returns `null` from the `returnType()` function. This causes aggregation to fail with a `NullPointerException`.

The correct behavior here would be to return `ColumnType.DOUBLE`. I will prepare a pull request to fix the issue.

**Comment by Traderjoe95** [comment]
Fixed by #826

**Comment by lwhite1** [comment]
thanks, @Traderjoe95
