### ISSUE TITLE
Broken Java Docs link

### ISSUE THREAD

**Issue by krystiangorecki** [jtablesaw/tablesaw#827]
1. "Conclusion" section of "Getting started with Tablesaw" page contains broken link to "Java Docs".
https://jtablesaw.github.io/tablesaw/gettingstarted#conclusion
2. "Exploring tables" section of "Getting started with Tablesaw" page contains broken link to "plotting".
https://jtablesaw.github.io/tablesaw/gettingstarted.html#exploring-tables

**Comment by benmccann** [comment]
Thanks so much for reporting! If you have any time to address, we'd welcome a PR for this
