### ISSUE TITLE
Ambiguous Reference error when call this method tech.tablesaw.api.NumericColumn#isIn(double...)   

### ISSUE THREAD

**Issue by xlhtc007** [jtablesaw/tablesaw#829]
When I use table filter where method, I use isIn method to construct my Selection. But the compiler print this Error: Ambiguous Reference.How to handle this error? The Demo code is below:
```
instMonthTable.where(
instMonthTable.stringColumn(TableEnum.ColumnNameEnum.IF_FIRST_TAG.getName()).isEqualTo("FIRST").and(
                                instMonthTable.intColumn(TableEnum.ColumnNameEnum.USER_STATUS.getName()).isIn(12,10)));
```

**Comment by benmccann** [comment]
Can you share more of the error?

**Comment by xlhtc007** [comment]
> Can you share more of the error?

the error is Chinese. You can use this demo code to demonstrate the error:
`        StringColumn s1 = StringColumn.create("1", "1","2","3");
        StringColumn s2 = StringColumn.create("2", "2","2","2");
        StringColumn s3 = StringColumn.create("3", "3","2","1");
        IntColumn s4 = IntColumn.create("4", 1,2,3);
        Table t = Table.create("t", s3, s2, s1, s4);
        t.where(t.intColumn("4").isIn(1,2));
`

**Comment by lwhite1** [comment]
candidate fix pull request is in progress

**Comment by lwhite1** [comment]
TBH, I don't really understand why this happens. It seems like if you use exactly the right syntax in calling the method, it would work, (which is why, apparently, it's not a compile time error in the library itself).  The examples I've seen online concern generics. Perhaps the compiler is converting the varargs to generic arrays.

**Comment by lwhite1** [comment]
fixed
