### ISSUE TITLE
Is there any method to modify the Column type?

### ISSUE THREAD

**Issue by xlhtc007** [jtablesaw/tablesaw#830]
I import data from Database, and I want to specify column type. Is there any way to do so?

**Comment by benmccann** [comment]
You can use `SqlResultSetReader.mapJdbcTypeToColumnType` or convert the column type after you've read the table

**Comment by xlhtc007** [comment]
> SqlResultSetReader

Thanks! Because I want to specify all the decimal column to DoubleColumn, so SqlResultSetReader.mapJdbcTypeToColumnType cannot achieve this. How to convert the column type after read the table? Thanks!

**Comment by lwhite1** [comment]
Common column transformations are available using method whose names begin with the word "as". For example, FloatColumn implements asDoubleColumn(), asIntColumn(), asLongColumn(), and asShortColumn().
