### ISSUE TITLE
Support to import and export data from and into mongodb

### ISSUE THREAD

**Issue by viveknani98** [jtablesaw/tablesaw#831]
Support to import and export mongo db collections

**Comment by benmccann** [comment]
There's JSON support already. I would recommend utilizing that. Tablesaw implements a reader and writer registry so you can create your own plugin for MongoDB and register it with Tablesaw if you wish. I don't think that we would implement this in the core library

**Comment by viveknani98** [comment]
How do I get the tablesaw 0.38.2-SNAPSHOT jar?

**Comment by benmccann** [comment]
If you run `mvn install` it will put it in the local Maven repository in `~/.m2`. You can then reference it from another Maven project or copy it elsewhere
