### ISSUE TITLE
Support to execute Sql like statement 

### ISSUE THREAD

**Issue by xlhtc007** [jtablesaw/tablesaw#836]
I want to execute the analytic query dynamically with the sql like statement configuration. Is there any api or method to implement this?

**Comment by benmccann** [comment]
@ryancerf implemented some analytic functions that I believe were similar: https://github.com/jtablesaw/tablesaw/commits?author=ryancerf

**Comment by ryancerf** [comment]
We have SQL-like analytic functions in the core.analytic module.

The best docs we have at the moment are the [tests](https://github.com/jtablesaw/tablesaw/blob/master/core/src/test/java/tech/tablesaw/analytic/AnalyticQueryEngineTest.java).

**Comment by xlhtc007** [comment]
> @ryancerf implemented some analytic functions that I believe were similar: https://github.com/jtablesaw/tablesaw/commits?author=ryancerf

Thanks for your quick reply and clues!

**Comment by xlhtc007** [comment]
> We have SQL-like analytic functions in the core.analytic module.
> 
> The best docs we have at the moment are the [tests](https://github.com/jtablesaw/tablesaw/blob/master/core/src/test/java/tech/tablesaw/analytic/AnalyticQueryEngineTest.java).

I have gone through the analytic function you provided and find that the AnalyticQuery has the toSqlLikeString() method.  It's awesome and powerful! But what I need is to execute the sql like string directly, or is there any way to convert the sql like string to the AnalyticQuery?

**Comment by ryancerf** [comment]
> I need is to execute the sql like string directly, or is there any way to convert the sql like string to the AnalyticQuery?

It is not possible to execute queries from sql strings. The closest you could get is dynamically building the query using the builder API.

**Comment by xlhtc007** [comment]
> > I need is to execute the sql like string directly, or is there any way to convert the sql like string to the AnalyticQuery?
> 
> It is not possible to execute queries from sql strings. The closest you could get is dynamically building the query using the builder API.

OK, thanks!

**Comment by xlhtc007** [comment]
> > I need is to execute the sql like string directly, or is there any way to convert the sql like string to the AnalyticQuery?
> 
> It is not possible to execute queries from sql strings. The closest you could get is dynamically building the query using the builder API.

Another question, does the analytic functions support filtering? I can not find that.
