### ISSUE TITLE
Is it possible to load data from List of Maps?

### ISSUE THREAD

**Issue by amoleb** [jtablesaw/tablesaw#839]
Can we build data frame from List<Map<String, Object>> resultSet ?
Couldn't see any reference for the above use case in the documentation.

**Comment by benmccann** [comment]
There is a JSON reader, but I don't think there's anything built-in for POJOs. You'd have to write the conversion code yourself.

**Comment by ScalaSci** [comment]
I ran into this also. I'll include my code in case it's helpful to others (it's scala, but things should work similar in java) Basically I wrote a simple helper method to do this:

`
object TablesawUtils {

  def tablesawTableFromMaps(data:Iterator[Map[String, _<:Any]], columns:Map[String, _<:ColumnType]) = {
    val builders:Map[String, Column[_]] = columns.map{col=> col._1 -> col._2.create(col._1)}

    data.foreach {
      d =>
        columns.foreach(col => builders(col._1).appendObj(d(col._1)))
    }

    Table.create(builders.values.toList.asJava)
  }
}

`

I pass in the collection of maps, and a mapping from the string/column-name/map-key to the column types I want to pull out, then construct the column data types.
