### ISSUE TITLE
Question: Support text type / finer column type

### ISSUE THREAD

**Issue by larshelge** [jtablesaw/tablesaw#840]
Hi, first thanks again for an excellent library.

We have a requirement for detecting the "type" of text for a column, where the data comes in as CSV files. The "types" to detect are i) URL and ii) email address. This type of text now resolves to `StringColumnType` or `TextColumnType`.

It could be interesting to offer a "Text type" property to `Column`, and have the `DataFrameReader` / `Table` implementation populate this property. The field would only be relevant for `StringColumnType` and `TextColumnType`. This could allow applications to understand more about the content of a text field, and render it in helpful ways (as hyperlinks, mailto links, etc).

I am aware that this can be handled outside of Tablesaw with an additional pass of the data. Now due to the high performance of Tablesaw and possibility of avoiding a second pass/maintaining external code it might be beneficial to support it within the library. I am also aware this might be on the side of the core mission of Tablesaw, but it could also be a useful addition that could expand the usability of the library.

I am just raising this as a question to see if there is appetite for such a feature. Will be happy to contribute if so.

**Comment by lwhite1** [comment]
Supporting new types for import and export is very attractive, but has
historically been an ongoing source of maintenance work as the implementer
often doesn't respond to bug reports that might come up a year or so
later.  As much as I like the idea, I think probably not. Maybe the other
maintainers feel differently.

At one point, you could add a column type without touching core, but i
doubt that's still true.

**Comment by larshelge** [comment]
Alright, thanks for the response and I understand the concern. I guess this is a general challenge with open source contributions. I might play around with the idea and see if something useful comes out of it. Feel free to close this issue.
