### ISSUE TITLE
.dropRowsWithMissingValues() and .dropDuplicateRows()

### ISSUE THREAD

**Issue by janicebloc** [jtablesaw/tablesaw#843]
Hi, I’m new to tech.tablesaw.
For some reason, the functions .dropRowsWithMissingValues() and .dropDuplicateRows() often don’t work the way I expect them to, and then I have to iterate to get the job done or else save the file and do the job in python instead.  Am I missing something?  Thanks for any help.

**Comment by lwhite1** [comment]
Closing as too vague to answer, since there's no way to no what result was expected.
