### ISSUE TITLE
column label mismatch in table object with maria db/mysql database

### ISSUE THREAD

**Issue by prabaryder007** [jtablesaw/tablesaw#846]
while parsing the data from **mysql/mariadb** database , the column alias is not reflecting in table object, instead of **column alias** its considering **original column name**. This is issue is only reproducible with **mysql/maria** db database only,

**Comment by lwhite1** [comment]
Closing as (a) it only affects one db, (b) there is a reasonable workaround in renaming the column after it's in tablesaw, (c) there's only so many hours in a day. 

#wontfix
