### ISSUE TITLE
Renaming column in StringFunctionMapper

### ISSUE THREAD

**Issue by Afollet** [jtablesaw/tablesaw#847]
Hi,
I'm using this library to clean some strings a column like so:
```
public static Table trimValuesOnAllColumns(Table table){
        return Table.create(table.columns().stream()
                .map(x -> x.asStringColumn().trim())
                .collect(Collectors.toList()));
    }
```
However, I am need the column names to remain the same. Why is the code like this? 
```
StringColumn newColumn = StringColumn.create(this.name() + "[trim]");
```
Is there a better way for me to avoid this column name changing beside changing it back?
```

**Comment by lwhite1** [comment]
no. you could change it back by calling setName() on the column, but if you
want it to be in the same table you need to remove the old version. Or use
replaceColumn().

**Comment by Afollet** [comment]
Yes, I have gotten the method to work. Is change in the column name to ensure the user knows the columns are immutable?

**Comment by lwhite1** [comment]
1) you can't have two cols in the same table with the same name, so the
name change usually means less work
2) the name changes that happen automatically provide info about what was
changed, which helps you keep track of what you did with the data
