### ISSUE TITLE
Feature request: make tech.tablesaw.plotly.Plot members public

### ISSUE THREAD

**Issue by hmf** [jtablesaw/tablesaw#860]
Would it be possible to make the class have its private members public. This way I can extend the plot class for additional functionality. It would also be great to refactor the `show` to use a `show(String html, File outputFile)` that saves the HTML to a file, so that it can be reused for other page set-ups.

**Comment by benmccann** [comment]
You just need them to be `protected` and not `public` then, right?

**Comment by hmf** [comment]
Yes, that is correct.

**Comment by lwhite1** [comment]
The private methods are now protected (on master. not sure when they'll be in a release version).  Not sure what you mean by 

>It would also be great to refactor the show to use a show(String html, File outputFile) that saves the HTML to a file, so that it can be reused for other page set-ups.

It takes a file now for the output. What is it you would like to see changed.

**Comment by hmf** [comment]
@lwhite1 Thank you.

Currently you have:

```java
public static void show(Figure figure, String divName, File outputFile) {
...
}
```
which creates the HTML page for a single figure with the `divName`. 
I create an HTML page with several figures and would like to `show` that.
So it is not possible for me to take that HTML and show it. However if you 
had a protected member:

```java
  public static void show(String HTML, File outputFile) {
...
}
```

I could use that. Note that I said refactor because I 
think that that call can be reused by your own class:

```java
  public static void show(output: String, File outputFile) {
    try {
      try (Writer writer =
          new OutputStreamWriter(new FileOutputStream(outputFile), StandardCharsets.UTF_8)) {
        writer.write(output);
      }
      new Browser().browse(outputFile);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  public static void show(Figure figure, String divName, File outputFile) {
    Page page = Page.pageBuilder(figure, divName).build();
    String output = page.asJavascript();
    show(output, outputFile);
  }
```
Ofcourse I don't know if this fits in ok with what you have planned here,
but I don't think it will affect  the current API.

**Comment by lwhite1** [comment]
It's possible to create your own html to display more than one image. I
will find the example code

**Comment by hmf** [comment]
I understand. I have used that for my own code so:

```scala
    val page = HTMLPlot.makePage(List(figure1, figure2), List(funcInfo.divName, gradInfo.divName))
    HTMLPlot.show(page, HTMLPlot.withName(funcInfo.divName))
```
I had to code my own `HTMLPlot.show` with source that I copy & pasted from your `Plot` because their is no `show` that take in a String/HTML. 

Not a big issues. But it will save people from explicitly adding code to save the HTML to a file and then opening a browser to load that file. 

As I said, no biggy. Please feel free to close this issue. 

Thank you

**Comment by lwhite1** [comment]
i will take a look when i have some time.

**Comment by lwhite1** [comment]
implemented.
