### ISSUE TITLE
asDoubleColumn() in BooleanColumn.java bug?

### ISSUE THREAD

**Issue by markbookk** [jtablesaw/tablesaw#872]
The method `asDoubleColumn` in `BooleanColumn.java` converts the boolean data it has to a `DoubleColumn` but when creating it, it initializes it with a specific size using `size()`, those values being null. After doing this, it then appends the real values. This seems to create an array double in size, while half of the elements are null.

Example using `col` as a `BooleanColumn`:
`col.data()`
returns: `[true, false, false, false]`

`col.asDoubleColumn().asList()`
returns `[null, null, null, null, 1.0, 0.0, 0.0, 0.0]`

Am I missing something or is this not supposed to be like this? 

As a possible solution `DoubleColumn numberColumn = DoubleColumn.create(this.name(), size());` could be changed to `DoubleColumn.create(this.name());` This will initialize it but empty and then appends the real values only.

I could do the PR if it indeed is a bug.

**Comment by benmccann** [comment]
that does sound like a bug. though the better fix would probably be to still initialize with the size and then set rather than append values as this might be slightly better performance

**Comment by lwhite1** [comment]
fix is being checked now

**Comment by lwhite1** [comment]
fixed.

**Comment by markbookk** [comment]
Cool, thanks!
