### ISSUE TITLE
add optional feature to export csv with column formats preserved

### ISSUE THREAD

**Issue by malaccan** [jtablesaw/tablesaw#886]
currently, CsvWriter.java exports only unformatted values from the table, code snippet here:
`entries[c] = table.getUnformatted(r, c);`

would be very useful to have the ability to export in the column formats that the user has set.
e.g. exporting to file and calling `table.printAll()` will produce the exact same values/formats.
thanks

**Comment by DanielMao1** [comment]
Hello developers,
We are a group of students.[ZhengXin](https://github.com/Carl-Rabbit), [Wendi](https://github.com/LUUUAN),[Shangxuan](https://github.com/ArslanaWu),[Jiashu](https://github.com/wateryloo) and me. We are trying to make contributions to some good Java open-source projects. Could we help to work on this new feature? Looking forward to your reply : ) @lwhite1 @benmccann

**Comment by lwhite1** [comment]
implemented in PR #914
