### ISSUE TITLE
XlsxReader doesn't respect calculated tableArea for header column names

### ISSUE THREAD

**Issue by lujop** [jtablesaw/tablesaw#887]
There is a buggy condition on some excels when there are blank columns at the start of the sheet.

When `es.decide.toolbox.util.XlsxReader#createTable` calculates header names it uses a `for(Cell cell : row) ` instead of using the supplied `tableArea` parameters.

And when there are some blank columns it doesn't always work. I don't know exactly why, but sometimes the first blank column is discarded in the iterator, but sometimes although all values are blank poi maintains the column, and the code doesn't work correctly detecting the header column names.

To calculate the header column names the code should use the `tableArea.startColumn` and `tableArea.endColumn`

**Comment by lujop** [comment]
I will be happy to provide a PR for this if it's recognized as an issue.

**Comment by lwhite1** [comment]
If you want to submit a PR with good test coverage, that would be great.

**Comment by DanielMao1** [comment]
@lujop Hello, bro, do you still work on this issue? I have encountered the same problem and got some ideas to fix this bug. If you are busy, I can work on this issue.

**Comment by lujop** [comment]
Thanks, @DanielMao1, just yesterday I got some time to do some work on a proposition for some reader-related issues that I've not yet finished but I will try to make a PR this weekend.
If you're in a hurry just do, and if not, and can wait this weekend I will try to submit.

**Comment by DanielMao1** [comment]
> Thanks, @DanielMao1, just yesterday I got some time to do some work on a proposition for some reader-related issues that I've not yet finished but I will try to make a PR this weekend.
> If you're in a hurry just do, and if not, and can wait this weekend I will try to submit.

OK, here you go. I am not in so hurry to do PR. You can go ahead on this issue anyway :).
