### ISSUE TITLE
Not able to remove default missingValueIndicator .

### ISSUE THREAD

**Issue by gs-agarain** [jtablesaw/tablesaw#891]
As per table saw documentation: 
> Tablesaw has a predefined set of strings that it interprets as missing data when reading from a CSV file. These are: "NaN", "*", "NA", "null" and, of course, the empty string "".
Would it be possible to externalize it? Maybe make it part of tech.tablesaw.io.ReadOptions?

**Comment by lwhite1** [comment]
Agreed

**Comment by lwhite1** [comment]
Sorry, I was thinking about write options. 

There is already a way to set the missing value indicator when reading. It is a readOption. The method is 

missingValueIndicator(String s);

**Comment by lwhite1** [comment]
It would probably be better if the readOption for this was modified to use varargs, and should be pretty simple to do.

**Comment by lwhite1** [comment]
fixed in PR #918
