### ISSUE TITLE
Is it possible to add the text "*" to a text column?

### ISSUE THREAD

**Issue by jglogan** [jtablesaw/tablesaw#897]
The following test code:

```
    @Test
    void testAddAsterisk() {
        final Table sourceTable = Table.create(TextColumn.create("text"), StringColumn.create("string"));
        sourceTable.textColumn("text").append("*");
        sourceTable.stringColumn("string").append("*");
        System.out.println(sourceTable.printAll());
    }
```

yields the result:

```
 text  |  string  |
-------------------
       |       *  |
```

It appears that the TextColumn.appendCell() method checks a hardcoded list of sentinel values for missing values that includes the asterisk character.  Is there any way to work around this behavior so that only the empty string is interpreted as a missing value when appending text?

Thanks in advance!

**Comment by jglogan** [comment]
Sorry, I didn't see #891 when I opened this one.  I'm pretty sure the above test exercises the same code path, so I'll close this as a duplicate.

**Comment by jglogan** [comment]
Reopening this - while it might be possible to work around the issue for CSV load, I'm running into the issue when trying to use `Table.appendRow()` to add to a table with a text column.  In this case, `TextColumn.appendObj()` gets called, and it appears there's no way to avoid using the missing value list that includes "*".

**Comment by lwhite1** [comment]
Can you work around by adding a different char and doing a replace on it
after it’s loaded?

**Comment by jglogan** [comment]
Thank you for the prompt response!

Defining a flag value is a possibility.  As far as I can tell in the Tablesaw source, the `TextColumnType.DEFAULT_PARSER` is only invoked when adding a column, and not when setting established values.  Does this seem correct to you?

At this point it's a choice between changing the type of this column to StringColumn (lots of refs across 30 source files - it works, but ugh), or the substitution method.  I'll stash the type change and work around the issue by substituting.

**Comment by jglogan** [comment]
Perhaps a longer term solution would be to add a `parser` field to TextColumn that defaults to `TextColumnType.DEFAULT_PARSER `, along with `TextColumn.setParser(otherParser)`?

**Comment by jglogan** [comment]
To safeguard against this, it looks like substitution won't be a good solution, because the parser is invoked when appending single values, columns, and table rows.  I'm going to try creating utility methods for all these cases based on a safe text column append method that adds the value, tests for the case that the value is not empty and the stored value is missing, and sets the stored value in that case.

**Comment by jglogan** [comment]
It's looking like using StringColumn is going to be the only workaround.  The code path in question is used in joins, so there are too many places where data can just evaporate.  The data I'm storing is text proper, so it's entirely feasible that some of the other missing values (especially "NA" and "N/A") could appear in the data that's being processed.

**Comment by lwhite1** [comment]
PR #912 "fix bug in appendCell that caused custom parser to be ignored" provides a partial workaround, which is: 
```
    final TextColumn sc = TextColumn.create("sc");
    StringParser parser = new StringParser(ColumnType.TEXT);
    parser.setMissingValueStrings(new ArrayList<>());
    sc.appendCell("*", parser);
    assertEquals(0, sc.countMissing());
```
Ostensibly, the appendCell(String, Parser) method should have _already_ been a workaround, but it was buggy. 

Unfortunately, this does not address the issue of using the the Row interface. so i will leave the issue open.

**Comment by jglogan** [comment]
I submitted PR #913 which allows a TextColumn to have a custom parser for appendCell.  LMK what you think about this approach.
