### ISSUE TITLE
rightOuter join will only join to the last table included in the list

### ISSUE THREAD

**Issue by Carl-Rabbit** [jtablesaw/tablesaw#907]
Hi, developers! @benmccann @lwhite1

`rightOuter` join has the same bug with leftOuter join, which is mentioned in #807. Left outer join is easy to fix, while this one will be a little bit difficult. 

The problem is related to field `joinColumnIndexes`. In the right outer join, the join columns in the first table will be removed, then the indexes in this field become invalid. If we continue to joining to next table, an error will show up in function `emptyTableFromColumns`. 

I plan to fix it by recomputing `joinColumnIndexes` after each join (which is not elegent in some way). OR we can choose to remove the join column in table2 rather than table1 (this will change the order of the column).

I look forward to hearing your thoughts.

**Comment by benmccann** [comment]
I think recomputing `joinColumnIndexes` is better than changing the column order

Thanks for finding and fixing these issues. Is there any bug with `fullOuter`?

**Comment by Carl-Rabbit** [comment]
OK, I will try to fix `rightOuter` first.
I haven't found any bugs in `fullOuter`. I'll add some tests later and keep an eye on it.

**Comment by Carl-Rabbit** [comment]
I do think recalculating would be easier. Thanks for giving your thoughts.

**Comment by lwhite1** [comment]
Hi @Carl-Rabbit, Thanks for working on this. Can this issue be closed now?
