### ISSUE TITLE
HtmlWriterTest  can't  across test dirve in html folder

### ISSUE THREAD

**Issue by HappyMan01** [jtablesaw/tablesaw#910]
hi,guys
     I want to  run the basic  method inside HtmlWriteTest.java,  but discover a issue that a NullPointerException

**Comment by lwhite1** [comment]
you need to write a better bug report if you would like me to look at this. Please show some simple example code and 
point out which variable is null. 

Also, the title is hard to understand.

**Comment by lwhite1** [comment]
Can't reproduce. Will reopen if more information is provided.
