### ISSUE TITLE
set scm release tag value using variable

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#947]
The tag is hardcoded in the parent pom scm section:

    <scm>
        <connection>scm:git:git@github.com:jtablesaw/tablesaw.git</connection>
        <developerConnection>scm:git:git@github.com:jtablesaw/tablesaw.git</developerConnection>
        <url>git@github.com:jtablesaw/tablesaw.git</url>
        <tag>v0.23.4</tag>
    </scm>

It should probably be set like the tag in the release plugin configuration section:

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>2.5.3</version>
                    <configuration>
                        <tagNameFormat>v@{project.version}</tagNameFormat>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <useReleaseProfile>false</useReleaseProfile>
                        <releaseProfiles>release</releaseProfiles>
                        <goals>deploy</goals>
                    </configuration>
                </plugin>

**Comment by benmccann** [comment]
`mvn release:prepare` followed by `mvn release: perform` should do most of the release process. Too bad it seems to be skipping this. Maybe we just remove the tag from this file instead? I don't know that we really need it for anything

**Comment by lwhite1** [comment]
that would be fine with me.

**Comment by benmccann** [comment]
removed
