### ISSUE TITLE
CSV export forces quoted strings

### ISSUE THREAD

**Issue by jordansamuels** [jtablesaw/tablesaw#95]
Can we have an option to export to CSV without quotes?

The following code:

        LongColumn a = new LongColumn("a");
        a.add(1L);
        a.add(2L);
        FloatColumn b = new FloatColumn("b");
        b.add(101.25);
        b.add(101.50);
        Table table = Table.create("name", a, b);
        table.exportToCsv("/tmp/t.csv");

Produces /tmp/t.csv with contents:

    "a","b"
    "1","101.25"
    "2","101.5"

Which is undesirable (e.g. you can't use pandas to read it, contains wasted characters, etc.).  It doesn't appear possible to pass an option through to opencsv to omit the quotes (but I may be missing something).

Thanks,
Jordan

**Comment by lwhite1** [comment]
You are right. It is not possible with OpenCSV. I believe the quotes are
'standard' CSV format, but I share your desire to get rid of them. They
waste a lot of space. It will require swapping CSV libraries, which is a
bit of work because OpenCSV has the simplest API.

**Comment by batterseapower** [comment]
You just need to parse false as the second arg when calling writeNext: http://opencsv.sourceforge.net/apidocs/com/opencsv/CSVWriter.html#writeNext(java.lang.String[], boolean)

**Comment by benmccann** [comment]
Thanks for the pointer. I just fixed this
