### ISSUE TITLE
Custom row comparator is not threadSafe and result is incorrect

### ISSUE THREAD

**Issue by Niclon** [jtablesaw/tablesaw#957]
Hi,
just found issue with custom row comparator on Table.class
`public Table sortOn(Comparator<Row> rowComparator) `
there is issue with sorting when table contain more than 8k rows. For sorting is used parallelQuickSort but there is issue that its not threadSafe and instances of Row class are being used by both threads and making mess out of result.

**Comment by lwhite1** [comment]
Thanks for the bug report. I'll look into this as soon as I can find the time. 
best.

**Comment by lwhite1** [comment]
fixed
