### ISSUE TITLE
Should Row implement equals and hashCode?

### ISSUE THREAD

**Issue by edwardzjl** [jtablesaw/tablesaw#971]
My team currently got a situation that we need to use `tech.tablesaw.api.Row` as a key of a map.

There are two solutions, first is implement `equals()` and `hashCode()` inside `Row` class, second is we can create a custom data structure from `Row`, then implement `equals()` and `hashCode()` there.

As far as I am concered, implementing `equals()` and `hashCode()` is always a good practice, So my question is is there any plan to impement them in `Row` class?

**Comment by lwhite1** [comment]
I don't think you want to try to do that. There is only one Row object if
you're iterating over a table. It just slides over the rows. This is done
for performance reasons. A real Row object that contained the cells from
the table would be hugely expensive in terms of memory if you have millions
of rows.

If it were me, I would use the row index. There is an int you can get from
Row that can be used for your key. For example, to build your map, you can
ask row for the id as you iterate. Then to get a row later, you can use the
method at(anInt) to retrieve the row you want. You only need one Row object
for all the values, just keep sending it "at()" to move the pointer.

I'm not sure if that is completely clear, or if the method names are
exactly correct. If it isn't i will write something more complete when i
have a bit more time.

**Comment by edwardzjl** [comment]
OK understood, It's a bit different situation here but yes we shouldn't use equals and hashcode. Thank you for your explaination, I'm going to close this issue.
