### ISSUE TITLE
Trying to add BigDecimal column

### ISSUE THREAD

**Issue by daugasauron** [jtablesaw/tablesaw#972]
Need the precision so tried implementing it. 

In TableSliceGroup, aggregate(ListMultimap<String, AggregateFunction<?, ?>> functions) it seems to me that there is some assumption about auto boxing "if (result instanceof Number)" fails because BigDecimal extends Number.

**Comment by lwhite1** [comment]
I think you would find that it is a non-trivial task to add a new column type, unfortunately, but let me know how it goes.

**Comment by daugasauron** [comment]
I have a quite small project with a lot of tables and simple aggregations, was quite straightforward to add the column type for what I need (with a lot of UnsupportedOperationExceptions..) but that if statement is quite annoying. I created my own version of tablesaw with the following and everything works like a charm. 

Would appreciate being able to use the official version.

`          
Object result = function.summarize(subTable.column(columnName));
if (firstFunction) {
  groupColumn.append(subTable.name());
}
if (function.returnType().equals(ColumnType.DOUBLE)) {
  Number number = (Number) result;
  resultColumn.append(number.doubleValue());
} else {
  resultColumn.append(result);
}
`
In my understanding it seems more reasonable since the return type will be determined by the AggregateFunction, and the standard numerical aggregation functions will return double column.

**Comment by lwhite1** [comment]
ok. I merged your PR.  Thanks
