### ISSUE TITLE
Wrong comment in Getting Started guide

### ISSUE THREAD

**Issue by mkarneim** [jtablesaw/tablesaw#978]
It looks like in section "Selection", subsection "Selecting by index" of the [Getting Started](https://jtablesaw.github.io/tablesaw/gettingstarted) guide, the code example has a wrong comment.

Instead of
```java
nc.where(Selection.withRange(1, 3)); // returns rows 1-3 inclusive
```
it should read
```java
nc.where(Selection.withRange(1, 3)); // returns rows 1-3 exclusive
```

**Comment by lwhite1** [comment]
fixed
